package micromark

import "testing"

// attentionFixtures hold no autolink, block quote, code (fenced or text), definition, html, label end
// (so no brackets), list, setext, strikethrough (no `~`), math (no `$`), liquid (no `{`), wiki-link or
// table syntax, and no URLs or emails: those constructs are not ported yet, so a fixture leaning on them
// would differ for reasons that are not attention's. CommonMark examples 353 (a list), 354 (`$`), 367 (a
// list), 404, 419, 422, 433, 473 and 474 (links), 475 to 477 (html), 478 and 479 (code) and 480 and 481
// (autolinks) are left out for that reason. Unicode neighbours are long-assigned code points, so their
// classification is the same in the bundle's table and in Node's.
var attentionFixtures = []string{
	// CommonMark examples 350 to 481, the ones that stay inside ported constructs.
	"*foo bar*\n",
	"a * foo bar*\n",
	"a*\"foo\"*\n",
	"foo*bar*\n",
	"5*6*78\n",
	"_foo bar_\n",
	"_ foo bar_\n",
	"a_\"foo\"_\n",
	"foo_bar_\n",
	"5_6_78\n",
	"пристаням_стремятся_\n",
	"aa_\"bb\"_cc\n",
	"foo-_(bar)_\n",
	"_foo*\n",
	"*foo bar *\n",
	"*(*foo)\n",
	"*(*foo*)*\n",
	"*foo*bar\n",
	"_foo bar _\n",
	"_(_foo)\n",
	"_(_foo_)_\n",
	"_foo_bar\n",
	"_пристаням_стремятся\n",
	"_foo_bar_baz_\n",
	"_(bar)_.\n",
	"**foo bar**\n",
	"** foo bar**\n",
	"a**\"foo\"**\n",
	"foo**bar**\n",
	"__foo bar__\n",
	"__ foo bar__\n",
	"__\nfoo bar__\n",
	"a__\"foo\"__\n",
	"foo__bar__\n",
	"5__6__78\n",
	"пристаням__стремятся__\n",
	"__foo, __bar__, baz__\n",
	"foo-__(bar)__\n",
	"**foo bar **\n",
	"**(**foo)\n",
	"*(**foo**)*\n",
	"**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n",
	"**foo \"*bar*\" foo**\n",
	"**foo**bar\n",
	"__foo bar __\n",
	"__(__foo)\n",
	"_(__foo__)_\n",
	"__foo__bar\n",
	"__пристаням__стремятся\n",
	"__foo__bar__baz__\n",
	"__(bar)__.\n",
	"*foo\nbar*\n",
	"_foo __bar__ baz_\n",
	"_foo _bar_ baz_\n",
	"__foo_ bar_\n",
	"*foo *bar**\n",
	"*foo **bar** baz*\n",
	"*foo**bar**baz*\n",
	"*foo**bar*\n",
	"***foo** bar*\n",
	"*foo **bar***\n",
	"*foo**bar***\n",
	"foo***bar***baz\n",
	"foo******bar*********baz\n",
	"*foo **bar *baz* bim** bop*\n",
	"** is not an empty emphasis\n",
	"**** is not an empty strong emphasis\n",
	"**foo\nbar**\n",
	"__foo _bar_ baz__\n",
	"__foo __bar__ baz__\n",
	"____foo__ bar__\n",
	"**foo **bar****\n",
	"**foo *bar* baz**\n",
	"**foo*bar*baz**\n",
	"***foo* bar**\n",
	"**foo *bar***\n",
	"**foo *bar **baz**\nbim* bop**\n",
	"__ is not an empty emphasis\n",
	"____ is not an empty strong emphasis\n",
	"foo ***\n",
	"foo *\\**\n",
	"foo *_*\n",
	"foo *****\n",
	"foo **\\***\n",
	"foo **_**\n",
	"**foo*\n",
	"*foo**\n",
	"***foo**\n",
	"****foo*\n",
	"**foo***\n",
	"*foo****\n",
	"foo ___\n",
	"foo _\\__\n",
	"foo _*_\n",
	"foo _____\n",
	"foo __\\___\n",
	"foo __*__\n",
	"__foo_\n",
	"_foo__\n",
	"___foo__\n",
	"____foo_\n",
	"__foo___\n",
	"_foo____\n",
	"**foo**\n",
	"*_foo_*\n",
	"__foo__\n",
	"_*foo*_\n",
	"****foo****\n",
	"____foo____\n",
	"******foo******\n",
	"***foo***\n",
	"_____foo_____\n",
	"*foo _bar* baz_\n",
	"*foo __bar *baz bim__ bam*\n",
	"**foo **bar baz**\n",
	"*foo *bar baz*\n",

	// start and inside: a lone sequence (a `*` or `* ` opening a line would be a list), end of input in the sequence, every length up to past use.
	"a *",
	"_",
	"**",
	"__",
	"a*",
	"*a",
	"a_",
	"_a",
	"*a*",
	"_a_",
	"***a***",
	"****a****",
	"*****a*****",
	"*******************a*******************",
	"a*b*c",
	"a_b_c",
	"*a**b*",
	"**a*b**",
	"*a***b*",
	"***a*",
	"*a***",
	"***a**",
	"**a***",
	"_a_b_c_",
	"_1_",
	"a_1_",
	"*_a_*",
	"_*a*_",
	"*a_*_",

	// Line endings and tabs on either side and inside.
	"*a*\n",
	"*a*\r\n",
	"*a*\r",
	"*a\nb*",
	"*a\r\nb*",
	"*a\rb*",
	"*a\n*b",
	"a*\nb*",
	"a *\ta*",
	"*a\t*",
	"a\t*b*\t",
	"_\ta_",
	"*a  \nb*",
	"*a\\\nb*",

	// Escapes and references beside a sequence.
	"\\*a*",
	"*a\\*",
	"*a\\\\*",
	"\\**a*",
	"*&amp;*",
	"&#42;a*",
	"*a&#42;",
	"_&copy;_",

	// Unicode whitespace and punctuation neighbours.
	"\u00a0*a*\u00a0",
	"*\u00a0a*",
	"*a\u00a0*",
	"\u3000_a_\u3000",
	"a_\u00a0b_",
	"«*a*»",
	"“_a_”",
	"a_«b»_c",
	"—*a*—",
	"*¿a?*",
	"*£*bravo.\n\n*€*charlie.\n",
	"_£_a",
	"a_£_",
	"é*é*é",
	"é_é_é",

	// Astral characters: two code units, neither punctuation nor whitespace.
	"𝔸*a*𝔸",
	"*𝔸*",
	"_𝔸_",
	"😀_a_😀",
	"😀*a*😀",

	// The replacement character is its own chunk, so moved points cross into it.
	"*\x00*",
	"**\x00a**",
	"***\x00a*",
	"*a\x00***",
	"_\x00_",

	// Inside other ported constructs.
	"# *a* #",
	"# **a**",
	"#*a*",
	"    *a*",
	"***\n*a*",
	"*a*\n***",
	"a\n\n_b_\n\nc",
}

func TestAttentionEvents(t *testing.T) {
	t.Parallel()
	compareEvents(t, attentionFixtures)
}
