package micromark

import "testing"

// gfmAutolinkLiteralFixtures avoid the constructs still pending: no `~` (strikethrough), no `[^`
// (footnotes), no `|` rows (tables), no `[ ]` after a list marker (task list items), no `[a]: b`
// (definitions), no `$` (math), no `[[` (wiki links), no `{{`/`{%` (liquid), and no `<` that would open
// html text. Spec examples 628, whose `<lp` html text fails on both sides, and 633 to 635, whose
// `mailto:`/`xmpp:` are not prefixes in this version, are kept because they stay inside ported behavior.
var gfmAutolinkLiteralFixtures = []string{
	// GFM spec examples 620 to 635.
	"http://example.com\n",
	"foo@bar.example.com\n",
	"www.commonmark.org\n",
	"Visit www.commonmark.org/help for more information.\n",
	"Visit www.commonmark.org.\n\nVisit www.commonmark.org/a.b.\n",
	"www.google.com/search?q=Markup+(business)\n\nwww.google.com/search?q=Markup+(business)))\n\n(www.google.com/search?q=Markup+(business))\n\n(www.google.com/search?q=Markup+(business)\n",
	"www.google.com/search?q=(business))+ok\n",
	"www.google.com/search?q=commonmark&hl=en\n\nwww.google.com/search?q=commonmark&hl;\n",
	"www.commonmark.org/he<lp\n",
	"http://commonmark.org\n\n(Visit https://encrypted.google.com/search?q=Markup+(business))\n",
	"foo@bar.baz\n",
	"hello@mail+xyz.example isn't valid, but hello+xyz@mail.example is.\n",
	"a.b-c_d@a.b\n\na.b-c_d@a.b.\n\na.b-c_d@a.b-\n\na.b-c_d@a.b_\n",
	"mailto:foo@bar.baz\n\nmailto:a.b-c_d@a.b\n\nmailto:a.b-c_d@a.b.\n\nmailto:a.b-c_d@a.b/\n\nmailto:a.b-c_d@a.b-\n\nmailto:a.b-c_d@a.b_\n\nxmpp:foo@bar.baz\n\nxmpp:foo@bar.baz.\n",
	"xmpp:foo@bar.baz/txt\n\nxmpp:foo@bar.baz/txt@bin\n\nxmpp:foo@bar.baz/txt@bin.com\n",
	"xmpp:foo@bar.baz/txt/bin\n",
	// CommonMark autolinks next to literals.
	"<http://foo.bar.baz>",
	"<foo@bar.example.com>",

	// www: the prefix, its length, its case, and what must follow it.
	"www.",
	"www.a",
	"WWW.a",
	"wWw.a.b",
	"ww.a",
	"wwww.a",
	"www",
	"www.\n",
	"www. a",
	"www..",
	"www.a_b",
	"www.a_b.c",
	"www.a_b.c.d",
	"www.a.b_c",
	"www.a_.b",
	"www.-a.b",
	"www.點看.com",
	"www.a𝔸b.c",
	"www.a.b\u00a0c",
	"www.a.b\tc",
	"www.a.b\r\nc",
	"www.a.b\rc",

	// The previous-character gates.
	"awww.a.b",
	"(www.a.b)",
	"*www.a.b*",
	"_www.a.b_",
	"**www.a.b**",
	"[www.a.b]",
	"]www.a.b",
	"a www.a.b",
	"a\nwww.a.b",
	"a\twww.a.b",
	".www.a.b",
	"/www.a.b",
	"ahttp://a.b",
	"1http://a.b",
	"*http://a.b*",
	"_http://a.b",
	"é http://a.b",
	"éhttp://a.b",
	"a/b@c.d",
	"a.b@c.d",
	"*a@b.c*",
	"!a@b.c",
	"é@b.c",

	// Protocols: case, length, slashes, and what follows them.
	"HTTP://a.b",
	"Https://a.b",
	"httpss://a.b",
	"ftp://a.b",
	"http:/a.b",
	"http:a.b",
	"http://",
	"http:// a",
	"http://.a",
	"http://-a",
	"http://\u00a0a",
	"http://\x01a",
	"http://a",
	"http://a_b",
	"http://a_b.c.d",
	"http://a.b_c/d",
	"https://a.b:8080/c?d=e#f",
	"h",
	"htt",
	"http",
	"http:",
	"http:/",

	// Paths: parentheses, trailing punctuation, character-reference-like trails, brackets.
	"www.a.b/c(d)",
	"www.a.b/c(d))",
	"www.a.b/c((d))",
	"www.a.b/c)",
	"www.a.b/c.",
	"www.a.b/c.d",
	"www.a.b/c!\"'*,.:;?_~",
	"www.a.b/c?!.",
	"www.a.b/c&amp;",
	"www.a.b/c&amp;d",
	"www.a.b/c&amp",
	"www.a.b/c&;",
	"www.a.b/c&1;",
	"www.a.b/c&amp;).",
	"www.a.b/c]",
	"www.a.b/c](d)",
	"www.a.b/c][d]",
	"www.a.b/c]d",
	"www.a.b/c]]",
	"www.a.b/c<d",
	"www.a.b/c\"d",
	"www.a.b.",
	"www.a.b_",
	"www.a.b._",
	"www.a.b/c\n",
	"www.a.b/c\r\n",
	"www.a.b/c 𝔸",

	// Labels: unbalanced brackets before gate a literal, balanced ones do not.
	"[a](www.a.b)",
	"[www.a.b](c)",
	"[a] www.a.b",
	"[a www.a.b",
	"![a www.a.b",
	"[a](b) www.a.b c@d.e http://f.g",
	"[a] [b www.a.b] http://c.d",
	"x www.a.b y www.c.d z a@b.c",

	// Email: atext, the domain, the dot trail, the end.
	"a@b",
	"a@b.",
	"a@b.c",
	"a@b.c.",
	"a@b.c1",
	"a@b.1",
	"a@b-.c",
	"a@.b",
	"a@",
	"@a.b",
	"a+b-c.d_e@f.g",
	"a@b.c@d.e",
	"a@b..c",
	"a@b.c\n",
	"a@b.c d",
	"a@b.c.d.e.f",
	"a_@b.c",
}

func TestGfmAutolinkLiteralEvents(t *testing.T) {
	t.Parallel()
	compareEvents(t, gfmAutolinkLiteralFixtures)
}
