// Code generated from micromark-util-symbol 2.0.1 (codes.js, types.js). DO NOT EDIT.

package micromark

// The character codes micromark names. eof is JavaScript's null, which compares as 0, and a real NUL never
// reaches a tokenizer because preprocessing replaces it, so 0 is the faithful spelling of both.
const (
	CodeCarriageReturn         Code = -5
	CodeLineFeed               Code = -4
	CodeCarriageReturnLineFeed Code = -3
	CodeHorizontalTab          Code = -2
	CodeVirtualSpace           Code = -1
	CodeEof                    Code = 0
	CodeSoh                    Code = 1
	CodeStx                    Code = 2
	CodeEtx                    Code = 3
	CodeEot                    Code = 4
	CodeEnq                    Code = 5
	CodeAck                    Code = 6
	CodeBel                    Code = 7
	CodeBs                     Code = 8
	CodeHt                     Code = 9
	CodeLf                     Code = 10
	CodeVt                     Code = 11
	CodeFf                     Code = 12
	CodeCr                     Code = 13
	CodeSo                     Code = 14
	CodeSi                     Code = 15
	CodeDle                    Code = 16
	CodeDc1                    Code = 17
	CodeDc2                    Code = 18
	CodeDc3                    Code = 19
	CodeDc4                    Code = 20
	CodeNak                    Code = 21
	CodeSyn                    Code = 22
	CodeEtb                    Code = 23
	CodeCan                    Code = 24
	CodeEm                     Code = 25
	CodeSub                    Code = 26
	CodeEsc                    Code = 27
	CodeFs                     Code = 28
	CodeGs                     Code = 29
	CodeRs                     Code = 30
	CodeUs                     Code = 31
	CodeSpace                  Code = 32
	CodeExclamationMark        Code = 33
	CodeQuotationMark          Code = 34
	CodeNumberSign             Code = 35
	CodeDollarSign             Code = 36
	CodePercentSign            Code = 37
	CodeAmpersand              Code = 38
	CodeApostrophe             Code = 39
	CodeLeftParenthesis        Code = 40
	CodeRightParenthesis       Code = 41
	CodeAsterisk               Code = 42
	CodePlusSign               Code = 43
	CodeComma                  Code = 44
	CodeDash                   Code = 45
	CodeDot                    Code = 46
	CodeSlash                  Code = 47
	CodeDigit0                 Code = 48
	CodeDigit1                 Code = 49
	CodeDigit2                 Code = 50
	CodeDigit3                 Code = 51
	CodeDigit4                 Code = 52
	CodeDigit5                 Code = 53
	CodeDigit6                 Code = 54
	CodeDigit7                 Code = 55
	CodeDigit8                 Code = 56
	CodeDigit9                 Code = 57
	CodeColon                  Code = 58
	CodeSemicolon              Code = 59
	CodeLessThan               Code = 60
	CodeEqualsTo               Code = 61
	CodeGreaterThan            Code = 62
	CodeQuestionMark           Code = 63
	CodeAtSign                 Code = 64
	CodeUppercaseA             Code = 65
	CodeUppercaseB             Code = 66
	CodeUppercaseC             Code = 67
	CodeUppercaseD             Code = 68
	CodeUppercaseE             Code = 69
	CodeUppercaseF             Code = 70
	CodeUppercaseG             Code = 71
	CodeUppercaseH             Code = 72
	CodeUppercaseI             Code = 73
	CodeUppercaseJ             Code = 74
	CodeUppercaseK             Code = 75
	CodeUppercaseL             Code = 76
	CodeUppercaseM             Code = 77
	CodeUppercaseN             Code = 78
	CodeUppercaseO             Code = 79
	CodeUppercaseP             Code = 80
	CodeUppercaseQ             Code = 81
	CodeUppercaseR             Code = 82
	CodeUppercaseS             Code = 83
	CodeUppercaseT             Code = 84
	CodeUppercaseU             Code = 85
	CodeUppercaseV             Code = 86
	CodeUppercaseW             Code = 87
	CodeUppercaseX             Code = 88
	CodeUppercaseY             Code = 89
	CodeUppercaseZ             Code = 90
	CodeLeftSquareBracket      Code = 91
	CodeBackslash              Code = 92
	CodeRightSquareBracket     Code = 93
	CodeCaret                  Code = 94
	CodeUnderscore             Code = 95
	CodeGraveAccent            Code = 96
	CodeLowercaseA             Code = 97
	CodeLowercaseB             Code = 98
	CodeLowercaseC             Code = 99
	CodeLowercaseD             Code = 100
	CodeLowercaseE             Code = 101
	CodeLowercaseF             Code = 102
	CodeLowercaseG             Code = 103
	CodeLowercaseH             Code = 104
	CodeLowercaseI             Code = 105
	CodeLowercaseJ             Code = 106
	CodeLowercaseK             Code = 107
	CodeLowercaseL             Code = 108
	CodeLowercaseM             Code = 109
	CodeLowercaseN             Code = 110
	CodeLowercaseO             Code = 111
	CodeLowercaseP             Code = 112
	CodeLowercaseQ             Code = 113
	CodeLowercaseR             Code = 114
	CodeLowercaseS             Code = 115
	CodeLowercaseT             Code = 116
	CodeLowercaseU             Code = 117
	CodeLowercaseV             Code = 118
	CodeLowercaseW             Code = 119
	CodeLowercaseX             Code = 120
	CodeLowercaseY             Code = 121
	CodeLowercaseZ             Code = 122
	CodeLeftCurlyBrace         Code = 123
	CodeVerticalBar            Code = 124
	CodeRightCurlyBrace        Code = 125
	CodeTilde                  Code = 126
	CodeDel                    Code = 127
	CodeByteOrderMarker        Code = 65279
	CodeReplacementCharacter   Code = 65533
	CodeNul                    Code = 0
)

// The token types micromark core names. Extensions declare their own beside their constructs.
const (
	TypeData                                = "data"
	TypeWhitespace                          = "whitespace"
	TypeLineEnding                          = "lineEnding"
	TypeLineEndingBlank                     = "lineEndingBlank"
	TypeLinePrefix                          = "linePrefix"
	TypeLineSuffix                          = "lineSuffix"
	TypeAtxHeading                          = "atxHeading"
	TypeAtxHeadingSequence                  = "atxHeadingSequence"
	TypeAtxHeadingText                      = "atxHeadingText"
	TypeAutolink                            = "autolink"
	TypeAutolinkEmail                       = "autolinkEmail"
	TypeAutolinkMarker                      = "autolinkMarker"
	TypeAutolinkProtocol                    = "autolinkProtocol"
	TypeCharacterEscape                     = "characterEscape"
	TypeCharacterEscapeValue                = "characterEscapeValue"
	TypeCharacterReference                  = "characterReference"
	TypeCharacterReferenceMarker            = "characterReferenceMarker"
	TypeCharacterReferenceMarkerNumeric     = "characterReferenceMarkerNumeric"
	TypeCharacterReferenceMarkerHexadecimal = "characterReferenceMarkerHexadecimal"
	TypeCharacterReferenceValue             = "characterReferenceValue"
	TypeCodeFenced                          = "codeFenced"
	TypeCodeFencedFence                     = "codeFencedFence"
	TypeCodeFencedFenceSequence             = "codeFencedFenceSequence"
	TypeCodeFencedFenceInfo                 = "codeFencedFenceInfo"
	TypeCodeFencedFenceMeta                 = "codeFencedFenceMeta"
	TypeCodeFlowValue                       = "codeFlowValue"
	TypeCodeIndented                        = "codeIndented"
	TypeCodeText                            = "codeText"
	TypeCodeTextData                        = "codeTextData"
	TypeCodeTextPadding                     = "codeTextPadding"
	TypeCodeTextSequence                    = "codeTextSequence"
	TypeContent                             = "content"
	TypeDefinition                          = "definition"
	TypeDefinitionDestination               = "definitionDestination"
	TypeDefinitionDestinationLiteral        = "definitionDestinationLiteral"
	TypeDefinitionDestinationLiteralMarker  = "definitionDestinationLiteralMarker"
	TypeDefinitionDestinationRaw            = "definitionDestinationRaw"
	TypeDefinitionDestinationString         = "definitionDestinationString"
	TypeDefinitionLabel                     = "definitionLabel"
	TypeDefinitionLabelMarker               = "definitionLabelMarker"
	TypeDefinitionLabelString               = "definitionLabelString"
	TypeDefinitionMarker                    = "definitionMarker"
	TypeDefinitionTitle                     = "definitionTitle"
	TypeDefinitionTitleMarker               = "definitionTitleMarker"
	TypeDefinitionTitleString               = "definitionTitleString"
	TypeEmphasis                            = "emphasis"
	TypeEmphasisSequence                    = "emphasisSequence"
	TypeEmphasisText                        = "emphasisText"
	TypeEscapeMarker                        = "escapeMarker"
	TypeHardBreakEscape                     = "hardBreakEscape"
	TypeHardBreakTrailing                   = "hardBreakTrailing"
	TypeHtmlFlow                            = "htmlFlow"
	TypeHtmlFlowData                        = "htmlFlowData"
	TypeHtmlText                            = "htmlText"
	TypeHtmlTextData                        = "htmlTextData"
	TypeImage                               = "image"
	TypeLabel                               = "label"
	TypeLabelText                           = "labelText"
	TypeLabelLink                           = "labelLink"
	TypeLabelImage                          = "labelImage"
	TypeLabelMarker                         = "labelMarker"
	TypeLabelImageMarker                    = "labelImageMarker"
	TypeLabelEnd                            = "labelEnd"
	TypeLink                                = "link"
	TypeParagraph                           = "paragraph"
	TypeReference                           = "reference"
	TypeReferenceMarker                     = "referenceMarker"
	TypeReferenceString                     = "referenceString"
	TypeResource                            = "resource"
	TypeResourceDestination                 = "resourceDestination"
	TypeResourceDestinationLiteral          = "resourceDestinationLiteral"
	TypeResourceDestinationLiteralMarker    = "resourceDestinationLiteralMarker"
	TypeResourceDestinationRaw              = "resourceDestinationRaw"
	TypeResourceDestinationString           = "resourceDestinationString"
	TypeResourceMarker                      = "resourceMarker"
	TypeResourceTitle                       = "resourceTitle"
	TypeResourceTitleMarker                 = "resourceTitleMarker"
	TypeResourceTitleString                 = "resourceTitleString"
	TypeSetextHeading                       = "setextHeading"
	TypeSetextHeadingText                   = "setextHeadingText"
	TypeSetextHeadingLine                   = "setextHeadingLine"
	TypeSetextHeadingLineSequence           = "setextHeadingLineSequence"
	TypeStrong                              = "strong"
	TypeStrongSequence                      = "strongSequence"
	TypeStrongText                          = "strongText"
	TypeThematicBreak                       = "thematicBreak"
	TypeThematicBreakSequence               = "thematicBreakSequence"
	TypeBlockQuote                          = "blockQuote"
	TypeBlockQuotePrefix                    = "blockQuotePrefix"
	TypeBlockQuoteMarker                    = "blockQuoteMarker"
	TypeBlockQuotePrefixWhitespace          = "blockQuotePrefixWhitespace"
	TypeListOrdered                         = "listOrdered"
	TypeListUnordered                       = "listUnordered"
	TypeListItemIndent                      = "listItemIndent"
	TypeListItemMarker                      = "listItemMarker"
	TypeListItemPrefix                      = "listItemPrefix"
	TypeListItemPrefixWhitespace            = "listItemPrefixWhitespace"
	TypeListItemValue                       = "listItemValue"
	TypeChunkDocument                       = "chunkDocument"
	TypeChunkContent                        = "chunkContent"
	TypeChunkFlow                           = "chunkFlow"
	TypeChunkText                           = "chunkText"
	TypeChunkString                         = "chunkString"
)
