// Command generate_characters captures micromark's two Unicode character classes from the bundle the
// oracle runs, and writes them as Go.
//
// Usage:
//
//	go run ./internal/format/markdown/micromark/tools/generate_characters [-output <file.go>] [-check]
//
// micromark-util-character tests `\p{P}|\p{S}` and `\s` against one UTF-16 code unit at a time, and
// those answers decide where emphasis opens and closes. goja implements no Unicode property escapes and
// silently answers false for every `\p{...}`, so the fork's build rewrote each one into an explicit
// class computed by the Node that built it. That rewritten class is what the oracle runs, so it is the
// authority here, not Go's unicode package and not today's Node: a code point reclassified between
// Unicode versions would flip an emphasis decision with nothing visibly wrong.
//
// So nothing is restated. The class is cut out of the embedded markdown bundle, compiled by goja, and
// asked about every code unit; `\s` is asked of goja the same way. The answers are compressed into
// ranges. `-check` regenerates and fails when the committed file disagrees.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"

	"github.com/dop251/goja"
	"github.com/system-inc/cohere/internal/format/prettier"
)

// punctuationPattern finds micromark's unicodePunctuation regexCheck in the minified bundle: the
// rewritten `\p{P}|\p{S}` is the only class literal that starts at U+0021 with the gap at U+0024, and it
// is the argument of the regexCheck factory. Exactly one match is required.
var punctuationPattern = regexp.MustCompile(`=[A-Za-z_$]{1,3}\(/(\[\\u\{21\}-\\u\{23\}\\u\{25\}-\\u\{2A\}[^/]*\])/u\)`)

func main() {
	output := flag.String("output", filepath.Join("internal", "format", "markdown", "micromark", "characters_generated.go"), "where to write the Go")
	check := flag.Bool("check", false, "regenerate and fail if the committed file disagrees")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *check {
		committed, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if !bytes.Equal(committed, generated) {
			fmt.Fprintf(os.Stderr, "%s is stale: regenerate it\n", *output)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	bundles, err := prettier.Bundles()
	if err != nil {
		return nil, err
	}
	markdown := string(bundles.Files["plugins/markdown.js"])

	matches := punctuationPattern.FindAllStringSubmatch(markdown, -1)
	if len(matches) != 1 {
		return nil, fmt.Errorf("found %d candidates for micromark's unicodePunctuation class in the markdown bundle, want exactly 1", len(matches))
	}

	runtime := goja.New()
	punctuation, err := unitRanges(runtime, matches[0][1], "u")
	if err != nil {
		return nil, err
	}
	whitespace, err := unitRanges(runtime, `\s`, "")
	if err != nil {
		return nil, err
	}

	// Controls in both directions, so a pattern that compiled into something else cannot pass: ASCII
	// punctuation and a symbol are in, a letter and a digit are out; space and no-break space are
	// whitespace, a letter is not.
	for _, probe := range []struct {
		ranges [][2]int
		unit   int
		want   bool
	}{
		{punctuation, '!', true}, {punctuation, '$', true}, {punctuation, 0x00A9, true},
		{punctuation, 'a', false}, {punctuation, '7', false},
		{whitespace, ' ', true}, {whitespace, 0x00A0, true}, {whitespace, 'a', false},
	} {
		if contains(probe.ranges, probe.unit) != probe.want {
			return nil, fmt.Errorf("control failed: U+%04X answered %v, want %v", probe.unit, !probe.want, probe.want)
		}
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by generate_characters. DO NOT EDIT.\n//\n")
	source.WriteString("// Captured from the embedded markdown bundle, run by goja: the fork's rewritten `\\p{P}|\\p{S}` and goja's\n")
	source.WriteString("// own `\\s`, each asked about every UTF-16 code unit. Regenerate with:\n//\n")
	source.WriteString("//\tgo run ./internal/format/markdown/micromark/tools/generate_characters\n\n")
	source.WriteString("package micromark\n\n")
	writeRanges(&source, "unicodePunctuationRanges", "are the code units micromark's unicodePunctuation accepts.", punctuation)
	writeRanges(&source, "unicodeWhitespaceRanges", "are the code units micromark's unicodeWhitespace accepts.", whitespace)

	return format.Source(source.Bytes())
}

// unitRanges asks a regex about every UTF-16 code unit, as micromark's regexCheck does with
// String.fromCharCode, and compresses the answers into inclusive ranges.
func unitRanges(runtime *goja.Runtime, pattern string, flags string) ([][2]int, error) {
	runtime.Set("__pattern", pattern)
	runtime.Set("__flags", flags)
	value, err := runtime.RunString(`
		(function () {
			const regex = new RegExp(__pattern, __flags);
			const ranges = [];
			let start = -1;
			for (let unit = 0; unit <= 0x10000; unit++) {
				const inside = unit <= 0xFFFF && regex.test(String.fromCharCode(unit));
				if (inside && start < 0) start = unit;
				if (!inside && start >= 0) { ranges.push([start, unit - 1]); start = -1; }
			}
			return JSON.stringify(ranges);
		})()
	`)
	if err != nil {
		return nil, err
	}
	var ranges [][2]int
	if err := json.Unmarshal([]byte(value.String()), &ranges); err != nil {
		return nil, err
	}
	if len(ranges) == 0 {
		return nil, fmt.Errorf("%q matched no code unit", pattern)
	}
	return ranges, nil
}

func contains(ranges [][2]int, unit int) bool {
	for _, entry := range ranges {
		if unit >= entry[0] && unit <= entry[1] {
			return true
		}
	}
	return false
}

func writeRanges(source *bytes.Buffer, name string, description string, ranges [][2]int) {
	fmt.Fprintf(source, "// %s %s\nvar %s = [][2]uint16{\n", name, description, name)
	for _, entry := range ranges {
		fmt.Fprintf(source, "\t{0x%04X, 0x%04X},\n", entry[0], entry[1])
	}
	source.WriteString("}\n\n")
}
