// Code generated by generate_languages. DO NOT EDIT.
//
// Captured from the embedded bundles, run by goja: the languages inferParser searches, in its order.
// Regenerate with:
//
//	go run ./internal/format/markdown/tools/generate_languages

package markdown

// inferableLanguages are options.plugins reversed and flattened into their languages, each with its
// first parser.
var inferableLanguages = []inferableLanguage{
	{name: "YAML", aliases: []string{"yml"}, extensions: []string{".yml", ".mir", ".reek", ".rviz", ".sublime-syntax", ".syntax", ".yaml", ".yaml-tmlanguage", ".yaml.sed", ".yml.mysql"}, parser: "yaml"},
	{name: "GraphQL", aliases: nil, extensions: []string{".graphql", ".gql", ".graphqls"}, parser: "graphql"},
	{name: "Markdown", aliases: []string{"md", "pandoc"}, extensions: []string{".md", ".livemd", ".markdown", ".mdown", ".mdwn", ".mkd", ".mkdn", ".mkdown", ".ronn", ".scd", ".workbook"}, parser: "markdown"},
	{name: "MDX", aliases: []string{"md", "pandoc"}, extensions: []string{".mdx"}, parser: "mdx"},
	{name: "CSS", aliases: nil, extensions: []string{".css", ".wxss"}, parser: "css"},
	{name: "PostCSS", aliases: nil, extensions: []string{".pcss", ".postcss"}, parser: "css"},
	{name: "Less", aliases: []string{"less-css"}, extensions: []string{".less"}, parser: "less"},
	{name: "SCSS", aliases: nil, extensions: []string{".scss"}, parser: "scss"},
	{name: "JavaScript", aliases: []string{"js", "node"}, extensions: []string{".js", "._js", ".bones", ".cjs", ".es", ".es6", ".gs", ".jake", ".javascript", ".jsb", ".jscad", ".jsfl", ".jslib", ".jsm", ".jspre", ".jss", ".mjs", ".njs", ".pac", ".sjs", ".ssjs", ".xsjs", ".xsjslib", ".start.frag", ".end.frag", ".wxs"}, parser: "babel"},
	{name: "Flow", aliases: nil, extensions: []string{".js.flow"}, parser: "flow"},
	{name: "JSX", aliases: nil, extensions: []string{".jsx"}, parser: "babel"},
	{name: "TypeScript", aliases: []string{"ts"}, extensions: []string{".ts", ".cts", ".mts"}, parser: "typescript"},
	{name: "TSX", aliases: []string{"typescriptreact"}, extensions: []string{".tsx"}, parser: "typescript"},
	{name: "JSON.stringify", aliases: []string{"geojson", "jsonl", "sarif", "topojson"}, extensions: []string{".importmap"}, parser: "json-stringify"},
	{name: "JSON", aliases: []string{"geojson", "jsonl", "sarif", "topojson"}, extensions: []string{".json", ".4DForm", ".4DProject", ".avsc", ".geojson", ".gltf", ".har", ".ice", ".JSON-tmLanguage", ".json.example", ".mcmeta", ".sarif", ".slnlaunch", ".tact", ".tfstate", ".tfstate.backup", ".topojson", ".webapp", ".webmanifest", ".yy", ".yyp"}, parser: "json"},
	{name: "JSON with Comments", aliases: []string{"jsonc"}, extensions: []string{".jsonc", ".code-snippets", ".code-workspace", ".sublime-build", ".sublime-color-scheme", ".sublime-commands", ".sublime-completions", ".sublime-keymap", ".sublime-macro", ".sublime-menu", ".sublime-mousemap", ".sublime-project", ".sublime-settings", ".sublime-theme", ".sublime-workspace", ".sublime_metrics", ".sublime_session"}, parser: "jsonc"},
	{name: "JSON5", aliases: nil, extensions: []string{".json5"}, parser: "json5"},
}
