
// Code generated by internal/types/tools/generate_shims. DO NOT EDIT.

package vfs

import "github.com/microsoft/TypeScript/tsc/internal/vfs"
import "io/fs"
import _ "unsafe"

type DirEntry = vfs.DirEntry
type Entries = vfs.Entries
var ErrClosed = vfs.ErrClosed
var ErrExist = vfs.ErrExist
var ErrInvalid = vfs.ErrInvalid
var ErrNotExist = vfs.ErrNotExist
var ErrPermission = vfs.ErrPermission
type FS = vfs.FS
type FileInfo = vfs.FileInfo
//go:linkname WalkDir github.com/microsoft/TypeScript/tsc/internal/vfs.WalkDir
func WalkDir(fileSystem vfs.FS, root string, walkFn fs.WalkDirFunc) error
