package react

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/system-inc/cohere/internal/lint/testing"
)

// The corpus for this rule is React's own, and it is two files.
//
// oxc's linter rule is `run_react_compiler_rule(ctx, ErrorCategory::Purity)` with the judgment in
// the compiler crate, so there is no inline oxc corpus to import. React ships exactly two fixtures
// whose golden expects `Cannot call impure function during render`, vendored at
// `internal/react_conformance/testdata/fixtures`, and both constants below are one of them byte for
// byte. They were generated by reading each file and emitting it through a JSON encoder, so no
// escape was ever typed, and `TestPurityFixturesMatchTheVendoredCorpusByte` proves that held.
//
// # Why almost every test below is NOT from the corpus
//
// The two fixtures are the same source twice. Three direct calls at the top level of a component,
// no nesting, no aliasing, no conditional, and not one VALID fixture anywhere in the 650-file
// corpus mentions any of the three builtins. A rule reporting on every lexical occurrence of
// `Math.random` in every file scores 2 of 2 here, and so does a correct rule.
//
// So the corpus is a floor in the weakest sense available and it cannot see this rule's actual
// discriminations. Every case below that is not one of the two fixtures was measured by running
// `eslint-plugin-react-hooks` version 7.1.1 through the ESLint Linter API on the exact string being
// asserted, and each says so at the line. That is the only evidence this rule has, and stating
// where it came from is part of the port.
const purityImpureFunctionsInRender = "// @validateNoImpureFunctionsInRender\n\nfunction Component() {\n  const date = Date.now();\n  const now = performance.now();\n  const rand = Math.random();\n  return <Foo date={date} now={now} rand={rand} />;\n}\n"

const purityImpureFunctionsInRenderNewMutability = "// @validateNoImpureFunctionsInRender @enableNewMutationAliasingModel\n\nfunction Component() {\n  const date = Date.now();\n  const now = performance.now();\n  const rand = Math.random();\n  return <Foo date={date} now={now} rand={rand} />;\n}\n"

// runPurityFixture runs one source through the typed harness.
//
// Typed rather than plain, and the reason is not that this rule reads a type. It reads none. The
// checker is what makes `internal/utilities/hir` resolve a shadowed binding to its declaration instead
// of to a global, and without it `const Math = {random: () => 1}` lowers to `LoadGlobal Math` and
// this rule reports an input React passes. `TestPurityRequiresTheTypedHarness` pins that.
func runPurityFixture(t *testing.T, source string) rule_testing.Result {
	t.Helper()
	return rule_testing.RunTyped(t, Purity, "fixture.tsx", source)
}

// TestPurityFiresOnTheVendoredCorpus runs both fixtures verbatim.
//
// Three findings each, one per impure call, which is what React's own rule produces on these exact
// strings and what the golden records. The second fixture differs only by a second pragma, and this
// rule reads no pragma at all, so the two are expected to agree.
func TestPurityFiresOnTheVendoredCorpus(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		source string
	}{
		{"the fixture as written", purityImpureFunctionsInRender},
		{"the same source under the new mutation aliasing model", purityImpureFunctionsInRenderNewMutability},
	}
	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			result := runPurityFixture(t, testCase.source)
			rule_testing.ExpectFindings(t, result,
				messagePurityImpureCallId, messagePurityImpureCallId, messagePurityImpureCallId)
		})
	}
}

// TestPurityFixturesMatchTheVendoredCorpusByte compares each constant against the file it came
// from, byte for byte.
//
// Reading them is not enough and it has cost three porters. The failure is a TOOL cooking an escape
// on the way in, so the fixture sits in the suite asserting the opposite of upstream while
// compiling and going green.
func TestPurityFixturesMatchTheVendoredCorpusByte(t *testing.T) {
	t.Parallel()

	cases := []struct {
		constant string
		fileName string
	}{
		{purityImpureFunctionsInRender, "error.invalid-impure-functions-in-render.js"},
		{purityImpureFunctionsInRenderNewMutability, filepath.Join("new-mutability", "error.invalid-impure-functions-in-render.js")},
	}

	directory := filepath.Join("conformance", "testdata", "fixtures")
	for _, testCase := range cases {
		t.Run(testCase.fileName, func(t *testing.T) {
			vendored, err := os.ReadFile(filepath.Join(directory, testCase.fileName))
			if err != nil {
				t.Fatalf("reading the vendored fixture: %v", err)
			}
			if string(vendored) != testCase.constant {
				t.Errorf("the constant and the vendored file differ\n constant: %q\n vendored: %q",
					testCase.constant, string(vendored))
			}
		})
	}
	if len(cases) != 2 {
		t.Errorf("checked %d fixtures, want the 2 whose golden expects this rule's diagnostic", len(cases))
	}
}

// TestPurityFiresOnMeasuredInputs covers every reporting shape that the corpus does not contain.
//
// Each `source` was run through React's own rule and each REPORTED with the finding count asserted
// here. The comment on each names what it separates, because a case whose verdict nothing else
// depends on is a case that will be deleted by the next reader.
func TestPurityFiresOnMeasuredInputs(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		source string
		want   int
	}{
		{
			// The simplest reporting shape and the baseline for everything below.
			name:   "a direct call in a component",
			source: "function Component() {\n  const d = Date.now();\n  return <div>{d}</div>;\n}\n",
			want:   1,
		},
		{
			// The alias, and the first input a lexical rule cannot span correctly: React points at
			// `r()` rather than at `Math.random`.
			name:   "a builtin reached through an alias",
			source: "function Component() {\n  const r = Math.random;\n  const x = r();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The input that settles the whole design. React prints `Date.now`, not `Math.random`,
			// and points at `r()`. Only value tracking through the reassignment produces that.
			name:   "an alias reassigned to a different builtin",
			source: "function Component() {\n  let r = Math.random;\n  r = Date.now;\n  const x = r();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// Destructuring carries the signature the same way a property load does.
			name:   "a builtin destructured off its container",
			source: "function Component() {\n  const {random} = Math;\n  const x = random();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The container itself travels, so `p.now()` is `performance.now()`.
			name:   "a container reached through an alias",
			source: "function Component() {\n  const p = performance;\n  const x = p.now();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The nested wrapper, CALLED. Its uncalled twin is in the silent test and the pair is
			// what proves this rule is not lexical.
			name:   "a nested arrow that is called",
			source: "function Component() {\n  const f = () => Math.random();\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// Two levels of wrapper, so the re-raise has to chain rather than stopping at one.
			name:   "a wrapper calling a wrapper",
			source: "function Component() {\n  const g = () => Math.random();\n  const f = () => g();\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// A function DECLARATION rather than an arrow, which lowers differently.
			name:   "a nested function declaration that is called",
			source: "function Component() {\n  function f() { return Math.random(); }\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The dedup case. React reports ONCE for a wrapper called twice, pointing at the inner
			// call, because the finding belongs to the inner site rather than to each caller.
			name:   "a wrapper called twice reports once",
			source: "function Component() {\n  const f = () => Math.random();\n  const a = f();\n  const b = f();\n  return <div>{a}{b}</div>;\n}\n",
			want:   1,
		},
		{
			// Three builtins inside one wrapper, so the re-raise carries a set rather than one.
			name:   "three builtins in one called wrapper",
			source: "function Component() {\n  const f = () => Math.random() + Date.now() + performance.now();\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   3,
		},
		{
			// A component nested inside a plain wrapper is still a unit, which is why a declined
			// function is descended into rather than skipped.
			name:   "a component declared inside a non-component",
			source: "function outer() {\n  function Component() { return <div>{Math.random()}</div>; }\n  return Component;\n}\n",
			want:   1,
		},
		{
			// The hook half of the gate. A hook has no JSX, so a gate asking only for JSX would
			// miss this one.
			name:   "a hook that calls a builtin",
			source: "function useThing() {\n  const x = Math.random();\n  return useMemo(() => x, [x]);\n}\n",
			want:   1,
		},
		{
			// An arrow component, which takes its name from the declarator rather than its own
			// identifier.
			name:   "an arrow component",
			source: "const Component = () => {\n  const x = Math.random();\n  return <div>{x}</div>;\n};\n",
			want:   1,
		},
		{
			// Directly inside a JSX expression, with no binding in between.
			name:   "a call inside a JSX expression container",
			source: "function Component() {\n  return <div>{Math.random()}</div>;\n}\n",
			want:   1,
		},
		{
			// Optional chaining does not change the call, and React reports it.
			name:   "an optional call",
			source: "function Component() {\n  const x = Date?.now();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// A computed property whose key is a static string resolves to the same signature.
			name:   "a computed property with a literal key",
			source: "function Component() {\n  const x = Math[\"random\"]();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// `globalThis` carries every typed global as a property, so the chain reaches through.
			// Its twin `window.Math.random()` is in the silent test.
			name:   "a builtin reached through globalThis",
			source: "function Component() {\n  const x = globalThis.Date.now();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// Inside a try, which is control flow the walk has to pass through rather than stop at.
			name:   "a call inside a try block",
			source: "function Component() {\n  let x = 0;\n  try { x = Math.random(); } catch (e) {}\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// A phi merge. `r` is impure on both paths and React prints the name from whichever
			// the merge kept, which is `Date.now`; the assertion here is the count, and
			// TestPurityMergesAConditionalAlias asserts the name.
			name:   "an alias reassigned on one branch",
			source: "function Component(props: {c: boolean}) {\n  let r = Math.random;\n  if (props.c) { r = Date.now; }\n  const x = r();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// A self-calling wrapper, which is what the recursion guard exists for. Without it the
			// analysis does not terminate; with it React and this agree on one finding.
			name:   "a recursive wrapper that is called",
			source: "function Component() {\n  function f(n: number): number { if (n <= 0) return Math.random(); return f(n - 1); }\n  const x = f(3);\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// A wrapper called inside a loop. The call sits in a block the walk reaches on a back
			// edge, and the finding still belongs to the inner site, so it reports once.
			name:   "a wrapper called in a loop",
			source: "function Component(props: {xs: number[]}) {\n  const f = () => Math.random();\n  let t = 0;\n  for (const i of props.xs) { t += f(); }\n  return <div>{t}</div>;\n}\n",
			want:   1,
		},
		{
			// A callback passed to an ordinary function, which upstream treats as invoked. This and
			// its `useCustom` twin in the silent test are the pair that pins the hook exemption.
			name:   "a callback passed to an unknown function",
			source: "function Component() {\n  doThing(() => { console.log(Math.random()); });\n  return <div />;\n}\n",
			want:   1,
		},
		{
			// The most common real purity bug there is, and the corpus contains nothing like it: a
			// random key on a mapped list, remounting every row on every render. Found by running
			// the rule on realistic shapes rather than on fixtures, where it was a false negative.
			name:   "a random key inside a map callback",
			source: "function List(props: {items: string[]}) {\n  return <ul>{props.items.map((i) => <li key={Math.random()}>{i}</li>)}</ul>;\n}\n",
			want:   1,
		},
		{
			// An array method's callback. `map` carries no freeze, so its effects re-raise.
			name:   "a callback passed to Array.map",
			source: "function Component(props: {items: string[]}) {\n  const xs = props.items.map(() => Math.random());\n  return <div>{xs}</div>;\n}\n",
			want:   1,
		},
		{
			// A DOM listener, which reads as an escape and is not one to upstream.
			name:   "a callback passed to addEventListener",
			source: "function Component() {\n  window.addEventListener(\"x\", () => { console.log(Math.random()); });\n  return <div />;\n}\n",
			want:   1,
		},
		{
			// `useMemo` is the one hook whose callback runs during render, so it is the one hook
			// that does NOT exempt. Its `useCallback` twin is in the silent test with a
			// byte-identical callback.
			name:   "a callback passed to useMemo",
			source: "import {useMemo} from \"react\";\nfunction Component() {\n  const v = useMemo(() => Math.random(), []);\n  return <div>{v}</div>;\n}\n",
			want:   1,
		},
		{
			// A direct argument rather than a callback, so nothing about the exemption applies.
			name:   "an impure call as a direct hook argument",
			source: "import {useState} from \"react\";\nfunction Component() {\n  const [x] = useState(Math.random());\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The input that crashed the linter on Kirk's tree, and the reason the recursion guard
			// in `findingsOf` exists. A function passing ITSELF as a callback argument re-enters
			// its own frame: `findingsOf -> walk -> step -> callbackArguments -> findingsOf` on one
			// function pointer, which ran until `fatal error: stack overflow`.
			//
			// No fixture caught it, because a self-reference on the plain CALL path resolves
			// through `byName` and cannot recur, and the callback path was added after the guard
			// was measured unreachable and deleted. It reports once, matching React.
			name:   "a function passing itself as a callback",
			source: "function Component() {\n  const f = () => { doThing(f); return Math.random(); };\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The same cycle entered from the outside rather than through a call, so the guard is
			// exercised on both entry paths.
			name:   "a self-referencing callback passed from outside",
			source: "function Component() {\n  const f = () => { doThing(f); Math.random(); };\n  doThing(f);\n  return <div />;\n}\n",
			want:   1,
		},
		{
			// Two functions passing each other, which is the same cycle at length two. A guard
			// keyed on a single in-progress function rather than on a set would still recur here.
			name:   "two functions passing each other as callbacks",
			source: "function Component() {\n  const a = () => { doThing(b); return Math.random(); };\n  const b = () => { doThing(a); return 1; };\n  const x = a();\n  return <div>{x}</div>;\n}\n",
			want:   1,
		},
		{
			// The same builtin twice directly is TWO findings, unlike the wrapper case above. The
			// pair is what shows dedup is a property of where the finding lives rather than a
			// count of names.
			name:   "the same builtin called twice directly",
			source: "function Component() {\n  const a = Math.random();\n  const b = Math.random();\n  return <div>{a}{b}</div>;\n}\n",
			want:   2,
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			result := runPurityFixture(t, testCase.source)
			want := make([]string, testCase.want)
			for index := range want {
				want[index] = messagePurityImpureCallId
			}
			rule_testing.ExpectFindings(t, result, want...)
		})
	}
}

// TestPurityStaysSilentOnMeasuredInputs covers everything React passes.
//
// These are the cases that catch a port, and every one was run through React's own rule and came
// back with no diagnostic. Several look like they should report, and the comment says why they do
// not, because a reader who thinks a silence is a bug will helpfully repair it into a divergence.
func TestPurityStaysSilentOnMeasuredInputs(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		source string
	}{
		{
			// The twin of "a nested arrow that is called". Byte-identical wrapper, never invoked,
			// and React is silent. This single pair is why the rule is not a lexical match.
			name:   "a nested arrow that is never called",
			source: "function Component() {\n  const f = () => Math.random();\n  return <div onClick={f} />;\n}\n",
			// nothing
		},
		{
			// The same wrapper handed to JSX as a prop rather than called.
			name:   "a wrapper passed as a prop",
			source: "function Component() {\n  const f = () => Math.random();\n  return <button onClick={f}>go</button>;\n}\n",
		},
		{
			// A plain function is not a compilation unit, so nothing in it is render.
			name:   "a lowercase helper",
			source: "function helper() {\n  return Math.random();\n}\n",
		},
		{
			// Capitalized but with no JSX and no hook call, so React does not compile it and this
			// is silent. It reads exactly like the reporting case and is not one.
			name:   "a capitalized function with no JSX and no hook",
			source: "function Component() {\n  return Math.random();\n}\n",
		},
		{
			// A class component's render is not a compilation unit either.
			name:   "a class component render method",
			source: "class C extends React.Component {\n  render() { return <div>{Math.random()}</div>; }\n}\n",
		},
		{
			// The effect callback is frozen by `useEffect`'s own signature, so its effects are
			// never re-raised. Its twin `setTimeout` is in the firing test.
			name:   "inside a useEffect callback",
			source: "import {useEffect} from \"react\";\nfunction Component() {\n  useEffect(() => { console.log(Math.random()); }, []);\n  return <div />;\n}\n",
		},
		{
			// `useCallback` produces a function that is not invoked during render, so unlike
			// `useMemo` it is silent even when the result is later called.
			name:   "inside a useCallback callback",
			source: "import {useCallback} from \"react\";\nfunction Component() {\n  const f = useCallback(() => Math.random(), []);\n  return <div onClick={f} />;\n}\n",
		},
		{
			// The lazy initializer runs once, not on every render.
			name:   "inside a useState lazy initializer",
			source: "import {useState} from \"react\";\nfunction Component() {\n  const [x] = useState(() => Math.random());\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A module-scope helper is opaque to upstream, which only knows the effects of
			// functions it lowered as part of the unit. The largest hole in the rule, and
			// upstream's rather than this port's.
			name:   "a module-scope helper that is called",
			source: "const g = () => Math.random();\nfunction Component() {\n  const x = g();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A local binding shadowing the global. This is the case the type checker buys, and
			// with a nil checker the rule reports it.
			name:   "a local binding shadowing Math",
			source: "function Component() {\n  const Math = {random: () => 1};\n  const x = Math.random();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A parameter shadowing the global, which resolves through a different declaration
			// shape than the const above.
			name:   "a parameter shadowing Math",
			source: "function Component(Math: {random: () => number}) {\n  const x = Math.random();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// An import shadowing the global. The binding kind is what declines this one.
			name:   "an import shadowing Math",
			source: "import Math from \"./m\";\nfunction Component() {\n  const x = Math.random();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A module-scope binding shadowing the global. Distinct from the import case: the
			// checker resolves both, and both are declared in a real source file rather than in a
			// declaration file, which is the test the rule applies.
			name:   "a module-scope binding shadowing Math",
			source: "const Math = {random: () => 1};\nfunction Component() {\n  const x = Math.random();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A genuinely dynamic property key. React is SILENT on `Math[props.k]()` even where the
			// type narrows the key to `'random'`, because the compiler resolves a computed key only
			// when it folds to a literal. Written for a surviving mutant that made a non-literal key
			// read as `random`; with that mutation this input reports and pristine does not, which
			// is the separation the count assertions elsewhere could not produce.
			name:   "a computed property with a dynamic key",
			source: "function Component(props: {k: 'random'}) {\n  const x = Math[props.k]();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// A property chain off a NESTED FUNCTION value, which is the input that separates the
			// container test in `purityLoadProperty` from the branches below it. Written for a
			// surviving mutant that dropped that test: without it, `f`'s empty CanonicalName makes
			// it read as the transparent `globalThis` container, `f.Date` becomes the `Date`
			// container, and `f.Date.now()` reports.
			//
			// # This case is silent here and REPORTS upstream, and that is a recorded divergence
			//
			// React reports at `Math.random` on line 2, not at this call. The reason is not the
			// property chain: measured, `const f = () => Math.random(); const x = f.Date;` alone is
			// SILENT, while `doThing(f)` and `f.z = 1` both REPORT at the same inner span. So what
			// upstream is reacting to is the impure function ESCAPING to somewhere it might be
			// called, which its aliasing model tracks and this port does not.
			//
			// The divergence is stated rather than repaired. Reproducing it needs the escape half
			// of the mutation aliasing model, which is the machinery `immutability` is blocked on,
			// and guessing at a subset of it would report inputs upstream passes. What is asserted
			// here is this rule's actual behaviour, so the next reader sees the gap rather than
			// inheriting a comment claiming the silence is correct.
			name:   "a property chain off a nested function value",
			source: "function Component() {\n  const f = () => Math.random();\n  const x = f.Date.now();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// `useLayoutEffect` freezes its callback the same way `useEffect` does.
			name:   "inside a useLayoutEffect callback",
			source: "import {useLayoutEffect} from \"react\";\nfunction Component() {\n  useLayoutEffect(() => { console.log(Math.random()); }, []);\n  return <div />;\n}\n",
		},
		{
			// So does `useInsertionEffect`, and all three are reached by the hook-name test rather
			// than by naming each one.
			name:   "inside a useInsertionEffect callback",
			source: "import {useInsertionEffect} from \"react\";\nfunction Component() {\n  useInsertionEffect(() => { console.log(Math.random()); }, []);\n  return <div />;\n}\n",
		},
		{
			// A lazy ref initializer, which runs once like useState's.
			name:   "inside a useRef lazy initializer",
			source: "import {useRef} from \"react\";\nfunction Component() {\n  const r = useRef(() => Math.random());\n  return <div />;\n}\n",
		},
		{
			// Only `random` is impure on `Math`. A rule keyed on the container alone reports this.
			name:   "a pure method on an impure container",
			source: "function Component() {\n  const x = Math.floor(1.5);\n  return <div>{x}</div>;\n}\n",
		},
		{
			// Only `Date.now` is impure. The constructor is not, so a rule keyed on the name
			// `Date` reports this.
			name:   "the Date constructor",
			source: "function Component() {\n  const d = new Date();\n  return <div>{String(d)}</div>;\n}\n",
		},
		{
			// `window` is not a modelled global, so the chain dies at the first property. Its twin
			// `globalThis.Date.now()` reports, and the asymmetry is upstream's.
			name:   "a builtin reached through window",
			source: "function Component() {\n  const x = window.Math.random();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// Storing into an object loses the value; upstream does not chase it back out.
			name:   "a builtin held in an object property",
			source: "function Component() {\n  const o = {r: Math.random};\n  const x = o.r();\n  return <div>{x}</div>;\n}\n",
		},
		{
			// The reference without the call. Reading the function is not calling it.
			name:   "a builtin referenced but not called",
			source: "function Component() {\n  const r = Math.random;\n  return <div>{String(r)}</div>;\n}\n",
		},
		{
			// A hook-named callee freezes a callback argument, so a custom hook is silent where an
			// ordinary function is not. Its twin `doThing` reports.
			name:   "a callback passed to a custom hook",
			source: "function Component() {\n  useCustom(() => { console.log(Math.random()); });\n  return <div />;\n}\n",
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			rule_testing.ExpectClean(t, runPurityFixture(t, testCase.source))
		})
	}
}

// TestPurityMessageNamesTheBuiltin asserts the rendered text, exactly.
//
// The id assertion cannot see anything the format string does, so a mutation moving only the
// per-finding text reads as a surviving mutant with no visible cause. The literal here is typed
// rather than built from the rule's own constants, because comparing a diagnostic to the constant
// it was reported with is an equality both sides of which move together under mutation.
func TestPurityMessageNamesTheBuiltin(t *testing.T) {
	t.Parallel()

	result := runPurityFixture(t, "function Component() {\n  const d = Date.now();\n  return <div>{d}</div>;\n}\n")
	if len(result.Diagnostics) != 1 {
		t.Fatalf("got %d findings, want 1", len(result.Diagnostics))
	}
	got := result.Diagnostics[0].Message.Description
	const wantPrefix = "`Date.now` is an impure function. Calling an impure function during render makes"
	if !strings.HasPrefix(got, wantPrefix) {
		t.Errorf("the message does not name the builtin\n got: %q\nwant prefix: %q", got, wantPrefix)
	}
	if strings.Contains(got, "``") || strings.Contains(got, "`Date.now`` ") {
		t.Errorf("the message has a doubled backtick: %q", got)
	}
}

// TestPurityMessageNamesEachBuiltinSeparately asserts that the canonical name is per finding rather
// than a constant.
//
// Written because a rule printing one fixed name would pass every count assertion in this file. The
// corpus fixture has all three builtins in one component, so this reads the three rendered messages
// and requires each name once.
func TestPurityMessageNamesEachBuiltinSeparately(t *testing.T) {
	t.Parallel()

	result := runPurityFixture(t, purityImpureFunctionsInRender)
	if len(result.Diagnostics) != 3 {
		t.Fatalf("got %d findings, want 3", len(result.Diagnostics))
	}
	want := map[string]bool{"`Date.now`": false, "`performance.now`": false, "`Math.random`": false}
	for _, diagnostic := range result.Diagnostics {
		for name := range want {
			if strings.HasPrefix(diagnostic.Message.Description, name+" is an impure function.") {
				want[name] = true
			}
		}
	}
	for name, found := range want {
		if !found {
			t.Errorf("no finding named %s; the canonical name is not per finding", name)
		}
	}
}

// TestPurityMergesAConditionalAlias asserts which name survives a phi merge.
//
// `let r = Math.random; if (c) { r = Date.now; } r();` is impure on both incoming paths, so the
// count assertion elsewhere cannot see which one the merge kept. React prints `Date.now`, measured
// on that exact input, and this pins it: a merge that took the other operand would still report
// once and would name the wrong builtin.
func TestPurityMergesAConditionalAlias(t *testing.T) {
	t.Parallel()

	result := runPurityFixture(t, "function Component(props: {c: boolean}) {\n  let r = Math.random;\n  if (props.c) { r = Date.now; }\n  const x = r();\n  return <div>{x}</div>;\n}\n")
	if len(result.Diagnostics) != 1 {
		t.Fatalf("got %d findings, want 1", len(result.Diagnostics))
	}
	got := result.Diagnostics[0].Message.Description
	if !strings.HasPrefix(got, "`Date.now` is an impure function.") {
		t.Errorf("the merge kept the wrong operand: %q", got)
	}
}

// TestPurityPointsAtTheCall asserts the span, on both shapes whose span a lexical port gets wrong.
//
// `ExpectFindings` asserts ids and count and nothing else, so a rule pointing at the wrong node
// passes a complete fixture pair. The source is sliced with the finding's own range and compared to
// the text, and the expectation is the text React underlines.
//
// The harness writes `strings.TrimSpace(contents)+"\n"`, so a source with a leading newline sits one
// byte off its Go literal. Every source here is written without one, and the slice is taken from
// the same string the harness was handed.
func TestPurityPointsAtTheCall(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name   string
		source string
		want   string
	}{
		{
			// React underlines `Date.now()`, the whole call expression, not the callee.
			name:   "a direct call",
			source: "function Component() {\n  const d = Date.now();\n  return <div>{d}</div>;\n}\n",
			want:   "Date.now()",
		},
		{
			// Through an alias React underlines `r()`, which no reading of the callee's syntax can
			// produce. This is the span assertion that separates value tracking from name matching.
			name:   "a call through an alias",
			source: "function Component() {\n  const r = Math.random;\n  const x = r();\n  return <div>{x}</div>;\n}\n",
			want:   "r()",
		},
		{
			// For a called wrapper React underlines the INNER call rather than the call that
			// triggered it, which is why a finding is recorded against the site that raised it.
			name:   "a called nested wrapper",
			source: "function Component() {\n  const f = () => Math.random();\n  const x = f();\n  return <div>{x}</div>;\n}\n",
			want:   "Math.random()",
		},
		{
			// The whole member chain, including the container.
			name:   "a call through globalThis",
			source: "function Component() {\n  const x = globalThis.Date.now();\n  return <div>{x}</div>;\n}\n",
			want:   "globalThis.Date.now()",
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			result := runPurityFixture(t, testCase.source)
			if len(result.Diagnostics) != 1 {
				t.Fatalf("got %d findings, want 1", len(result.Diagnostics))
			}
			written := strings.TrimSpace(testCase.source) + "\n"
			diagnostic := result.Diagnostics[0]
			got := written[diagnostic.Range.Pos():diagnostic.Range.End()]
			if got != testCase.want {
				t.Errorf("the finding points at %q, want %q", got, testCase.want)
			}
		})
	}
}

// TestPurityRequiresTheTypedHarness asserts that the checker is load-bearing.
//
// This rule reads no type, so the `NeedsTypeChecker` declaration reads as over-declaration and a
// later reader could remove it and watch every test above stay green. It would not stay correct:
// lowering resolves a free identifier through the checker, and without one a shadowed binding
// becomes indistinguishable from the real global.
//
// The plain harness hands the rule a nil checker, and the rule returns early rather than reporting,
// so this asserts silence on an input the typed harness reports. A revert that dropped the
// declaration would make the shadow case above red, and this makes the mechanism explicit.
func TestPurityRequiresTheTypedHarness(t *testing.T) {
	t.Parallel()

	const source = "function Component() {\n  const d = Date.now();\n  return <div>{d}</div>;\n}\n"

	typed := runPurityFixture(t, source)
	if len(typed.Diagnostics) != 1 {
		t.Fatalf("the typed harness got %d findings, want 1", len(typed.Diagnostics))
	}

	untyped := rule_testing.Run(t, Purity, "fixture.tsx", source)
	rule_testing.ExpectClean(t, untyped)
}
