package notices

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/system-inc/cohere/internal/release/packaging"
)

// generatedBy heads both files, so nobody edits what the next generation overwrites.
const generatedBy = "Generated by `go run ./internal/release/tools/notices`. Edit internal/release/notices, not this file."

// compilerFork is the repository the vendored compiler is built from, a modified fork of Microsoft's.
const compilerFork = "https://github.com/kirkouimet/TypeScript"

// renderNotice is NOTICE: the statement Apache-2.0 section 4 asks of a work built on the TypeScript
// compiler, then Microsoft's NOTICE.txt from the compiler's checkout, unmodified.
//
// No commit is named, so the file changes only when Microsoft's notice does, not on every compiler pin.
//
// Microsoft's file has CRLF line endings, and this repository stores every text file as LF
// (.gitattributes), so the copy is written with LF. A CRLF copy would be converted on commit, and every
// fresh clone would then differ from what this writes.
func renderNotice(moduleDirectory string) ([]byte, error) {
	microsoft, err := os.ReadFile(filepath.Join(moduleDirectory, "TypeScript", "NOTICE.txt"))
	if err != nil {
		return nil, fmt.Errorf("reading the TypeScript compiler's NOTICE.txt, which NOTICE carries unmodified: %w", err)
	}
	microsoft = bytes.ReplaceAll(microsoft, []byte("\r\n"), []byte("\n"))
	var builder strings.Builder
	builder.WriteString("cohere\n" + release.CopyrightLine + "\n\n")
	builder.WriteString("cohere includes the TypeScript compiler (typescript-go), Copyright (c) Microsoft Corporation, licensed\n")
	builder.WriteString("under the Apache License, Version 2.0. cohere builds a modified version of it, from the fork at\n")
	builder.WriteString(compilerFork + ", which changes files of the original.\n\n")
	builder.WriteString("The original's NOTICE.txt follows, unmodified but for its line endings. The licenses of everything else\n")
	builder.WriteString("cohere is built on are in THIRD_PARTY_NOTICES.md.\n\n")
	builder.WriteString(generatedBy + "\n\n")
	builder.WriteString(strings.Repeat("-", 100) + "\n\n")
	builder.Write(microsoft)
	if !strings.HasSuffix(string(microsoft), "\n") {
		builder.WriteString("\n")
	}
	return []byte(builder.String()), nil
}

// renderThirdPartyNotices is THIRD_PARTY_NOTICES.md: every project cohere is built on, grouped by where
// it reaches a user, each with its license in full.
func renderThirdPartyNotices(moduleDirectory string, compiled []Module, repositoryOnly []Module, swiftPins []swiftPin) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("# Third-party notices\n\n")
	builder.WriteString("cohere is licensed `MIT OR Apache-2.0` ([LICENSE-MIT](LICENSE-MIT), [LICENSE-APACHE](LICENSE-APACHE)). It is built\n")
	builder.WriteString("on the work of the projects below, each under its own license, reproduced here in full. The TypeScript\n")
	builder.WriteString("compiler's notice is in [NOTICE](NOTICE).\n\n")
	builder.WriteString(generatedBy + "\n\n")

	builder.WriteString("## Compiled into cohere\n\n")
	builder.WriteString("In the `cohere` binary every platform package ships.\n\n")

	goLicense, err := licenseTexts.ReadFile("licenses/go.txt")
	if err != nil {
		return nil, err
	}
	writeEntry(&builder, entry{Name: "The Go toolchain and standard library", URL: "https://go.dev", License: "BSD-3-Clause",
		Carries: "The runtime and standard library linked into every Go binary.", Text: string(goLicense)})

	compilerLicense, err := os.ReadFile(filepath.Join(moduleDirectory, "TypeScript", "LICENSE.txt"))
	if err != nil {
		return nil, fmt.Errorf("reading the TypeScript compiler's license: %w", err)
	}
	writeEntry(&builder, entry{Name: "TypeScript (typescript-go)", URL: "https://github.com/microsoft/typescript-go", License: "Apache-2.0",
		Carries: "The TypeScript compiler, built from the modified fork " + compilerFork + ", and a few of its functions copied into internal/lint/checking. Its NOTICE is in [NOTICE](NOTICE).",
		Text:    string(compilerLicense)})

	for _, module := range compiled {
		if err := writeModule(&builder, module, "A Go module in cohere's build graph."); err != nil {
			return nil, err
		}
	}

	builder.WriteString("### Ported or vendored into cohere's source\n\n")
	builder.WriteString("Code adapted from these projects, translated to Go or copied in, compiled into the binary.\n\n")
	for _, upstream := range Upstreams {
		if upstream.Reach != Compiled {
			continue
		}
		if err := writeUpstream(&builder, upstream); err != nil {
			return nil, err
		}
	}

	builder.WriteString("## In the Swift engine\n\n")
	builder.WriteString("In `cohere-swift`, which the two macOS packages ship beside `cohere`. Packages resolved by\n")
	builder.WriteString("[swift/Package.resolved](swift/Package.resolved).\n\n")
	for _, pin := range swiftPins {
		license, known := swiftLicenses[pin.Identity]
		if !known {
			return nil, fmt.Errorf("the Swift engine resolves %s (%s), which has no license recorded in swiftLicenses", pin.Identity, pin.Location)
		}
		text, err := licenseTexts.ReadFile("licenses/" + license.File)
		if err != nil {
			return nil, err
		}
		writeEntry(&builder, entry{Name: pin.Identity, URL: pin.Location, Version: pin.Version, License: license.Expression,
			Carries: "A Swift package compiled into cohere-swift.", Text: string(text)})
	}

	builder.WriteString("## In this repository only\n\n")
	builder.WriteString("Used by tests and tools, or kept for them. None of these ship in any package.\n\n")
	for _, module := range repositoryOnly {
		if err := writeModule(&builder, module, "A Go module that tests and tools import."); err != nil {
			return nil, err
		}
	}
	for _, upstream := range Upstreams {
		if upstream.Reach != RepositoryOnly {
			continue
		}
		if err := writeUpstream(&builder, upstream); err != nil {
			return nil, err
		}
	}

	return []byte(strings.TrimRight(builder.String(), "\n") + "\n"), nil
}

// entry is one credited project, as it is written.
type entry struct {
	Name    string
	URL     string
	Version string
	License string
	Carries string
	Text    string

	// Note is written in place of Text when a project publishes no license text.
	Note string
}

func writeEntry(builder *strings.Builder, entry entry) {
	builder.WriteString("### " + entry.Name + "\n\n")
	builder.WriteString("- Source: " + entry.URL + "\n")
	if entry.Version != "" {
		builder.WriteString("- Version: " + entry.Version + "\n")
	}
	builder.WriteString("- License: `" + entry.License + "`\n")
	builder.WriteString("- In cohere: " + entry.Carries + "\n\n")
	if entry.Text == "" {
		builder.WriteString(entry.Note + "\n\n")
		return
	}
	// Four backticks, so a license that quotes code in three can't close the block early.
	builder.WriteString("````text\n")
	builder.WriteString(strings.TrimRight(strings.ReplaceAll(entry.Text, "\r\n", "\n"), "\n \t") + "\n")
	builder.WriteString("````\n\n")
}

func writeModule(builder *strings.Builder, module Module, carries string) error {
	license, known := moduleLicenses[module.Path]
	if !known {
		return fmt.Errorf("%s@%s is in cohere's module graph with no license recorded in moduleLicenses: read its license and add it", module.Path, module.Version)
	}
	text, err := readModuleLicense(module)
	if err != nil {
		return err
	}
	// A module only some platforms link says which, since the rest ship without it.
	if len(module.Targets) > 0 {
		carries += " Linked on " + strings.Join(module.Targets, ", ") + " only."
	}
	writeEntry(builder, entry{Name: module.Path, URL: "https://pkg.go.dev/" + module.Path + "@" + module.Version, Version: module.Version,
		License: license, Carries: carries, Text: text})
	return nil
}

func writeUpstream(builder *strings.Builder, upstream Upstream) error {
	if (upstream.LicenseFile == "") == (upstream.Note == "") {
		return fmt.Errorf("%s needs exactly one of a license file and a note saying why there is none", upstream.Name)
	}
	if upstream.LicenseFile == "" {
		writeEntry(builder, entry{Name: upstream.Name, URL: upstream.URL, Version: upstream.Version, License: upstream.License,
			Carries: upstream.Carries, Note: upstream.Note})
		return nil
	}
	text, err := licenseTexts.ReadFile("licenses/" + upstream.LicenseFile)
	if err != nil {
		return fmt.Errorf("%s names the license file %s, which isn't in internal/release/notices/licenses: %w", upstream.Name, upstream.LicenseFile, err)
	}
	writeEntry(builder, entry{Name: upstream.Name, URL: upstream.URL, Version: upstream.Version, License: upstream.License,
		Carries: upstream.Carries, Text: string(text)})
	return nil
}
