// Command generate_languages captures the languages markdown's embed infers a parser from, from the
// bundles the oracle runs, and writes them as Go.
//
// Usage:
//
//	go run ./internal/format/markdown/tools/generate_languages [-output <file.go>] [-check]
//
// embed.js formats a fenced code block when inferParser (src/utilities/infer-parser.js) finds a parser
// for its info string, by language name, then alias, then extension, over options.plugins reversed and
// flattened into their languages. The engine passes prettierPlugins, an object the standalone build
// turns into Object.values in evaluation order, so the order and the lists are read from the evaluated
// bundles rather than from linguist, which would drift from what the oracle ran.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"

	"github.com/dop251/goja"
	"github.com/system-inc/cohere/internal/format/prettier"
)

func main() {
	output := flag.String("output", filepath.Join("internal", "format", "markdown", "languages_generated.go"), "where to write the Go")
	check := flag.Bool("check", false, "regenerate and fail if the committed file disagrees")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *check {
		committed, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if !bytes.Equal(committed, generated) {
			fmt.Fprintf(os.Stderr, "%s is stale: regenerate it\n", *output)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

type language struct {
	Name       string   `json:"name"`
	Aliases    []string `json:"aliases"`
	Extensions []string `json:"extensions"`
	Parser     string   `json:"parser"`
}

func generate() ([]byte, error) {
	bundles, err := prettier.Bundles()
	if err != nil {
		return nil, err
	}
	runtime := goja.New()
	for _, name := range prettier.BundleFiles {
		if _, err := runtime.RunString(string(bundles.Files[name])); err != nil {
			return nil, fmt.Errorf("evaluating %s: %w", name, err)
		}
	}

	// inferParser: options.plugins.toReversed().flatMap((plugin) => plugin.languages ?? []), and a
	// language answers with parsers[0].
	value, err := runtime.RunString(`
		JSON.stringify(
			Object.values(prettierPlugins)
				.toReversed()
				.flatMap((plugin) => plugin.languages ?? [])
				.map((language) => ({
					name: language.name,
					aliases: language.aliases ?? [],
					extensions: language.extensions ?? [],
					parser: language.parsers[0],
				})),
		)
	`)
	if err != nil {
		return nil, err
	}
	var languages []language
	if err := json.Unmarshal([]byte(value.String()), &languages); err != nil {
		return nil, err
	}

	// Controls: a language found by each of the three routes, and a name nothing claims.
	byName := map[string]string{}
	for _, language := range languages {
		byName[language.Name] = language.Parser
	}
	for name, parser := range map[string]string{"TypeScript": "typescript", "JSON": "json", "Markdown": "markdown", "YAML": "yaml"} {
		if byName[name] != parser {
			return nil, fmt.Errorf("control failed: %s answered %q, want %q", name, byName[name], parser)
		}
	}

	var source bytes.Buffer
	source.WriteString("// Code generated by generate_languages. DO NOT EDIT.\n//\n")
	source.WriteString("// Captured from the embedded bundles, run by goja: the languages inferParser searches, in its order.\n")
	source.WriteString("// Regenerate with:\n//\n")
	source.WriteString("//\tgo run ./internal/format/markdown/tools/generate_languages\n\n")
	source.WriteString("package markdown\n\n")
	source.WriteString("// inferableLanguages are options.plugins reversed and flattened into their languages, each with its\n")
	source.WriteString("// first parser.\n")
	source.WriteString("var inferableLanguages = []inferableLanguage{\n")
	for _, language := range languages {
		fmt.Fprintf(&source, "\t{name: %s, aliases: %s, extensions: %s, parser: %s},\n",
			strconv.Quote(language.Name), quoteAll(language.Aliases), quoteAll(language.Extensions), strconv.Quote(language.Parser))
	}
	source.WriteString("}\n")

	return format.Source(source.Bytes())
}

func quoteAll(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	var buffer bytes.Buffer
	buffer.WriteString("[]string{")
	for index, value := range values {
		if index > 0 {
			buffer.WriteString(", ")
		}
		buffer.WriteString(strconv.Quote(value))
	}
	buffer.WriteString("}")
	return buffer.String()
}
