/*
 * Capture what the engine reads for every class of the wave-1 roots, so the Go table is checked
 * against measurements rather than against the extraction that produced it.
 *
 * The table in `internal/tailwind/frameworkutility.go` was generated by pattern-matching
 * `utilities.ts`, and an extractor and the source are two different claims. Spot-checking the
 * extraction against the source already found one defect in it. This closes the loop the other way:
 * it asks the engine what each root actually reads, over every class the registry advertises for it
 * plus probes that reach each resolution branch.
 *
 * Usage:
 *
 *   node tools/gen_tailwind_functional/wave1.mjs <theme.css> [--resolve-root <dir>] > wave1.json
 */

import { loadDesignSystem, parseCandidate, readingOf } from '../gen_tailwind_descriptors/loader.mjs';

const entryPointArgument = process.argv[2];
if (!entryPointArgument) {
    process.stderr.write('usage: wave1.mjs <theme.css> [--resolve-root <dir>]\n');
    process.exit(2);
}

function flagValue(name) {
    const index = process.argv.indexOf(name);
    return index === -1 ? undefined : process.argv[index + 1];
}

const { designSystem, tailwindVersion, entryPoint } = await loadDesignSystem(
    entryPointArgument,
    flagValue('--resolve-root'),
);

/*
 * The roots, taken from the Go table rather than retyped.
 *
 * A hand-written list here drifted on its first run: it carried `delay`, which is not a wave-1 root,
 * and omitted `z`, which is. The test caught it as a fixture-versus-table disagreement, which is the
 * right failure, but the list has no business being written twice. Regenerate this array from
 * FrameworkFunctionalUtilities when the table changes.
 */
const roots = [
    'align',
    'animate',
    'bg-position',
    'bg-size',
    'col',
    'col-end',
    'col-start',
    'columns',
    'contain',
    'cursor',
    'delay',
    'font-features',
    'grow',
    'list',
    'list-image',
    'mask-position',
    'mask-radial-at',
    'mask-size',
    'object',
    'opacity',
    'order',
    'origin',
    'outline-offset',
    'perspective',
    'perspective-origin',
    'row',
    'row-end',
    'row-start',
    'shrink',
    'tab',
    'will-change',
    'z',
    'zoom',
];

/*
 * The population is the registry's own classes for each root, plus branch probes.
 *
 * The registry classes are what the differential will compare, so they are the population that
 * matters. The probes are added because a registry advertises theme-backed and static values and
 * advertises no arbitrary ones at all, so a run over registry classes alone would never exercise the
 * arbitrary branch or the rejections.
 */
/*
 * The probe suffixes, and why the fractional ones are here.
 *
 * The registry advertises theme-backed and static values, so a run over registry classes alone never
 * reaches the arbitrary branch, never reaches a rejection, and never separates one bare-value
 * predicate from another. `-2.5` and `-1.3` are the pair that does the last of those: `isPositiveInteger`
 * rejects both, `isValidOpacityValue` accepts `2.5` and rejects `1.3`. Without them, swapping
 * opacity's predicate for the integer one changed no answer in the whole fixture and the mutation
 * survived, which is how the gap was found.
 */
const probeSuffixes = ['', '-4', '-0', '-1', '-auto', '-none', '-[3px]', '-[var(--a)]', '-1/2', '/50', '-2.5', '-1.3'];

const registryByRoot = new Map();
for (const entry of designSystem.getClassList?.() ?? []) {
    const name = Array.isArray(entry) ? entry[0] : typeof entry === 'string' ? entry : entry?.name;
    if (typeof name !== 'string') continue;
    const candidate = parseCandidate(designSystem, name);
    if (!candidate || candidate.kind !== 'functional' || !candidate.root) continue;
    if (!roots.includes(candidate.root)) continue;
    const list = registryByRoot.get(candidate.root) ?? [];
    list.push(name);
    registryByRoot.set(candidate.root, list);
}

const cases = [];
for (const root of roots) {
    const names = new Set(registryByRoot.get(root) ?? []);
    for (const suffix of probeSuffixes) names.add(root + suffix);
    for (const negative of ['-' + root + '-1', '-' + root + '-4']) names.add(negative);

    for (const className of names) {
        const candidate = parseCandidate(designSystem, className);
        const reading = readingOf(designSystem, className);
        cases.push({
            root,
            className,
            parsedRoot: candidate?.root ?? null,
            kind: candidate?.kind ?? null,
            reading: reading === null ? null : { order: reading.order, count: reading.count },
        });
    }
}

const answered = cases.filter((entry) => entry.reading !== null).length;
const rejected = cases.length - answered;
if (answered === 0) {
    process.stderr.write('wave1.mjs: no case produced a reading, so a comparison against this fixture would pass by comparing nothing\n');
    process.exit(4);
}
if (rejected === 0) {
    process.stderr.write('wave1.mjs: no case was rejected, so the branches that must produce nothing are unexercised\n');
    process.exit(4);
}

process.stdout.write(JSON.stringify({
    tailwindVersion,
    entryPoint,
    groundTruth: 'compileAstNodes propertySort, via readingOf',
    rootCount: roots.length,
    caseCount: cases.length,
    answered,
    rejected,
    cases,
}, null, 2) + '\n');
