// Code generated by internal/lint/rules/tailwind/tools/generate_collapse. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./internal/lint/rules/tailwind/tools/generate_collapse -entry-point <theme.css>
//
// Source: Tailwind 4.3.3, enumerated from theme.css.
// 341 functional roots produced 57970 candidate pairs, of which 45 collapse.
//
// Each entry is a fact about roots rather than about classes: `px + py => p`
// holds for every value the two roots share, so the table is small and does not grow with the
// codebase. Enumerated from the design system's own class list rather than from any codebase's
// usage, because a table built from observed classes is silently missing every family nobody has
// written yet.
//
// Only CollapseFamilies is claimed invariant. The other tables in this file are per-repository by
// construction, and KnownStatics is the proof: it carries markdown-content, one of ahra's own
// @utility blocks, under a header naming only a Tailwind version. Read this file as one framework
// fact sitting beside several repository extractions, not as framework data throughout.
//
// CollapseFamilies re-measured on this run against:
//	tools/generate_descriptor_base/testdata/independent_theme.css (316 roots, 49770 pairs)
//
// Identical families, down to the value each was discovered at and whether it needs logicalToPhysical.

package tailwind

// CollapseFamily is two utility roots that merge into a third.
//
// The merge only happens when everything except the root already agrees between the two classes:
// their variants, their importance, and their value. That precondition is the gate's job; this
// table answers only "if those match, do these two roots have a shorthand".
type CollapseFamily struct {
	First  string
	Second string
	Output string
	// RequiresLogicalToPhysical is true when the canonicalizer collapses this pair only while it
	// reads logical properties as their physical longhands, its logicalToPhysical option. With
	// `logical: false`, enforce-canonical-classes skips the family.
	RequiresLogicalToPhysical bool
}

// CollapseFamilies is every family the installed Tailwind knows, sorted by input roots.
//
// Upstream ships shorthand data and it does not derive this. Two maps keyed on CSS property,
// `padding-inline: [padding-left, padding-right]` and its kin, cover inset, margin, padding,
// scroll-margin, scroll-padding, border width/style/colour, gap, overflow, overscroll-behavior and
// ten logical block/inline pairs. This is keyed on utility roots, `pl + pr => px`, and bridging the
// two key spaces is `canonicalizeCandidates`, the signature-equivalence search `enumerate.mjs`
// prices at eight to ten thousand lines that changes every Tailwind minor.
//
// It also holds families no CSS shorthand covers, which is the half that makes the two genuinely
// different questions rather than one restated: `h + w => size`, `skew`, `translate`, the `rounded-*`
// corners, the `mask-*` edges and `border-spacing` collapse through a utility relationship rather
// than a property one.
var CollapseFamilies = []CollapseFamily{
	{First: "-bottom", Second: "-top", Output: "-inset-y", RequiresLogicalToPhysical: true},
	{First: "-inset-x", Second: "-inset-y", Output: "-inset", RequiresLogicalToPhysical: true},
	{First: "-left", Second: "-right", Output: "-inset-x", RequiresLogicalToPhysical: true},
	{First: "-mb", Second: "-mt", Output: "-my", RequiresLogicalToPhysical: true},
	{First: "-ml", Second: "-mr", Output: "-mx", RequiresLogicalToPhysical: true},
	{First: "-mx", Second: "-my", Output: "-m", RequiresLogicalToPhysical: true},
	{First: "-scroll-mb", Second: "-scroll-mt", Output: "-scroll-my", RequiresLogicalToPhysical: true},
	{First: "-scroll-ml", Second: "-scroll-mr", Output: "-scroll-mx", RequiresLogicalToPhysical: true},
	{First: "-scroll-mx", Second: "-scroll-my", Output: "-scroll-m", RequiresLogicalToPhysical: true},
	{First: "-skew-x", Second: "-skew-y", Output: "-skew", RequiresLogicalToPhysical: false},
	{First: "-translate-x", Second: "-translate-y", Output: "-translate", RequiresLogicalToPhysical: false},
	{First: "border-b", Second: "border-t", Output: "border-y", RequiresLogicalToPhysical: true},
	{First: "border-l", Second: "border-r", Output: "border-x", RequiresLogicalToPhysical: true},
	{First: "border-spacing-x", Second: "border-spacing-y", Output: "border-spacing", RequiresLogicalToPhysical: false},
	{First: "border-x", Second: "border-y", Output: "border", RequiresLogicalToPhysical: true},
	{First: "bottom", Second: "top", Output: "inset-y", RequiresLogicalToPhysical: true},
	{First: "gap-x", Second: "gap-y", Output: "gap", RequiresLogicalToPhysical: false},
	{First: "h", Second: "w", Output: "size", RequiresLogicalToPhysical: false},
	{First: "inset-x", Second: "inset-y", Output: "inset", RequiresLogicalToPhysical: true},
	{First: "left", Second: "right", Output: "inset-x", RequiresLogicalToPhysical: true},
	{First: "mask-b-from", Second: "mask-t-from", Output: "mask-y-from", RequiresLogicalToPhysical: false},
	{First: "mask-b-to", Second: "mask-t-to", Output: "mask-y-to", RequiresLogicalToPhysical: false},
	{First: "mask-l-from", Second: "mask-r-from", Output: "mask-x-from", RequiresLogicalToPhysical: false},
	{First: "mask-l-to", Second: "mask-r-to", Output: "mask-x-to", RequiresLogicalToPhysical: false},
	{First: "max-w", Second: "max-w-screen", Output: "max-w", RequiresLogicalToPhysical: false},
	{First: "mb", Second: "mt", Output: "my", RequiresLogicalToPhysical: true},
	{First: "ml", Second: "mr", Output: "mx", RequiresLogicalToPhysical: true},
	{First: "mx", Second: "my", Output: "m", RequiresLogicalToPhysical: true},
	{First: "pb", Second: "pt", Output: "py", RequiresLogicalToPhysical: true},
	{First: "pl", Second: "pr", Output: "px", RequiresLogicalToPhysical: true},
	{First: "px", Second: "py", Output: "p", RequiresLogicalToPhysical: true},
	{First: "rounded-bl", Second: "rounded-br", Output: "rounded-b", RequiresLogicalToPhysical: false},
	{First: "rounded-bl", Second: "rounded-tl", Output: "rounded-l", RequiresLogicalToPhysical: false},
	{First: "rounded-br", Second: "rounded-tr", Output: "rounded-r", RequiresLogicalToPhysical: false},
	{First: "rounded-ee", Second: "rounded-se", Output: "rounded-e", RequiresLogicalToPhysical: false},
	{First: "rounded-es", Second: "rounded-ss", Output: "rounded-s", RequiresLogicalToPhysical: false},
	{First: "rounded-tl", Second: "rounded-tr", Output: "rounded-t", RequiresLogicalToPhysical: false},
	{First: "scroll-mb", Second: "scroll-mt", Output: "scroll-my", RequiresLogicalToPhysical: true},
	{First: "scroll-ml", Second: "scroll-mr", Output: "scroll-mx", RequiresLogicalToPhysical: true},
	{First: "scroll-mx", Second: "scroll-my", Output: "scroll-m", RequiresLogicalToPhysical: true},
	{First: "scroll-pb", Second: "scroll-pt", Output: "scroll-py", RequiresLogicalToPhysical: true},
	{First: "scroll-pl", Second: "scroll-pr", Output: "scroll-px", RequiresLogicalToPhysical: true},
	{First: "scroll-px", Second: "scroll-py", Output: "scroll-p", RequiresLogicalToPhysical: true},
	{First: "skew-x", Second: "skew-y", Output: "skew", RequiresLogicalToPhysical: false},
	{First: "translate-x", Second: "translate-y", Output: "translate", RequiresLogicalToPhysical: false},
}

// RootSelectorShapes used to be printed here and is not any more.
//
// internal/tailwind's SelectorShapeForRoot reads the nested-rule wrapper off the ported handle
// bodies, which is where upstream keeps it. The eight shapes this printed are reproduced exactly,
// and a repository block that declares a nested selector is answered rather than missed.

// ColorNames used to be printed here and is not any more.
//
// internal/rules/tailwind's valueIsColorIn asks the live theme's `--color` namespace, which is what
// upstream does, with IsColorKeyword beside it for the three keywords that sit in no namespace.
// Measured before the deletion: 558 of its 561 names answered by the theme and the other 3 by
// colorKeywords, 0 uncovered, and the table knew nothing of the three colours www-connected-app
// declares because it was generated from ahra.

// TailwindVersion is the version these families were enumerated from.
//
// Recorded so a mismatch between this and the installed Tailwind is greppable, and so a reader of a
// finding can tell which engine's opinion produced it.
const TailwindVersion = "4.3.3"
