// Code generated by internal/lint/rules/tailwind/tools/generate_collapse. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./internal/lint/rules/tailwind/tools/generate_collapse -entry-point <theme.css>
//
// Source: Tailwind 4.3.3, enumerated from theme.css.
// 341 functional roots produced 57970 candidate pairs, of which 45 collapse.
//
// Each entry is a fact about roots rather than about classes: `px + py => p`
// holds for every value the two roots share, so the table is small and does not grow with the
// codebase. Enumerated from the design system's own class list rather than from any codebase's
// usage, because a table built from observed classes is silently missing every family nobody has
// written yet.
//
// Only CollapseFamilies is claimed invariant. The other tables in this file are per-repository by
// construction, and KnownStatics is the proof: it carries markdown-content, one of ahra's own
// @utility blocks, under a header naming only a Tailwind version. Read this file as one framework
// fact sitting beside several repository extractions, not as framework data throughout.
//
// CollapseFamilies re-measured on this run against:
//	~/Projects/system/cohere/tools/tailwind/generate_descriptor_base/testdata/independent_theme.css (316 roots, 49770 pairs)
//
// Identical families, down to the value each was discovered at.

package tailwind

// CollapseFamily is two utility roots that merge into a third.
//
// The merge only happens when everything except the root already agrees between the two classes:
// their variants, their importance, and their value. That precondition is the gate's job; this
// table answers only "if those match, do these two roots have a shorthand".
type CollapseFamily struct {
	First  string
	Second string
	Output string
}

// CollapseFamilies is every family the installed Tailwind knows, sorted by input roots.
//
// Upstream ships shorthand data and it does not derive this. Two maps keyed on CSS property,
// `padding-inline: [padding-left, padding-right]` and its kin, cover inset, margin, padding,
// scroll-margin, scroll-padding, border width/style/colour, gap, overflow, overscroll-behavior and
// ten logical block/inline pairs. This is keyed on utility roots, `pl + pr => px`, and bridging the
// two key spaces is `canonicalizeCandidates`, the signature-equivalence search `enumerate.mjs`
// prices at eight to ten thousand lines that changes every Tailwind minor.
//
// It also holds families no CSS shorthand covers, which is the half that makes the two genuinely
// different questions rather than one restated: `h + w => size`, `skew`, `translate`, the `rounded-*`
// corners, the `mask-*` edges and `border-spacing` collapse through a utility relationship rather
// than a property one.
var CollapseFamilies = []CollapseFamily{
	{First: "-bottom", Second: "-top", Output: "-inset-y"},
	{First: "-inset-x", Second: "-inset-y", Output: "-inset"},
	{First: "-left", Second: "-right", Output: "-inset-x"},
	{First: "-mb", Second: "-mt", Output: "-my"},
	{First: "-ml", Second: "-mr", Output: "-mx"},
	{First: "-mx", Second: "-my", Output: "-m"},
	{First: "-scroll-mb", Second: "-scroll-mt", Output: "-scroll-my"},
	{First: "-scroll-ml", Second: "-scroll-mr", Output: "-scroll-mx"},
	{First: "-scroll-mx", Second: "-scroll-my", Output: "-scroll-m"},
	{First: "-skew-x", Second: "-skew-y", Output: "-skew"},
	{First: "-translate-x", Second: "-translate-y", Output: "-translate"},
	{First: "border-b", Second: "border-t", Output: "border-y"},
	{First: "border-l", Second: "border-r", Output: "border-x"},
	{First: "border-spacing-x", Second: "border-spacing-y", Output: "border-spacing"},
	{First: "border-x", Second: "border-y", Output: "border"},
	{First: "bottom", Second: "top", Output: "inset-y"},
	{First: "gap-x", Second: "gap-y", Output: "gap"},
	{First: "h", Second: "w", Output: "size"},
	{First: "inset-x", Second: "inset-y", Output: "inset"},
	{First: "left", Second: "right", Output: "inset-x"},
	{First: "mask-b-from", Second: "mask-t-from", Output: "mask-y-from"},
	{First: "mask-b-to", Second: "mask-t-to", Output: "mask-y-to"},
	{First: "mask-l-from", Second: "mask-r-from", Output: "mask-x-from"},
	{First: "mask-l-to", Second: "mask-r-to", Output: "mask-x-to"},
	{First: "max-w", Second: "max-w-screen", Output: "max-w"},
	{First: "mb", Second: "mt", Output: "my"},
	{First: "ml", Second: "mr", Output: "mx"},
	{First: "mx", Second: "my", Output: "m"},
	{First: "pb", Second: "pt", Output: "py"},
	{First: "pl", Second: "pr", Output: "px"},
	{First: "px", Second: "py", Output: "p"},
	{First: "rounded-bl", Second: "rounded-br", Output: "rounded-b"},
	{First: "rounded-bl", Second: "rounded-tl", Output: "rounded-l"},
	{First: "rounded-br", Second: "rounded-tr", Output: "rounded-r"},
	{First: "rounded-ee", Second: "rounded-se", Output: "rounded-e"},
	{First: "rounded-es", Second: "rounded-ss", Output: "rounded-s"},
	{First: "rounded-tl", Second: "rounded-tr", Output: "rounded-t"},
	{First: "scroll-mb", Second: "scroll-mt", Output: "scroll-my"},
	{First: "scroll-ml", Second: "scroll-mr", Output: "scroll-mx"},
	{First: "scroll-mx", Second: "scroll-my", Output: "scroll-m"},
	{First: "scroll-pb", Second: "scroll-pt", Output: "scroll-py"},
	{First: "scroll-pl", Second: "scroll-pr", Output: "scroll-px"},
	{First: "scroll-px", Second: "scroll-py", Output: "scroll-p"},
	{First: "skew-x", Second: "skew-y", Output: "skew"},
	{First: "translate-x", Second: "translate-y", Output: "translate"},
}

// RootSelectorShapes used to be printed here and is not any more.
//
// It held the eight roots whose utilities land somewhere other than the element itself. Upstream
// stores no such table: a handle body wraps its declarations in `rule(selector, [...])` and six
// roots do. Those bodies are ported, so `SelectorShapeForRoot` reads the wrapper off what the
// emitter produced and returns the same eight shapes, byte for byte.
//
// Its own comment had already found the reason a table cannot be right here: the invariance
// measurement across an independent design system was "necessary and insufficient", because a
// repository `@utility` block can declare a nested selector no corpus writes. Computing the shape
// removes the question rather than bounding it.

// ComposingRoots used to be printed here and is not any more.
//
// It answered whether two utilities of one root layer or overwrite, in 82 rows generated by
// compiling two values through the real engine and diffing the CSS. `ComposesFor` in
// declaredproperties.go now runs that same comparison against the ported handle bodies, across all
// three emitter slices. Measured before the deletion: 81 of the 82 rows answered and all 81 agreed,
// and the row that did not was `shadow-`, a trailing-dash repository token rather than a utility,
// which is declined before composition is ever asked.
//
// The generator's 82 answers are kept as a fixture in composes_test.go so the computation stays
// checked against an independent measurement rather than against itself.

// KnownRoots is every functional utility root the design system defines.
//
// ColorNames used to be printed here and is not any more.
//
// It held 561 colour names so a caller could ask whether a value names a colour. Upstream has no
// such table: it resolves through `--color` at 39 sites, always asking the theme in front of it.
// `valueIsColorIn` now does the same, with `IsColorKeyword` beside it for the three CSS keywords
// that sit in no namespace.
//
// Measured across both corpus systems before deleting: 558 of 561 answered by the live theme, the
// other 3 answered by `colorKeywords`, 0 left uncovered. And in the other direction,
// www-connected-app declares `--color-brand`, `--color-brand-hover` and `--color-brand-active`,
// which this table knew nothing about because it was generated from ahra. A generated palette is
// wrong for every repository except its source, which is why this is a deletion rather than a
// simplification.

// TailwindVersion is the version these families were enumerated from.
//
// Recorded so a mismatch between this and the installed Tailwind is greppable, and so a reader of a
// finding can tell which engine's opinion produced it.
const TailwindVersion = "4.3.3"
