package tailwind

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"testing"

	"github.com/system-inc/cohere/internal/lint/testing"
)

// TestStrictVariantsMatchUpstream holds the variants strict order groups each class by against
// upstream's own reading of them: eslint-plugin-better-tailwindcss 4.7.0's getDissectedClasses run on
// the real engine with ahra's theme, followed by the rule's colon fallback, over every variant-bearing
// class in ahra's source and a set of edge cases (arbitrary selectors, `&:is(…)`, named groups,
// container queries, the `(--x)` shorthand, and classes that do not parse). Generated by a scratch
// script, sandboxed, into testdata/strict_variants.json.
func TestStrictVariantsMatchUpstream(t *testing.T) {
	t.Parallel()
	designSystem := classOrderLiveRepositorySystem(t)

	data, err := os.ReadFile(filepath.Join("testdata", "strict_variants.json"))
	if err != nil {
		t.Fatal(err)
	}
	var file struct {
		Classes []struct {
			ClassName string   `json:"className"`
			Variants  []string `json:"variants"`
		} `json:"classes"`
	}
	if err := json.Unmarshal(data, &file); err != nil {
		t.Fatal(err)
	}
	if len(file.Classes) < 100 {
		t.Fatalf("only %d classes in the goldens, too few to speak for the printer", len(file.Classes))
	}

	for _, golden := range file.Classes {
		got := strictVariantsOf(golden.ClassName, designSystem.System)
		if len(got) == 0 && len(golden.Variants) == 0 {
			continue
		}
		if !slices.Equal(got, golden.Variants) {
			t.Errorf("%s: variants %q, upstream %q", golden.ClassName, got, golden.Variants)
		}
	}
}

// TestStrictOrderMatchesUpstream is upstream's own four cases for `order: "strict"`
// (enforce-consistent-class-order.test.ts at 4.7.0), written and wanted exactly as their jsx case is.
func TestStrictOrderMatchesUpstream(t *testing.T) {
	t.Parallel()
	testCases := []struct {
		name, source, want string
	}{
		{
			name:   "variants grouped together",
			source: "hover:text-black text-black hover:dark:text-black",
			want:   "text-black hover:text-black hover:dark:text-black",
		},
		{
			name:   "arbitrary variants grouped together",
			source: "data-[attr=a]:*:text-black text-black data-[attr=a]:text-black",
			want:   "text-black data-[attr=a]:text-black data-[attr=a]:*:text-black",
		},
		{
			name:   "arbitrary variants last",
			source: "data-[attr=a]:*:text-black data-[attr=a]:text-black text-black md:dark:text-black md:text-black",
			want:   "text-black md:text-black md:dark:text-black data-[attr=a]:text-black data-[attr=a]:*:text-black",
		},
		{
			name:   "the official order within a group",
			source: "data-[attr=a]:*:text-black text-white px-4 block mix-blend-difference py-2 data-[attr=a]:text-black",
			want:   "block px-4 py-2 text-white mix-blend-difference data-[attr=a]:text-black data-[attr=a]:*:text-black",
		},
	}
	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			t.Parallel()
			result := runClassOrderFixtureWithOptions(t,
				`export const element = <img className="`+testCase.source+`" />;`,
				EnforceConsistentClassOrderOptions{Order: "strict"})
			rule_testing.ExpectFixedSource(t, result, `export const element = <img className="`+testCase.want+`" />;`+"\n")
		})
	}
}

// TestStrictOrderKeysClassesByName pins what upstream's strict order does with a repeated class: it
// builds its groups as an object keyed by class name, so a repeat collapses into one. Asked of the
// plugin itself (4.7.0, sandboxed): `a b a` under strict becomes `a b ` (its fixer leaves the freed
// slot as a trailing space), and `flex block flex` becomes `block flex `, while official keeps both.
// This rule never reaches it in practice, since a literal holding a repeat waits for
// no-duplicate-classes before it is ordered; both paths end at `a b`.
func TestStrictOrderKeysClassesByName(t *testing.T) {
	t.Parallel()
	if got := strictClassOrder([]string{"a", "b", "a"}, nil); !slices.Equal(got, []string{"a", "b"}) {
		t.Errorf("strict order of a b a: %q, want upstream's [a b]", got)
	}
	rule_testing.ExpectClean(t, runClassOrderFixtureWithOptions(t,
		`export const element = <img className="flex block flex" />;`,
		EnforceConsistentClassOrderOptions{Order: "strict"}))
}
