import Foundation
import Testing

@testable import CohereSwift

/*
 What git would list, read from the ignore files with no git process. Each repository here is a directory
 holding a `.git`, and each run gets a home of its own, so this machine's global ignore file cannot decide
 what a test proves.
 */
struct IgnoreRulesTests {
    /* A repository on disk: its root, a home for the global config, and the rules read from both. */
    struct Fixture {
        var root: URL
        var home: URL

        init(
            files: [String: String],
            gitDirectory: [String: String] = [:],
            home homeFiles: [String: String] = [:],
        ) throws {
            let base = FileManager.default.temporaryDirectory.appendingPathComponent(
                "cohere-swift-ignore-\(UUID().uuidString)",
                isDirectory: true,
            )
            root = base.appendingPathComponent("repository", isDirectory: true)
            home = base.appendingPathComponent("home", isDirectory: true)
            try FileManager.default.createDirectory(
                at: root.appendingPathComponent(".git", isDirectory: true),
                withIntermediateDirectories: true,
            )
            try FileManager.default.createDirectory(at: home, withIntermediateDirectories: true)
            try Self.write(files, under: root)
            try Self.write(gitDirectory, under: root.appendingPathComponent(".git", isDirectory: true))
            try Self.write(homeFiles, under: home)
        }

        static func write(_ files: [String: String], under directory: URL) throws {
            for (path, text) in files {
                let url = directory.appendingPathComponent(path)
                try FileManager.default.createDirectory(
                    at: url.deletingLastPathComponent(),
                    withIntermediateDirectories: true,
                )
                try text.write(to: url, atomically: true, encoding: .utf8)
            }
        }

        var environment: [String: String] { ["HOME": home.path] }

        func rules() throws -> IgnoreRules {
            let repository = try #require(IgnoreRules.Repository.containing(root))
            return IgnoreRules(repository: repository, environment: environment)
        }

        /* The files git would list, relative to the root, sorted. */
        func visible() throws -> [String] {
            let rules = try rules()
            let rootPath = rules.repository.root.path + "/"
            return rules.visibleFiles(under: rules.repository.root.path).map { String($0.dropFirst(rootPath.count)) }
                .sorted()
        }
    }

    @Test func anIgnoredFileIsNotListed() throws {
        let fixture = try Fixture(files: [".gitignore": "Generated.swift\n", "Kept.swift": "", "Generated.swift": ""])
        #expect(try fixture.visible() == [".gitignore", "Kept.swift"])
    }

    @Test func anIgnoredSourceStaysExcludedFromTheFileSet() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "Sources/A/Generated.swift\n",
            "Package.swift": "",
            "Sources/A/A.swift": "",
            "Sources/A/Generated.swift": "",
            "Script.swift": "",
        ])
        let describe =
            #"{"name":"Example","targets":[{"name":"A","type":"library","path":"Sources/A","sources":["A.swift","Generated.swift"]}]}"#
        let dump = #"{"toolsVersion":{"_version":"6.4.0"},"swiftLanguageVersions":null,"targets":[]}"#
        let package = try PackageModel(
            root: fixture.root,
            describeJson: Data(describe.utf8),
            dumpPackageJson: Data(dump.utf8),
        )
        let fileSet = try FileSet.build(package: package, environment: fixture.environment)
        #expect(fileSet.owned.map(\.url.lastPathComponent) == ["A.swift"])
        let reasons = Dictionary(
            uniqueKeysWithValues: fileSet.excluded.map { (URL(fileURLWithPath: $0.file).lastPathComponent, $0.reason) }
        )
        #expect(
            reasons == [
                "Generated.swift": "ignored by git", "Package.swift": "a package manifest",
                "Script.swift": "no target of this package compiles it",
            ]
        )
        #expect(fileSet.note.isEmpty)
    }

    /* A generated file is ours, header marker or not: Kirk's convention names it `*.generated.swift` and gives it every rule but file-length. */
    @Test func aGeneratedFileIsOurs() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "",
            "Package.swift": "",
            "Sources/A/A.swift": "",
            "Sources/A/Schema.generated.swift": "// @generated by a tool\nstruct Schema {}\n",
        ])
        let describe =
            #"{"name":"Example","targets":[{"name":"A","type":"library","path":"Sources/A","sources":["A.swift","Schema.generated.swift"]}]}"#
        let dump = #"{"toolsVersion":{"_version":"6.4.0"},"swiftLanguageVersions":null,"targets":[]}"#
        let package = try PackageModel(
            root: fixture.root,
            describeJson: Data(describe.utf8),
            dumpPackageJson: Data(dump.utf8),
        )
        let fileSet = try FileSet.build(package: package, environment: fixture.environment)
        #expect(fileSet.owned.map(\.url.lastPathComponent) == ["A.swift", "Schema.generated.swift"])
    }

    @Test func aPackageOutsideAnyRepositoryTreatsEveryTargetFileAsOurs() throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent(
            "cohere-swift-no-git-\(UUID().uuidString)",
            isDirectory: true,
        )
        try Fixture.write(
            [".gitignore": "Generated.swift\n", "Sources/A/A.swift": "", "Sources/A/Generated.swift": ""],
            under: root,
        )
        #expect(
            IgnoreRules.Repository.containing(root) == nil,
            "the temporary directory sits inside a repository, so this test proves nothing",
        )
        let describe =
            #"{"name":"Example","targets":[{"name":"A","type":"library","path":"Sources/A","sources":["A.swift","Generated.swift"]}]}"#
        let dump = #"{"toolsVersion":{"_version":"6.4.0"},"swiftLanguageVersions":null,"targets":[]}"#
        let package = try PackageModel(root: root, describeJson: Data(describe.utf8), dumpPackageJson: Data(dump.utf8))
        let fileSet = try FileSet.build(package: package)
        #expect(fileSet.owned.map(\.url.lastPathComponent) == ["A.swift", "Generated.swift"])
        #expect(fileSet.excluded.isEmpty)
        #expect(fileSet.note == "not a git repository, so every file a target compiles was treated as ours")
    }

    @Test func aNestedIgnoreAppliesOnlyBelowItsDirectory() throws {
        let fixture = try Fixture(files: [
            "Sources/.gitignore": "Local.swift\n",
            "Sources/Local.swift": "",
            "Sources/Deeper/Local.swift": "",
            "Local.swift": "",
            "Tools/Local.swift": "",
        ])
        #expect(try fixture.visible() == ["Local.swift", "Sources/.gitignore", "Tools/Local.swift"])
    }

    @Test func aDeeperIgnoreFileOutranksTheRoot() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "*.swift\n",
            "Sources/.gitignore": "!Kept.swift\n",
            "Sources/Kept.swift": "",
            "Sources/Other.swift": "",
        ])
        #expect(try fixture.visible() == [".gitignore", "Sources/.gitignore", "Sources/Kept.swift"])
    }

    @Test func aNegatedPatternIsHonouredAndTheLastLineWins() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "*.swift\n!keep.swift\nagain.swift\n!again.swift\nlast.swift\n",
            "keep.swift": "",
            "drop.swift": "",
            "again.swift": "",
            "last.swift": "",
        ])
        #expect(try fixture.visible() == [".gitignore", "again.swift", "keep.swift"])
    }

    @Test func aFileInsideAnExcludedDirectoryCannotBeReincluded() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "Build/\n!Build/Keep.swift\nCache/*\n!Cache/Keep.swift\n",
            "Build/Keep.swift": "",
            "Cache/Keep.swift": "",
            "Cache/Drop.swift": "",
        ])
        /* A star after `Cache/` ignores what is in the directory, not the directory, so its negation can reach inside: git's own documented example. */
        #expect(try fixture.visible() == [".gitignore", "Cache/Keep.swift"])
    }

    @Test func aDoubleAsteriskCrossesDirectoriesLeadingInTheMiddleAndTrailing() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "**/Fixtures\nDocuments/**/Draft.swift\nVendor/**\nSources/*.swift\n",
            "Fixtures/A.swift": "",
            "Deep/Down/Fixtures/B.swift": "",
            "Documents/Draft.swift": "",
            "Documents/One/Two/Draft.swift": "",
            "Documents/One/Final.swift": "",
            "Vendor/Package/C.swift": "",
            "Sources/Top.swift": "",
            "Sources/Module/Kept.swift": "",
        ])
        #expect(try fixture.visible() == [".gitignore", "Documents/One/Final.swift", "Sources/Module/Kept.swift"])
    }

    @Test func aSlashAnchorsAndANameMatchesAtAnyDepth() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "/Top.swift\nAnywhere.swift\nSources/Anchored.swift\n",
            "Top.swift": "",
            "Sub/Top.swift": "",
            "Anywhere.swift": "",
            "Sub/Deep/Anywhere.swift": "",
            "Sources/Anchored.swift": "",
            "Sub/Sources/Anchored.swift": "",
        ])
        #expect(try fixture.visible() == [".gitignore", "Sub/Sources/Anchored.swift", "Sub/Top.swift"])
    }

    @Test func aTrailingSlashMatchesOnlyDirectories() throws {
        let fixture = try Fixture(files: [".gitignore": "Output/\n", "Output/A.swift": "", "Sources/Output": ""])
        #expect(try fixture.visible() == [".gitignore", "Sources/Output"])
    }

    @Test func commentsBlankLinesTrailingSpacesAndEscapesReadAsGitReadsThem() throws {
        let fixture = try Fixture(files: [
            ".gitignore":
                "# Comment.swift\n\n   \nSpaced.swift   \nEscaped\\ \n\\#Hash.swift\n\\!Bang.swift\r\nCarriage.swift\r\n",
            "Comment.swift": "",
            "# Comment.swift": "",
            "Spaced.swift": "",
            "Escaped ": "",
            "Escaped": "",
            "#Hash.swift": "",
            "!Bang.swift": "",
            "Carriage.swift": "",
        ])
        #expect(try fixture.visible() == ["# Comment.swift", ".gitignore", "Comment.swift", "Escaped"])
    }

    @Test func bracketsAndQuestionMarksNeverCrossASlash() throws {
        let fixture = try Fixture(files: [
            ".gitignore": "File[0-9].swift\nCase[!a].swift\nWho?.swift\nSources/?/X.swift\n",
            "File1.swift": "",
            "FileA.swift": "",
            "Caseb.swift": "",
            "Casea.swift": "",
            "Whom.swift": "",
            "Sources/A/X.swift": "",
            "Sources/AB/X.swift": "",
        ])
        #expect(try fixture.visible() == [".gitignore", "Casea.swift", "FileA.swift", "Sources/AB/X.swift"])
    }

    @Test func ignoreCaseFoldsWhenTheRepositorySaysSo() throws {
        let files = [".gitignore": "generated.swift\n", "Generated.swift": ""]
        #expect(try Fixture(files: files).visible() == [".gitignore", "Generated.swift"])
        #expect(
            try Fixture(files: files, gitDirectory: ["config": "[core]\n\tignorecase = true\n"]).visible() == [
                ".gitignore"
            ]
        )
    }

    @Test func infoExcludeAndTheGlobalExcludesFileApply() throws {
        let files = [".gitignore": "", "Local.swift": "", "Global.swift": "", "Custom.swift": "", "Kept.swift": ""]
        let fromDefaultPlace = try Fixture(
            files: files,
            gitDirectory: ["info/exclude": "Local.swift\n"],
            home: [".config/git/ignore": "Global.swift\n"],
        )
        #expect(try fromDefaultPlace.visible() == [".gitignore", "Custom.swift", "Kept.swift"])
        let configured = try Fixture(
            files: files,
            home: [
                ".gitconfig": "[user]\n\tname = x\n[core]\n\texcludesFile = \"~/custom ignore\" ; why\n",
                "custom ignore": "Custom.swift\n", ".config/git/ignore": "Global.swift\n",
            ],
        )
        #expect(try configured.visible() == [".gitignore", "Global.swift", "Kept.swift", "Local.swift"])
    }

    @Test func anotherRepositoryInsideIsNotEntered() throws {
        let fixture = try Fixture(files: [
            "Kept.swift": "", "Clone/.git/HEAD": "", "Clone/Theirs.swift": "",
            "Submodule/.git": "gitdir: ../.git/modules/Submodule\n", "Submodule/Theirs.swift": "",
        ])
        #expect(try fixture.visible() == ["Kept.swift"])
        let rules = try fixture.rules()
        #expect(!rules.isVisible(rules.repository.root.appendingPathComponent("Clone/Theirs.swift").path))
    }

    @Test func aWorktreeGitFileIsFollowedToItsCommonDirectory() throws {
        let main = try Fixture(
            files: ["Kept.swift": ""],
            gitDirectory: [
                "info/exclude": "Excluded.swift\n",
                "worktrees/feature/commondir": "../..\n",
                "worktrees/feature/HEAD": "",
            ],
        )
        let worktree = main.root.deletingLastPathComponent().appendingPathComponent("feature", isDirectory: true)
        try Fixture.write(
            [
                ".git": "gitdir: \(main.root.path)/.git/worktrees/feature\n",
                "Sources/Excluded.swift": "",
                "Sources/Kept.swift": "",
            ],
            under: worktree,
        )

        let repository = try #require(
            IgnoreRules.Repository.containing(worktree.appendingPathComponent("Sources", isDirectory: true))
        )
        #expect(repository.root.path == worktree.resolvingSymlinksInPath().path)
        #expect(
            repository.commonDirectory?.resolvingSymlinksInPath().path
                == main.root.appendingPathComponent(".git").resolvingSymlinksInPath().path
        )
        let rules = IgnoreRules(repository: repository, environment: main.environment)
        #expect(rules.isVisible(repository.root.appendingPathComponent("Sources/Kept.swift").path))
        #expect(!rules.isVisible(repository.root.appendingPathComponent("Sources/Excluded.swift").path))
    }

    @Test func theNearestGitIsTheRepositoryRoot() throws {
        let fixture = try Fixture(files: ["Packages/Inner/Sources/A.swift": ""])
        let repository = try #require(
            IgnoreRules.Repository.containing(fixture.root.appendingPathComponent("Packages/Inner", isDirectory: true))
        )
        #expect(repository.root.path == fixture.root.resolvingSymlinksInPath().path)
        #expect(repository.commonDirectory?.lastPathComponent == ".git")
    }
}
