package core

// Generated from ESLint's own no-unreachable-loop corpus and verified byte for byte against it.
// Every case is upstream's, and the expected finding count on each is what the installed eslint
// 10.8.1 build reported when driven through the Linter API on that exact source.
//
// Do not hand-edit a case here. Cases added beyond upstream's live in no_unreachable_loop_test.go
// with a comment saying why each exists.

// unreachableLoopFiringCases are the corpus inputs upstream reports on, with how many findings each
// produces.
var unreachableLoopFiringCases = []struct {
	source   string
	findings int
}{
	{"while (a) break;", 1},
	{"while (a) { break; }", 1},
	{"function someFunc() { while (a) return; }", 1},
	{"function someFunc() { while (a) { return; } }", 1},
	{"while (a) throw err;", 1},
	{"while (a) { throw err; }", 1},
	{"while (a) { foo(); break; }", 1},
	{"while (a) { break; foo(); }", 1},
	{"function someFunc() { while (a) if (foo) break; else return; }", 1},
	{"function someFunc() { while (a) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { while (a) { if (foo) { return; } throw err; } }", 1},
	{"while (a) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { while (a) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { while (a) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { while (a) { try { return bar(); } catch (e) { break; } } }", 1},
	{"while (a) { break; continue; }", 1},
	{"while (a) { () => a; break; }", 1},
	{"while (a) { (() => a)(); break; }", 1},
	{"while (a) { while (a); break; }", 1},
	{"while (a) { do ; while (a) break; }", 1},
	{"while (a) { for (a; b; c); break; }", 1},
	{"while (a) { for (; b;); break; }", 1},
	{"while (a) { for (; ; c) if (foo) break; break; }", 1},
	{"while (a) { for(;;) if (foo) break; break; }", 1},
	{"while (a) { for (a in b); break; }", 1},
	{"while (a) { for (a of b); break; }", 1},
	{"while (a) for (;;);", 1},
	{"while (a) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"while (a) while (true);", 1},
	{"while (a && b) break;", 1},
	{"while (a && b) { break; }", 1},
	{"function someFunc() { while (a && b) return; }", 1},
	{"function someFunc() { while (a && b) { return; } }", 1},
	{"while (a && b) throw err;", 1},
	{"while (a && b) { throw err; }", 1},
	{"while (a && b) { foo(); break; }", 1},
	{"while (a && b) { break; foo(); }", 1},
	{"function someFunc() { while (a && b) if (foo) break; else return; }", 1},
	{"function someFunc() { while (a && b) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { while (a && b) { if (foo) { return; } throw err; } }", 1},
	{"while (a && b) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { while (a && b) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { while (a && b) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { while (a && b) { try { return bar(); } catch (e) { break; } } }", 1},
	{"while (a && b) { break; continue; }", 1},
	{"while (a && b) { () => a; break; }", 1},
	{"while (a && b) { (() => a)(); break; }", 1},
	{"while (a && b) { while (a); break; }", 1},
	{"while (a && b) { do ; while (a) break; }", 1},
	{"while (a && b) { for (a; b; c); break; }", 1},
	{"while (a && b) { for (; b;); break; }", 1},
	{"while (a && b) { for (; ; c) if (foo) break; break; }", 1},
	{"while (a && b) { for(;;) if (foo) break; break; }", 1},
	{"while (a && b) { for (a in b); break; }", 1},
	{"while (a && b) { for (a of b); break; }", 1},
	{"while (a && b) for (;;);", 1},
	{"while (a && b) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"while (a && b) while (true);", 1},
	{"do break; while (a)", 1},
	{"do { break; } while (a)", 1},
	{"function someFunc() { do return; while (a) }", 1},
	{"function someFunc() { do { return; } while (a) }", 1},
	{"do throw err; while (a)", 1},
	{"do { throw err; } while (a)", 1},
	{"do { foo(); break; } while (a)", 1},
	{"do { break; foo(); } while (a)", 1},
	{"function someFunc() { do if (foo) break; else return; while (a) }", 1},
	{"function someFunc() { do { if (foo) { return; } else { break; } bar(); } while (a) }", 1},
	{"function someFunc() { do { if (foo) { return; } throw err; } while (a) }", 1},
	{"do { switch (foo) { default: throw err; } } while (a)", 1},
	{"function someFunc() { do { switch (foo) { case 1: throw err; default: return; } } while (a) }", 1},
	{"function someFunc() { do { switch (foo) { case 1: something(); default: return; } } while (a) }", 1},
	{"function someFunc() { do { try { return bar(); } catch (e) { break; } } while (a) }", 1},
	{"do { break; continue; } while (a)", 1},
	{"do { () => a; break; } while (a)", 1},
	{"do { (() => a)(); break; } while (a)", 1},
	{"do { while (a); break; } while (a)", 1},
	{"do { do ; while (a) break; } while (a)", 1},
	{"do { for (a; b; c); break; } while (a)", 1},
	{"do { for (; b;); break; } while (a)", 1},
	{"do { for (; ; c) if (foo) break; break; } while (a)", 1},
	{"do { for(;;) if (foo) break; break; } while (a)", 1},
	{"do { for (a in b); break; } while (a)", 1},
	{"do { for (a of b); break; } while (a)", 1},
	{"do for (;;); while (a)", 1},
	{"do { for (var i = 0; ; i< 10) { foo(); } } while (a)", 1},
	{"do while (true); while (a)", 1},
	{"do break; while (a && b)", 1},
	{"do { break; } while (a && b)", 1},
	{"function someFunc() { do return; while (a && b) }", 1},
	{"function someFunc() { do { return; } while (a && b) }", 1},
	{"do throw err; while (a && b)", 1},
	{"do { throw err; } while (a && b)", 1},
	{"do { foo(); break; } while (a && b)", 1},
	{"do { break; foo(); } while (a && b)", 1},
	{"function someFunc() { do if (foo) break; else return; while (a && b) }", 1},
	{"function someFunc() { do { if (foo) { return; } else { break; } bar(); } while (a && b) }", 1},
	{"function someFunc() { do { if (foo) { return; } throw err; } while (a && b) }", 1},
	{"do { switch (foo) { default: throw err; } } while (a && b)", 1},
	{"function someFunc() { do { switch (foo) { case 1: throw err; default: return; } } while (a && b) }", 1},
	{"function someFunc() { do { switch (foo) { case 1: something(); default: return; } } while (a && b) }", 1},
	{"function someFunc() { do { try { return bar(); } catch (e) { break; } } while (a && b) }", 1},
	{"do { break; continue; } while (a && b)", 1},
	{"do { () => a; break; } while (a && b)", 1},
	{"do { (() => a)(); break; } while (a && b)", 1},
	{"do { while (a); break; } while (a && b)", 1},
	{"do { do ; while (a) break; } while (a && b)", 1},
	{"do { for (a; b; c); break; } while (a && b)", 1},
	{"do { for (; b;); break; } while (a && b)", 1},
	{"do { for (; ; c) if (foo) break; break; } while (a && b)", 1},
	{"do { for(;;) if (foo) break; break; } while (a && b)", 1},
	{"do { for (a in b); break; } while (a && b)", 1},
	{"do { for (a of b); break; } while (a && b)", 1},
	{"do for (;;); while (a && b)", 1},
	{"do { for (var i = 0; ; i< 10) { foo(); } } while (a && b)", 1},
	{"do while (true); while (a && b)", 1},
	{"for (a; b; c) break;", 1},
	{"for (a; b; c) { break; }", 1},
	{"function someFunc() { for (a; b; c) return; }", 1},
	{"function someFunc() { for (a; b; c) { return; } }", 1},
	{"for (a; b; c) throw err;", 1},
	{"for (a; b; c) { throw err; }", 1},
	{"for (a; b; c) { foo(); break; }", 1},
	{"for (a; b; c) { break; foo(); }", 1},
	{"function someFunc() { for (a; b; c) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a; b; c) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a; b; c) { if (foo) { return; } throw err; } }", 1},
	{"for (a; b; c) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a; b; c) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a; b; c) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a; b; c) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a; b; c) { break; continue; }", 1},
	{"for (a; b; c) { () => a; break; }", 1},
	{"for (a; b; c) { (() => a)(); break; }", 1},
	{"for (a; b; c) { while (a); break; }", 1},
	{"for (a; b; c) { do ; while (a) break; }", 1},
	{"for (a; b; c) { for (a; b; c); break; }", 1},
	{"for (a; b; c) { for (; b;); break; }", 1},
	{"for (a; b; c) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a; b; c) { for(;;) if (foo) break; break; }", 1},
	{"for (a; b; c) { for (a in b); break; }", 1},
	{"for (a; b; c) { for (a of b); break; }", 1},
	{"for (a; b; c) for (;;);", 1},
	{"for (a; b; c) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a; b; c) while (true);", 1},
	{"for (var i = 0; i < a.length; i++) break;", 1},
	{"for (var i = 0; i < a.length; i++) { break; }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) return; }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { return; } }", 1},
	{"for (var i = 0; i < a.length; i++) throw err;", 1},
	{"for (var i = 0; i < a.length; i++) { throw err; }", 1},
	{"for (var i = 0; i < a.length; i++) { foo(); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { break; foo(); }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) if (foo) break; else return; }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { if (foo) { return; } throw err; } }", 1},
	{"for (var i = 0; i < a.length; i++) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (var i = 0; i < a.length; i++) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (var i = 0; i < a.length; i++) { break; continue; }", 1},
	{"for (var i = 0; i < a.length; i++) { () => a; break; }", 1},
	{"for (var i = 0; i < a.length; i++) { (() => a)(); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { while (a); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { do ; while (a) break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for (a; b; c); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for (; b;); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for (; ; c) if (foo) break; break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for(;;) if (foo) break; break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for (a in b); break; }", 1},
	{"for (var i = 0; i < a.length; i++) { for (a of b); break; }", 1},
	{"for (var i = 0; i < a.length; i++) for (;;);", 1},
	{"for (var i = 0; i < a.length; i++) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (var i = 0; i < a.length; i++) while (true);", 1},
	{"for (; b; c) break;", 1},
	{"for (; b; c) { break; }", 1},
	{"function someFunc() { for (; b; c) return; }", 1},
	{"function someFunc() { for (; b; c) { return; } }", 1},
	{"for (; b; c) throw err;", 1},
	{"for (; b; c) { throw err; }", 1},
	{"for (; b; c) { foo(); break; }", 1},
	{"for (; b; c) { break; foo(); }", 1},
	{"function someFunc() { for (; b; c) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; b; c) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; b; c) { if (foo) { return; } throw err; } }", 1},
	{"for (; b; c) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; b; c) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; b; c) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; b; c) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; b; c) { break; continue; }", 1},
	{"for (; b; c) { () => a; break; }", 1},
	{"for (; b; c) { (() => a)(); break; }", 1},
	{"for (; b; c) { while (a); break; }", 1},
	{"for (; b; c) { do ; while (a) break; }", 1},
	{"for (; b; c) { for (a; b; c); break; }", 1},
	{"for (; b; c) { for (; b;); break; }", 1},
	{"for (; b; c) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; b; c) { for(;;) if (foo) break; break; }", 1},
	{"for (; b; c) { for (a in b); break; }", 1},
	{"for (; b; c) { for (a of b); break; }", 1},
	{"for (; b; c) for (;;);", 1},
	{"for (; b; c) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; b; c) while (true);", 1},
	{"for (; b < foo; c++) break;", 1},
	{"for (; b < foo; c++) { break; }", 1},
	{"function someFunc() { for (; b < foo; c++) return; }", 1},
	{"function someFunc() { for (; b < foo; c++) { return; } }", 1},
	{"for (; b < foo; c++) throw err;", 1},
	{"for (; b < foo; c++) { throw err; }", 1},
	{"for (; b < foo; c++) { foo(); break; }", 1},
	{"for (; b < foo; c++) { break; foo(); }", 1},
	{"function someFunc() { for (; b < foo; c++) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; b < foo; c++) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; b < foo; c++) { if (foo) { return; } throw err; } }", 1},
	{"for (; b < foo; c++) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; b < foo; c++) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; b < foo; c++) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; b < foo; c++) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; b < foo; c++) { break; continue; }", 1},
	{"for (; b < foo; c++) { () => a; break; }", 1},
	{"for (; b < foo; c++) { (() => a)(); break; }", 1},
	{"for (; b < foo; c++) { while (a); break; }", 1},
	{"for (; b < foo; c++) { do ; while (a) break; }", 1},
	{"for (; b < foo; c++) { for (a; b; c); break; }", 1},
	{"for (; b < foo; c++) { for (; b;); break; }", 1},
	{"for (; b < foo; c++) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; b < foo; c++) { for(;;) if (foo) break; break; }", 1},
	{"for (; b < foo; c++) { for (a in b); break; }", 1},
	{"for (; b < foo; c++) { for (a of b); break; }", 1},
	{"for (; b < foo; c++) for (;;);", 1},
	{"for (; b < foo; c++) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; b < foo; c++) while (true);", 1},
	{"for (a; ; c) break;", 1},
	{"for (a; ; c) { break; }", 1},
	{"function someFunc() { for (a; ; c) return; }", 1},
	{"function someFunc() { for (a; ; c) { return; } }", 1},
	{"for (a; ; c) throw err;", 1},
	{"for (a; ; c) { throw err; }", 1},
	{"for (a; ; c) { foo(); break; }", 1},
	{"for (a; ; c) { break; foo(); }", 1},
	{"function someFunc() { for (a; ; c) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a; ; c) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a; ; c) { if (foo) { return; } throw err; } }", 1},
	{"for (a; ; c) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a; ; c) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a; ; c) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a; ; c) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a; ; c) { break; continue; }", 1},
	{"for (a; ; c) { () => a; break; }", 1},
	{"for (a; ; c) { (() => a)(); break; }", 1},
	{"for (a; ; c) { while (a); break; }", 1},
	{"for (a; ; c) { do ; while (a) break; }", 1},
	{"for (a; ; c) { for (a; b; c); break; }", 1},
	{"for (a; ; c) { for (; b;); break; }", 1},
	{"for (a; ; c) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a; ; c) { for(;;) if (foo) break; break; }", 1},
	{"for (a; ; c) { for (a in b); break; }", 1},
	{"for (a; ; c) { for (a of b); break; }", 1},
	{"for (a; ; c) for (;;);", 1},
	{"for (a; ; c) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a; ; c) while (true);", 1},
	{"for (a = 0; ; c++) break;", 1},
	{"for (a = 0; ; c++) { break; }", 1},
	{"function someFunc() { for (a = 0; ; c++) return; }", 1},
	{"function someFunc() { for (a = 0; ; c++) { return; } }", 1},
	{"for (a = 0; ; c++) throw err;", 1},
	{"for (a = 0; ; c++) { throw err; }", 1},
	{"for (a = 0; ; c++) { foo(); break; }", 1},
	{"for (a = 0; ; c++) { break; foo(); }", 1},
	{"function someFunc() { for (a = 0; ; c++) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a = 0; ; c++) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a = 0; ; c++) { if (foo) { return; } throw err; } }", 1},
	{"for (a = 0; ; c++) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a = 0; ; c++) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a = 0; ; c++) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a = 0; ; c++) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a = 0; ; c++) { break; continue; }", 1},
	{"for (a = 0; ; c++) { () => a; break; }", 1},
	{"for (a = 0; ; c++) { (() => a)(); break; }", 1},
	{"for (a = 0; ; c++) { while (a); break; }", 1},
	{"for (a = 0; ; c++) { do ; while (a) break; }", 1},
	{"for (a = 0; ; c++) { for (a; b; c); break; }", 1},
	{"for (a = 0; ; c++) { for (; b;); break; }", 1},
	{"for (a = 0; ; c++) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a = 0; ; c++) { for(;;) if (foo) break; break; }", 1},
	{"for (a = 0; ; c++) { for (a in b); break; }", 1},
	{"for (a = 0; ; c++) { for (a of b); break; }", 1},
	{"for (a = 0; ; c++) for (;;);", 1},
	{"for (a = 0; ; c++) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a = 0; ; c++) while (true);", 1},
	{"for (a; b;) break;", 1},
	{"for (a; b;) { break; }", 1},
	{"function someFunc() { for (a; b;) return; }", 1},
	{"function someFunc() { for (a; b;) { return; } }", 1},
	{"for (a; b;) throw err;", 1},
	{"for (a; b;) { throw err; }", 1},
	{"for (a; b;) { foo(); break; }", 1},
	{"for (a; b;) { break; foo(); }", 1},
	{"function someFunc() { for (a; b;) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a; b;) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a; b;) { if (foo) { return; } throw err; } }", 1},
	{"for (a; b;) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a; b;) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a; b;) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a; b;) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a; b;) { break; continue; }", 1},
	{"for (a; b;) { () => a; break; }", 1},
	{"for (a; b;) { (() => a)(); break; }", 1},
	{"for (a; b;) { while (a); break; }", 1},
	{"for (a; b;) { do ; while (a) break; }", 1},
	{"for (a; b;) { for (a; b; c); break; }", 1},
	{"for (a; b;) { for (; b;); break; }", 1},
	{"for (a; b;) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a; b;) { for(;;) if (foo) break; break; }", 1},
	{"for (a; b;) { for (a in b); break; }", 1},
	{"for (a; b;) { for (a of b); break; }", 1},
	{"for (a; b;) for (;;);", 1},
	{"for (a; b;) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a; b;) while (true);", 1},
	{"for (a = 0; b < foo; ) break;", 1},
	{"for (a = 0; b < foo; ) { break; }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) return; }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { return; } }", 1},
	{"for (a = 0; b < foo; ) throw err;", 1},
	{"for (a = 0; b < foo; ) { throw err; }", 1},
	{"for (a = 0; b < foo; ) { foo(); break; }", 1},
	{"for (a = 0; b < foo; ) { break; foo(); }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { if (foo) { return; } throw err; } }", 1},
	{"for (a = 0; b < foo; ) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a = 0; b < foo; ) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a = 0; b < foo; ) { break; continue; }", 1},
	{"for (a = 0; b < foo; ) { () => a; break; }", 1},
	{"for (a = 0; b < foo; ) { (() => a)(); break; }", 1},
	{"for (a = 0; b < foo; ) { while (a); break; }", 1},
	{"for (a = 0; b < foo; ) { do ; while (a) break; }", 1},
	{"for (a = 0; b < foo; ) { for (a; b; c); break; }", 1},
	{"for (a = 0; b < foo; ) { for (; b;); break; }", 1},
	{"for (a = 0; b < foo; ) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a = 0; b < foo; ) { for(;;) if (foo) break; break; }", 1},
	{"for (a = 0; b < foo; ) { for (a in b); break; }", 1},
	{"for (a = 0; b < foo; ) { for (a of b); break; }", 1},
	{"for (a = 0; b < foo; ) for (;;);", 1},
	{"for (a = 0; b < foo; ) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a = 0; b < foo; ) while (true);", 1},
	{"for (; ; c) break;", 1},
	{"for (; ; c) { break; }", 1},
	{"function someFunc() { for (; ; c) return; }", 1},
	{"function someFunc() { for (; ; c) { return; } }", 1},
	{"for (; ; c) throw err;", 1},
	{"for (; ; c) { throw err; }", 1},
	{"for (; ; c) { foo(); break; }", 1},
	{"for (; ; c) { break; foo(); }", 1},
	{"function someFunc() { for (; ; c) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; ; c) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; ; c) { if (foo) { return; } throw err; } }", 1},
	{"for (; ; c) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; ; c) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; ; c) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; ; c) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; ; c) { break; continue; }", 1},
	{"for (; ; c) { () => a; break; }", 1},
	{"for (; ; c) { (() => a)(); break; }", 1},
	{"for (; ; c) { while (a); break; }", 1},
	{"for (; ; c) { do ; while (a) break; }", 1},
	{"for (; ; c) { for (a; b; c); break; }", 1},
	{"for (; ; c) { for (; b;); break; }", 1},
	{"for (; ; c) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; ; c) { for(;;) if (foo) break; break; }", 1},
	{"for (; ; c) { for (a in b); break; }", 1},
	{"for (; ; c) { for (a of b); break; }", 1},
	{"for (; ; c) for (;;);", 1},
	{"for (; ; c) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; ; c) while (true);", 1},
	{"for (; ; c++) break;", 1},
	{"for (; ; c++) { break; }", 1},
	{"function someFunc() { for (; ; c++) return; }", 1},
	{"function someFunc() { for (; ; c++) { return; } }", 1},
	{"for (; ; c++) throw err;", 1},
	{"for (; ; c++) { throw err; }", 1},
	{"for (; ; c++) { foo(); break; }", 1},
	{"for (; ; c++) { break; foo(); }", 1},
	{"function someFunc() { for (; ; c++) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; ; c++) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; ; c++) { if (foo) { return; } throw err; } }", 1},
	{"for (; ; c++) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; ; c++) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; ; c++) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; ; c++) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; ; c++) { break; continue; }", 1},
	{"for (; ; c++) { () => a; break; }", 1},
	{"for (; ; c++) { (() => a)(); break; }", 1},
	{"for (; ; c++) { while (a); break; }", 1},
	{"for (; ; c++) { do ; while (a) break; }", 1},
	{"for (; ; c++) { for (a; b; c); break; }", 1},
	{"for (; ; c++) { for (; b;); break; }", 1},
	{"for (; ; c++) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; ; c++) { for(;;) if (foo) break; break; }", 1},
	{"for (; ; c++) { for (a in b); break; }", 1},
	{"for (; ; c++) { for (a of b); break; }", 1},
	{"for (; ; c++) for (;;);", 1},
	{"for (; ; c++) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; ; c++) while (true);", 1},
	{"for (; b;) break;", 1},
	{"for (; b;) { break; }", 1},
	{"function someFunc() { for (; b;) return; }", 1},
	{"function someFunc() { for (; b;) { return; } }", 1},
	{"for (; b;) throw err;", 1},
	{"for (; b;) { throw err; }", 1},
	{"for (; b;) { foo(); break; }", 1},
	{"for (; b;) { break; foo(); }", 1},
	{"function someFunc() { for (; b;) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; b;) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; b;) { if (foo) { return; } throw err; } }", 1},
	{"for (; b;) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; b;) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; b;) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; b;) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; b;) { break; continue; }", 1},
	{"for (; b;) { () => a; break; }", 1},
	{"for (; b;) { (() => a)(); break; }", 1},
	{"for (; b;) { while (a); break; }", 1},
	{"for (; b;) { do ; while (a) break; }", 1},
	{"for (; b;) { for (a; b; c); break; }", 1},
	{"for (; b;) { for (; b;); break; }", 1},
	{"for (; b;) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; b;) { for(;;) if (foo) break; break; }", 1},
	{"for (; b;) { for (a in b); break; }", 1},
	{"for (; b;) { for (a of b); break; }", 1},
	{"for (; b;) for (;;);", 1},
	{"for (; b;) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; b;) while (true);", 1},
	{"for (; b < foo; ) break;", 1},
	{"for (; b < foo; ) { break; }", 1},
	{"function someFunc() { for (; b < foo; ) return; }", 1},
	{"function someFunc() { for (; b < foo; ) { return; } }", 1},
	{"for (; b < foo; ) throw err;", 1},
	{"for (; b < foo; ) { throw err; }", 1},
	{"for (; b < foo; ) { foo(); break; }", 1},
	{"for (; b < foo; ) { break; foo(); }", 1},
	{"function someFunc() { for (; b < foo; ) if (foo) break; else return; }", 1},
	{"function someFunc() { for (; b < foo; ) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (; b < foo; ) { if (foo) { return; } throw err; } }", 1},
	{"for (; b < foo; ) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (; b < foo; ) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (; b < foo; ) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (; b < foo; ) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (; b < foo; ) { break; continue; }", 1},
	{"for (; b < foo; ) { () => a; break; }", 1},
	{"for (; b < foo; ) { (() => a)(); break; }", 1},
	{"for (; b < foo; ) { while (a); break; }", 1},
	{"for (; b < foo; ) { do ; while (a) break; }", 1},
	{"for (; b < foo; ) { for (a; b; c); break; }", 1},
	{"for (; b < foo; ) { for (; b;); break; }", 1},
	{"for (; b < foo; ) { for (; ; c) if (foo) break; break; }", 1},
	{"for (; b < foo; ) { for(;;) if (foo) break; break; }", 1},
	{"for (; b < foo; ) { for (a in b); break; }", 1},
	{"for (; b < foo; ) { for (a of b); break; }", 1},
	{"for (; b < foo; ) for (;;);", 1},
	{"for (; b < foo; ) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (; b < foo; ) while (true);", 1},
	{"for (a; ;) break;", 1},
	{"for (a; ;) { break; }", 1},
	{"function someFunc() { for (a; ;) return; }", 1},
	{"function someFunc() { for (a; ;) { return; } }", 1},
	{"for (a; ;) throw err;", 1},
	{"for (a; ;) { throw err; }", 1},
	{"for (a; ;) { foo(); break; }", 1},
	{"for (a; ;) { break; foo(); }", 1},
	{"function someFunc() { for (a; ;) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a; ;) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a; ;) { if (foo) { return; } throw err; } }", 1},
	{"for (a; ;) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a; ;) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a; ;) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a; ;) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a; ;) { break; continue; }", 1},
	{"for (a; ;) { () => a; break; }", 1},
	{"for (a; ;) { (() => a)(); break; }", 1},
	{"for (a; ;) { while (a); break; }", 1},
	{"for (a; ;) { do ; while (a) break; }", 1},
	{"for (a; ;) { for (a; b; c); break; }", 1},
	{"for (a; ;) { for (; b;); break; }", 1},
	{"for (a; ;) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a; ;) { for(;;) if (foo) break; break; }", 1},
	{"for (a; ;) { for (a in b); break; }", 1},
	{"for (a; ;) { for (a of b); break; }", 1},
	{"for (a; ;) for (;;);", 1},
	{"for (a; ;) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a; ;) while (true);", 1},
	{"for (a = 0; ;) break;", 1},
	{"for (a = 0; ;) { break; }", 1},
	{"function someFunc() { for (a = 0; ;) return; }", 1},
	{"function someFunc() { for (a = 0; ;) { return; } }", 1},
	{"for (a = 0; ;) throw err;", 1},
	{"for (a = 0; ;) { throw err; }", 1},
	{"for (a = 0; ;) { foo(); break; }", 1},
	{"for (a = 0; ;) { break; foo(); }", 1},
	{"function someFunc() { for (a = 0; ;) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a = 0; ;) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a = 0; ;) { if (foo) { return; } throw err; } }", 1},
	{"for (a = 0; ;) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a = 0; ;) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a = 0; ;) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a = 0; ;) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a = 0; ;) { break; continue; }", 1},
	{"for (a = 0; ;) { () => a; break; }", 1},
	{"for (a = 0; ;) { (() => a)(); break; }", 1},
	{"for (a = 0; ;) { while (a); break; }", 1},
	{"for (a = 0; ;) { do ; while (a) break; }", 1},
	{"for (a = 0; ;) { for (a; b; c); break; }", 1},
	{"for (a = 0; ;) { for (; b;); break; }", 1},
	{"for (a = 0; ;) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a = 0; ;) { for(;;) if (foo) break; break; }", 1},
	{"for (a = 0; ;) { for (a in b); break; }", 1},
	{"for (a = 0; ;) { for (a of b); break; }", 1},
	{"for (a = 0; ;) for (;;);", 1},
	{"for (a = 0; ;) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a = 0; ;) while (true);", 1},
	{"for (;;) break;", 1},
	{"for (;;) { break; }", 1},
	{"function someFunc() { for (;;) return; }", 1},
	{"function someFunc() { for (;;) { return; } }", 1},
	{"for (;;) throw err;", 1},
	{"for (;;) { throw err; }", 1},
	{"for (;;) { foo(); break; }", 1},
	{"for (;;) { break; foo(); }", 1},
	{"function someFunc() { for (;;) if (foo) break; else return; }", 1},
	{"function someFunc() { for (;;) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (;;) { if (foo) { return; } throw err; } }", 1},
	{"for (;;) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (;;) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (;;) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (;;) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (;;) { break; continue; }", 1},
	{"for (;;) { () => a; break; }", 1},
	{"for (;;) { (() => a)(); break; }", 1},
	{"for (;;) { while (a); break; }", 1},
	{"for (;;) { do ; while (a) break; }", 1},
	{"for (;;) { for (a; b; c); break; }", 1},
	{"for (;;) { for (; b;); break; }", 1},
	{"for (;;) { for (; ; c) if (foo) break; break; }", 1},
	{"for (;;) { for(;;) if (foo) break; break; }", 1},
	{"for (;;) { for (a in b); break; }", 1},
	{"for (;;) { for (a of b); break; }", 1},
	{"for (;;) for (;;);", 1},
	{"for (;;) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (;;) while (true);", 1},
	{"for (a in b) break;", 1},
	{"for (a in b) { break; }", 1},
	{"function someFunc() { for (a in b) return; }", 1},
	{"function someFunc() { for (a in b) { return; } }", 1},
	{"for (a in b) throw err;", 1},
	{"for (a in b) { throw err; }", 1},
	{"for (a in b) { foo(); break; }", 1},
	{"for (a in b) { break; foo(); }", 1},
	{"function someFunc() { for (a in b) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a in b) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a in b) { if (foo) { return; } throw err; } }", 1},
	{"for (a in b) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a in b) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a in b) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a in b) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a in b) { break; continue; }", 1},
	{"for (a in b) { () => a; break; }", 1},
	{"for (a in b) { (() => a)(); break; }", 1},
	{"for (a in b) { while (a); break; }", 1},
	{"for (a in b) { do ; while (a) break; }", 1},
	{"for (a in b) { for (a; b; c); break; }", 1},
	{"for (a in b) { for (; b;); break; }", 1},
	{"for (a in b) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a in b) { for(;;) if (foo) break; break; }", 1},
	{"for (a in b) { for (a in b); break; }", 1},
	{"for (a in b) { for (a of b); break; }", 1},
	{"for (a in b) for (;;);", 1},
	{"for (a in b) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a in b) while (true);", 1},
	{"for (a in f(b)) break;", 1},
	{"for (a in f(b)) { break; }", 1},
	{"function someFunc() { for (a in f(b)) return; }", 1},
	{"function someFunc() { for (a in f(b)) { return; } }", 1},
	{"for (a in f(b)) throw err;", 1},
	{"for (a in f(b)) { throw err; }", 1},
	{"for (a in f(b)) { foo(); break; }", 1},
	{"for (a in f(b)) { break; foo(); }", 1},
	{"function someFunc() { for (a in f(b)) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a in f(b)) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a in f(b)) { if (foo) { return; } throw err; } }", 1},
	{"for (a in f(b)) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a in f(b)) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a in f(b)) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a in f(b)) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a in f(b)) { break; continue; }", 1},
	{"for (a in f(b)) { () => a; break; }", 1},
	{"for (a in f(b)) { (() => a)(); break; }", 1},
	{"for (a in f(b)) { while (a); break; }", 1},
	{"for (a in f(b)) { do ; while (a) break; }", 1},
	{"for (a in f(b)) { for (a; b; c); break; }", 1},
	{"for (a in f(b)) { for (; b;); break; }", 1},
	{"for (a in f(b)) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a in f(b)) { for(;;) if (foo) break; break; }", 1},
	{"for (a in f(b)) { for (a in b); break; }", 1},
	{"for (a in f(b)) { for (a of b); break; }", 1},
	{"for (a in f(b)) for (;;);", 1},
	{"for (a in f(b)) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a in f(b)) while (true);", 1},
	{"for (var a in b) break;", 1},
	{"for (var a in b) { break; }", 1},
	{"function someFunc() { for (var a in b) return; }", 1},
	{"function someFunc() { for (var a in b) { return; } }", 1},
	{"for (var a in b) throw err;", 1},
	{"for (var a in b) { throw err; }", 1},
	{"for (var a in b) { foo(); break; }", 1},
	{"for (var a in b) { break; foo(); }", 1},
	{"function someFunc() { for (var a in b) if (foo) break; else return; }", 1},
	{"function someFunc() { for (var a in b) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (var a in b) { if (foo) { return; } throw err; } }", 1},
	{"for (var a in b) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (var a in b) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (var a in b) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (var a in b) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (var a in b) { break; continue; }", 1},
	{"for (var a in b) { () => a; break; }", 1},
	{"for (var a in b) { (() => a)(); break; }", 1},
	{"for (var a in b) { while (a); break; }", 1},
	{"for (var a in b) { do ; while (a) break; }", 1},
	{"for (var a in b) { for (a; b; c); break; }", 1},
	{"for (var a in b) { for (; b;); break; }", 1},
	{"for (var a in b) { for (; ; c) if (foo) break; break; }", 1},
	{"for (var a in b) { for(;;) if (foo) break; break; }", 1},
	{"for (var a in b) { for (a in b); break; }", 1},
	{"for (var a in b) { for (a of b); break; }", 1},
	{"for (var a in b) for (;;);", 1},
	{"for (var a in b) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (var a in b) while (true);", 1},
	{"for (let a in f(b)) break;", 1},
	{"for (let a in f(b)) { break; }", 1},
	{"function someFunc() { for (let a in f(b)) return; }", 1},
	{"function someFunc() { for (let a in f(b)) { return; } }", 1},
	{"for (let a in f(b)) throw err;", 1},
	{"for (let a in f(b)) { throw err; }", 1},
	{"for (let a in f(b)) { foo(); break; }", 1},
	{"for (let a in f(b)) { break; foo(); }", 1},
	{"function someFunc() { for (let a in f(b)) if (foo) break; else return; }", 1},
	{"function someFunc() { for (let a in f(b)) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (let a in f(b)) { if (foo) { return; } throw err; } }", 1},
	{"for (let a in f(b)) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (let a in f(b)) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (let a in f(b)) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (let a in f(b)) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (let a in f(b)) { break; continue; }", 1},
	{"for (let a in f(b)) { () => a; break; }", 1},
	{"for (let a in f(b)) { (() => a)(); break; }", 1},
	{"for (let a in f(b)) { while (a); break; }", 1},
	{"for (let a in f(b)) { do ; while (a) break; }", 1},
	{"for (let a in f(b)) { for (a; b; c); break; }", 1},
	{"for (let a in f(b)) { for (; b;); break; }", 1},
	{"for (let a in f(b)) { for (; ; c) if (foo) break; break; }", 1},
	{"for (let a in f(b)) { for(;;) if (foo) break; break; }", 1},
	{"for (let a in f(b)) { for (a in b); break; }", 1},
	{"for (let a in f(b)) { for (a of b); break; }", 1},
	{"for (let a in f(b)) for (;;);", 1},
	{"for (let a in f(b)) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (let a in f(b)) while (true);", 1},
	{"for (a of b) break;", 1},
	{"for (a of b) { break; }", 1},
	{"function someFunc() { for (a of b) return; }", 1},
	{"function someFunc() { for (a of b) { return; } }", 1},
	{"for (a of b) throw err;", 1},
	{"for (a of b) { throw err; }", 1},
	{"for (a of b) { foo(); break; }", 1},
	{"for (a of b) { break; foo(); }", 1},
	{"function someFunc() { for (a of b) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a of b) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a of b) { if (foo) { return; } throw err; } }", 1},
	{"for (a of b) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a of b) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a of b) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a of b) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a of b) { break; continue; }", 1},
	{"for (a of b) { () => a; break; }", 1},
	{"for (a of b) { (() => a)(); break; }", 1},
	{"for (a of b) { while (a); break; }", 1},
	{"for (a of b) { do ; while (a) break; }", 1},
	{"for (a of b) { for (a; b; c); break; }", 1},
	{"for (a of b) { for (; b;); break; }", 1},
	{"for (a of b) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a of b) { for(;;) if (foo) break; break; }", 1},
	{"for (a of b) { for (a in b); break; }", 1},
	{"for (a of b) { for (a of b); break; }", 1},
	{"for (a of b) for (;;);", 1},
	{"for (a of b) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a of b) while (true);", 1},
	{"for (a of f(b)) break;", 1},
	{"for (a of f(b)) { break; }", 1},
	{"function someFunc() { for (a of f(b)) return; }", 1},
	{"function someFunc() { for (a of f(b)) { return; } }", 1},
	{"for (a of f(b)) throw err;", 1},
	{"for (a of f(b)) { throw err; }", 1},
	{"for (a of f(b)) { foo(); break; }", 1},
	{"for (a of f(b)) { break; foo(); }", 1},
	{"function someFunc() { for (a of f(b)) if (foo) break; else return; }", 1},
	{"function someFunc() { for (a of f(b)) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (a of f(b)) { if (foo) { return; } throw err; } }", 1},
	{"for (a of f(b)) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (a of f(b)) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (a of f(b)) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (a of f(b)) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (a of f(b)) { break; continue; }", 1},
	{"for (a of f(b)) { () => a; break; }", 1},
	{"for (a of f(b)) { (() => a)(); break; }", 1},
	{"for (a of f(b)) { while (a); break; }", 1},
	{"for (a of f(b)) { do ; while (a) break; }", 1},
	{"for (a of f(b)) { for (a; b; c); break; }", 1},
	{"for (a of f(b)) { for (; b;); break; }", 1},
	{"for (a of f(b)) { for (; ; c) if (foo) break; break; }", 1},
	{"for (a of f(b)) { for(;;) if (foo) break; break; }", 1},
	{"for (a of f(b)) { for (a in b); break; }", 1},
	{"for (a of f(b)) { for (a of b); break; }", 1},
	{"for (a of f(b)) for (;;);", 1},
	{"for (a of f(b)) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (a of f(b)) while (true);", 1},
	{"for ({ a, b } of c) break;", 1},
	{"for ({ a, b } of c) { break; }", 1},
	{"function someFunc() { for ({ a, b } of c) return; }", 1},
	{"function someFunc() { for ({ a, b } of c) { return; } }", 1},
	{"for ({ a, b } of c) throw err;", 1},
	{"for ({ a, b } of c) { throw err; }", 1},
	{"for ({ a, b } of c) { foo(); break; }", 1},
	{"for ({ a, b } of c) { break; foo(); }", 1},
	{"function someFunc() { for ({ a, b } of c) if (foo) break; else return; }", 1},
	{"function someFunc() { for ({ a, b } of c) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for ({ a, b } of c) { if (foo) { return; } throw err; } }", 1},
	{"for ({ a, b } of c) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for ({ a, b } of c) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for ({ a, b } of c) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for ({ a, b } of c) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for ({ a, b } of c) { break; continue; }", 1},
	{"for ({ a, b } of c) { () => a; break; }", 1},
	{"for ({ a, b } of c) { (() => a)(); break; }", 1},
	{"for ({ a, b } of c) { while (a); break; }", 1},
	{"for ({ a, b } of c) { do ; while (a) break; }", 1},
	{"for ({ a, b } of c) { for (a; b; c); break; }", 1},
	{"for ({ a, b } of c) { for (; b;); break; }", 1},
	{"for ({ a, b } of c) { for (; ; c) if (foo) break; break; }", 1},
	{"for ({ a, b } of c) { for(;;) if (foo) break; break; }", 1},
	{"for ({ a, b } of c) { for (a in b); break; }", 1},
	{"for ({ a, b } of c) { for (a of b); break; }", 1},
	{"for ({ a, b } of c) for (;;);", 1},
	{"for ({ a, b } of c) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for ({ a, b } of c) while (true);", 1},
	{"for (var a of f(b)) break;", 1},
	{"for (var a of f(b)) { break; }", 1},
	{"function someFunc() { for (var a of f(b)) return; }", 1},
	{"function someFunc() { for (var a of f(b)) { return; } }", 1},
	{"for (var a of f(b)) throw err;", 1},
	{"for (var a of f(b)) { throw err; }", 1},
	{"for (var a of f(b)) { foo(); break; }", 1},
	{"for (var a of f(b)) { break; foo(); }", 1},
	{"function someFunc() { for (var a of f(b)) if (foo) break; else return; }", 1},
	{"function someFunc() { for (var a of f(b)) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"function someFunc() { for (var a of f(b)) { if (foo) { return; } throw err; } }", 1},
	{"for (var a of f(b)) { switch (foo) { default: throw err; } }", 1},
	{"function someFunc() { for (var a of f(b)) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"function someFunc() { for (var a of f(b)) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"function someFunc() { for (var a of f(b)) { try { return bar(); } catch (e) { break; } } }", 1},
	{"for (var a of f(b)) { break; continue; }", 1},
	{"for (var a of f(b)) { () => a; break; }", 1},
	{"for (var a of f(b)) { (() => a)(); break; }", 1},
	{"for (var a of f(b)) { while (a); break; }", 1},
	{"for (var a of f(b)) { do ; while (a) break; }", 1},
	{"for (var a of f(b)) { for (a; b; c); break; }", 1},
	{"for (var a of f(b)) { for (; b;); break; }", 1},
	{"for (var a of f(b)) { for (; ; c) if (foo) break; break; }", 1},
	{"for (var a of f(b)) { for(;;) if (foo) break; break; }", 1},
	{"for (var a of f(b)) { for (a in b); break; }", 1},
	{"for (var a of f(b)) { for (a of b); break; }", 1},
	{"for (var a of f(b)) for (;;);", 1},
	{"for (var a of f(b)) { for (var i = 0; ; i< 10) { foo(); } }", 1},
	{"for (var a of f(b)) while (true);", 1},
	{"async function foo() { for await (const a of b) break; }", 1},
	{"async function foo() { for await (const a of b) { break; } }", 1},
	{"async function foo() { for await (const a of b) return; }", 1},
	{"async function foo() { for await (const a of b) { return; } }", 1},
	{"async function foo() { for await (const a of b) throw err; }", 1},
	{"async function foo() { for await (const a of b) { throw err; } }", 1},
	{"async function foo() { for await (const a of b) { foo(); break; } }", 1},
	{"async function foo() { for await (const a of b) { break; foo(); } }", 1},
	{"async function foo() { for await (const a of b) if (foo) break; else return; }", 1},
	{"async function foo() { for await (const a of b) { if (foo) { return; } else { break; } bar(); } }", 1},
	{"async function foo() { for await (const a of b) { if (foo) { return; } throw err; } }", 1},
	{"async function foo() { for await (const a of b) { switch (foo) { default: throw err; } } }", 1},
	{"async function foo() { for await (const a of b) { switch (foo) { case 1: throw err; default: return; } } }", 1},
	{"async function foo() { for await (const a of b) { switch (foo) { case 1: something(); default: return; } } }", 1},
	{"async function foo() { for await (const a of b) { try { return bar(); } catch (e) { break; } } }", 1},
	{"async function foo() { for await (const a of b) { break; continue; } }", 1},
	{"async function foo() { for await (const a of b) { () => a; break; } }", 1},
	{"async function foo() { for await (const a of b) { (() => a)(); break; } }", 1},
	{"async function foo() { for await (const a of b) { while (a); break; } }", 1},
	{"async function foo() { for await (const a of b) { do ; while (a) break; } }", 1},
	{"async function foo() { for await (const a of b) { for (a; b; c); break; } }", 1},
	{"async function foo() { for await (const a of b) { for (; b;); break; } }", 1},
	{"async function foo() { for await (const a of b) { for (; ; c) if (foo) break; break; } }", 1},
	{"async function foo() { for await (const a of b) { for(;;) if (foo) break; break; } }", 1},
	{"async function foo() { for await (const a of b) { for (a in b); break; } }", 1},
	{"async function foo() { for await (const a of b) { for (a of b); break; } }", 1},
	{"async function foo() { for await (const a of b) for (;;); }", 1},
	{"async function foo() { for await (const a of b) { for (var i = 0; ; i< 10) { foo(); } } }", 1},
	{"async function foo() { for await (const a of b) while (true); }", 1},
	{"while (foo) { for (a of b) { if (baz) { break; } else { throw err; } } }", 1},
	{"lbl: for (var i = 0; i < 10; i++) { while (foo) break lbl; } /* outer is valid because inner can have 0 iterations */", 1},
	{"for (a in b) { while (foo) { if(baz) { break; } else { break; } } break; }", 2},
	{"function foo() { for (var i = 0; i < 10; i++) { do { return; } while(i) } }", 2},
	{"lbl: while(foo) { do { break lbl; } while(baz) }", 2},
	{"lbl: for (a in b) { while(foo) { continue lbl; } }", 1},
	{"for (a of b) { for(;;) { if (foo) { throw err; } } }", 1},
	{"function foo () { for (a in b) { while (true) { if (bar) { return; } } } }", 1},
	{"do for (var i = 1; i < 10; i++) break; while(foo)", 1},
	{"do { for (var i = 1; i < 10; i++) continue; break; } while(foo)", 1},
	{"for (;;) { for (var i = 1; i < 10; i ++) break; if (foo) break; continue; }", 1},
}

// unreachableLoopCleanCases are the corpus inputs upstream stays silent on. These are the false
// positives upstream already thought about.
var unreachableLoopCleanCases = []string{
	"while (a) ;",
	"while (a) {}",
	"while (a) { bar(); }",
	"while (a) continue;",
	"while (a) { continue; }",
	"while (a) { if (foo) break; }",
	"function someFunc() { while (a) { if (foo) { return; } bar(); } }",
	"while (a) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { while (a) { if (foo) { continue; } return; } }",
	"function someFunc() { while (a) { switch (foo) { case 1: return; } } }",
	"function someFunc() { while (a) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { while (a) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { while (a) { try { return bar(); } catch (e) {} } }",
	"while (a) { continue; break; }",
	"while (a) () => a;",
	"while (a) { () => a }",
	"while (a) (() => a)();",
	"while (a) { (() => a)() }",
	"while (a) while (a);",
	"while (a) do ; while (a)",
	"while (a) for (a; b; c);",
	"while (a) for (; b;);",
	"while (a) for (; ; c) if (foo) break;",
	"while (a) for (;;) if (foo) break;",
	"while (a) while (true) if (foo) break;",
	"function someFunc() { while (a) while (foo) if (bar) return; }",
	"while (a) for (a in b);",
	"while (a) for (a of b);",
	"while (a && b) ;",
	"while (a && b) {}",
	"while (a && b) { bar(); }",
	"while (a && b) continue;",
	"while (a && b) { continue; }",
	"while (a && b) { if (foo) break; }",
	"function someFunc() { while (a && b) { if (foo) { return; } bar(); } }",
	"while (a && b) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { while (a && b) { if (foo) { continue; } return; } }",
	"function someFunc() { while (a && b) { switch (foo) { case 1: return; } } }",
	"function someFunc() { while (a && b) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { while (a && b) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { while (a && b) { try { return bar(); } catch (e) {} } }",
	"while (a && b) { continue; break; }",
	"while (a && b) () => a;",
	"while (a && b) { () => a }",
	"while (a && b) (() => a)();",
	"while (a && b) { (() => a)() }",
	"while (a && b) while (a);",
	"while (a && b) do ; while (a)",
	"while (a && b) for (a; b; c);",
	"while (a && b) for (; b;);",
	"while (a && b) for (; ; c) if (foo) break;",
	"while (a && b) for (;;) if (foo) break;",
	"while (a && b) while (true) if (foo) break;",
	"function someFunc() { while (a && b) while (foo) if (bar) return; }",
	"while (a && b) for (a in b);",
	"while (a && b) for (a of b);",
	"do ; while (a)",
	"do {} while (a)",
	"do { bar(); } while (a)",
	"do continue; while (a)",
	"do { continue; } while (a)",
	"do { if (foo) break; } while (a)",
	"function someFunc() { do { if (foo) { return; } bar(); } while (a) }",
	"do { if (foo) { bar(); } else { break; } } while (a)",
	"function someFunc() { do { if (foo) { continue; } return; } while (a) }",
	"function someFunc() { do { switch (foo) { case 1: return; } } while (a) }",
	"function someFunc() { do { switch (foo) { case 1: break; default: return; } } while (a) }",
	"function someFunc() { do { switch (foo) { case 1: continue; default: return; } throw err; } while (a) }",
	"function someFunc() { do { try { return bar(); } catch (e) {} } while (a) }",
	"do { continue; break; } while (a)",
	"do () => a; while (a)",
	"do { () => a } while (a)",
	"do (() => a)(); while (a)",
	"do { (() => a)() } while (a)",
	"do while (a); while (a)",
	"do do ; while (a) while (a)",
	"do for (a; b; c); while (a)",
	"do for (; b;); while (a)",
	"do for (; ; c) if (foo) break; while (a)",
	"do for (;;) if (foo) break; while (a)",
	"do while (true) if (foo) break; while (a)",
	"function someFunc() { do while (foo) if (bar) return; while (a) }",
	"do for (a in b); while (a)",
	"do for (a of b); while (a)",
	"do ; while (a && b)",
	"do {} while (a && b)",
	"do { bar(); } while (a && b)",
	"do continue; while (a && b)",
	"do { continue; } while (a && b)",
	"do { if (foo) break; } while (a && b)",
	"function someFunc() { do { if (foo) { return; } bar(); } while (a && b) }",
	"do { if (foo) { bar(); } else { break; } } while (a && b)",
	"function someFunc() { do { if (foo) { continue; } return; } while (a && b) }",
	"function someFunc() { do { switch (foo) { case 1: return; } } while (a && b) }",
	"function someFunc() { do { switch (foo) { case 1: break; default: return; } } while (a && b) }",
	"function someFunc() { do { switch (foo) { case 1: continue; default: return; } throw err; } while (a && b) }",
	"function someFunc() { do { try { return bar(); } catch (e) {} } while (a && b) }",
	"do { continue; break; } while (a && b)",
	"do () => a; while (a && b)",
	"do { () => a } while (a && b)",
	"do (() => a)(); while (a && b)",
	"do { (() => a)() } while (a && b)",
	"do while (a); while (a && b)",
	"do do ; while (a) while (a && b)",
	"do for (a; b; c); while (a && b)",
	"do for (; b;); while (a && b)",
	"do for (; ; c) if (foo) break; while (a && b)",
	"do for (;;) if (foo) break; while (a && b)",
	"do while (true) if (foo) break; while (a && b)",
	"function someFunc() { do while (foo) if (bar) return; while (a && b) }",
	"do for (a in b); while (a && b)",
	"do for (a of b); while (a && b)",
	"for (a; b; c) ;",
	"for (a; b; c) {}",
	"for (a; b; c) { bar(); }",
	"for (a; b; c) continue;",
	"for (a; b; c) { continue; }",
	"for (a; b; c) { if (foo) break; }",
	"function someFunc() { for (a; b; c) { if (foo) { return; } bar(); } }",
	"for (a; b; c) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a; b; c) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a; b; c) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a; b; c) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a; b; c) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a; b; c) { try { return bar(); } catch (e) {} } }",
	"for (a; b; c) { continue; break; }",
	"for (a; b; c) () => a;",
	"for (a; b; c) { () => a }",
	"for (a; b; c) (() => a)();",
	"for (a; b; c) { (() => a)() }",
	"for (a; b; c) while (a);",
	"for (a; b; c) do ; while (a)",
	"for (a; b; c) for (a; b; c);",
	"for (a; b; c) for (; b;);",
	"for (a; b; c) for (; ; c) if (foo) break;",
	"for (a; b; c) for (;;) if (foo) break;",
	"for (a; b; c) while (true) if (foo) break;",
	"function someFunc() { for (a; b; c) while (foo) if (bar) return; }",
	"for (a; b; c) for (a in b);",
	"for (a; b; c) for (a of b);",
	"for (var i = 0; i < a.length; i++) ;",
	"for (var i = 0; i < a.length; i++) {}",
	"for (var i = 0; i < a.length; i++) { bar(); }",
	"for (var i = 0; i < a.length; i++) continue;",
	"for (var i = 0; i < a.length; i++) { continue; }",
	"for (var i = 0; i < a.length; i++) { if (foo) break; }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { if (foo) { return; } bar(); } }",
	"for (var i = 0; i < a.length; i++) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { if (foo) { continue; } return; } }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (var i = 0; i < a.length; i++) { try { return bar(); } catch (e) {} } }",
	"for (var i = 0; i < a.length; i++) { continue; break; }",
	"for (var i = 0; i < a.length; i++) () => a;",
	"for (var i = 0; i < a.length; i++) { () => a }",
	"for (var i = 0; i < a.length; i++) (() => a)();",
	"for (var i = 0; i < a.length; i++) { (() => a)() }",
	"for (var i = 0; i < a.length; i++) while (a);",
	"for (var i = 0; i < a.length; i++) do ; while (a)",
	"for (var i = 0; i < a.length; i++) for (a; b; c);",
	"for (var i = 0; i < a.length; i++) for (; b;);",
	"for (var i = 0; i < a.length; i++) for (; ; c) if (foo) break;",
	"for (var i = 0; i < a.length; i++) for (;;) if (foo) break;",
	"for (var i = 0; i < a.length; i++) while (true) if (foo) break;",
	"function someFunc() { for (var i = 0; i < a.length; i++) while (foo) if (bar) return; }",
	"for (var i = 0; i < a.length; i++) for (a in b);",
	"for (var i = 0; i < a.length; i++) for (a of b);",
	"for (; b; c) ;",
	"for (; b; c) {}",
	"for (; b; c) { bar(); }",
	"for (; b; c) continue;",
	"for (; b; c) { continue; }",
	"for (; b; c) { if (foo) break; }",
	"function someFunc() { for (; b; c) { if (foo) { return; } bar(); } }",
	"for (; b; c) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; b; c) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; b; c) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; b; c) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; b; c) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; b; c) { try { return bar(); } catch (e) {} } }",
	"for (; b; c) { continue; break; }",
	"for (; b; c) () => a;",
	"for (; b; c) { () => a }",
	"for (; b; c) (() => a)();",
	"for (; b; c) { (() => a)() }",
	"for (; b; c) while (a);",
	"for (; b; c) do ; while (a)",
	"for (; b; c) for (a; b; c);",
	"for (; b; c) for (; b;);",
	"for (; b; c) for (; ; c) if (foo) break;",
	"for (; b; c) for (;;) if (foo) break;",
	"for (; b; c) while (true) if (foo) break;",
	"function someFunc() { for (; b; c) while (foo) if (bar) return; }",
	"for (; b; c) for (a in b);",
	"for (; b; c) for (a of b);",
	"for (; b < foo; c++) ;",
	"for (; b < foo; c++) {}",
	"for (; b < foo; c++) { bar(); }",
	"for (; b < foo; c++) continue;",
	"for (; b < foo; c++) { continue; }",
	"for (; b < foo; c++) { if (foo) break; }",
	"function someFunc() { for (; b < foo; c++) { if (foo) { return; } bar(); } }",
	"for (; b < foo; c++) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; b < foo; c++) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; b < foo; c++) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; b < foo; c++) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; b < foo; c++) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; b < foo; c++) { try { return bar(); } catch (e) {} } }",
	"for (; b < foo; c++) { continue; break; }",
	"for (; b < foo; c++) () => a;",
	"for (; b < foo; c++) { () => a }",
	"for (; b < foo; c++) (() => a)();",
	"for (; b < foo; c++) { (() => a)() }",
	"for (; b < foo; c++) while (a);",
	"for (; b < foo; c++) do ; while (a)",
	"for (; b < foo; c++) for (a; b; c);",
	"for (; b < foo; c++) for (; b;);",
	"for (; b < foo; c++) for (; ; c) if (foo) break;",
	"for (; b < foo; c++) for (;;) if (foo) break;",
	"for (; b < foo; c++) while (true) if (foo) break;",
	"function someFunc() { for (; b < foo; c++) while (foo) if (bar) return; }",
	"for (; b < foo; c++) for (a in b);",
	"for (; b < foo; c++) for (a of b);",
	"for (a; ; c) ;",
	"for (a; ; c) {}",
	"for (a; ; c) { bar(); }",
	"for (a; ; c) continue;",
	"for (a; ; c) { continue; }",
	"for (a; ; c) { if (foo) break; }",
	"function someFunc() { for (a; ; c) { if (foo) { return; } bar(); } }",
	"for (a; ; c) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a; ; c) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a; ; c) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a; ; c) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a; ; c) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a; ; c) { try { return bar(); } catch (e) {} } }",
	"for (a; ; c) { continue; break; }",
	"for (a; ; c) () => a;",
	"for (a; ; c) { () => a }",
	"for (a; ; c) (() => a)();",
	"for (a; ; c) { (() => a)() }",
	"for (a; ; c) while (a);",
	"for (a; ; c) do ; while (a)",
	"for (a; ; c) for (a; b; c);",
	"for (a; ; c) for (; b;);",
	"for (a; ; c) for (; ; c) if (foo) break;",
	"for (a; ; c) for (;;) if (foo) break;",
	"for (a; ; c) while (true) if (foo) break;",
	"function someFunc() { for (a; ; c) while (foo) if (bar) return; }",
	"for (a; ; c) for (a in b);",
	"for (a; ; c) for (a of b);",
	"for (a = 0; ; c++) ;",
	"for (a = 0; ; c++) {}",
	"for (a = 0; ; c++) { bar(); }",
	"for (a = 0; ; c++) continue;",
	"for (a = 0; ; c++) { continue; }",
	"for (a = 0; ; c++) { if (foo) break; }",
	"function someFunc() { for (a = 0; ; c++) { if (foo) { return; } bar(); } }",
	"for (a = 0; ; c++) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a = 0; ; c++) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a = 0; ; c++) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a = 0; ; c++) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a = 0; ; c++) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a = 0; ; c++) { try { return bar(); } catch (e) {} } }",
	"for (a = 0; ; c++) { continue; break; }",
	"for (a = 0; ; c++) () => a;",
	"for (a = 0; ; c++) { () => a }",
	"for (a = 0; ; c++) (() => a)();",
	"for (a = 0; ; c++) { (() => a)() }",
	"for (a = 0; ; c++) while (a);",
	"for (a = 0; ; c++) do ; while (a)",
	"for (a = 0; ; c++) for (a; b; c);",
	"for (a = 0; ; c++) for (; b;);",
	"for (a = 0; ; c++) for (; ; c) if (foo) break;",
	"for (a = 0; ; c++) for (;;) if (foo) break;",
	"for (a = 0; ; c++) while (true) if (foo) break;",
	"function someFunc() { for (a = 0; ; c++) while (foo) if (bar) return; }",
	"for (a = 0; ; c++) for (a in b);",
	"for (a = 0; ; c++) for (a of b);",
	"for (a; b;) ;",
	"for (a; b;) {}",
	"for (a; b;) { bar(); }",
	"for (a; b;) continue;",
	"for (a; b;) { continue; }",
	"for (a; b;) { if (foo) break; }",
	"function someFunc() { for (a; b;) { if (foo) { return; } bar(); } }",
	"for (a; b;) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a; b;) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a; b;) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a; b;) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a; b;) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a; b;) { try { return bar(); } catch (e) {} } }",
	"for (a; b;) { continue; break; }",
	"for (a; b;) () => a;",
	"for (a; b;) { () => a }",
	"for (a; b;) (() => a)();",
	"for (a; b;) { (() => a)() }",
	"for (a; b;) while (a);",
	"for (a; b;) do ; while (a)",
	"for (a; b;) for (a; b; c);",
	"for (a; b;) for (; b;);",
	"for (a; b;) for (; ; c) if (foo) break;",
	"for (a; b;) for (;;) if (foo) break;",
	"for (a; b;) while (true) if (foo) break;",
	"function someFunc() { for (a; b;) while (foo) if (bar) return; }",
	"for (a; b;) for (a in b);",
	"for (a; b;) for (a of b);",
	"for (a = 0; b < foo; ) ;",
	"for (a = 0; b < foo; ) {}",
	"for (a = 0; b < foo; ) { bar(); }",
	"for (a = 0; b < foo; ) continue;",
	"for (a = 0; b < foo; ) { continue; }",
	"for (a = 0; b < foo; ) { if (foo) break; }",
	"function someFunc() { for (a = 0; b < foo; ) { if (foo) { return; } bar(); } }",
	"for (a = 0; b < foo; ) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a = 0; b < foo; ) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a = 0; b < foo; ) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a = 0; b < foo; ) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a = 0; b < foo; ) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a = 0; b < foo; ) { try { return bar(); } catch (e) {} } }",
	"for (a = 0; b < foo; ) { continue; break; }",
	"for (a = 0; b < foo; ) () => a;",
	"for (a = 0; b < foo; ) { () => a }",
	"for (a = 0; b < foo; ) (() => a)();",
	"for (a = 0; b < foo; ) { (() => a)() }",
	"for (a = 0; b < foo; ) while (a);",
	"for (a = 0; b < foo; ) do ; while (a)",
	"for (a = 0; b < foo; ) for (a; b; c);",
	"for (a = 0; b < foo; ) for (; b;);",
	"for (a = 0; b < foo; ) for (; ; c) if (foo) break;",
	"for (a = 0; b < foo; ) for (;;) if (foo) break;",
	"for (a = 0; b < foo; ) while (true) if (foo) break;",
	"function someFunc() { for (a = 0; b < foo; ) while (foo) if (bar) return; }",
	"for (a = 0; b < foo; ) for (a in b);",
	"for (a = 0; b < foo; ) for (a of b);",
	"for (; ; c) ;",
	"for (; ; c) {}",
	"for (; ; c) { bar(); }",
	"for (; ; c) continue;",
	"for (; ; c) { continue; }",
	"for (; ; c) { if (foo) break; }",
	"function someFunc() { for (; ; c) { if (foo) { return; } bar(); } }",
	"for (; ; c) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; ; c) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; ; c) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; ; c) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; ; c) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; ; c) { try { return bar(); } catch (e) {} } }",
	"for (; ; c) { continue; break; }",
	"for (; ; c) () => a;",
	"for (; ; c) { () => a }",
	"for (; ; c) (() => a)();",
	"for (; ; c) { (() => a)() }",
	"for (; ; c) while (a);",
	"for (; ; c) do ; while (a)",
	"for (; ; c) for (a; b; c);",
	"for (; ; c) for (; b;);",
	"for (; ; c) for (; ; c) if (foo) break;",
	"for (; ; c) for (;;) if (foo) break;",
	"for (; ; c) while (true) if (foo) break;",
	"function someFunc() { for (; ; c) while (foo) if (bar) return; }",
	"for (; ; c) for (a in b);",
	"for (; ; c) for (a of b);",
	"for (; ; c++) ;",
	"for (; ; c++) {}",
	"for (; ; c++) { bar(); }",
	"for (; ; c++) continue;",
	"for (; ; c++) { continue; }",
	"for (; ; c++) { if (foo) break; }",
	"function someFunc() { for (; ; c++) { if (foo) { return; } bar(); } }",
	"for (; ; c++) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; ; c++) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; ; c++) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; ; c++) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; ; c++) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; ; c++) { try { return bar(); } catch (e) {} } }",
	"for (; ; c++) { continue; break; }",
	"for (; ; c++) () => a;",
	"for (; ; c++) { () => a }",
	"for (; ; c++) (() => a)();",
	"for (; ; c++) { (() => a)() }",
	"for (; ; c++) while (a);",
	"for (; ; c++) do ; while (a)",
	"for (; ; c++) for (a; b; c);",
	"for (; ; c++) for (; b;);",
	"for (; ; c++) for (; ; c) if (foo) break;",
	"for (; ; c++) for (;;) if (foo) break;",
	"for (; ; c++) while (true) if (foo) break;",
	"function someFunc() { for (; ; c++) while (foo) if (bar) return; }",
	"for (; ; c++) for (a in b);",
	"for (; ; c++) for (a of b);",
	"for (; b;) ;",
	"for (; b;) {}",
	"for (; b;) { bar(); }",
	"for (; b;) continue;",
	"for (; b;) { continue; }",
	"for (; b;) { if (foo) break; }",
	"function someFunc() { for (; b;) { if (foo) { return; } bar(); } }",
	"for (; b;) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; b;) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; b;) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; b;) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; b;) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; b;) { try { return bar(); } catch (e) {} } }",
	"for (; b;) { continue; break; }",
	"for (; b;) () => a;",
	"for (; b;) { () => a }",
	"for (; b;) (() => a)();",
	"for (; b;) { (() => a)() }",
	"for (; b;) while (a);",
	"for (; b;) do ; while (a)",
	"for (; b;) for (a; b; c);",
	"for (; b;) for (; b;);",
	"for (; b;) for (; ; c) if (foo) break;",
	"for (; b;) for (;;) if (foo) break;",
	"for (; b;) while (true) if (foo) break;",
	"function someFunc() { for (; b;) while (foo) if (bar) return; }",
	"for (; b;) for (a in b);",
	"for (; b;) for (a of b);",
	"for (; b < foo; ) ;",
	"for (; b < foo; ) {}",
	"for (; b < foo; ) { bar(); }",
	"for (; b < foo; ) continue;",
	"for (; b < foo; ) { continue; }",
	"for (; b < foo; ) { if (foo) break; }",
	"function someFunc() { for (; b < foo; ) { if (foo) { return; } bar(); } }",
	"for (; b < foo; ) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (; b < foo; ) { if (foo) { continue; } return; } }",
	"function someFunc() { for (; b < foo; ) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (; b < foo; ) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (; b < foo; ) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (; b < foo; ) { try { return bar(); } catch (e) {} } }",
	"for (; b < foo; ) { continue; break; }",
	"for (; b < foo; ) () => a;",
	"for (; b < foo; ) { () => a }",
	"for (; b < foo; ) (() => a)();",
	"for (; b < foo; ) { (() => a)() }",
	"for (; b < foo; ) while (a);",
	"for (; b < foo; ) do ; while (a)",
	"for (; b < foo; ) for (a; b; c);",
	"for (; b < foo; ) for (; b;);",
	"for (; b < foo; ) for (; ; c) if (foo) break;",
	"for (; b < foo; ) for (;;) if (foo) break;",
	"for (; b < foo; ) while (true) if (foo) break;",
	"function someFunc() { for (; b < foo; ) while (foo) if (bar) return; }",
	"for (; b < foo; ) for (a in b);",
	"for (; b < foo; ) for (a of b);",
	"for (a; ;) ;",
	"for (a; ;) {}",
	"for (a; ;) { bar(); }",
	"for (a; ;) continue;",
	"for (a; ;) { continue; }",
	"for (a; ;) { if (foo) break; }",
	"function someFunc() { for (a; ;) { if (foo) { return; } bar(); } }",
	"for (a; ;) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a; ;) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a; ;) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a; ;) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a; ;) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a; ;) { try { return bar(); } catch (e) {} } }",
	"for (a; ;) { continue; break; }",
	"for (a; ;) () => a;",
	"for (a; ;) { () => a }",
	"for (a; ;) (() => a)();",
	"for (a; ;) { (() => a)() }",
	"for (a; ;) while (a);",
	"for (a; ;) do ; while (a)",
	"for (a; ;) for (a; b; c);",
	"for (a; ;) for (; b;);",
	"for (a; ;) for (; ; c) if (foo) break;",
	"for (a; ;) for (;;) if (foo) break;",
	"for (a; ;) while (true) if (foo) break;",
	"function someFunc() { for (a; ;) while (foo) if (bar) return; }",
	"for (a; ;) for (a in b);",
	"for (a; ;) for (a of b);",
	"for (a = 0; ;) ;",
	"for (a = 0; ;) {}",
	"for (a = 0; ;) { bar(); }",
	"for (a = 0; ;) continue;",
	"for (a = 0; ;) { continue; }",
	"for (a = 0; ;) { if (foo) break; }",
	"function someFunc() { for (a = 0; ;) { if (foo) { return; } bar(); } }",
	"for (a = 0; ;) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a = 0; ;) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a = 0; ;) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a = 0; ;) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a = 0; ;) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a = 0; ;) { try { return bar(); } catch (e) {} } }",
	"for (a = 0; ;) { continue; break; }",
	"for (a = 0; ;) () => a;",
	"for (a = 0; ;) { () => a }",
	"for (a = 0; ;) (() => a)();",
	"for (a = 0; ;) { (() => a)() }",
	"for (a = 0; ;) while (a);",
	"for (a = 0; ;) do ; while (a)",
	"for (a = 0; ;) for (a; b; c);",
	"for (a = 0; ;) for (; b;);",
	"for (a = 0; ;) for (; ; c) if (foo) break;",
	"for (a = 0; ;) for (;;) if (foo) break;",
	"for (a = 0; ;) while (true) if (foo) break;",
	"function someFunc() { for (a = 0; ;) while (foo) if (bar) return; }",
	"for (a = 0; ;) for (a in b);",
	"for (a = 0; ;) for (a of b);",
	"for (;;) ;",
	"for (;;) {}",
	"for (;;) { bar(); }",
	"for (;;) continue;",
	"for (;;) { continue; }",
	"for (;;) { if (foo) break; }",
	"function someFunc() { for (;;) { if (foo) { return; } bar(); } }",
	"for (;;) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (;;) { if (foo) { continue; } return; } }",
	"function someFunc() { for (;;) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (;;) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (;;) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (;;) { try { return bar(); } catch (e) {} } }",
	"for (;;) { continue; break; }",
	"for (;;) () => a;",
	"for (;;) { () => a }",
	"for (;;) (() => a)();",
	"for (;;) { (() => a)() }",
	"for (;;) while (a);",
	"for (;;) do ; while (a)",
	"for (;;) for (a; b; c);",
	"for (;;) for (; b;);",
	"for (;;) for (; ; c) if (foo) break;",
	"for (;;) for (;;) if (foo) break;",
	"for (;;) while (true) if (foo) break;",
	"function someFunc() { for (;;) while (foo) if (bar) return; }",
	"for (;;) for (a in b);",
	"for (;;) for (a of b);",
	"for (a in b) ;",
	"for (a in b) {}",
	"for (a in b) { bar(); }",
	"for (a in b) continue;",
	"for (a in b) { continue; }",
	"for (a in b) { if (foo) break; }",
	"function someFunc() { for (a in b) { if (foo) { return; } bar(); } }",
	"for (a in b) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a in b) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a in b) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a in b) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a in b) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a in b) { try { return bar(); } catch (e) {} } }",
	"for (a in b) { continue; break; }",
	"for (a in b) () => a;",
	"for (a in b) { () => a }",
	"for (a in b) (() => a)();",
	"for (a in b) { (() => a)() }",
	"for (a in b) while (a);",
	"for (a in b) do ; while (a)",
	"for (a in b) for (a; b; c);",
	"for (a in b) for (; b;);",
	"for (a in b) for (; ; c) if (foo) break;",
	"for (a in b) for (;;) if (foo) break;",
	"for (a in b) while (true) if (foo) break;",
	"function someFunc() { for (a in b) while (foo) if (bar) return; }",
	"for (a in b) for (a in b);",
	"for (a in b) for (a of b);",
	"for (a in f(b)) ;",
	"for (a in f(b)) {}",
	"for (a in f(b)) { bar(); }",
	"for (a in f(b)) continue;",
	"for (a in f(b)) { continue; }",
	"for (a in f(b)) { if (foo) break; }",
	"function someFunc() { for (a in f(b)) { if (foo) { return; } bar(); } }",
	"for (a in f(b)) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a in f(b)) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a in f(b)) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a in f(b)) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a in f(b)) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a in f(b)) { try { return bar(); } catch (e) {} } }",
	"for (a in f(b)) { continue; break; }",
	"for (a in f(b)) () => a;",
	"for (a in f(b)) { () => a }",
	"for (a in f(b)) (() => a)();",
	"for (a in f(b)) { (() => a)() }",
	"for (a in f(b)) while (a);",
	"for (a in f(b)) do ; while (a)",
	"for (a in f(b)) for (a; b; c);",
	"for (a in f(b)) for (; b;);",
	"for (a in f(b)) for (; ; c) if (foo) break;",
	"for (a in f(b)) for (;;) if (foo) break;",
	"for (a in f(b)) while (true) if (foo) break;",
	"function someFunc() { for (a in f(b)) while (foo) if (bar) return; }",
	"for (a in f(b)) for (a in b);",
	"for (a in f(b)) for (a of b);",
	"for (var a in b) ;",
	"for (var a in b) {}",
	"for (var a in b) { bar(); }",
	"for (var a in b) continue;",
	"for (var a in b) { continue; }",
	"for (var a in b) { if (foo) break; }",
	"function someFunc() { for (var a in b) { if (foo) { return; } bar(); } }",
	"for (var a in b) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (var a in b) { if (foo) { continue; } return; } }",
	"function someFunc() { for (var a in b) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (var a in b) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (var a in b) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (var a in b) { try { return bar(); } catch (e) {} } }",
	"for (var a in b) { continue; break; }",
	"for (var a in b) () => a;",
	"for (var a in b) { () => a }",
	"for (var a in b) (() => a)();",
	"for (var a in b) { (() => a)() }",
	"for (var a in b) while (a);",
	"for (var a in b) do ; while (a)",
	"for (var a in b) for (a; b; c);",
	"for (var a in b) for (; b;);",
	"for (var a in b) for (; ; c) if (foo) break;",
	"for (var a in b) for (;;) if (foo) break;",
	"for (var a in b) while (true) if (foo) break;",
	"function someFunc() { for (var a in b) while (foo) if (bar) return; }",
	"for (var a in b) for (a in b);",
	"for (var a in b) for (a of b);",
	"for (let a in f(b)) ;",
	"for (let a in f(b)) {}",
	"for (let a in f(b)) { bar(); }",
	"for (let a in f(b)) continue;",
	"for (let a in f(b)) { continue; }",
	"for (let a in f(b)) { if (foo) break; }",
	"function someFunc() { for (let a in f(b)) { if (foo) { return; } bar(); } }",
	"for (let a in f(b)) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (let a in f(b)) { if (foo) { continue; } return; } }",
	"function someFunc() { for (let a in f(b)) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (let a in f(b)) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (let a in f(b)) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (let a in f(b)) { try { return bar(); } catch (e) {} } }",
	"for (let a in f(b)) { continue; break; }",
	"for (let a in f(b)) () => a;",
	"for (let a in f(b)) { () => a }",
	"for (let a in f(b)) (() => a)();",
	"for (let a in f(b)) { (() => a)() }",
	"for (let a in f(b)) while (a);",
	"for (let a in f(b)) do ; while (a)",
	"for (let a in f(b)) for (a; b; c);",
	"for (let a in f(b)) for (; b;);",
	"for (let a in f(b)) for (; ; c) if (foo) break;",
	"for (let a in f(b)) for (;;) if (foo) break;",
	"for (let a in f(b)) while (true) if (foo) break;",
	"function someFunc() { for (let a in f(b)) while (foo) if (bar) return; }",
	"for (let a in f(b)) for (a in b);",
	"for (let a in f(b)) for (a of b);",
	"for (a of b) ;",
	"for (a of b) {}",
	"for (a of b) { bar(); }",
	"for (a of b) continue;",
	"for (a of b) { continue; }",
	"for (a of b) { if (foo) break; }",
	"function someFunc() { for (a of b) { if (foo) { return; } bar(); } }",
	"for (a of b) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a of b) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a of b) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a of b) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a of b) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a of b) { try { return bar(); } catch (e) {} } }",
	"for (a of b) { continue; break; }",
	"for (a of b) () => a;",
	"for (a of b) { () => a }",
	"for (a of b) (() => a)();",
	"for (a of b) { (() => a)() }",
	"for (a of b) while (a);",
	"for (a of b) do ; while (a)",
	"for (a of b) for (a; b; c);",
	"for (a of b) for (; b;);",
	"for (a of b) for (; ; c) if (foo) break;",
	"for (a of b) for (;;) if (foo) break;",
	"for (a of b) while (true) if (foo) break;",
	"function someFunc() { for (a of b) while (foo) if (bar) return; }",
	"for (a of b) for (a in b);",
	"for (a of b) for (a of b);",
	"for (a of f(b)) ;",
	"for (a of f(b)) {}",
	"for (a of f(b)) { bar(); }",
	"for (a of f(b)) continue;",
	"for (a of f(b)) { continue; }",
	"for (a of f(b)) { if (foo) break; }",
	"function someFunc() { for (a of f(b)) { if (foo) { return; } bar(); } }",
	"for (a of f(b)) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (a of f(b)) { if (foo) { continue; } return; } }",
	"function someFunc() { for (a of f(b)) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (a of f(b)) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (a of f(b)) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (a of f(b)) { try { return bar(); } catch (e) {} } }",
	"for (a of f(b)) { continue; break; }",
	"for (a of f(b)) () => a;",
	"for (a of f(b)) { () => a }",
	"for (a of f(b)) (() => a)();",
	"for (a of f(b)) { (() => a)() }",
	"for (a of f(b)) while (a);",
	"for (a of f(b)) do ; while (a)",
	"for (a of f(b)) for (a; b; c);",
	"for (a of f(b)) for (; b;);",
	"for (a of f(b)) for (; ; c) if (foo) break;",
	"for (a of f(b)) for (;;) if (foo) break;",
	"for (a of f(b)) while (true) if (foo) break;",
	"function someFunc() { for (a of f(b)) while (foo) if (bar) return; }",
	"for (a of f(b)) for (a in b);",
	"for (a of f(b)) for (a of b);",
	"for ({ a, b } of c) ;",
	"for ({ a, b } of c) {}",
	"for ({ a, b } of c) { bar(); }",
	"for ({ a, b } of c) continue;",
	"for ({ a, b } of c) { continue; }",
	"for ({ a, b } of c) { if (foo) break; }",
	"function someFunc() { for ({ a, b } of c) { if (foo) { return; } bar(); } }",
	"for ({ a, b } of c) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for ({ a, b } of c) { if (foo) { continue; } return; } }",
	"function someFunc() { for ({ a, b } of c) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for ({ a, b } of c) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for ({ a, b } of c) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for ({ a, b } of c) { try { return bar(); } catch (e) {} } }",
	"for ({ a, b } of c) { continue; break; }",
	"for ({ a, b } of c) () => a;",
	"for ({ a, b } of c) { () => a }",
	"for ({ a, b } of c) (() => a)();",
	"for ({ a, b } of c) { (() => a)() }",
	"for ({ a, b } of c) while (a);",
	"for ({ a, b } of c) do ; while (a)",
	"for ({ a, b } of c) for (a; b; c);",
	"for ({ a, b } of c) for (; b;);",
	"for ({ a, b } of c) for (; ; c) if (foo) break;",
	"for ({ a, b } of c) for (;;) if (foo) break;",
	"for ({ a, b } of c) while (true) if (foo) break;",
	"function someFunc() { for ({ a, b } of c) while (foo) if (bar) return; }",
	"for ({ a, b } of c) for (a in b);",
	"for ({ a, b } of c) for (a of b);",
	"for (var a of f(b)) ;",
	"for (var a of f(b)) {}",
	"for (var a of f(b)) { bar(); }",
	"for (var a of f(b)) continue;",
	"for (var a of f(b)) { continue; }",
	"for (var a of f(b)) { if (foo) break; }",
	"function someFunc() { for (var a of f(b)) { if (foo) { return; } bar(); } }",
	"for (var a of f(b)) { if (foo) { bar(); } else { break; } }",
	"function someFunc() { for (var a of f(b)) { if (foo) { continue; } return; } }",
	"function someFunc() { for (var a of f(b)) { switch (foo) { case 1: return; } } }",
	"function someFunc() { for (var a of f(b)) { switch (foo) { case 1: break; default: return; } } }",
	"function someFunc() { for (var a of f(b)) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"function someFunc() { for (var a of f(b)) { try { return bar(); } catch (e) {} } }",
	"for (var a of f(b)) { continue; break; }",
	"for (var a of f(b)) () => a;",
	"for (var a of f(b)) { () => a }",
	"for (var a of f(b)) (() => a)();",
	"for (var a of f(b)) { (() => a)() }",
	"for (var a of f(b)) while (a);",
	"for (var a of f(b)) do ; while (a)",
	"for (var a of f(b)) for (a; b; c);",
	"for (var a of f(b)) for (; b;);",
	"for (var a of f(b)) for (; ; c) if (foo) break;",
	"for (var a of f(b)) for (;;) if (foo) break;",
	"for (var a of f(b)) while (true) if (foo) break;",
	"function someFunc() { for (var a of f(b)) while (foo) if (bar) return; }",
	"for (var a of f(b)) for (a in b);",
	"for (var a of f(b)) for (a of b);",
	"async function foo() { for await (const a of b) ; }",
	"async function foo() { for await (const a of b) {} }",
	"async function foo() { for await (const a of b) { bar(); } }",
	"async function foo() { for await (const a of b) continue; }",
	"async function foo() { for await (const a of b) { continue; } }",
	"async function foo() { for await (const a of b) { if (foo) break; } }",
	"async function foo() { for await (const a of b) { if (foo) { return; } bar(); } }",
	"async function foo() { for await (const a of b) { if (foo) { bar(); } else { break; } } }",
	"async function foo() { for await (const a of b) { if (foo) { continue; } return; } }",
	"async function foo() { for await (const a of b) { switch (foo) { case 1: return; } } }",
	"async function foo() { for await (const a of b) { switch (foo) { case 1: break; default: return; } } }",
	"async function foo() { for await (const a of b) { switch (foo) { case 1: continue; default: return; } throw err; } }",
	"async function foo() { for await (const a of b) { try { return bar(); } catch (e) {} } }",
	"async function foo() { for await (const a of b) { continue; break; } }",
	"async function foo() { for await (const a of b) () => a; }",
	"async function foo() { for await (const a of b) { () => a } }",
	"async function foo() { for await (const a of b) (() => a)(); }",
	"async function foo() { for await (const a of b) { (() => a)() } }",
	"async function foo() { for await (const a of b) while (a); }",
	"async function foo() { for await (const a of b) do ; while (a) }",
	"async function foo() { for await (const a of b) for (a; b; c); }",
	"async function foo() { for await (const a of b) for (; b;); }",
	"async function foo() { for await (const a of b) for (; ; c) if (foo) break; }",
	"async function foo() { for await (const a of b) for (;;) if (foo) break; }",
	"async function foo() { for await (const a of b) while (true) if (foo) break; }",
	"async function foo() { for await (const a of b) while (foo) if (bar) return; }",
	"async function foo() { for await (const a of b) for (a in b); }",
	"async function foo() { for await (const a of b) for (a of b); }",
	"while (false) { foo(); }",
	"while (bar) { foo(); if (true) { break; } }",
	"do foo(); while (false)",
	"for (x = 1; x < 10; i++) { if (x > 0) { foo(); throw err; } }",
	"for (x of []);",
	"for (x of [1]);",
	"function foo() { return; while (a); }",
	"function foo() { return; while (a) break; }",
	"while(true); while(true);",
	"while(true); while(true) break;",
}

// unreachableLoopOptionCases are the corpus inputs carrying an `ignore` setting, with the JSON the
// config layer would hand the decoder. The array wrapper upstream writes is stripped before a
// decoder sees it, so these are the bare objects.
var unreachableLoopOptionCases = []struct {
	source   string
	options  string
	findings int
}{
	{"while (a) break;", `{"ignore":["WhileStatement"]}`, 0},
	{"do break; while (a)", `{"ignore":["DoWhileStatement"]}`, 0},
	{"for (a; b; c) break;", `{"ignore":["ForStatement"]}`, 0},
	{"for (a in b) break;", `{"ignore":["ForInStatement"]}`, 0},
	{"for (a of b) break;", `{"ignore":["ForOfStatement"]}`, 0},
	{"for (var key in obj) { hasEnumerableProperties = true; break; } for (const a of b) break;", `{"ignore":["ForInStatement","ForOfStatement"]}`, 0},
	{"while (a) break;", `{"ignore":["WhileStatement","DoWhileStatement","ForStatement","ForInStatement","ForOfStatement"]}`, 0},
	{"while (a) break; do break; while (b); for (;;) break; for (c in d) break; for (e of f) break;", `{"ignore":[]}`, 5},
	{"while (a) break;", `{"ignore":["DoWhileStatement"]}`, 1},
	{"do break; while (a)", `{"ignore":["WhileStatement"]}`, 1},
	{"for (a in b) break; for (c of d) break;", `{"ignore":["ForStatement"]}`, 2},
	{"for (a in b) break; for (;;) break; for (c of d) break;", `{"ignore":["ForInStatement","ForOfStatement"]}`, 1},
}
