package typescript

// Code generated from typescript-eslint v8.67.0's tests/rules/await-thenable.test.ts. DO NOT EDIT BY HAND.
//
// Every case was extracted by loading upstream's test file with its RuleTester stubbed, then replayed
// against the INSTALLED rule (@typescript-eslint/eslint-plugin 8.67.0, one program per case, the
// fixture tsconfig's libs) on the same bytes this harness writes: the source trimmed plus one
// newline. All 122 replayed verdicts agreed with the corpus's own annotations. Each finding records
// the message id and the exact text the installed rule's location covers. TestAwaitThenableUpstreamCorpus
// in await_thenable_test.go replays this table and says how it was built.

// awaitThenableCorpusFinding is one finding the installed rule produced.
type awaitThenableCorpusFinding struct {
	id   string
	text string
}

// awaitThenableCorpusCase is one upstream case with the installed rule's verdict.
type awaitThenableCorpusCase struct {
	index    int
	source   string
	findings []awaitThenableCorpusFinding
}

var awaitThenableCorpus = []awaitThenableCorpusCase{
	{0, "async function test() {\n  await Promise.resolve('value');\n  await Promise.reject(new Error('message'));\n}\n", []awaitThenableCorpusFinding{}},
	{1, "async function test() {\n  await (async () => true)();\n}\n", []awaitThenableCorpusFinding{}},
	{2, "async function test() {\n  function returnsPromise() {\n    return Promise.resolve('value');\n  }\n  await returnsPromise();\n}\n", []awaitThenableCorpusFinding{}},
	{3, "async function test() {\n  async function returnsPromiseAsync() {}\n  await returnsPromiseAsync();\n}\n", []awaitThenableCorpusFinding{}},
	{4, "async function test() {\n  let anyValue: any;\n  await anyValue;\n}\n", []awaitThenableCorpusFinding{}},
	{5, "async function test() {\n  let unknownValue: unknown;\n  await unknownValue;\n}\n", []awaitThenableCorpusFinding{}},
	{6, "async function test() {\n  const numberPromise: Promise<number>;\n  await numberPromise;\n}\n", []awaitThenableCorpusFinding{}},
	{7, "async function test() {\n  class Foo extends Promise<number> {}\n  const foo: Foo = Foo.resolve(2);\n  await foo;\n\n  class Bar extends Foo {}\n  const bar: Bar = Bar.resolve(2);\n  await bar;\n}\n", []awaitThenableCorpusFinding{}},
	{8, "async function test() {\n  await (Math.random() > 0.5 ? numberPromise : 0);\n  await (Math.random() > 0.5 ? foo : 0);\n  await (Math.random() > 0.5 ? bar : 0);\n\n  const intersectionPromise: Promise<number> & number;\n  await intersectionPromise;\n}\n", []awaitThenableCorpusFinding{}},
	{9, "async function test() {\n  class Thenable {\n    then(callback: () => {}) {}\n  }\n  const thenable = new Thenable();\n\n  await thenable;\n}\n", []awaitThenableCorpusFinding{}},
	{10, "// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/promise-polyfill/index.d.ts\n// Type definitions for promise-polyfill 6.0\n// Project: https://github.com/taylorhakes/promise-polyfill\n// Definitions by: Steve Jenkins <https://github.com/skysteve>\n//                 Daniel Cassidy <https://github.com/djcsdy>\n// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped\n\ninterface PromisePolyfillConstructor extends PromiseConstructor {\n  _immediateFn?: (handler: (() => void) | string) => void;\n}\n\ndeclare const PromisePolyfill: PromisePolyfillConstructor;\n\nasync function test() {\n  const promise = new PromisePolyfill(() => {});\n\n  await promise;\n}\n", []awaitThenableCorpusFinding{}},
	{11, "// https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts\n// Type definitions for bluebird 3.5\n// Project: https://github.com/petkaantonov/bluebird\n// Definitions by: Leonard Hecker <https://github.com/lhecker>\n// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped\n// TypeScript Version: 2.8\n\n/*!\n * The code following this comment originates from:\n *   https://github.com/types/npm-bluebird\n *\n * Note for browser users: use bluebird-global typings instead of this one\n * if you want to use Bluebird via the global Promise symbol.\n *\n * Licensed under:\n *   The MIT License (MIT)\n *\n *   Copyright (c) 2016 unional\n *\n *   Permission is hereby granted, free of charge, to any person obtaining a copy\n *   of this software and associated documentation files (the \"Software\"), to deal\n *   in the Software without restriction, including without limitation the rights\n *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n *   copies of the Software, and to permit persons to whom the Software is\n *   furnished to do so, subject to the following conditions:\n *\n *   The above copyright notice and this permission notice shall be included in\n *   all copies or substantial portions of the Software.\n *\n *   THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n *   THE SOFTWARE.\n */\n\ntype Constructor<E> = new (...args: any[]) => E;\ntype CatchFilter<E> = ((error: E) => boolean) | (object & E);\ntype IterableItem<R> = R extends Iterable<infer U> ? U : never;\ntype IterableOrNever<R> = Extract<R, Iterable<any>>;\ntype Resolvable<R> = R | PromiseLike<R>;\ntype IterateFunction<T, R> = (\n  item: T,\n  index: number,\n  arrayLength: number,\n) => Resolvable<R>;\n\ndeclare class Bluebird<R> implements PromiseLike<R> {\n  then<U>(\n    onFulfill?: (value: R) => Resolvable<U>,\n    onReject?: (error: any) => Resolvable<U>,\n  ): Bluebird<U>; // For simpler signature help.\n  then<TResult1 = R, TResult2 = never>(\n    onfulfilled?: ((value: R) => Resolvable<TResult1>) | null,\n    onrejected?: ((reason: any) => Resolvable<TResult2>) | null,\n  ): Bluebird<TResult1 | TResult2>;\n}\n\ndeclare const bluebird: Bluebird;\n\nasync function test() {\n  await bluebird;\n}\n", []awaitThenableCorpusFinding{}},
	{12, "const doSomething = async (\n  obj1: { a?: { b?: { c?: () => Promise<void> } } },\n  obj2: { a?: { b?: { c: () => Promise<void> } } },\n  obj3: { a?: { b: { c?: () => Promise<void> } } },\n  obj4: { a: { b: { c?: () => Promise<void> } } },\n  obj5: { a?: () => { b?: { c?: () => Promise<void> } } },\n  obj6?: { a: { b: { c?: () => Promise<void> } } },\n  callback?: () => Promise<void>,\n): Promise<void> => {\n  await obj1.a?.b?.c?.();\n  await obj2.a?.b?.c();\n  await obj3.a?.b.c?.();\n  await obj4.a.b.c?.();\n  await obj5.a?.().b?.c?.();\n  await obj6?.a.b.c?.();\n\n  await callback?.();\n};\n", []awaitThenableCorpusFinding{}},
	{13, "async function* asyncYieldNumbers() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\nfor await (const value of asyncYieldNumbers()) {\n  console.log(value);\n}\n", []awaitThenableCorpusFinding{}},
	{14, "declare const anee: any;\nasync function forAwait() {\n  for await (const value of anee) {\n    console.log(value);\n  }\n}\n", []awaitThenableCorpusFinding{}},
	{15, "declare const asyncIter: AsyncIterable<string> | Iterable<string>;\nfor await (const s of asyncIter) {\n}\n", []awaitThenableCorpusFinding{}},
	{16, "declare const d: AsyncDisposable;\n\nawait using foo = d;\n\nexport {};\n", []awaitThenableCorpusFinding{}},
	{17, "using foo = {\n  [Symbol.dispose]() {},\n};\n\nexport {};\n", []awaitThenableCorpusFinding{}},
	{18, "await using foo = 3 as any;\n\nexport {};\n", []awaitThenableCorpusFinding{}},
	{19, "using foo = {\n  async [Symbol.dispose]() {},\n};\n\nexport {};\n", []awaitThenableCorpusFinding{}},
	{20, "declare const maybeAsyncDisposable: Disposable | AsyncDisposable;\nasync function foo() {\n  await using _ = maybeAsyncDisposable;\n}\n", []awaitThenableCorpusFinding{}},
	{21, "async function iterateUsing(arr: Array<AsyncDisposable>) {\n  for (await using foo of arr) {\n  }\n}\n", []awaitThenableCorpusFinding{}},
	{22, "async function wrapper<T>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{}},
	{23, "async function wrapper<T extends unknown>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{}},
	{24, "async function wrapper<T extends any>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{}},
	{25, "async function wrapper<T extends Promise<unknown>>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{}},
	{26, "async function wrapper<T extends number | Promise<unknown>>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{}},
	{27, "class C<T> {\n  async wrapper<T>(value: T) {\n    return await value;\n  }\n}\n", []awaitThenableCorpusFinding{}},
	{28, "class C<R> {\n  async wrapper<T extends R>(value: T) {\n    return await value;\n  }\n}\n", []awaitThenableCorpusFinding{}},
	{29, "class C<R extends unknown> {\n  async wrapper<T extends R>(value: T) {\n    return await value;\n  }\n}\n", []awaitThenableCorpusFinding{}},
	{30, "// @ts-expect-error\nPromise.all();\n", []awaitThenableCorpusFinding{}},
	{31, "Promise.all([,]);\n", []awaitThenableCorpusFinding{}},
	{32, "declare const x: unknown;\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{33, "declare const x: any;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{34, "declare const x: Array<Promise<unknown>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{35, "declare const x: Array<Promise<number>> | Array<Promise<string>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{36, "declare const x: Array<Promise<number> | Promise<string>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{37, "function f<T>(x: Array<Promise<T>>) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{38, "function f<T extends Promise<unknown>>(x: Array<T>) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{39, "declare const x: Array<unknown>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{40, "declare const x: Array<any>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{41, "declare const x: number | Array<Promise<number>>;\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{42, "declare const x: [Promise<unknown>, Promise<void>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{43, "declare const x: [Promise<number>] | [Promise<string>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{44, "declare const x: [Promise<number> | Promise<string>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{45, "function f<T>(x: [Promise<T>]) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{46, "function f<T extends Promise<unknown>>(x: [T]) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{47, "declare const x: [unknown, any];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{48, "declare const x: number | [Promise<number>];\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{49, "declare const x: Iterable<Promise<unknown>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{50, "declare const x: Iterable<Promise<number>> | Iterable<Promise<string>>;\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{51, "declare const x: Iterable<Promise<number | string>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{52, "function f<T>(x: Iterable<Promise<T>>) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{53, "function f<T extends Promise<unknown>>(x: Iterable<T>) {\n  Promise.all(x);\n}\n", []awaitThenableCorpusFinding{}},
	{54, "declare const x: Iterable<unknown>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{55, "declare const x: Iterable<any>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{56, "declare const x: number | Iterable<Promise<number>>;\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{57, "declare const x: Iterable<Promise<unknown>, number>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{58, "declare const x: Iterable<Promise<string>> | Array<Promise<string>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{59, "declare const x:\n  Iterable<Promise<string>> | [Promise<string>, Promise<unknown>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{60, "declare const x: Array<Promise<string>> | [Promise<string>, Promise<unknown>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{61, "// @ts-expect-error\nPromise.all(1);\n", []awaitThenableCorpusFinding{}},
	{62, "declare const x: Promise<number>;\n\n// @ts-expect-error\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{63, "interface MyArray<Unused, T> extends Array<T> {}\ndeclare const x: MyArray<null, Promise<void>>;\n\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{64, "function* x() {\n  yield Promise.resolve(1);\n  yield Promise.resolve(2);\n  yield Promise.resolve(3);\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{}},
	{65, "function* x() {\n  yield 1 as unknown;\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{}},
	{66, "function* x() {\n  yield 1 as any;\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{}},
	{67, "declare const x: Generator<Promise<number>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{68, "declare const x: Generator<unknown>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{69, "declare const x: Generator<any>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{70, "declare const x: ReadonlyArray<Promise<number>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{71, "declare const x: ReadonlyArray<unknown>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{72, "declare const x: ReadonlyArray<any>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{}},
	{73, "Promise.all([Promise.resolve(1), Promise.resolve(2), Promise.resolve(3)]);\n", []awaitThenableCorpusFinding{}},
	{74, "declare const _unknown_: unknown;\n\nPromise.all([\n  _unknown_,\n  Promise.resolve(1),\n  Promise.resolve(2),\n  Promise.resolve(3),\n]);\n", []awaitThenableCorpusFinding{}},
	{75, "declare const _any_: any;\n\nPromise.all([\n  _any_,\n  Promise.resolve(1),\n  Promise.resolve(2),\n  Promise.resolve(3),\n]);\n", []awaitThenableCorpusFinding{}},
	{76, "declare const _promise_: Promise<number | string>;\n\nPromise.all([\n  _promise_,\n  Promise.resolve(1),\n  Promise.resolve(2),\n  Promise.resolve(3),\n]);\n", []awaitThenableCorpusFinding{}},
	{77, "Promise.all([\n  Promise.resolve(1),\n  Promise.resolve(2),\n  Promise.resolve(3),\n  ...[Promise.resolve(4), Promise.resolve(5), Promise.resolve(6)],\n]);\n", []awaitThenableCorpusFinding{}},
	{78, "declare const maybePromise: Promise<number> | number;\n\nPromise.all([\n  maybePromise,\n  Promise.resolve(1),\n  Promise.resolve(2),\n  Promise.resolve(3),\n]);\n", []awaitThenableCorpusFinding{}},
	{79, "await 0;\n", []awaitThenableCorpusFinding{{"await", "await 0"}}},
	{80, "await 'value';\n", []awaitThenableCorpusFinding{{"await", "await 'value'"}}},
	{81, "async () => await (Math.random() > 0.5 ? '' : 0);\n", []awaitThenableCorpusFinding{{"await", "await (Math.random() > 0.5 ? '' : 0)"}}},
	{82, "async () => await(Math.random() > 0.5 ? '' : 0);\n", []awaitThenableCorpusFinding{{"await", "await(Math.random() > 0.5 ? '' : 0)"}}},
	{83, "class NonPromise extends Array {}\nawait new NonPromise();\n", []awaitThenableCorpusFinding{{"await", "await new NonPromise()"}}},
	{84, "async function test() {\n  class IncorrectThenable {\n    then() {}\n  }\n  const thenable = new IncorrectThenable();\n\n  await thenable;\n}\n", []awaitThenableCorpusFinding{{"await", "await thenable"}}},
	{85, "declare const callback: (() => void) | undefined;\nawait callback?.();\n", []awaitThenableCorpusFinding{{"await", "await callback?.()"}}},
	{86, "declare const obj: { a?: { b?: () => void } };\nawait obj.a?.b?.();\n", []awaitThenableCorpusFinding{{"await", "await obj.a?.b?.()"}}},
	{87, "declare const obj: { a: { b: { c?: () => void } } } | undefined;\nawait obj?.a.b.c?.();\n", []awaitThenableCorpusFinding{{"await", "await obj?.a.b.c?.()"}}},
	{88, "function* yieldNumbers() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\nfor await (const value of yieldNumbers()) {\n  console.log(value);\n}\n", []awaitThenableCorpusFinding{{"forAwaitOfNonAsyncIterable", "for await (const value of yieldNumbers())"}}},
	{89, "function* yieldNumberPromises() {\n  yield Promise.resolve(1);\n  yield Promise.resolve(2);\n  yield Promise.resolve(3);\n}\nfor await (const value of yieldNumberPromises()) {\n  console.log(value);\n}\n", []awaitThenableCorpusFinding{{"forAwaitOfNonAsyncIterable", "for await (const value of yieldNumberPromises())"}}},
	{90, "declare const disposable: Disposable;\nasync function foo() {\n  await using d = disposable;\n}\n", []awaitThenableCorpusFinding{{"awaitUsingOfNonAsyncDisposable", "disposable"}}},
	{91, "async function foo() {\n  await using _ = {\n    async [Symbol.dispose]() {},\n  };\n}\n", []awaitThenableCorpusFinding{{"awaitUsingOfNonAsyncDisposable", "{\n    async [Symbol.dispose]() {},\n  }"}}},
	{92, "declare const disposable: Disposable;\ndeclare const asyncDisposable: AsyncDisposable;\nasync function foo() {\n  await using a = disposable,\n    b = asyncDisposable,\n    c = disposable,\n    d = asyncDisposable,\n    e = disposable;\n}\n", []awaitThenableCorpusFinding{{"awaitUsingOfNonAsyncDisposable", "disposable"}, {"awaitUsingOfNonAsyncDisposable", "disposable"}, {"awaitUsingOfNonAsyncDisposable", "disposable"}}},
	{93, "declare const anee: any;\ndeclare const disposable: Disposable;\nasync function foo() {\n  await using a = anee,\n    b = disposable;\n}\n", []awaitThenableCorpusFinding{{"awaitUsingOfNonAsyncDisposable", "disposable"}}},
	{94, "async function wrapper<T extends number>(value: T) {\n  return await value;\n}\n", []awaitThenableCorpusFinding{{"await", "await value"}}},
	{95, "class C<T> {\n  async wrapper<T extends string>(value: T) {\n    return await value;\n  }\n}\n", []awaitThenableCorpusFinding{{"await", "await value"}}},
	{96, "class C<R extends number> {\n  async wrapper<T extends R>(value: T) {\n    return await value;\n  }\n}\n", []awaitThenableCorpusFinding{{"await", "await value"}}},
	{97, "declare const x: Array<number>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{98, "declare const x: Array<number> | Array<Promise<number>>;\nPromise.race(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{99, "declare const x: Array<number> | Array<string>;\nPromise.allSettled(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{100, "declare const x: Array<number | Promise<number>>;\nPromise.any(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{101, "declare const x: [number];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{102, "declare const x: [number] | [Promise<number>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{103, "declare const x: [number | Promise<number>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{104, "declare const x: [Promise<number>, number];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{105, "declare const x: Iterable<number>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{106, "declare const x: Iterable<number> | Iterable<Promise<number>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{107, "declare const x: Iterable<number | Promise<number>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{108, "declare const x: Iterable<string> | Array<Promise<unknown>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{109, "declare const x: Iterable<Promise<string>> | [string, Promise<unknown>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{110, "declare const x: Array<string> | [Promise<string>, Promise<unknown>];\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{111, "declare const x: Array<Array<Promise<number>>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{112, "interface MyArray<Unused, T> extends Array<T> {}\ndeclare const x: MyArray<Promise<void>, null>;\n\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{113, "function* x() {\n  yield 1;\n  yield 2;\n  yield 3;\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x()"}}},
	{114, "function* x() {\n  yield 1 as number;\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x()"}}},
	{115, "function* x() {\n  yield 1 as number | Promise<number>;\n}\n\nPromise.all(x());\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x()"}}},
	{116, "declare const x: Generator<number>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{117, "declare const x: ReadonlyArray<number>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{118, "declare const x: ReadonlyArray<number | Promise<string>>;\nPromise.all(x);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "x"}}},
	{119, "Promise.all([Promise.resolve(1), 2, Promise.resolve(3)]);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "2"}}},
	{120, "Promise.all([1, 2, Promise.resolve(3)]);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "1"}, {"invalidPromiseAggregatorInput", "2"}}},
	{121, "Promise.all([...[1, 2, 3]]);\n", []awaitThenableCorpusFinding{{"invalidPromiseAggregatorInput", "...[1, 2, 3]"}}},
}
