package typescript

// Code generated from typescript-eslint v8.71.0's tests/rules/ban-ts-comment.test.ts and edge rows. DO NOT EDIT BY HAND.
//
// The 52 valid and 62 invalid rows, from all four of the test file's ruleTester.run blocks, were extracted by
// loading it with RuleTester stubbed, and 40 edge rows were added for what that corpus leaves open: grapheme
// lengths, the whitespace JavaScript trim does and does not remove, a description failing both checks,
// three-slash pragmas, block comments, and CRLF. Every row was replayed against the INSTALLED rule
// (@typescript-eslint/eslint-plugin 8.71.0) on the bytes this harness writes: the source trimmed plus one newline.
// Before recording, every upstream row was replayed on its own bytes and agreed with upstream's own
// assertions, suggestions included. Each finding records the message id, the exact text the installed
// rule's location covers, and the output of its suggestion, empty when it offers none. The rule offers
// no autofix on any row. TestBanTsCommentUpstreamCorpus replays this table.

// banTsCommentCorpusFinding is one finding the installed rule produced.
type banTsCommentCorpusFinding struct {
	id         string
	text       string
	suggestion string
}

// banTsCommentCorpusCase is one row with the installed rule's verdict. edge is empty for upstream's own rows.
type banTsCommentCorpusCase struct {
	index    int
	edge     string
	source   string
	options  string
	findings []banTsCommentCorpusFinding
}

// banTsCommentCorpusUpstreamValid and banTsCommentCorpusUpstreamInvalid pin how many of upstream's rows
// are here, so a filter cannot empty either direction.
const banTsCommentCorpusUpstreamValid, banTsCommentCorpusUpstreamInvalid = 52, 62

var banTsCommentCorpus = []banTsCommentCorpusCase{
	{0, "", "// just a comment containing @ts-expect-error somewhere\n", "", []banTsCommentCorpusFinding{}},
	{1, "", "/*\n @ts-expect-error running with long description in a block\n*/\n", "", []banTsCommentCorpusFinding{}},
	{2, "", "/* @ts-expect-error not on the last line\n */\n", "", []banTsCommentCorpusFinding{}},
	{3, "", "/**\n * @ts-expect-error not on the last line\n */\n", "", []banTsCommentCorpusFinding{}},
	{4, "", "/* not on the last line\n * @ts-expect-error\n */\n", "", []banTsCommentCorpusFinding{}},
	{5, "", "/* @ts-expect-error\n * not on the last line */\n", "", []banTsCommentCorpusFinding{}},
	{6, "", "// @ts-expect-error\n", "{\"ts-expect-error\":false}", []banTsCommentCorpusFinding{}},
	{7, "", "// @ts-expect-error here is why the error is expected\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{8, "", "/*\n * @ts-expect-error here is why the error is expected */\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{9, "", "// @ts-expect-error exactly 21 characters\n", "{\"minimumDescriptionLength\":21,\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{10, "", "/*\n * @ts-expect-error exactly 21 characters*/\n", "{\"minimumDescriptionLength\":21,\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{11, "", "// @ts-expect-error: TS1234 because xyz\n", "{\"minimumDescriptionLength\":10,\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{12, "", "/*\n * @ts-expect-error: TS1234 because xyz */\n", "{\"minimumDescriptionLength\":10,\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{13, "", "// @ts-expect-error 👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{14, "", "// @ts-expect-error\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-expect-error", ""}}},
	{15, "", "/* @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* @ts-expect-error */", ""}}},
	{16, "", "/*\n@ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/*\n@ts-expect-error */", ""}}},
	{17, "", "/** on the last line\n  @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/** on the last line\n  @ts-expect-error */", ""}}},
	{18, "", "/** on the last line\n * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/** on the last line\n * @ts-expect-error */", ""}}},
	{19, "", "/**\n * @ts-expect-error: TODO */\n", "{\"minimumDescriptionLength\":10,\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "/**\n * @ts-expect-error: TODO */", ""}}},
	{20, "", "/**\n * @ts-expect-error: TS1234 because xyz */\n", "{\"minimumDescriptionLength\":25,\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "/**\n * @ts-expect-error: TS1234 because xyz */", ""}}},
	{21, "", "/**\n * @ts-expect-error: TS1234 */\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "/**\n * @ts-expect-error: TS1234 */", ""}}},
	{22, "", "/**\n * @ts-expect-error    : TS1234 */\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "/**\n * @ts-expect-error    : TS1234 */", ""}}},
	{23, "", "/**\n * @ts-expect-error 👨\u200d👩\u200d👧\u200d👦 */\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "/**\n * @ts-expect-error 👨\u200d👩\u200d👧\u200d👦 */", ""}}},
	{24, "", "/** @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/** @ts-expect-error */", ""}}},
	{25, "", "// @ts-expect-error: Suppress next line\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-expect-error: Suppress next line", ""}}},
	{26, "", "/////@ts-expect-error: Suppress next line\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/////@ts-expect-error: Suppress next line", ""}}},
	{27, "", "if (false) {\n  // @ts-expect-error: Unreachable code error\n  console.log('hello');\n}\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-expect-error: Unreachable code error", ""}}},
	{28, "", "/* not on the last line\r\n * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* not on the last line\r\n * @ts-expect-error */", ""}}},
	{29, "", "/* not on the last line\r * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* not on the last line\r * @ts-expect-error */", ""}}},
	{30, "", "/* not on the last line\n * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* not on the last line\n * @ts-expect-error */", ""}}},
	{31, "", "/* not on the last line\u2028 * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* not on the last line\u2028 * @ts-expect-error */", ""}}},
	{32, "", "/* not on the last line\u2029 * @ts-expect-error */\n", "{\"ts-expect-error\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/* not on the last line\u2029 * @ts-expect-error */", ""}}},
	{33, "", "// @ts-expect-error\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error", ""}}},
	{34, "", "// @ts-expect-error: TODO\n", "{\"minimumDescriptionLength\":10,\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error: TODO", ""}}},
	{35, "", "// @ts-expect-error: TS1234 because xyz\n", "{\"minimumDescriptionLength\":25,\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error: TS1234 because xyz", ""}}},
	{36, "", "// @ts-expect-error: TS1234\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-expect-error: TS1234", ""}}},
	{37, "", "// @ts-expect-error    : TS1234 because xyz\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-expect-error    : TS1234 because xyz", ""}}},
	{38, "", "// @ts-expect-error 👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 👨\u200d👩\u200d👧\u200d👦", ""}}},
	{39, "", "// just a comment containing @ts-ignore somewhere\n", "", []banTsCommentCorpusFinding{}},
	{40, "", "// @ts-ignore\n", "{\"ts-ignore\":false}", []banTsCommentCorpusFinding{}},
	{41, "", "// @ts-ignore I think that I am exempted from any need to follow the rules!\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{42, "", "/*\n @ts-ignore running with long description in a block\n*/\n", "{\"minimumDescriptionLength\":21,\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{43, "", "/*\n @ts-ignore\n*/\n", "", []banTsCommentCorpusFinding{}},
	{44, "", "/* @ts-ignore not on the last line\n */\n", "", []banTsCommentCorpusFinding{}},
	{45, "", "/**\n * @ts-ignore not on the last line\n */\n", "", []banTsCommentCorpusFinding{}},
	{46, "", "/* not on the last line\n * @ts-expect-error\n */\n", "", []banTsCommentCorpusFinding{}},
	{47, "", "/* @ts-ignore\n * not on the last line */\n", "", []banTsCommentCorpusFinding{}},
	{48, "", "// @ts-ignore: TS1234 because xyz\n", "{\"minimumDescriptionLength\":10,\"ts-ignore\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{49, "", "// @ts-ignore 👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{50, "", "/*\n * @ts-ignore here is why the error is expected */\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{51, "", "// @ts-ignore exactly 21 characters\n", "{\"minimumDescriptionLength\":21,\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{52, "", "/*\n * @ts-ignore exactly 21 characters*/\n", "{\"minimumDescriptionLength\":21,\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{53, "", "/*\n * @ts-ignore: TS1234 because xyz */\n", "{\"minimumDescriptionLength\":10,\"ts-ignore\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{54, "", "// @ts-ignore\n", "{\"ts-expect-error\":true,\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore", "// @ts-expect-error\n"}}},
	{55, "", "// @ts-ignore\n", "{\"ts-expect-error\":\"allow-with-description\",\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore", "// @ts-expect-error\n"}}},
	{56, "", "// @ts-ignore\n", "", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore", "// @ts-expect-error\n"}}},
	{57, "", "/* @ts-ignore */\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/* @ts-ignore */", "/* @ts-expect-error */\n"}}},
	{58, "", "/*\n @ts-ignore */\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/*\n @ts-ignore */", "/*\n @ts-expect-error */\n"}}},
	{59, "", "/** on the last line\n  @ts-ignore */\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/** on the last line\n  @ts-ignore */", "/** on the last line\n  @ts-expect-error */\n"}}},
	{60, "", "/** on the last line\n * @ts-ignore */\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/** on the last line\n * @ts-ignore */", "/** on the last line\n * @ts-expect-error */\n"}}},
	{61, "", "/** @ts-ignore */\n", "{\"ts-expect-error\":false,\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/** @ts-ignore */", "/** @ts-expect-error */\n"}}},
	{62, "", "/**\n * @ts-ignore: TODO */\n", "{\"minimumDescriptionLength\":10,\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/**\n * @ts-ignore: TODO */", "/**\n * @ts-expect-error: TODO */\n"}}},
	{63, "", "/**\n * @ts-ignore: TS1234 because xyz */\n", "{\"minimumDescriptionLength\":25,\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/**\n * @ts-ignore: TS1234 because xyz */", "/**\n * @ts-expect-error: TS1234 because xyz */\n"}}},
	{64, "", "// @ts-ignore: Suppress next line\n", "", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore: Suppress next line", "// @ts-expect-error: Suppress next line\n"}}},
	{65, "", "/////@ts-ignore: Suppress next line\n", "", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/////@ts-ignore: Suppress next line", "/////@ts-expect-error: Suppress next line\n"}}},
	{66, "", "if (false) {\n  // @ts-ignore: Unreachable code error\n  console.log('hello');\n}\n", "", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore: Unreachable code error", "if (false) {\n  // @ts-expect-error: Unreachable code error\n  console.log('hello');\n}\n"}}},
	{67, "", "// @ts-ignore\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-ignore", ""}}},
	{68, "", "// @ts-ignore\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-ignore", ""}}},
	{69, "", "// @ts-ignore    .\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-ignore    .", ""}}},
	{70, "", "// @ts-ignore: TS1234 because xyz\n", "{\"minimumDescriptionLength\":25,\"ts-ignore\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-ignore: TS1234 because xyz", ""}}},
	{71, "", "// @ts-ignore: TS1234\n", "{\"ts-ignore\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-ignore: TS1234", ""}}},
	{72, "", "// @ts-ignore    : TS1234 because xyz\n", "{\"ts-ignore\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-ignore    : TS1234 because xyz", ""}}},
	{73, "", "// @ts-ignore 👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-ignore\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-ignore 👨\u200d👩\u200d👧\u200d👦", ""}}},
	{74, "", "// just a comment containing @ts-nocheck somewhere\n", "", []banTsCommentCorpusFinding{}},
	{75, "", "// @ts-nocheck\n", "{\"ts-nocheck\":false}", []banTsCommentCorpusFinding{}},
	{76, "", "// @ts-nocheck no doubt, people will put nonsense here from time to time just to get the rule to stop reporting, perhaps even long messages with other nonsense in them like other // @ts-nocheck or // @ts-ignore things\n", "{\"ts-nocheck\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{77, "", "/*\n @ts-nocheck running with long description in a block\n*/\n", "{\"minimumDescriptionLength\":21,\"ts-nocheck\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{78, "", "// @ts-nocheck: TS1234 because xyz\n", "{\"minimumDescriptionLength\":10,\"ts-nocheck\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{79, "", "// @ts-nocheck 👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-nocheck\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{80, "", "//// @ts-nocheck - pragma comments may contain 2 or 3 leading slashes\n", "", []banTsCommentCorpusFinding{}},
	{81, "", "/**\n @ts-nocheck\n*/\n", "", []banTsCommentCorpusFinding{}},
	{82, "", "/*\n @ts-nocheck\n*/\n", "", []banTsCommentCorpusFinding{}},
	{83, "", "/** @ts-nocheck */\n", "", []banTsCommentCorpusFinding{}},
	{84, "", "/* @ts-nocheck */\n", "", []banTsCommentCorpusFinding{}},
	{85, "", "const a = 1;\n\n// @ts-nocheck - should not be reported\n\n// TS error is not actually suppressed\nconst b: string = a;\n", "", []banTsCommentCorpusFinding{}},
	{86, "", "// @ts-nocheck\n", "{\"ts-nocheck\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-nocheck", ""}}},
	{87, "", "// @ts-nocheck\n", "", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-nocheck", ""}}},
	{88, "", "// @ts-nocheck: Suppress next line\n", "", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-nocheck: Suppress next line", ""}}},
	{89, "", "// @ts-nocheck\n", "{\"ts-nocheck\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-nocheck", ""}}},
	{90, "", "// @ts-nocheck: TS1234 because xyz\n", "{\"minimumDescriptionLength\":25,\"ts-nocheck\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-nocheck: TS1234 because xyz", ""}}},
	{91, "", "// @ts-nocheck: TS1234\n", "{\"ts-nocheck\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-nocheck: TS1234", ""}}},
	{92, "", "// @ts-nocheck    : TS1234 because xyz\n", "{\"ts-nocheck\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-nocheck    : TS1234 because xyz", ""}}},
	{93, "", "// @ts-nocheck 👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-nocheck\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-nocheck 👨\u200d👩\u200d👧\u200d👦", ""}}},
	{94, "", "// @ts-nocheck\nconst a: true = false;\n", "", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-nocheck", ""}}},
	{95, "", "// just a comment containing @ts-check somewhere\n", "", []banTsCommentCorpusFinding{}},
	{96, "", "/*\n @ts-check running with long description in a block\n*/\n", "", []banTsCommentCorpusFinding{}},
	{97, "", "// @ts-check\n", "{\"ts-check\":false}", []banTsCommentCorpusFinding{}},
	{98, "", "// @ts-check with a description and also with a no-op // @ts-ignore\n", "{\"minimumDescriptionLength\":3,\"ts-check\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{99, "", "// @ts-check: TS1234 because xyz\n", "{\"minimumDescriptionLength\":10,\"ts-check\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{}},
	{100, "", "// @ts-check 👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-check\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{101, "", "//// @ts-check - pragma comments may contain 2 or 3 leading slashes\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{}},
	{102, "", "/**\n @ts-check\n*/\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{}},
	{103, "", "/*\n @ts-check\n*/\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{}},
	{104, "", "/** @ts-check */\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{}},
	{105, "", "/* @ts-check */\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{}},
	{106, "", "// @ts-check\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-check", ""}}},
	{107, "", "// @ts-check: Suppress next line\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-check: Suppress next line", ""}}},
	{108, "", "if (false) {\n  // @ts-check: Unreachable code error\n  console.log('hello');\n}\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "// @ts-check: Unreachable code error", ""}}},
	{109, "", "// @ts-check\n", "{\"ts-check\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-check", ""}}},
	{110, "", "// @ts-check: TS1234 because xyz\n", "{\"minimumDescriptionLength\":25,\"ts-check\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-check: TS1234 because xyz", ""}}},
	{111, "", "// @ts-check: TS1234\n", "{\"ts-check\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-check: TS1234", ""}}},
	{112, "", "// @ts-check    : TS1234 because xyz\n", "{\"ts-check\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"}}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-check    : TS1234 because xyz", ""}}},
	{113, "", "// @ts-check 👨\u200d👩\u200d👧\u200d👦\n", "{\"ts-check\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-check 👨\u200d👩\u200d👧\u200d👦", ""}}},
	{114, "length: family emoji is one grapheme", "// @ts-expect-error 👨\u200d👩\u200d👧\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 👨\u200d👩\u200d👧", ""}}},
	{115, "length: two family emoji are two graphemes", "// @ts-expect-error 👨\u200d👩\u200d👧👨\u200d👩\u200d👧\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 👨\u200d👩\u200d👧👨\u200d👩\u200d👧", ""}}},
	{116, "length: three family emoji are three graphemes", "// @ts-expect-error 👨\u200d👩\u200d👧👨\u200d👩\u200d👧👨\u200d👩\u200d👧\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{117, "length: a flag is one grapheme", "// @ts-expect-error 🇺🇸\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 🇺🇸", ""}}},
	{118, "length: three flags", "// @ts-expect-error 🇺🇸🇫🇷🇯🇵\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{119, "length: skin tone modifier joins its emoji", "// @ts-expect-error 👍🏽👍🏽\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 👍🏽👍🏽", ""}}},
	{120, "length: three skin-toned thumbs", "// @ts-expect-error 👍🏽👍🏽👍🏽\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{121, "length: combining acute joins its letter", "// @ts-expect-error e\u0301e\u0301\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error e\u0301e\u0301", ""}}},
	{122, "length: three combined letters", "// @ts-expect-error e\u0301e\u0301e\u0301\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{123, "length: two accented letters", "// @ts-expect-error éé\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error éé", ""}}},
	{124, "length: three accented letters", "// @ts-expect-error ééé\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{125, "length: decomposed hangul", "// @ts-expect-error 각가\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 각가", ""}}},
	{126, "length: keycap sequences", "// @ts-expect-error 1\ufe0f\u20e32\ufe0f\u20e3\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 1\ufe0f\u20e32\ufe0f\u20e3", ""}}},
	{127, "length: tag sequence flag", "// @ts-expect-error 🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 🏴\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f", ""}}},
	{128, "length: three CJK", "// @ts-expect-error 漢字字\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{129, "length: two CJK", "// @ts-expect-error 漢字\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error 漢字", ""}}},
	{130, "trim: BOM around two letters", "// @ts-expect-error \ufeffab\ufeff\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error \ufeffab\ufeff", ""}}},
	{131, "trim: BOM around three letters", "// @ts-expect-error \ufeffabc\ufeff\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{132, "trim: NEL around two letters", "// @ts-expect-error \u0085ab\u0085\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{133, "trim: NEL around three letters", "// @ts-expect-error \u0085abc\u0085\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{134, "trim: NBSP around two letters", "// @ts-expect-error \u00a0ab\u00a0\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error \u00a0ab\u00a0", ""}}},
	{135, "trim: NBSP around three letters", "// @ts-expect-error \u00a0abc\u00a0\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{136, "trim: ideographic space around two letters", "// @ts-expect-error \u3000ab\u3000\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error \u3000ab\u3000", ""}}},
	{137, "trim: ideographic space around three letters", "// @ts-expect-error \u3000abc\u3000\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{}},
	{138, "trim: line separator around two letters", "// @ts-expect-error \u2028ab\u2028\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error ", ""}}},
	{139, "trim: line separator around three letters", "// @ts-expect-error \u2028abc\u2028\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error ", ""}}},
	{140, "both checks fail, length reported alone", "// @ts-expect-error: TS1\nconst a = 1;\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"},\"minimumDescriptionLength\":25}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error: TS1", ""}}},
	{141, "format fails, length passes", "// @ts-expect-error this is long enough to pass the length\nconst a = 1;\n", "{\"ts-expect-error\":{\"descriptionFormat\":\"^: TS\\\\d+ because .+$\"},\"minimumDescriptionLength\":25}", []banTsCommentCorpusFinding{{"tsDirectiveCommentDescriptionNotMatchPattern", "// @ts-expect-error this is long enough to pass the length", ""}}},
	{142, "three-slash nocheck before code", "/// @ts-nocheck\nconst a = 1;\n", "{\"ts-nocheck\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/// @ts-nocheck", ""}}},
	{143, "three-slash check", "/// @ts-check\nconst a = 1;\n", "{\"ts-check\":true}", []banTsCommentCorpusFinding{{"tsDirectiveComment", "/// @ts-check", ""}}},
	{144, "three-slash ignore", "/// @ts-ignore\nconst a = 1;\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "/// @ts-ignore", "/// @ts-expect-error\nconst a = 1;\n"}}},
	{145, "nocheck after first statement", "const a = 1;\n// @ts-nocheck\nconst b = 2;\n", "{\"ts-nocheck\":true}", []banTsCommentCorpusFinding{}},
	{146, "nocheck in a block comment", "/* @ts-nocheck */\nconst a = 1;\n", "{\"ts-nocheck\":true}", []banTsCommentCorpusFinding{}},
	{147, "ignore on the last line of a block", "/*\n * stuff\n * @ts-ignore\n */\nconst a = 1;\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{}},
	{148, "ignore on a middle line of a block", "/*\n * @ts-ignore\n * stuff\n */\nconst a = 1;\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{}},
	{149, "ignore twice in one comment", "// @ts-ignore see other @ts-ignore\nconst a = 1;\n", "{\"ts-ignore\":true}", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore see other @ts-ignore", "// @ts-expect-error see other @ts-ignore\nconst a = 1;\n"}}},
	{150, "default options ignore", "// @ts-ignore\nconst a = 1;\n", "", []banTsCommentCorpusFinding{{"tsIgnoreInsteadOfExpectError", "// @ts-ignore", "// @ts-expect-error\nconst a = 1;\n"}}},
	{151, "default options expect-error without description", "// @ts-expect-error\nconst a = 1;\n", "", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error", ""}}},
	{152, "default options expect-error with description", "// @ts-expect-error: TS2345 because the type is wrong\nconst a = 1;\n", "", []banTsCommentCorpusFinding{}},
	{153, "CRLF line comment", "// @ts-expect-error ab\r\nconst a = 1;\n", "{\"ts-expect-error\":\"allow-with-description\"}", []banTsCommentCorpusFinding{{"tsDirectiveCommentRequiresDescription", "// @ts-expect-error ab", ""}}},
}
