package typescript

// Code generated from typescript-eslint v8.71.0's tests/rules/no-shadow/*.test.ts and edge rows. DO NOT EDIT BY HAND.
//
// The 239 upstream rows are every row in the two test files, 139 valid and 100 invalid, extracted by
// loading the files with RuleTester stubbed. 84 edge rows were added for what they leave open. Before recording,
// every upstream row was linted untyped, as upstream's RuleTester runs it, and agreed with upstream's own
// assertions: message ids, lines, columns and the shadowed declaration's place. Every row was then replayed
// against the INSTALLED rule (@typescript-eslint/eslint-plugin 8.71.0, one program per row) under
// noShadowCorpusTsconfig, on the bytes this harness writes: the source trimmed plus one newline, in file.ts, or
// in file.d.ts for a row upstream names a definition file. Upstream's rows are modules, and one with no import
// or export gets `export {};` appended (exportAppended), since cohere's module is TypeScript's. Each finding
// records upstream's message id, the exact text its location covers, where it starts, and the shadowed
// declaration's line and column as the message quotes them, or "global". The rows that configure `globals`
// are pinned and recorded with it dropped, since cohere carries no globals configuration; edge rows make the
// same points with the globals the program has. TestNoShadowUpstreamCorpus replays this table.

// noShadowCorpusTsconfig is the no-unused-vars options corpus's tsconfig. include names the row's file.
const noShadowCorpusTsconfig = "{\n \"compilerOptions\": {\n  \"strict\": true,\n  \"target\": \"ES2022\",\n  \"lib\": [\n   \"ES2022\",\n   \"ESNext.Disposable\"\n  ],\n  \"types\": []\n },\n \"include\": [\n  \"file.ts\"\n ]\n}"

// noShadowCorpusFinding is one finding the installed rule produced, by upstream's message id.
type noShadowCorpusFinding struct {
	id       string
	text     string
	at       string
	shadowed string
}

// noShadowCorpusCase is one row with the installed rule's verdict. edge is empty for upstream's own rows.
type noShadowCorpusCase struct {
	index          int
	edge           string
	valid          bool
	fileName       string
	source         string
	options        string
	exportAppended bool
	pinned         []string
	findings       []noShadowCorpusFinding
}

// noShadowCorpusUpstreamValid, noShadowCorpusUpstreamInvalid and noShadowCorpusUpstreamPinned pin how many of
// upstream's rows are here and how many carry a pin, so a filter cannot empty either direction.
const noShadowCorpusUpstreamValid, noShadowCorpusUpstreamInvalid, noShadowCorpusUpstreamPinned = 139, 100, 22

var noShadowCorpus = []noShadowCorpusCase{
	{0, "", true, "file.ts", "function foo<T = (arg: any) => any>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{1, "", true, "file.ts", "function foo<T = ([arg]: [any]) => any>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{2, "", true, "file.ts", "function foo<T = ({ args }: { args: any }) => any>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{3, "", true, "file.ts", "function foo<T = (...args: any[]) => any>(fn: T, args: any[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{4, "", true, "file.ts", "function foo<T extends (...args: any[]) => any>(fn: T, args: any[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{5, "", true, "file.ts", "function foo<T extends (...args: any[]) => any>(fn: T, ...args: any[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{6, "", true, "file.ts", "function foo<T extends ([args]: any[]) => any>(fn: T, args: any[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{7, "", true, "file.ts", "function foo<T extends ([...args]: any[]) => any>(fn: T, args: any[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{8, "", true, "file.ts", "function foo<T extends ({ args }: { args: any }) => any>(fn: T, args: any) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{9, "", true, "file.ts", "function foo<T extends (id: string, ...args: any[]) => any>(\n  fn: T,\n  ...args: any[]\n) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{10, "", true, "file.ts", "type Args = 1;\nfunction foo<T extends (Args: any) => void>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{11, "", true, "file.ts", "export type ArrayInput<Func> = Func extends (arg0: Array<infer T>) => any\n  ? T[]\n  : Func extends (...args: infer T) => any\n    ? T\n    : never;\n", "", false, nil, []noShadowCorpusFinding{}},
	{12, "", true, "file.ts", "function foo() {\n  var Object = 0;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{13, "", true, "file.ts", "function test(this: Foo) {\n  function test2(this: Bar) {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{14, "", true, "file.ts", "class Foo {\n  prop = 1;\n}\nnamespace Foo {\n  export const v = 2;\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{15, "", true, "file.ts", "function Foo() {}\nnamespace Foo {\n  export const v = 2;\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{16, "", true, "file.ts", "class Foo {\n  prop = 1;\n}\ninterface Foo {\n  prop2: string;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{17, "", true, "file.ts", "import type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{18, "", true, "file.ts", "const x = 1;\ntype x = string;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{19, "", true, "file.ts", "const x = 1;\n{\n  type x = string;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{20, "", true, "file.ts", "type Foo = 1;\nexport {};\n", "{\"ignoreTypeValueShadow\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{21, "", true, "file.ts", "type Foo = 1;\nexport {};\n", "{\"builtinGlobals\":false,\"ignoreTypeValueShadow\":false}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{22, "", true, "file.ts", "enum Direction {\n  left = 'left',\n  right = 'right',\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{23, "", true, "file.ts", "enum A {\n  B,\n  C,\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{24, "", true, "file.ts", "enum A {\n  B,\n  C = A.B,\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{25, "", true, "file.ts", "const test = 1;\ntype Fn = (test: string) => typeof test;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{26, "", true, "file.ts", "type Fn = (Foo: string) => typeof Foo;\nexport {};\n", "{\"builtinGlobals\":false,\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{27, "", true, "file.ts", "const arg = 0;\n\ninterface Test {\n  (arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{28, "", true, "file.ts", "const arg = 0;\n\ninterface Test {\n  p1(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{29, "", true, "file.ts", "const arg = 0;\n\ndeclare function test(arg: string): typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{30, "", true, "file.ts", "const arg = 0;\n\ndeclare const test: (arg: string) => typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{31, "", true, "file.ts", "const arg = 0;\n\ndeclare class Test {\n  p1(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{32, "", true, "file.ts", "const arg = 0;\n\ndeclare const Test: {\n  new (arg: string): typeof arg;\n};\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{33, "", true, "file.ts", "const arg = 0;\n\ntype Bar = new (arg: number) => typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{34, "", true, "file.ts", "const arg = 0;\n\ndeclare namespace Lib {\n  function test(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{35, "", true, "file.ts", "declare global {\n  interface ArrayConstructor {}\n}\nexport {};\n", "{\"builtinGlobals\":true}", false, nil, []noShadowCorpusFinding{}},
	{36, "", true, "file.ts", "declare global {\n  const a: string;\n\n  namespace Foo {\n    const a: number;\n  }\n}\nexport {};\n", "", false, nil, []noShadowCorpusFinding{}},
	{37, "", true, "file.ts", "declare global {\n  type A = 'foo';\n\n  namespace Foo {\n    type A = 'bar';\n  }\n}\nexport {};\n", "{\"ignoreTypeValueShadow\":false}", false, nil, []noShadowCorpusFinding{}},
	{38, "", true, "file.ts", "declare global {\n  const foo: string;\n  type Fn = (foo: number) => void;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", false, nil, []noShadowCorpusFinding{}},
	{39, "", true, "file.ts", "export class Wrapper<Wrapped> {\n  private constructor(private readonly wrapped: Wrapped) {}\n\n  unwrap(): Wrapped {\n    return this.wrapped;\n  }\n\n  static create<Wrapped>(wrapped: Wrapped) {\n    return new Wrapper<Wrapped>(wrapped);\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{40, "", true, "file.ts", "function makeA() {\n  return class A<T> {\n    constructor(public value: T) {}\n\n    static make<T>(value: T) {\n      return new A<T>(value);\n    }\n  };\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{41, "", true, "file.ts", "import type { foo } from './foo';\ntype bar = number;\n\n// 'foo' is already declared in the upper scope\n// 'bar' is fine\nfunction doThing(foo: number, bar: number) {}\n", "{\"ignoreTypeValueShadow\":true}", false, nil, []noShadowCorpusFinding{}},
	{42, "", true, "file.ts", "import { type foo } from './foo';\n\n// 'foo' is already declared in the upper scope\nfunction doThing(foo: number) {}\n", "{\"ignoreTypeValueShadow\":true}", false, nil, []noShadowCorpusFinding{}},
	{43, "", true, "file.ts", "const a = [].find(a => a);\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{44, "", true, "file.ts", "const a = [].find(function (a) {\n  return a;\n});\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{45, "", true, "file.ts", "const [a = [].find(a => true)] = dummy;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{46, "", true, "file.ts", "const { a = [].find(a => true) } = dummy;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{47, "", true, "file.ts", "function func(a = [].find(a => true)) {}\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{48, "", true, "file.ts", "for (const a in [].find(a => true)) {\n}\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{49, "", true, "file.ts", "for (const a of [].find(a => true)) {\n}\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{50, "", true, "file.ts", "const a = [].map(a => true).filter(a => a === 'b');\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{51, "", true, "file.ts", "const a = []\n  .map(a => true)\n  .filter(a => a === 'b')\n  .find(a => a === 'c');\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{52, "", true, "file.ts", "const { a } = (({ a }) => ({ a }))();\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{53, "", true, "file.ts", "const person = people.find(item => {\n  const person = item.name;\n  return person === 'foo';\n});\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{54, "", true, "file.ts", "var y = bar || foo(y => y);\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{55, "", true, "file.ts", "var y = bar && foo(y => y);\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{56, "", true, "file.ts", "var z = bar(foo(z => z));\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{57, "", true, "file.ts", "var z = boo(bar(foo(z => z)));\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{58, "", true, "file.ts", "var match = function (person) {\n  return person.name === 'foo';\n};\nconst person = [].find(match);\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{59, "", true, "file.ts", "const a = foo(x || (a => {}));\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{60, "", true, "file.ts", "const { a = 1 } = foo(a => {});\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{61, "", true, "file.ts", "const person = { ...people.find(person => person.firstName.startsWith('s')) };\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{62, "", true, "file.ts", "const person = {\n  firstName: people\n    .filter(person => person.firstName.startsWith('s'))\n    .map(person => person.firstName)[0],\n};\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{63, "", true, "file.ts", "() => {\n  const y = foo(y => y);\n};\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{64, "", true, "file.ts", "const x = (x => x)();\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{65, "", true, "file.ts", "var y = bar || (y => y)();\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{66, "", true, "file.ts", "var y = bar && (y => y)();\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{67, "", true, "file.ts", "var x = (x => x)((y => y)());\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{68, "", true, "file.ts", "const { a = 1 } = (a => {})();\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{69, "", true, "file.ts", "() => {\n  const y = (y => y)();\n};\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{70, "", true, "file.ts", "const [x = y => y] = [].map(y => y);\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{71, "", true, "file.ts", "type Foo<A> = 1;\ntype A = 1;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{72, "", true, "file.ts", "interface Foo<A> {}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{73, "", true, "file.ts", "interface Foo<A> {}\ninterface A {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{74, "", true, "file.ts", "type Foo<A> = 1;\ninterface A {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{75, "", true, "file.ts", "{\n  type A = 1;\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{76, "", true, "file.ts", "{\n  interface Foo<A> {}\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{77, "", true, "file.ts", "type Foo<A> = 1;\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{78, "", true, "file.ts", "interface Foo<A> {}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{79, "", true, "file.ts", "interface Foo<A> {}\ninterface A {}\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{80, "", true, "file.ts", "type Foo<A> = 1;\ninterface A {}\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{81, "", true, "file.ts", "{\n  type A = 1;\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{82, "", true, "file.ts", "{\n  interface Foo<A> {}\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{83, "", true, "file.ts", "import type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  export type Foo = string;\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{84, "", true, "file.ts", "import type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{85, "", true, "file.ts", "import { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  export type Foo = string;\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{86, "", true, "file.ts", "import { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{87, "", true, "file.ts", "import { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  type Foo = string;\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{88, "", true, "file.ts", "import { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{}},
	{89, "", true, "file.d.ts", "declare const foo1: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{90, "", true, "file.d.ts", "declare let foo2: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{91, "", true, "file.d.ts", "declare var foo3: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{92, "", true, "file.d.ts", "function foo4(name: string): void;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{93, "", true, "file.d.ts", "declare class Foopy1 {\n  name: string;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{94, "", true, "file.d.ts", "declare interface Foopy2 {\n  name: string;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{95, "", true, "file.d.ts", "declare type Foopy3 = {\n  x: number;\n};\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{96, "", true, "file.d.ts", "declare enum Foopy4 {\n  x,\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{97, "", true, "file.d.ts", "declare namespace Foopy5 {}\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{98, "", true, "file.d.ts", "declare;\nfoo5: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{99, "", false, "file.ts", "type T = 1;\n{\n  type T = 2;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "T", "3:8", "1:6"}}},
	{100, "", false, "file.ts", "type T = 1;\nfunction foo<T>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "T", "2:14", "1:6"}}},
	{101, "", false, "file.ts", "function foo<T>() {\n  return function <T>() {};\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "T", "2:20", "1:14"}}},
	{102, "", false, "file.ts", "type T = string;\nfunction foo<T extends (arg: any) => void>(arg: T) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "T", "2:14", "1:6"}}},
	{103, "", false, "file.ts", "enum A {\n  A,\n  B,\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noEnumShadow", "A", "2:3", "1:6"}}},
	{104, "", false, "file.ts", "enum A {\n  B = 2,\n}\n\nenum A {\n  A = 1,\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noEnumShadow", "A", "6:3", "1:6"}}},
	{105, "", false, "file.ts", "const x = 1;\n{\n  type x = string;\n}\nexport {};\n", "{\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:8", "1:7"}}},
	{106, "", false, "file.ts", "type Foo = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":false}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{107, "", false, "file.ts", "const test = 1;\ntype Fn = (test: string) => typeof test;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "test: string", "2:12", "1:7"}}},
	{108, "", false, "file.ts", "type Fn = (Foo: string) => typeof Foo;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{109, "", false, "file.ts", "const arg = 0;\n\ninterface Test {\n  (arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "4:4", "1:7"}}},
	{110, "", false, "file.ts", "const arg = 0;\n\ninterface Test {\n  p1(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "4:6", "1:7"}}},
	{111, "", false, "file.ts", "const arg = 0;\n\ndeclare function test(arg: string): typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "3:23", "1:7"}}},
	{112, "", false, "file.ts", "const arg = 0;\n\ndeclare const test: (arg: string) => typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "3:22", "1:7"}}},
	{113, "", false, "file.ts", "const arg = 0;\n\ndeclare class Test {\n  p1(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "4:6", "1:7"}}},
	{114, "", false, "file.ts", "const arg = 0;\n\ndeclare const Test: {\n  new (arg: string): typeof arg;\n};\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "4:8", "1:7"}}},
	{115, "", false, "file.ts", "const arg = 0;\n\ntype Bar = new (arg: number) => typeof arg;\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: number", "3:17", "1:7"}}},
	{116, "", false, "file.ts", "const arg = 0;\n\ndeclare namespace Lib {\n  function test(arg: string): typeof arg;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "arg: string", "4:17", "1:7"}}},
	{117, "", false, "file.ts", "import type { foo } from './foo';\nfunction doThing(foo: number) {}\n", "{\"ignoreTypeValueShadow\":false}", false, nil, []noShadowCorpusFinding{{"noShadow", "foo: number", "2:18", "1:15"}}},
	{118, "", false, "file.ts", "import { type foo } from './foo';\nfunction doThing(foo: number) {}\n", "{\"ignoreTypeValueShadow\":false}", false, nil, []noShadowCorpusFinding{{"noShadow", "foo: number", "2:18", "1:15"}}},
	{119, "", false, "file.ts", "import { foo } from './foo';\nfunction doThing(foo: number, bar: number) {}\n", "{\"ignoreTypeValueShadow\":true}", false, nil, []noShadowCorpusFinding{{"noShadow", "foo: number", "2:18", "1:10"}}},
	{120, "", false, "file.ts", "interface Foo {}\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{{"noShadow", "Foo", "4:20", "1:11"}}},
	{121, "", false, "file.ts", "import type { Foo } from 'bar';\n\ndeclare module 'baz' {\n  export interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{{"noShadow", "Foo", "4:20", "1:15"}}},
	{122, "", false, "file.ts", "import { type Foo } from 'bar';\n\ndeclare module 'baz' {\n  export interface Foo {\n    x: string;\n  }\n}\n", "", false, nil, []noShadowCorpusFinding{{"noShadow", "Foo", "4:20", "1:15"}}},
	{123, "", false, "file.ts", "let x = foo((x, y) => {});\nlet y;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "1:14", "1:5"}, {"noShadow", "y", "1:17", "2:5"}}},
	{124, "", false, "file.ts", "let x = foo((x, y) => {});\nlet y;\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "1:14", "1:5"}}},
	{125, "", false, "file.ts", "type Foo<A> = 1;\ntype A = 1;\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:6"}}},
	{126, "", false, "file.ts", "interface Foo<A> {}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:6"}}},
	{127, "", false, "file.ts", "interface Foo<A> {}\ninterface A {}\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:11"}}},
	{128, "", false, "file.ts", "type Foo<A> = 1;\ninterface A {}\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:11"}}},
	{129, "", false, "file.ts", "{\n  type A = 1;\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:8", "4:6"}}},
	{130, "", false, "file.ts", "{\n  interface A {}\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:13", "4:6"}}},
	{131, "", false, "file.ts", "type Foo<A> = 1;\ntype A = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:6"}}},
	{132, "", false, "file.ts", "interface Foo<A> {}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:6"}}},
	{133, "", false, "file.ts", "interface Foo<A> {}\ninterface A {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:11"}}},
	{134, "", false, "file.ts", "type Foo<A> = 1;\ninterface A {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:11"}}},
	{135, "", false, "file.ts", "{\n  type A = 1;\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:8", "4:6"}}},
	{136, "", false, "file.ts", "{\n  interface A {}\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:13", "4:6"}}},
	{137, "", false, "file.ts", "type Foo<A> = 1;\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:6"}}},
	{138, "", false, "file.ts", "interface Foo<A> {}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:6"}}},
	{139, "", false, "file.ts", "interface Foo<A> {}\ninterface A {}\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:15", "2:11"}}},
	{140, "", false, "file.ts", "type Foo<A> = 1;\ninterface A {}\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "1:10", "2:11"}}},
	{141, "", false, "file.ts", "{\n  type A = 1;\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:8", "4:6"}}},
	{142, "", false, "file.ts", "{\n  interface A {}\n}\ntype A = 1;\nexport {};\n", "{\"hoist\":\"functions-and-types\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "2:13", "4:6"}}},
	{143, "", false, "file.ts", "function foo<T extends (...args: any[]) => any>(fn: T, args: any[]) {}\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":false}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{144, "", false, "file.ts", "declare const has = (environment: 'dev' | 'prod' | 'test') => boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{145, "", false, "file.d.ts", "declare const has: (environment: 'dev' | 'prod' | 'test') => boolean;\nconst fn = (has: string) => {};\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{{"noShadow", "has: string", "2:13", "1:15"}}},
	{146, "", true, "file.ts", "var a = 3;\nfunction b(x) {\n  a++;\n  return x + a;\n}\nsetTimeout(function () {\n  b(a);\n}, 0);\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{147, "", true, "file.ts", "(function () {\n  var doSomething = function doSomething() {};\n  doSomething();\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{148, "", true, "file.ts", "var a = foo || function a() {};\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{149, "", true, "file.ts", "var a = foo ? function a() {} : bar;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{150, "", true, "file.ts", "function foo(a = function a() {}) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{151, "", true, "file.ts", "var arguments;\nfunction bar() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{152, "", true, "file.ts", "var a = 3;\nvar b = x => {\n  a++;\n  return x + a;\n};\nsetTimeout(() => {\n  b(a);\n}, 0);\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{153, "", true, "file.ts", "class A {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{154, "", true, "file.ts", "class A {\n  constructor() {\n    var a;\n  }\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{155, "", true, "file.ts", "(function () {\n  var A = class A {};\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{156, "", true, "file.ts", "{\n  var a;\n}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{157, "", true, "file.ts", "{\n  let a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{158, "", true, "file.ts", "{\n  let a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{159, "", true, "file.ts", "{\n  let a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{160, "", true, "file.ts", "{\n  const a = 0;\n}\nconst a = 1;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{161, "", true, "file.ts", "{\n  const a = 0;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{162, "", true, "file.ts", "{\n  const a = 0;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{163, "", true, "file.ts", "function foo() {\n  let a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{164, "", true, "file.ts", "function foo() {\n  let a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{165, "", true, "file.ts", "function foo() {\n  let a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{166, "", true, "file.ts", "function foo() {\n  var a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{167, "", true, "file.ts", "function foo() {\n  var a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{168, "", true, "file.ts", "function foo() {\n  var a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{169, "", true, "file.ts", "function foo(a) {}\nlet a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{170, "", true, "file.ts", "function foo(a) {}\nvar a;\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{171, "", true, "file.ts", "function foo(a) {}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{172, "", true, "file.ts", "{\n  let a;\n}\nlet a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{173, "", true, "file.ts", "{\n  let a;\n}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{174, "", true, "file.ts", "{\n  const a = 0;\n}\nconst a = 1;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{175, "", true, "file.ts", "{\n  const a = 0;\n}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{176, "", true, "file.ts", "function foo() {\n  let a;\n}\nlet a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{177, "", true, "file.ts", "function foo() {\n  let a;\n}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{178, "", true, "file.ts", "function foo() {\n  var a;\n}\nlet a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{179, "", true, "file.ts", "function foo() {\n  var a;\n}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{180, "", true, "file.ts", "function foo(a) {}\nlet a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{181, "", true, "file.ts", "function foo(a) {}\nvar a;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{182, "", true, "file.ts", "function foo() {\n  var Object = 0;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{183, "", true, "file.ts", "function foo() {\n  var top = 0;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{184, "", true, "file.ts", "var top = 0;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{185, "", true, "file.ts", "function foo(cb) {\n  (function (cb) {\n    cb(42);\n  })(cb);\n}\nexport {};\n", "{\"allow\":[\"cb\"]}", true, nil, []noShadowCorpusFinding{}},
	{186, "", false, "file.ts", "function a(x) {\n  var b = function c() {\n    var x = 'foo';\n  };\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:9", "1:12"}}},
	{187, "", false, "file.ts", "var a = x => {\n  var b = () => {\n    var x = 'foo';\n  };\n};\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:9", "1:9"}}},
	{188, "", false, "file.ts", "function a(x) {\n  var b = function () {\n    var x = 'foo';\n  };\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:9", "1:12"}}},
	{189, "", false, "file.ts", "var x = 1;\nfunction a(x) {\n  return ++x;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "2:12", "1:5"}}},
	{190, "", false, "file.ts", "var a = 3;\nfunction b() {\n  var a = 10;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:7", "1:5"}}},
	{191, "", false, "file.ts", "var a = 3;\nfunction b() {\n  var a = 10;\n}\nsetTimeout(function () {\n  b();\n}, 0);\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:7", "1:5"}}},
	{192, "", false, "file.ts", "var a = 3;\nfunction b() {\n  var a = 10;\n  var b = 0;\n}\nsetTimeout(function () {\n  b();\n}, 0);\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:7", "1:5"}, {"noShadow", "b", "4:7", "2:10"}}},
	{193, "", false, "file.ts", "var x = 1;\n{\n  let x = 2;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:7", "1:5"}}},
	{194, "", false, "file.ts", "let x = 1;\n{\n  const x = 2;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:9", "1:5"}}},
	{195, "", false, "file.ts", "{\n  let a;\n}\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{196, "", false, "file.ts", "{\n  const a = 0;\n}\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:9", "4:10"}}},
	{197, "", false, "file.ts", "function foo() {\n  let a;\n}\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{198, "", false, "file.ts", "function foo() {\n  var a;\n}\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{199, "", false, "file.ts", "function foo(a) {}\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:14", "2:10"}}},
	{200, "", false, "file.ts", "{\n  let a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{201, "", false, "file.ts", "{\n  let a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{202, "", false, "file.ts", "{\n  let a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{203, "", false, "file.ts", "{\n  const a = 0;\n}\nconst a = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:9", "4:7"}}},
	{204, "", false, "file.ts", "{\n  const a = 0;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:9", "4:5"}}},
	{205, "", false, "file.ts", "{\n  const a = 0;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:9", "4:10"}}},
	{206, "", false, "file.ts", "function foo() {\n  let a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{207, "", false, "file.ts", "function foo() {\n  let a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{208, "", false, "file.ts", "function foo() {\n  let a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{209, "", false, "file.ts", "function foo() {\n  var a;\n}\nlet a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{210, "", false, "file.ts", "function foo() {\n  var a;\n}\nvar a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:5"}}},
	{211, "", false, "file.ts", "function foo() {\n  var a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{212, "", false, "file.ts", "function foo(a) {}\nlet a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:14", "2:5"}}},
	{213, "", false, "file.ts", "function foo(a) {}\nvar a;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:14", "2:5"}}},
	{214, "", false, "file.ts", "function foo(a) {}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:14", "2:10"}}},
	{215, "", false, "file.ts", "(function a() {\n  function a() {}\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:12", "1:11"}}},
	{216, "", false, "file.ts", "(function a() {\n  class a {}\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:9", "1:11"}}},
	{217, "", false, "file.ts", "(function a() {\n  (function a() {});\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:13", "1:11"}}},
	{218, "", false, "file.ts", "(function a() {\n  (class a {});\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:10", "1:11"}}},
	{219, "", false, "file.ts", "(function () {\n  var a = function (a) {};\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:21", "2:7"}}},
	{220, "", false, "file.ts", "(function () {\n  var a = function () {\n    function a() {}\n  };\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:14", "2:7"}}},
	{221, "", false, "file.ts", "(function () {\n  var a = function () {\n    class a {}\n  };\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:11", "2:7"}}},
	{222, "", false, "file.ts", "(function () {\n  var a = function () {\n    (function a() {});\n  };\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:15", "2:7"}}},
	{223, "", false, "file.ts", "(function () {\n  var a = function () {\n    (class a {});\n  };\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:12", "2:7"}}},
	{224, "", false, "file.ts", "(function () {\n  var a = class {\n    constructor() {\n      class a {}\n    }\n  };\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "4:13", "2:7"}}},
	{225, "", false, "file.ts", "class A {\n  constructor() {\n    var A;\n  }\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "A", "3:9", "1:7"}}},
	{226, "", false, "file.ts", "(function a() {\n  function a() {\n    function a() {}\n  }\n})();\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:12", "1:11"}, {"noShadow", "a", "3:14", "2:12"}}},
	{227, "", false, "file.ts", "function foo() {\n  var Object = 0;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "2:7", "global"}}},
	{228, "", false, "file.ts", "function foo() {\n  var top = 0;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{229, "", false, "file.ts", "var Object = 0;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "1:5", "global"}}},
	{230, "", false, "file.ts", "var top = 0;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration"}, []noShadowCorpusFinding{}},
	{231, "", false, "file.ts", "var Object = 0;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"ecmaFeatures.globalReturn"}, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "1:5", "global"}}},
	{232, "", false, "file.ts", "var top = 0;\nexport {};\n", "{\"builtinGlobals\":true}", true, []string{"globals configuration", "ecmaFeatures.globalReturn"}, []noShadowCorpusFinding{}},
	{233, "", false, "file.ts", "function foo(cb) {\n  (function (cb) {\n    cb(42);\n  })(cb);\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "cb", "2:14", "1:14"}}},
	{234, "", false, "file.ts", "const FooBarComponent = memo(function FooBarComponent() {});\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "FooBarComponent", "1:39", "1:7"}}},
	{235, "", false, "file.ts", "const FooBarComponent = memo(class FooBarComponent {});\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "FooBarComponent", "1:36", "1:7"}}},
	{236, "", false, "file.ts", "const FooBarComponent = memo(function FooBarComponent() {});\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{{"noShadow", "FooBarComponent", "1:39", "1:7"}}},
	{237, "", false, "file.ts", "function foo(a = wrap(function a() {})) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:32", "1:14"}}},
	{238, "", false, "file.ts", "var a = 1;\nvar b = function a() {};\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:18", "1:5"}}},
	{239, "a type over a lib value global, ignoreTypeValueShadow on", false, "file.ts", "type Object = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":true}", true, nil, []noShadowCorpusFinding{}},
	{240, "a type over a lib value global, ignoreTypeValueShadow off", false, "file.ts", "type Object = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "1:6", "global"}}},
	{241, "a type over an ESLint-only global, ignoreTypeValueShadow on", false, "file.ts", "type NaN = 1;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{242, "a type over an ESLint-only global, ignoreTypeValueShadow off", false, "file.ts", "type NaN = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "NaN", "1:6", "global"}}},
	{243, "a type over a lib type-only global", false, "file.ts", "type Partial = 1;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{244, "a type over a lib type-only global, ignoreTypeValueShadow off", false, "file.ts", "type Partial = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Partial", "1:6", "global"}}},
	{245, "a value over a lib type-only global", false, "file.ts", "const Record = 1;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Record", "1:7", "global"}}},
	{246, "a value over an ESLint-only global at module level", false, "file.ts", "const NaN = 1;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "NaN", "1:7", "global"}}},
	{247, "a value over an ESLint-only global in a function", false, "file.ts", "function f() {\n  var parseInt = 0;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "parseInt", "2:7", "global"}}},
	{248, "a value over a lib global without builtinGlobals", false, "file.ts", "function f() {\n  var Object = 0;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{249, "a function type parameter over a lib value global", false, "file.ts", "type Fn = (Object: string) => typeof Object;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{250, "a function type parameter over a lib value global, ignore off", false, "file.ts", "type Fn = (Object: string) => typeof Object;\nexport {};\n", "{\"builtinGlobals\":true,\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object: string", "1:12", "global"}}},
	{251, "a function type parameter over a lib type-only global", false, "file.ts", "type Fn = (Record: string) => void;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Record: string", "1:12", "global"}}},
	{252, "a function type parameter over an ESLint-only global", false, "file.ts", "type Fn = (NaN: string) => void;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{253, "a script's top level is the global scope", false, "file.ts", "var Object = 0;\n", "{\"builtinGlobals\":true}", false, nil, []noShadowCorpusFinding{}},
	{254, "a script's function scope shadows a builtin", false, "file.ts", "function f() {\n  var Object = 0;\n}\n", "{\"builtinGlobals\":true}", false, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "2:7", "global"}}},
	{255, "a script's own global shadowed", false, "file.ts", "var Object = 0;\nfunction f() {\n  var Object = 1;\n}\n", "{\"builtinGlobals\":true}", false, nil, []noShadowCorpusFinding{{"noShadow", "Object", "3:7", "1:5"}}},
	{256, "a module's own binding shadowed, not the global", false, "file.ts", "const Object = 0;\nfunction f() {\n  const Object = 1;\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "1:7", "global"}, {"noShadow", "Object", "3:9", "1:7"}}},
	{257, "allow names a builtin", false, "file.ts", "const Object = 1;\nexport {};\n", "{\"builtinGlobals\":true,\"allow\":[\"Object\"]}", true, nil, []noShadowCorpusFinding{}},
	{258, "allow names a different binding", false, "file.ts", "const a = 1;\nfunction f() {\n  const a = 2;\n  const b = 3;\n}\nconst b = 4;\nexport {};\n", "{\"allow\":[\"a\"],\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "b", "4:9", "6:7"}}},
	{259, "a builtin is never in the dead zone", false, "file.ts", "function f() {\n  let Promise = 0;\n}\nexport {};\n", "{\"builtinGlobals\":true,\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Promise", "2:7", "global"}}},
	{260, "d.ts declare const over a builtin", false, "file.d.ts", "declare const Object: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{261, "d.ts declare class over a builtin", false, "file.d.ts", "declare class Map {}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{262, "d.ts declare enum over a builtin", false, "file.d.ts", "declare enum Set {\n  x,\n}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{263, "d.ts declare namespace over a builtin", false, "file.d.ts", "declare namespace Symbol {}\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{264, "d.ts overload signature over a builtin", false, "file.d.ts", "function parseInt(name: string): void;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{265, "d.ts declare function over a builtin", false, "file.d.ts", "declare function parseInt(name: string): void;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{}},
	{266, "ts declare const over a builtin", false, "file.ts", "declare const Object: boolean;\nexport {};\n", "{\"builtinGlobals\":true}", true, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object: boolean", "1:15", "global"}}},
	{267, "d.ts declare const over a user binding", false, "file.d.ts", "declare const a: number;\ndeclare namespace N {\n  const a: string;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a: string", "3:9", "1:15"}}},
	{268, "d.ts declare var in a namespace over a user binding", false, "file.d.ts", "declare const a: number;\ndeclare namespace N {\n  var a: string;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a: string", "3:7", "1:15"}}},
	{269, "d.ts nested declare namespace over a user binding", false, "file.d.ts", "declare const N: number;\ndeclare namespace M {\n  namespace N {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "N", "3:13", "1:15"}}},
	{270, "hoist functions, outer is an overload set", false, "file.ts", "{\n  let a;\n}\nfunction a(): void;\nfunction a() {}\nexport {};\n", "{\"hoist\":\"functions\"}", true, nil, []noShadowCorpusFinding{}},
	{271, "hoist default, outer is an overload set", false, "file.ts", "{\n  let a;\n}\nfunction a(): void;\nfunction a() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{272, "hoist default, outer is declare function", false, "file.ts", "{\n  let a;\n}\ndeclare function a(): void;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{273, "hoist types, outer is an interface", false, "file.ts", "{\n  let a;\n}\ninterface a {}\nexport {};\n", "{\"hoist\":\"types\",\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:11"}}},
	{274, "hoist functions, outer is a type alias", false, "file.ts", "{\n  let a;\n}\ntype a = 1;\nexport {};\n", "{\"hoist\":\"functions\",\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{}},
	{275, "hoist never, outer is a function", false, "file.ts", "{\n  let a;\n}\nfunction a() {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{276, "hoist all, outer is a const", false, "file.ts", "{\n  let a;\n}\nconst a = 1;\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:7"}}},
	{277, "hoist never, outer is a class", false, "file.ts", "{\n  let a;\n}\nclass a {}\nexport {};\n", "{\"hoist\":\"never\"}", true, nil, []noShadowCorpusFinding{}},
	{278, "hoist all, outer is an enum", false, "file.ts", "{\n  let a;\n}\nenum a {}\nexport {};\n", "{\"hoist\":\"all\"}", true, nil, []noShadowCorpusFinding{{"noEnumShadow", "a", "2:7", "4:6"}}},
	{279, "hoist all, outer is an import", false, "file.ts", "function f() {\n  let a;\n}\nimport { a } from 'x';\n", "{\"hoist\":\"all\"}", false, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "4:10"}}},
	{280, "inner overload set in a block", false, "file.ts", "function f() {}\n{\n  function f(): void;\n  function f() {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "f", "3:12", "1:10"}}},
	{281, "initialization through a destructuring default", false, "file.ts", "const { a = foo(() => {\n  let a;\n}) } = {} as any;\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{282, "initialization through a parameter default", false, "file.ts", "function f(a = foo(() => {\n  let a;\n})) {}\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{283, "initialization through a for-of right side", false, "file.ts", "for (const a of foo(() => {\n  let a;\n})) {}\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{284, "initialization through an object method", false, "file.ts", "const a = foo({\n  m() {\n    let a;\n  },\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{285, "initialization through a class method", false, "file.ts", "const a = foo(class {\n  m() {\n    let a;\n  }\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "3:9", "1:7"}}},
	{286, "initialization through a named function expression", false, "file.ts", "const a = foo(function g() {\n  let a;\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{287, "initialization through a nested arrow", false, "file.ts", "const a = foo(() => () => {\n  let a;\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "1:7"}}},
	{288, "initialization through a block in the arrow", false, "file.ts", "const a = foo(() => {\n  {\n    let a;\n  }\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{289, "initialization through a parenthesized call", false, "file.ts", "const a = (foo)((() => {\n  let a;\n}));\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{290, "initialization through a new expression", false, "file.ts", "const a = new Foo(() => {\n  let a;\n});\ndeclare class Foo { constructor(x: unknown); }\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "1:7"}}},
	{291, "initialization with a type parameter", false, "file.ts", "const a = foo(<a,>() => {});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true,\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{}},
	{292, "initialization with an inner parameter", false, "file.ts", "const a = foo((a: number) => a);\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{}},
	{293, "initialization after the call ends", false, "file.ts", "const a = foo(() => {}) || (() => {\n  let a;\n});\ndeclare function foo(x: unknown): any;\nexport {};\n", "{\"ignoreOnInitialization\":true}", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:7", "1:7"}}},
	{294, "static method generic over a class generic", false, "file.ts", "class A<T> {\n  static m<T>() {}\n  n<T>() {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "T", "3:5", "1:9"}}},
	{295, "static method generic over a class generic, class expression", false, "file.ts", "const A = class<T> {\n  static m<T>(): void;\n  static m() {}\n};\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{296, "a function type parameter in an overload", false, "file.ts", "const a = 1;\nfunction f(a: string): void;\nfunction f() {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{297, "a function type parameter in a declare function", false, "file.ts", "const a = 1;\ndeclare function f(a: string): void;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{298, "a function type parameter in an abstract method", false, "file.ts", "const a = 1;\nabstract class C {\n  abstract m(a: string): void;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{299, "a function type parameter in an overload, ignore off", false, "file.ts", "const a = 1;\nfunction f(a: string): void;\nfunction f() {}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "a: string", "2:12", "1:7"}}},
	{300, "a function type parameter over a type", false, "file.ts", "type a = 1;\ntype F = (a: string) => void;\nexport {};\n", "{\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "a: string", "2:11", "1:6"}}},
	{301, "span: an optional parameter with no type", false, "file.ts", "const a = 1;\nfunction f(a?) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a?", "2:12", "1:7"}}},
	{302, "span: an optional parameter with a type", false, "file.ts", "const a = 1;\nfunction f(a?: number) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a?: number", "2:12", "1:7"}}},
	{303, "span: a rest parameter with a type", false, "file.ts", "const a = 1;\nfunction f(...a: number[]) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:15", "1:7"}}},
	{304, "span: a defaulted parameter with a type", false, "file.ts", "const a = 1;\nfunction f(a: number = 2) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a: number", "2:12", "1:7"}}},
	{305, "span: a definite assignment", false, "file.ts", "const a = 1;\nfunction f() {\n  let a!: number;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a!: number", "3:7", "1:7"}}},
	{306, "span: a parameter property", false, "file.ts", "const a = 1;\nclass C {\n  constructor(private a: number) {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a: number", "3:23", "1:7"}}},
	{307, "span: a catch binding with a type", false, "file.ts", "const e = 1;\ntry {\n} catch (e: unknown) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "e: unknown", "3:10", "1:7"}}},
	{308, "span: a destructured binding", false, "file.ts", "const a = 1;\nfunction f({ a }: { a: number }) {}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:14", "1:7"}}},
	{309, "span: a var with a type and initializer", false, "file.ts", "const a = 1;\nfunction f() {\n  const a: number = 2;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a: number", "3:9", "1:7"}}},
	{310, "an index signature parameter", false, "file.ts", "const key = 1;\ninterface X {\n  [key: string]: number;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{311, "an interface setter parameter", false, "file.ts", "const v = 1;\ninterface I {\n  set x(v: number);\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{312, "a declare class method parameter", false, "file.ts", "const v = 1;\ndeclare class C {\n  m(v: number): void;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{313, "a bodiless function name over a value", false, "file.ts", "const parseInt2 = 1;\nfunction f() {\n  function parseInt2(): void;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{314, "a bodiless function name over a value, ignore off", false, "file.ts", "const g = 1;\nfunction f() {\n  function g(): void;\n}\nexport {};\n", "{\"ignoreFunctionTypeParameterNameValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "g", "3:12", "1:7"}}},
	{315, "an overload set name over a value", false, "file.ts", "const g = 1;\nfunction f() {\n  function g(): void;\n  function g() {}\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "g", "3:12", "1:7"}}},
	{316, "a merged inner value and type", false, "file.ts", "const x = 1;\nfunction f() {\n  const x = 2;\n  type x = string;\n}\nexport {};\n", "{\"ignoreTypeValueShadow\":false}", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:9", "1:7"}}},
	{317, "a merged inner type then value", false, "file.ts", "const x = 1;\nfunction f() {\n  type x = string;\n  const x = 2;\n}\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "x", "3:8", "1:7"}}},
	{318, "a destructuring default is the expression itself", false, "file.ts", "const { a = function a() {} } = {} as any;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{}},
	{319, "a destructuring default wraps the expression", false, "file.ts", "const { a = wrap(function a() {}) } = {} as any;\ndeclare function wrap(x: unknown): any;\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "1:27", "1:9"}}},
	{320, "a class expression name over a module binding", false, "file.ts", "var a = 1;\nvar b = class a {};\nexport {};\n", "", true, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:15", "1:5"}}},
	{321, "a class expression name over a script global", false, "file.ts", "var a = 1;\nvar b = class a {};\n", "", false, nil, []noShadowCorpusFinding{{"noShadow", "a", "2:15", "1:5"}}},
	{322, "a class expression name over a builtin in a script", false, "file.ts", "var b = class Object {};\n", "{\"builtinGlobals\":true}", false, nil, []noShadowCorpusFinding{{"noShadowGlobal", "Object", "1:15", "global"}}},
}
