// Code generated from the Prettier fork's src/language-js/traverse/visitor-keys.evaluate.js. DO NOT EDIT.
//
// Regenerate by evaluating that module under node and printing the result, the way this file was made:
// node --input-type=module -e "import k from './src/language-js/traverse/visitor-keys.evaluate.js'; ..."

package estree

// visitorKeys are Prettier's getVisitorKeys table for ESTree, in upstream's key order.
var visitorKeys = map[string][]string{
	"AccessorProperty":                {"decorators", "key", "typeAnnotation", "value"},
	"AnyTypeAnnotation":               {},
	"ArgumentPlaceholder":             {},
	"ArrayExpression":                 {"elements"},
	"ArrayPattern":                    {"elements", "typeAnnotation", "decorators"},
	"ArrayTypeAnnotation":             {"elementType"},
	"ArrowFunctionExpression":         {"typeParameters", "params", "predicate", "returnType", "body"},
	"AsConstExpression":               {"expression"},
	"AsExpression":                    {"expression", "typeAnnotation"},
	"AssignmentExpression":            {"left", "right"},
	"AssignmentPattern":               {"left", "right", "decorators", "typeAnnotation"},
	"AwaitExpression":                 {"argument"},
	"BigIntLiteral":                   {},
	"BigIntLiteralTypeAnnotation":     {},
	"BigIntTypeAnnotation":            {},
	"BinaryExpression":                {"left", "right"},
	"BindExpression":                  {"object", "callee"},
	"BlockStatement":                  {"directives", "body"},
	"BooleanLiteral":                  {},
	"BooleanLiteralTypeAnnotation":    {},
	"BooleanTypeAnnotation":           {},
	"BreakStatement":                  {"label"},
	"CallExpression":                  {"callee", "typeArguments", "arguments"},
	"CatchClause":                     {"param", "body"},
	"ChainExpression":                 {"expression"},
	"ClassAccessorProperty":           {"decorators", "key", "typeAnnotation", "value"},
	"ClassBody":                       {"body"},
	"ClassDeclaration":                {"decorators", "id", "typeParameters", "superClass", "superTypeArguments", "mixins", "implements", "body"},
	"ClassExpression":                 {"decorators", "id", "typeParameters", "superClass", "superTypeArguments", "mixins", "implements", "body"},
	"ClassImplements":                 {"id", "typeParameters"},
	"ClassMethod":                     {"decorators", "key", "typeParameters", "params", "returnType", "body"},
	"ClassPrivateMethod":              {"decorators", "key", "typeParameters", "params", "returnType", "body"},
	"ClassPrivateProperty":            {"decorators", "variance", "key", "typeAnnotation", "value"},
	"ClassProperty":                   {"decorators", "variance", "key", "typeAnnotation", "value"},
	"ComponentDeclaration":            {"id", "params", "body", "typeParameters", "rendersType"},
	"ComponentParameter":              {"name", "local"},
	"ComponentTypeAnnotation":         {"params", "rest", "typeParameters", "rendersType"},
	"ComponentTypeParameter":          {"name", "typeAnnotation"},
	"ConditionalExpression":           {"test", "consequent", "alternate"},
	"ConditionalTypeAnnotation":       {"checkType", "extendsType", "trueType", "falseType"},
	"ContinueStatement":               {"label"},
	"DebuggerStatement":               {},
	"DeclareClass":                    {"id", "typeParameters", "extends", "mixins", "implements", "body"},
	"DeclareComponent":                {"id", "params", "rest", "typeParameters", "rendersType"},
	"DeclareEnum":                     {"id", "body"},
	"DeclareExportAllDeclaration":     {"source", "attributes"},
	"DeclareExportDeclaration":        {"declaration", "specifiers", "source", "attributes"},
	"DeclareFunction":                 {"id", "predicate"},
	"DeclareHook":                     {"id"},
	"DeclareInterface":                {"id", "typeParameters", "extends", "body"},
	"DeclareModule":                   {"id", "body"},
	"DeclareModuleExports":            {"typeAnnotation"},
	"DeclareNamespace":                {"id", "body"},
	"DeclareOpaqueType":               {"id", "typeParameters", "supertype", "lowerBound", "upperBound"},
	"DeclareTypeAlias":                {"id", "typeParameters", "right"},
	"DeclareVariable":                 {"id", "declarations"},
	"DeclaredPredicate":               {"value"},
	"Decorator":                       {"expression"},
	"Directive":                       {"value"},
	"DirectiveLiteral":                {},
	"DoExpression":                    {"body"},
	"DoWhileStatement":                {"body", "test"},
	"EmptyStatement":                  {},
	"EmptyTypeAnnotation":             {},
	"EnumBigIntBody":                  {"members"},
	"EnumBigIntMember":                {"id", "init"},
	"EnumBody":                        {"members"},
	"EnumBooleanBody":                 {"members"},
	"EnumBooleanMember":               {"id", "init"},
	"EnumDeclaration":                 {"id", "body"},
	"EnumDefaultedMember":             {"id"},
	"EnumNumberBody":                  {"members"},
	"EnumNumberMember":                {"id", "init"},
	"EnumStringBody":                  {"members"},
	"EnumStringMember":                {"id", "init"},
	"EnumSymbolBody":                  {"members"},
	"ExistsTypeAnnotation":            {},
	"ExportAllDeclaration":            {"source", "attributes", "exported"},
	"ExportDefaultDeclaration":        {"declaration"},
	"ExportDefaultSpecifier":          {"exported"},
	"ExportNamedDeclaration":          {"declaration", "specifiers", "source", "attributes"},
	"ExportNamespaceSpecifier":        {"exported"},
	"ExportSpecifier":                 {"local", "exported"},
	"ExpressionStatement":             {"expression"},
	"File":                            {"program"},
	"ForInStatement":                  {"left", "right", "body"},
	"ForOfStatement":                  {"left", "right", "body"},
	"ForStatement":                    {"init", "test", "update", "body"},
	"FunctionDeclaration":             {"id", "typeParameters", "params", "predicate", "returnType", "body"},
	"FunctionExpression":              {"id", "typeParameters", "params", "predicate", "returnType", "body"},
	"FunctionTypeAnnotation":          {"typeParameters", "this", "params", "rest", "returnType"},
	"FunctionTypeParam":               {"name", "typeAnnotation"},
	"GenericTypeAnnotation":           {"id", "typeParameters"},
	"HookDeclaration":                 {"id", "typeParameters", "params", "returnType", "body"},
	"HookTypeAnnotation":              {"params", "returnType", "rest", "typeParameters"},
	"Identifier":                      {"typeAnnotation", "decorators"},
	"IfStatement":                     {"test", "consequent", "alternate"},
	"ImportAttribute":                 {"key", "value"},
	"ImportDeclaration":               {"specifiers", "source", "attributes"},
	"ImportDefaultSpecifier":          {"local"},
	"ImportExpression":                {"source", "options"},
	"ImportNamespaceSpecifier":        {"local"},
	"ImportSpecifier":                 {"imported", "local"},
	"IndexedAccessType":               {"objectType", "indexType"},
	"InferTypeAnnotation":             {"typeParameter"},
	"InferredPredicate":               {},
	"InterfaceDeclaration":            {"id", "typeParameters", "extends", "body"},
	"InterfaceExtends":                {"id", "typeParameters"},
	"InterfaceTypeAnnotation":         {"extends", "body"},
	"InterpreterDirective":            {},
	"IntersectionTypeAnnotation":      {"types"},
	"JSXAttribute":                    {"name", "value"},
	"JSXClosingElement":               {"name"},
	"JSXClosingFragment":              {},
	"JSXElement":                      {"openingElement", "children", "closingElement"},
	"JSXEmptyExpression":              {},
	"JSXExpressionContainer":          {"expression"},
	"JSXFragment":                     {"openingFragment", "children", "closingFragment"},
	"JSXIdentifier":                   {},
	"JSXMemberExpression":             {"object", "property"},
	"JSXNamespacedName":               {"namespace", "name"},
	"JSXOpeningElement":               {"name", "typeArguments", "attributes"},
	"JSXOpeningFragment":              {},
	"JSXSpreadAttribute":              {"argument"},
	"JSXSpreadChild":                  {"expression"},
	"JSXText":                         {},
	"JsExpressionRoot":                {"node"},
	"JsonRoot":                        {"node"},
	"KeyofTypeAnnotation":             {"argument"},
	"LabeledStatement":                {"label", "body"},
	"Literal":                         {},
	"LogicalExpression":               {"left", "right"},
	"MatchArrayPattern":               {"elements", "rest"},
	"MatchAsPattern":                  {"pattern", "target"},
	"MatchBindingPattern":             {"id"},
	"MatchExpression":                 {"argument", "cases"},
	"MatchExpressionCase":             {"pattern", "body", "guard"},
	"MatchIdentifierPattern":          {"id"},
	"MatchInstanceObjectPattern":      {"properties", "rest"},
	"MatchInstancePattern":            {"targetConstructor", "properties"},
	"MatchLiteralPattern":             {"literal"},
	"MatchMemberPattern":              {"base", "property"},
	"MatchObjectPattern":              {"properties", "rest"},
	"MatchObjectPatternProperty":      {"key", "pattern"},
	"MatchOrPattern":                  {"patterns"},
	"MatchRestPattern":                {"argument"},
	"MatchStatement":                  {"argument", "cases"},
	"MatchStatementCase":              {"pattern", "body", "guard"},
	"MatchUnaryPattern":               {"argument"},
	"MatchWildcardPattern":            {},
	"MemberExpression":                {"object", "property"},
	"MetaProperty":                    {"meta", "property"},
	"MethodDefinition":                {"decorators", "key", "value"},
	"MixedTypeAnnotation":             {},
	"ModuleExpression":                {"body"},
	"NGChainedExpression":             {"expressions"},
	"NGEmptyExpression":               {},
	"NGMicrosyntax":                   {"body"},
	"NGMicrosyntaxAs":                 {"key", "alias"},
	"NGMicrosyntaxExpression":         {"expression", "alias"},
	"NGMicrosyntaxKey":                {},
	"NGMicrosyntaxKeyedExpression":    {"key", "expression"},
	"NGMicrosyntaxLet":                {"key", "value"},
	"NGPipeExpression":                {"left", "right", "arguments"},
	"NGRoot":                          {"node"},
	"NeverTypeAnnotation":             {},
	"NewExpression":                   {"callee", "typeArguments", "arguments"},
	"NullLiteral":                     {},
	"NullLiteralTypeAnnotation":       {},
	"NullableTypeAnnotation":          {"typeAnnotation"},
	"NumberLiteralTypeAnnotation":     {},
	"NumberTypeAnnotation":            {},
	"NumericLiteral":                  {},
	"ObjectExpression":                {"properties"},
	"ObjectMethod":                    {"decorators", "key", "typeParameters", "params", "returnType", "body"},
	"ObjectPattern":                   {"decorators", "properties", "typeAnnotation"},
	"ObjectProperty":                  {"decorators", "key", "value"},
	"ObjectTypeAnnotation":            {"properties", "indexers", "callProperties", "internalSlots"},
	"ObjectTypeCallProperty":          {"value"},
	"ObjectTypeIndexer":               {"variance", "id", "key", "value"},
	"ObjectTypeInternalSlot":          {"id", "value"},
	"ObjectTypeMappedTypeProperty":    {"keyTparam", "propType", "sourceType", "variance"},
	"ObjectTypeProperty":              {"key", "value", "variance"},
	"ObjectTypeSpreadProperty":        {"argument"},
	"OpaqueType":                      {"id", "typeParameters", "supertype", "impltype", "lowerBound", "upperBound"},
	"OptionalCallExpression":          {"callee", "typeArguments", "arguments"},
	"OptionalIndexedAccessType":       {"objectType", "indexType"},
	"OptionalMemberExpression":        {"object", "property"},
	"ParenthesizedExpression":         {"expression"},
	"Placeholder":                     {},
	"PrivateIdentifier":               {},
	"PrivateName":                     {"id"},
	"Program":                         {"directives", "body"},
	"Property":                        {"key", "value"},
	"PropertyDefinition":              {"decorators", "variance", "key", "typeAnnotation", "value"},
	"QualifiedTypeIdentifier":         {"qualification", "id"},
	"QualifiedTypeofIdentifier":       {"qualification", "id"},
	"RecordDeclaration":               {"id", "typeParameters", "implements", "body"},
	"RecordDeclarationBody":           {"elements"},
	"RecordDeclarationImplements":     {"id", "typeArguments"},
	"RecordDeclarationProperty":       {"key", "typeAnnotation", "defaultValue"},
	"RecordDeclarationStaticProperty": {"key", "typeAnnotation", "value"},
	"RecordExpression":                {"recordConstructor", "typeArguments", "properties"},
	"RecordExpressionProperties":      {"properties"},
	"RegExpLiteral":                   {},
	"RestElement":                     {"argument", "typeAnnotation", "decorators"},
	"ReturnStatement":                 {"argument"},
	"SatisfiesExpression":             {"expression", "typeAnnotation"},
	"SequenceExpression":              {"expressions"},
	"SpreadElement":                   {"argument"},
	"StaticBlock":                     {"body"},
	"StringLiteral":                   {},
	"StringLiteralTypeAnnotation":     {},
	"StringTypeAnnotation":            {},
	"Super":                           {},
	"SwitchCase":                      {"test", "consequent"},
	"SwitchStatement":                 {"discriminant", "cases"},
	"SymbolTypeAnnotation":            {},
	"TSAbstractAccessorProperty":      {"decorators", "key", "typeAnnotation"},
	"TSAbstractKeyword":               {},
	"TSAbstractMethodDefinition":      {"key", "value"},
	"TSAbstractPropertyDefinition":    {"decorators", "key", "typeAnnotation"},
	"TSAnyKeyword":                    {},
	"TSArrayType":                     {"elementType"},
	"TSAsExpression":                  {"expression", "typeAnnotation"},
	"TSAsyncKeyword":                  {},
	"TSBigIntKeyword":                 {},
	"TSBooleanKeyword":                {},
	"TSCallSignatureDeclaration":      {"typeParameters", "params", "returnType"},
	"TSClassImplements":               {"expression", "typeArguments"},
	"TSConditionalType":               {"checkType", "extendsType", "trueType", "falseType"},
	"TSConstructSignatureDeclaration": {"typeParameters", "params", "returnType"},
	"TSConstructorType":               {"typeParameters", "params", "returnType"},
	"TSDeclareFunction":               {"id", "typeParameters", "params", "returnType", "body"},
	"TSDeclareKeyword":                {},
	"TSDeclareMethod":                 {"key", "typeParameters", "params", "returnType"},
	"TSEmptyBodyFunctionExpression":   {"id", "typeParameters", "params", "returnType"},
	"TSEnumBody":                      {"members"},
	"TSEnumDeclaration":               {"id", "body"},
	"TSEnumMember":                    {"id", "initializer"},
	"TSExportAssignment":              {"expression"},
	"TSExportKeyword":                 {},
	"TSExternalModuleReference":       {"expression"},
	"TSFunctionType":                  {"typeParameters", "params", "returnType"},
	"TSImportEqualsDeclaration":       {"id", "moduleReference"},
	"TSImportType":                    {"source", "options", "qualifier", "typeArguments"},
	"TSIndexSignature":                {"parameters", "typeAnnotation"},
	"TSIndexedAccessType":             {"objectType", "indexType"},
	"TSInferType":                     {"typeParameter"},
	"TSInstantiationExpression":       {"expression", "typeArguments"},
	"TSInterfaceBody":                 {"body"},
	"TSInterfaceDeclaration":          {"id", "typeParameters", "extends", "body"},
	"TSInterfaceHeritage":             {"expression", "typeArguments"},
	"TSIntersectionType":              {"types"},
	"TSIntrinsicKeyword":              {},
	"TSJSDocAllType":                  {},
	"TSJSDocNonNullableType":          {"typeAnnotation"},
	"TSJSDocNullableType":             {"typeAnnotation"},
	"TSJSDocUnknownType":              {},
	"TSLiteralType":                   {"literal"},
	"TSMappedType":                    {"key", "constraint", "nameType", "typeAnnotation"},
	"TSMethodSignature":               {"key", "typeParameters", "params", "returnType"},
	"TSModuleBlock":                   {"body"},
	"TSModuleDeclaration":             {"id", "body"},
	"TSNamedTupleMember":              {"label", "elementType"},
	"TSNamespaceExportDeclaration":    {"id"},
	"TSNeverKeyword":                  {},
	"TSNonNullExpression":             {"expression"},
	"TSNullKeyword":                   {},
	"TSNumberKeyword":                 {},
	"TSObjectKeyword":                 {},
	"TSOptionalType":                  {"typeAnnotation"},
	"TSParameterProperty":             {"parameter", "decorators"},
	"TSParenthesizedType":             {"typeAnnotation"},
	"TSPrivateKeyword":                {},
	"TSPropertySignature":             {"key", "typeAnnotation"},
	"TSProtectedKeyword":              {},
	"TSPublicKeyword":                 {},
	"TSQualifiedName":                 {"left", "right"},
	"TSReadonlyKeyword":               {},
	"TSRestType":                      {"typeAnnotation"},
	"TSSatisfiesExpression":           {"expression", "typeAnnotation"},
	"TSStaticKeyword":                 {},
	"TSStringKeyword":                 {},
	"TSSymbolKeyword":                 {},
	"TSTemplateLiteralType":           {"quasis", "types"},
	"TSThisType":                      {},
	"TSTupleType":                     {"elementTypes"},
	"TSTypeAliasDeclaration":          {"id", "typeParameters", "typeAnnotation"},
	"TSTypeAnnotation":                {"typeAnnotation"},
	"TSTypeAssertion":                 {"expression", "typeAnnotation"},
	"TSTypeLiteral":                   {"members"},
	"TSTypeOperator":                  {"typeAnnotation"},
	"TSTypeParameter":                 {"name", "constraint", "default"},
	"TSTypeParameterDeclaration":      {"params"},
	"TSTypeParameterInstantiation":    {"params"},
	"TSTypePredicate":                 {"parameterName", "typeAnnotation"},
	"TSTypeQuery":                     {"exprName", "typeArguments"},
	"TSTypeReference":                 {"typeName", "typeArguments"},
	"TSUndefinedKeyword":              {},
	"TSUnionType":                     {"types"},
	"TSUnknownKeyword":                {},
	"TSVoidKeyword":                   {},
	"TaggedTemplateExpression":        {"tag", "typeArguments", "quasi"},
	"TemplateElement":                 {},
	"TemplateLiteral":                 {"quasis", "expressions"},
	"ThisExpression":                  {},
	"ThisTypeAnnotation":              {},
	"ThrowStatement":                  {"argument"},
	"TopicReference":                  {},
	"TryStatement":                    {"block", "handler", "finalizer"},
	"TupleTypeAnnotation":             {"elementTypes"},
	"TupleTypeLabeledElement":         {"label", "elementType", "variance"},
	"TupleTypeSpreadElement":          {"label", "typeAnnotation"},
	"TypeAlias":                       {"id", "typeParameters", "right"},
	"TypeAnnotation":                  {"typeAnnotation"},
	"TypeCastExpression":              {"expression", "typeAnnotation"},
	"TypeOperator":                    {"typeAnnotation"},
	"TypeParameter":                   {"bound", "default", "variance"},
	"TypeParameterDeclaration":        {"params"},
	"TypeParameterInstantiation":      {"params"},
	"TypePredicate":                   {"parameterName", "typeAnnotation"},
	"TypeofTypeAnnotation":            {"argument", "typeArguments"},
	"UnaryExpression":                 {"argument"},
	"UndefinedTypeAnnotation":         {},
	"UnionTypeAnnotation":             {"types"},
	"UnknownTypeAnnotation":           {},
	"UpdateExpression":                {"argument"},
	"V8IntrinsicIdentifier":           {},
	"VariableDeclaration":             {"declarations"},
	"VariableDeclarator":              {"id", "init"},
	"Variance":                        {},
	"VoidPattern":                     {},
	"VoidTypeAnnotation":              {},
	"WhileStatement":                  {"body", "test"},
	"WithStatement":                   {"object", "body"},
	"YieldExpression":                 {"argument"},
}
