package compose

import (
	"math/rand/v2"
	"strings"
)

// fixtures are compared document for document against upstream. They are grouped by the compose or
// resolve function they mostly drive; most drive several.
var fixtures = []string{
	// composer: empty streams, comments before, between and after documents, byte order marks
	"",
	"\n",
	"\n\n",
	"# c",
	"# c\n",
	"#\n",
	"# a\n\n# b\n",
	"# a\n# b\nkey: value\n",
	"# a\n\nkey: value\n",
	"# a\n- b\n",
	"# a\n[b]\n",
	"# a\nscalar\n",
	"# a\n--- b\n",
	"a\n# trailing\n",
	"a\n# t1\n\n# t2\n",
	"\uFEFFa",
	"\uFEFF# c\n",
	"\uFEFF",
	"a\n...\n# after end\n",
	"a\n... # end comment\n",
	"a\n...\n...\n",
	"...\n",
	"... # c\n",
	"a\n--- b\n--- c\n",
	"---\n---\n---\n",
	"--- # c\na\n",
	"---\n# c\na\n",
	"--- a # c\n",
	"--- |\n  block\n",
	"--- >-\n  folded\n...\n",
	"a\n---\n# between\nb\n",
	"a\n...\n# between\n---\nb\n",
	"--- {a: b}\n--- [c]\n",
	"--- a: b\n",
	"--- - a\n",
	"---\n- a\n",
	"--- !!map\na: b\n",
	"--- &x\na: b\n",
	"key: value\n... trailing junk\n",
	"a\n...\nb\n",

	// directives
	"%YAML 1.2\n---\na\n",
	"%YAML 1.2\na\n",
	"%YAML 1.1\n---\na: yes\nb: 0b101\nc: 0o17\nd: 017\ne: 1_000\nf: 190:20:30\ng: 1:30.5\nh: 2001-12-14t21:59:43.10-05:00\ni: !!binary aGVsbG8=\nj: 0x1_F\nk: 1_0.5_0\nl: .5e3\nm: Off\n",
	"%YAML 1.1\n---\na\n---\nb\n",
	"%YAML 1.1\n---\na\n...\n%YAML 1.2\n---\nb\n",
	"%YAML 1.3\n---\na\n",
	"%YAML 2.0\n---\na\n",
	"%YAML x\n---\na\n",
	"%YAML 1.2 1.1\n---\na\n",
	"%YAML\n---\na\n",
	"%TAG ! tag:example.com,2000:\n--- !foo a\n",
	"%TAG !e! tag:example.com,2000:app/\n--- !e!foo a\n",
	"%TAG !e! tag:example.com,2000:app/\n--- !e!foo a\n--- !e!foo b\n",
	"%TAG !e!\n---\na\n",
	"%TAG !e! a b\n--- !e!x a\n",
	"%FOO bar\n---\na\n",
	"%YAML 1.2\n",
	"%YAML 1.2\n# c\n",
	"%YAML 1.2\n%YAML 1.2\n---\na\n",
	"%TAG !! tag:example.com,2000:\n--- !!str a\n",
	"%YAML 1.2 # comment\n---\na\n",
	"a\n%YAML 1.2\n---\nb\n",
	"%YAML 1.1\n--- !!set\n? a\n? b\n",
	"%YAML 1.1\n--- !!omap\n- a: 1\n- b: 2\n",
	"%YAML 1.1\n--- !!timestamp foo\n",
	"%YAML 1.1\n---\n- 0b\n- 0b_\n- 0_\n- 0x_\n- e5\n- .\n- -.\n- +12_3\n- -0b11\n- 1:2:3\n- -1:30\n- 1:2.\n- y\n- N\n",
	"%YAML 1.1\n---\n<<: {a: 1}\n",

	// tags: resolution, the non-specific tag, verbatim, local, unresolved, URI escapes
	"!!str a",
	"!!str 1",
	"!!int 1",
	"!!int a",
	"!!float 1",
	"!!float 1.5",
	"!!bool true",
	"!!bool yes",
	"!!null ~",
	"!!null a",
	"! a",
	"! [a]",
	"! {a: b}",
	"!foo a",
	"!foo [a]",
	"!<tag:yaml.org,2002:str> a",
	"!<tag:example.com,2000:x> a",
	"!<!> a",
	"!<!!> a",
	"!<> a",
	"!<a",
	"!! a",
	"!e!x a",
	"!!str%21 a",
	"!!%C3%A9 a",
	"!!%E9 a",
	"!!%ZZ a",
	"!!a%2 a",
	"!!%F0%9F%98%80 a",
	"!!%ED%A0%80 a",
	"!!%C0%80 a",
	"!!map {a: b}",
	"!!map [a]",
	"!!seq [a]",
	"!!seq {a: b}",
	"!!str [a]",
	"!!str {a: b}",
	"!!map a",
	"!!seq a",
	"!!set {a, b}",
	"!!set\n? a\n? b\n",
	"!!set {a: b}",
	"!!set [a]",
	"!!set {a: !!null , b}",
	"!!set {a: !!str , b}",
	"!!set {? a # c\n}",
	"!!omap [a: 1, b: 2]",
	"!!omap\n- a: 1\n- b: 2\n",
	"!!omap [a: 1, a: 2]",
	"!!omap [1: a, 1: b]",
	"!!omap [.nan: a, .NaN: b]",
	"!!omap [null: a, ~: b]",
	"!!omap [true: a, True: b]",
	"!!omap [<<: a, <<: b]",
	"!!omap [a]",
	"!!omap {a: b}",
	"!!omap [{}, {a: b, c: d}]",
	"!!omap\n- a: 1\n  b: 2\n",
	"!!omap\n# before\n- a: 1 # after\n",
	"!!pairs [a: 1, a: 2]",
	"!!pairs\n- a: 1\n- b\n- [c]\n",
	"!!pairs [{}, a]",
	"!!pairs\n- # c\n  a: 1\n",
	"!!pairs {a: b}",
	"!!binary aGVsbG8=",
	"!!binary |\n  aGVs\n  bG8=\n",
	"!!binary 'aGVs bG8'",
	"!!binary QUJD=QUJD",
	"!!binary QU*JD",
	"!!binary QU-_",
	"!!binary Q",
	"!!binary Q=UJD",
	"!!binary \"\\u0141QUJD\"",
	"!!binary \"\\u00e9QUJD\"",
	"!!binary QUJDRA===x",
	"!!binary [a]",
	"!!timestamp 2001-12-14",
	"!!timestamp 2001-12-14t21:59:43.10-05:00",
	"!!timestamp 2001-12-14 21:59:43.10 -5",
	"!!timestamp 2001-12-14 21:59:43.123456 +05:30",
	"!!timestamp 2001-12-14T21:59:43Z",
	"!!timestamp 0050-01-01",
	"!!timestamp 2001-13-40",
	"!!timestamp 2001-00-00 99:99:99",
	"!!timestamp foo",
	"!!timestamp [a]",
	"!!merge <<",
	"!!merge a",
	"!!merge {a: b}",
	"!<constructor> a",
	"!<constructor> {a: b}",
	"!<__proto__> a",
	"!<toString> [a]",
	"!<hasOwnProperty> a",
	"%TAG !c! cons\n--- !c!tructor a\n",
	"a: !!str\nb: !!int\n",
	"- !!str\n- !foo\n",
	"!!str &a b",
	"&a !!str b",
	"!!str !!int a",
	"&a &b c",
	"!!str\n- a\n",
	"!!str - a\n",
	"&a - a\n",
	"&a !!seq - a\n",
	"!!seq &a - a\n",
	"&a\n- a\n",
	"&a\n!!seq\n- a\n",
	"!!str\n&a\n- a\n",
	"? !!str\n: !!str\n",

	// anchors and aliases
	"&a a",
	"&a [b]",
	"&a {b: c}",
	"& a",
	"&a: b",
	"a: &b: c",
	"*a",
	"*a # c",
	"* a",
	"*a:",
	"&x a\n*x\n",
	"- &a 1\n- *a\n- &a 2\n- *a\n",
	"a: &x 1\nb: *x\n",
	"&a *b",
	"!!str *b",
	"&a\n*b\n",
	"{&a a: *a}",
	"[*a, *b]",
	"*a : b",
	"? *a\n: *b\n",
	"&anchor\n",
	"a: &anchor\n",
	"- &anchor\n",
	"&a # comment\nb\n",

	// plain scalars: core schema values, folding, bad starts
	"a",
	"a b",
	" a",
	"a\n b",
	"a\n\n b",
	"a\n\n\n b",
	"a \n b",
	"a\t\n\tb",
	"a\r\n b",
	"a\r\n\r\n b",
	"a  \r\n  b  \r\n  c",
	"a\n \n b",
	"a\n \t \n b",
	"null",
	"Null",
	"NULL",
	"~",
	"nULL",
	"true",
	"True",
	"TRUE",
	"false",
	"tRUE",
	"yes",
	"0",
	"-0",
	"+0",
	"007",
	"12345",
	"-12345",
	"+12",
	"123456789012345678901234567890",
	"9007199254740993",
	"0o17",
	"0o",
	"0o8",
	"0x1F",
	"0xff",
	"0x",
	"0xFFFFFFFFFFFFFFFFFF",
	"0x20000000000000100000000001",
	"0x1fffffffffffff1",
	"0o7777777777777777777777777",
	"1.5",
	"1.",
	".5",
	"-.5",
	"+1.50",
	"1.500",
	"10.0",
	"0.0",
	"-0.0",
	"1e5",
	"1E5",
	"1.e5",
	".5e-3",
	"1e400",
	"-1e400",
	"1e-400",
	"1.0e1",
	"1_0",
	".inf",
	"-.inf",
	"+.Inf",
	".INF",
	".nan",
	".NaN",
	".NAN",
	".Nan",
	"0.1",
	"3.141592653589793238462643383279",
	"<<",
	"<< : a",
	"<<: a",
	"{<<: a}",
	"[<<: a]",
	"- <<: a",
	"? <<\n: a\n",
	"'<<': a",
	",a",
	"%a",
	"@a",
	"`a",
	"|a",
	"a: @b",
	"a: `b",
	"a: %b",
	"[@a, `b]",
	"a\u00e9",
	"\u00e9: \U0001F600",
	"\U0001F600 \U0001F600\n \U0001F600",

	// single-quoted scalars
	"'a'",
	"''",
	"'''a'''",
	"'a''b'",
	"'a\n b'",
	"'a\n\n b'",
	"'a  \n  b'",
	"'a\r\n b'",
	"'a",
	"'",
	"'a' # c",
	"'a'#c",
	"'a' b",
	"a: 'b\n  c'\n",
	"'\U0001F600'",
	"' a '",
	"'a\n'",
	"'\n'",

	// double-quoted scalars: every escape, folding, errors
	`"a"`,
	`""`,
	`"a\"b"`,
	`"\0\a\b\e\f\n\r\t\v\N\_\L\P\ \"\/\\"`,
	"\"\\\t\"",
	`"\x41\u00e9\U0001F600"`,
	`"\x4"`,
	`"\xZZ"`,
	`"\u12"`,
	`"\uD800"`,
	`"\uDC00\uD800"`,
	`"\uD83D\uDE00"`,
	`"\U00110000"`,
	`"\UFFFFFFFF"`,
	`"\U0010FFFF"`,
	`"\q"`,
	`"\`,
	`"\"`,
	`"a\`,
	"\"\\\U0001F600\"",
	"\"a\\\nb\"",
	"\"a\\\n   b\"",
	"\"a\\\r\n  b\"",
	"\"a\nb\"",
	"\"a\n\nb\"",
	"\"a \n b\"",
	"\"a\t\n\tb\"",
	"\"a\r\nb\"",
	"\"a\r\n\r\nb\"",
	"\"a  b\"",
	"\"a \"",
	"\"a\t\t\"",
	"\"a  \r\n b\"",
	"\"a\rb\"",
	"\"a\n \r b\"",
	"\"a",
	"\"",
	"\"a\" # c",
	"\"a\"#c",
	"key: \"a\n  b\"\n",

	// block scalars: headers, chomping, indentation, folding, errors
	"|\n a\n",
	"|\n a\n b\n",
	">\n a\n b\n",
	">\n a\n\n b\n",
	">\n a\n  b\n c\n",
	">\n a\n\n  b\n\n c\n",
	">\n  a\n \tb\n",
	">\n a\n\tb\n",
	">\n\ta\n",
	"|-\n a\n\n",
	"|+\n a\n\n\n",
	"|+\n a",
	"|+\n\n\n",
	"|+\n",
	"|-\n",
	"|\n",
	"|",
	">",
	">+",
	"|2\n   a\n",
	"|2-\n   a\n",
	"|-2\n   a\n",
	"|+1\n  a\n",
	"|0\n a\n",
	"|10\n a\n",
	"|22\n a\n",
	"|--\n a\n",
	"|+-\n a\n",
	"|x\n a\n",
	"| # comment\n a\n",
	"|# comment\n a\n",
	"|\n\n  a\n",
	"|\n  \n a\n",
	"|\n   \n  a\n",
	"|1\n  \n a\n",
	"|\n a\n  \n",
	"|+\n a\n  \n   \n",
	"|\n a\r\n b\r\n",
	"|\r\n a\r\n\r\n",
	">\r\n a\r\n b\r\n",
	"- |\n a\n- >\n b\n",
	"a: |\n  b\n  c\nd: e\n",
	"a: |\nb\n",
	"a:\n  - |\n   b\n",
	"- |\nb\n",
	"|\na\n",
	"--- |\na\n",
	"a: >\n  more\n    indented\n  back\n",
	">\n  a\n\n    b\n\n  c\n",
	">\n\n  a\n",
	"|\n  a\n b\n",
	"|2\n  a\n b\n",
	">-\n  trimmed\n\n\n",
	">+\n  kept\n\n\n",
	"|\n  \U0001F600\n",

	// block maps: implicit and explicit keys, empty keys and values, comments, indentation errors
	"a: b",
	"a: b\nc: d",
	"a:",
	"a:\n",
	": b",
	":",
	"a: b\n c: d",
	"a: b\n  c: d",
	"a:\n  b: c\n d: e",
	"a: b: c",
	"a: b\nc",
	"a\nb: c",
	"? a",
	"? a\n: b",
	"? a\n: b\n? c\n: d",
	"?\n: b",
	"? \n:",
	"? a\n  : b",
	" ? a\n: b",
	"? - a\n: - b",
	"? |\n  a\n: b",
	"? a: b\n: c",
	"?: a",
	"a: 1\na: 2",
	"a: 1 # c\nb: 2",
	"a: 1\n# c\nb: 2",
	"a: 1\n\nb: 2",
	"a: 1\n\n\nb: 2",
	"a:\n  # c\n  b",
	"a: # c\n  b",
	"a: # c\n",
	"a: # c\n# d\n",
	"a: b\n# end\n",
	"a: b\n  # end\n",
	"a:\n  b: c\n  # end\n",
	"a:\n  b: c\n# end\n",
	"a:\n  - b\n  # end\n",
	"a:\n- b\n- c\n",
	"a:\n  b:\n    c: d\n",
	"- a: b\n  c: d\n",
	"- a: b\n c: d\n",
	"a: - b",
	"- a\nb: c",
	"a: b\n- c",
	"a b: c",
	"a\n b: c",
	"\"a\n b\": c",
	"'a\n b': c",
	"[a,\n b]: c",
	"{a: b}: c",
	"[a]: b\n{c: d}: e",
	"&x a: b",
	"!!str a: b",
	"&x\na: b",
	"!!map\na: b",
	"&x !!map\na: b",
	"? &x a\n: &y b",
	"a: &x\n  b: c",
	"a: !!map\n  b: c",
	"a: &x - b",
	"a:\n\tb",
	"a:\t\n  b: c",
	"\ta: b",
	"a:\n  b\n\t\n  c",
	"a: b\t# c",
	"a: b #c\n",
	"a: b#c\n",
	"a: [b]#c\n",
	"a: {b: c} # c\n",
	strings.Repeat("k", 1030) + ": v",
	"\"" + strings.Repeat("k", 1030) + "\": v",
	"? " + strings.Repeat("k", 1030) + "\n: v",
	"a: b\n...\n",
	"a: b\n--- c: d\n",
	"a:\r\n  b: c\r\n",
	"a: b\n c\n",
	"a: b\n\nc\n",
	"a:\n  b\n  c\n",
	"x:\n  a: 1\n   b: 2\n",

	// block sequences
	"- a",
	"- a\n- b",
	"-",
	"- ",
	"-\n-\n",
	"- - a",
	"- - a\n  - b\n- c",
	"- a\n - b",
	"- a\n  - b",
	"-  a\n -  b",
	"- a\n# c\n- b",
	"- a # c\n- b",
	"- a\n\n- b",
	"- # c\n  a",
	"- # c\n",
	"-\n  # c\n",
	"- a\n  # end\n",
	"- a\n# end\n",
	"- &x a\n- !!str b",
	"- &x\n  a\n",
	"- !!str\n  a\n",
	"- !!seq\n  - a\n",
	"- !!seq - a\n",
	"- &x - a\n",
	"- a: b\n  - c\n",
	"- [a]\n- {b: c}\n",
	"- |\n  a\n- b\n",
	"-\ta",
	"- \ta",
	"-\t- a",
	"- a\n -b",
	"  - a\n  - b\n",
	"- a\n-",
	"- a\n- ",

	// flow sequences
	"[]",
	"[a]",
	"[a, b]",
	"[a, b, ]",
	"[a b]",
	"[a,, b]",
	"[, a]",
	"[,]",
	"[a, , ]",
	"[a",
	"[a, b",
	"[a]]",
	"[a] # c",
	"[a]#c",
	"[a] b",
	"[a: b]",
	"[a: b, c: d]",
	"[a:b]",
	"[? a: b]",
	"[? a]",
	"[: b]",
	"[a: ]",
	"[a :b]",
	"[\"a\":b]",
	"[a\n: b]",
	"[a\n, b]",
	"[\n a,\n b\n]",
	"[a, # c\n b]",
	"[a, # c\n # d\n b]",
	"[a # c\n, b]",
	"[ # c\n a]",
	"[ , # c\n a]",
	"[ , , # c\n a]",
	"[a, # c\n]",
	"[# c\n]",
	"[a # c\n]",
	"[[a], [b]]",
	"[{a: b}, {c: d}]",
	"[&x a, *x]",
	"[!!str a, !!int 1]",
	"[&x , !!str ]",
	"[a: [b]]",
	"[[a]: b]",
	"[{a: b}: c]",
	"[- a]",
	"[a: - b]",
	"[\"a\nb\": c]",
	"[a\n b: c]",
	"[" + strings.Repeat("k", 1030) + ": v]",
	"[&x" + strings.Repeat(" ", 1030) + ": v]",
	"[a, b] : c",
	"a: [b,\nc]\n",
	"a: [b,\n  c]\n",
	"a:\n  [b,\n  c]\n",
	"a:\n  - [b,\n  ]\n",
	"- [a,\n  b\n  ]\n",
	"key:\n  - [a\n",
	"[a\n- b]",
	"[\t a]",
	"[a\t]",
	"[a,\tb]",

	// flow maps
	"{}",
	"{a: b}",
	"{a: b, c: d}",
	"{a: b, c: d, }",
	"{a, b}",
	"{a: b c: d}",
	"{a:b}",
	"{\"a\":b}",
	"{a: }",
	"{: b}",
	"{:}",
	"{? a: b}",
	"{? a}",
	"{?}",
	"{a: b",
	"{a: b]",
	"{a: b}}",
	"{a: b} # c",
	"{a: b, # c\n c: d}",
	"{a: b # c\n}",
	"{a # c\n: b}",
	"{a: # c\n b}",
	"{a: 1, a: 2}",
	"{a: {b: c}}",
	"{a: [b, c]}",
	"{[a]: b}",
	"{{a: b}: c}",
	"{a: - b}",
	"{- a: b}",
	"{a\n: b}",
	"{a: b\n}",
	"{\na: b\n}",
	"a: {b: c,\nd: e}\n",
	"a:\n  {b: c,\n  }\n",
	"{a: b,, c: d}",
	"{, a: b}",
	"{&x a: *x}",
	"{!!str a: !!int 1}",
	"{a: &x}",
	"{a: !!str}",
	"{a: # c\n}",
	"{a\n # c\n}",
	"{\"a\" :b}",
	"{a: b}: c\n",
	"{\ta: b}",

	// nesting, documents of each kind, comments everywhere
	"a:\n  b:\n    - c\n    - d: [e, {f: g}]\n  h: |\n    i\n",
	"- - - a\n    - b\n  - c\n- d\n",
	"a: [b, {c: [d, e]}]\nf: {g: [h]}\n",
	"# 1\na: # 2\n  # 3\n  b # 4\n  # 5\n# 6\n",
	"# 1\n- # 2\n  a # 3\n# 4\n- b\n# 5\n",
	"[ # 1\n a, # 2\n b # 3\n] # 4\n# 5\n",
	"{ # 1\n a: b, # 2\n c: d # 3\n} # 4\n",
	"? # 1\n  a # 2\n: # 3\n  b # 4\n",
	"a:\n\n  b: c\n\n  d: e\n",
	"- a\n\n- b\n\n\n- c\n",
	"a: b\n---\nc: d\n...\n---\n- e\n",
	"key: value\r\nlist:\r\n  - a\r\n  - b\r\n",
	"\U0001F600: \u00e9\n\u00e9\u00e9: [\U0001F600, \u00e9]\n",
	"a: \"\U0001F600\n  \u00e9\"\n",

	// tabs as indentation and separation
	"a:\n\t- b",
	"-\ta\n-\tb",
	"\t- a",
	"a: b\n\t# c\n",
	"? a\n:\tb",
	"\t[a]",
	"--- \t[a]",
	"---\t- a",
	"a:\t\tb",

	// comments the composer moves between nodes: onto a previous flow item, a pair's key, a !!pairs key
	"{a, # c\n b}",
	"{a, # c\n # d\n b}",
	"[a # c1\n, # c2\n b]",
	"[a: # c1\n, # c2\n b]",
	"[? a, # c\n b]",
	"{? a # k\n # v\n}",
	"{a # k\n : # v\n}",
	"[? a # k\n # v\n]",
	"? a # k\n# v\n",
	"? a\n# c\n",
	"? a # k\n  # v\n",
	"a:\n  b: 1\n  # c1\n  # c2\n",
	"a:\n  b: 1\n  # c1\n\n  # c2\n",
	"a: 1\n# c\n# d\n",
	"- a\n  # c1\n  # c2\n",
	"!!pairs\n- a: 1\n  # c\n- b: 2\n",
	"!!pairs [{a: 1} # c\n, b]",
	"!!pairs [{a} # c\n]",
	"!!pairs [{a: } # c\n]",
	"!!omap [{a: 1} # c\n]",
	"!!pairs\n# c\n- a: 1\n",
	"!!pairs\n- # c\n  # d\n  a: 1\n",
	"- !!pairs\n  - # c\n    a: 1\n",
	"!!pairs\n- &x # c\n  a: 1\n",
	"!!pairs\n- # c\n  ? # k\n    a\n  : 1\n",
	"!!pairs\n- # c\n  # k\n  a: 1 # v\n",
	"!!pairs\n- {a: b} # c\n",
	"!!pairs\n- {a} # c\n",
	"!!pairs [{a: b, c: d} # c\n]",
	" # d\n\n\n  : \t # d\n # d\n? ---\n: ",
	"\t # d\n\t!t  ? b-  # c\n# c\n",
	"*a{,   # d\n\n # d\n!!pairs\nb]",
	"{ # c\n}!!omap  # c\n\t",
	"!!binary 'QUJD QUJD QUJD'",
	"!!binary 'QUJDQUJ*DQUJD'",
	"!!binary 'QUJDQUJ=DQUJD'",
	"!!binary QUJDQ",
	"!!binary QUJDQU",
	"!!binary QUJDQUJ",
	"!!binary 'QUJD QQ=='",
	"!!binary QUJD=",
	"!!binary '  '",
	"!!binary ''",
	"!!binary 'Q U J D Q U J D'",
	"!!binary |\n  QUJD\n  QUJD\n  QQ==\n",
	"? ? a",
	"? a\n? ? b",
	"- ? ? a",
	"[a, ? , b]",
	"[a, ?, b]",
	"{a: b, ?, c: d}",
	"[a\n...\n",
	"{a: b\n---\n",
	"[a\n---\n",
	"key:\n  [a\n...\n",

	// error tokens from the parser and the composer's unsupported paths
	"a: b\n  - c\n",
	"[a]\n- b",
	"]",
	"}",
	",",
	"a: b\n]",
	"- a\n}",
	"a\n]\n",
	"\"a\" b: c",
	"a: \"b\" c",
	"- a\n b: c\n",
	"a:\n  - b\n c\n",
	"[a,\n- b]",
	"? a\n? b\n: c\n: d",
	"a: b\n: c",
	"- a\n:",
	"- a\n? b",
	"&a\n",
	"!!str\n",
	"&a !!str\n",
	"--- &a\n",
	"--- !!str\n",
	"--- !!map\n",
	"--- !!seq\n",
	"--- !!set\n",
	"--- !!omap\n",
	"- !!omap\n",
	"key: !!omap\n",
	"--- &a # c\n",
	"a: |\n  b\n c: d\n",
	"'a\n\n...\n",
	"\"a\n---\nb\"\n",
	"a: 'b\n--- c'\n",
}

// generatedInputs draws inputs from YAML's indicators, properties, scalar styles, spaces, tabs, line
// breaks and a few letters, values and non-ASCII characters, seeded so every run compares the same set.
func generatedInputs(count int) []string {
	random := rand.New(rand.NewPCG(3, 4))
	pieces := []string{
		" ", " ", " ", "  ", "\n", "\n", "\n", "\n  ", "\n    ", "\t", "\r\n",
		"-", "- ", "- ", "? ", ": ", ": ", ":", "#", " #", " # c", "[", "]", "{", "}", ",", ", ",
		"'", "\"", "\\", "|", ">", "|-", ">+", "|2", "&a ", "&", "!", "!!str ", "!!int ", "!!set ",
		"!!omap ", "!!pairs ", "!!map ", "!!seq ", "!foo ", "!<x> ", "*a", "*", "<<",
		"%YAML 1.1\n", "%YAML 1.2\n", "%TAG !e! tag:x,\n", "%", "---", "...", "--- ", "... ",
		"a", "b", "ab", "x y", "1", "1.0", "0x1F", "true", "null", "~", ".inf", "\\u00e9", "\\x4",
		"\U0001F600", "\u00e9", "\uFEFF",
	}
	inputs := make([]string, 0, count)
	for range count {
		length := 1 + random.IntN(24)
		var builder strings.Builder
		for range length {
			builder.WriteString(pieces[random.IntN(len(pieces))])
		}
		inputs = append(inputs, builder.String())
	}
	return inputs
}
