// Code generated by tools/gen_tailwind_collapse. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/gen_tailwind_collapse -entry-point <theme.css>
//
// Source: Tailwind 4.3.3, enumerated from theme.css.
// 327 functional roots produced 53301 candidate pairs, of which 38 collapse.
//
// Each entry is a fact about roots rather than about classes: `px + py => p`
// holds for every value the two roots share, so the table is small and does not grow with the
// codebase. Enumerated from the design system's own class list rather than from any codebase's
// usage, because a table built from observed classes is silently missing every family nobody has
// written yet.

package tailwind

// CollapseFamily is two utility roots that merge into a third.
//
// The merge only happens when everything except the root already agrees between the two classes:
// their variants, their importance, and their value. That precondition is the gate's job; this
// table answers only "if those match, do these two roots have a shorthand".
type CollapseFamily struct {
	First  string
	Second string
	Output string
}

// CollapseFamilies is every family the installed Tailwind knows, sorted by input roots.
var CollapseFamilies = []CollapseFamily{
	{First: "-bottom", Second: "-top", Output: "-inset-y"},
	{First: "-inset-x", Second: "-inset-y", Output: "-inset"},
	{First: "-left", Second: "-right", Output: "-inset-x"},
	{First: "-mb", Second: "-mt", Output: "-my"},
	{First: "-ml", Second: "-mr", Output: "-mx"},
	{First: "-mx", Second: "-my", Output: "-m"},
	{First: "-scroll-mb", Second: "-scroll-mt", Output: "-scroll-my"},
	{First: "-scroll-ml", Second: "-scroll-mr", Output: "-scroll-mx"},
	{First: "-scroll-mx", Second: "-scroll-my", Output: "-scroll-m"},
	{First: "-skew-x", Second: "-skew-y", Output: "-skew"},
	{First: "-translate-x", Second: "-translate-y", Output: "-translate"},
	{First: "border-b", Second: "border-t", Output: "border-y"},
	{First: "border-l", Second: "border-r", Output: "border-x"},
	{First: "border-spacing-x", Second: "border-spacing-y", Output: "border-spacing"},
	{First: "border-x", Second: "border-y", Output: "border"},
	{First: "bottom", Second: "top", Output: "inset-y"},
	{First: "gap-x", Second: "gap-y", Output: "gap"},
	{First: "h", Second: "w", Output: "size"},
	{First: "inset-x", Second: "inset-y", Output: "inset"},
	{First: "left", Second: "right", Output: "inset-x"},
	{First: "mask-b-from", Second: "mask-t-from", Output: "mask-y-from"},
	{First: "mask-b-to", Second: "mask-t-to", Output: "mask-y-to"},
	{First: "mask-l-from", Second: "mask-r-from", Output: "mask-x-from"},
	{First: "mask-l-to", Second: "mask-r-to", Output: "mask-x-to"},
	{First: "mb", Second: "mt", Output: "my"},
	{First: "ml", Second: "mr", Output: "mx"},
	{First: "mx", Second: "my", Output: "m"},
	{First: "pb", Second: "pt", Output: "py"},
	{First: "pl", Second: "pr", Output: "px"},
	{First: "px", Second: "py", Output: "p"},
	{First: "scroll-mb", Second: "scroll-mt", Output: "scroll-my"},
	{First: "scroll-ml", Second: "scroll-mr", Output: "scroll-mx"},
	{First: "scroll-mx", Second: "scroll-my", Output: "scroll-m"},
	{First: "scroll-pb", Second: "scroll-pt", Output: "scroll-py"},
	{First: "scroll-pl", Second: "scroll-pr", Output: "scroll-px"},
	{First: "scroll-px", Second: "scroll-py", Output: "scroll-p"},
	{First: "skew-x", Second: "skew-y", Output: "skew"},
	{First: "translate-x", Second: "translate-y", Output: "translate"},
}

// TailwindVersion is the version these families were enumerated from.
//
// Recorded so a mismatch between this and the installed Tailwind is greppable, and so a reader of a
// finding can tell which engine's opinion produced it.
const TailwindVersion = "4.3.3"
