package tailwind

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

type wave1Fixture struct {
	RootCount int `json:"rootCount"`
	CaseCount int `json:"caseCount"`
	Answered  int `json:"answered"`
	Rejected  int `json:"rejected"`
	Cases     []struct {
		Root       string  `json:"root"`
		ClassName  string  `json:"className"`
		ParsedRoot *string `json:"parsedRoot"`
		Kind       *string `json:"kind"`
		Reading    *struct {
			Order []int `json:"order"`
			Count int   `json:"count"`
		} `json:"reading"`
	} `json:"cases"`
}

// TestFrameworkFunctionalUtilitiesMatchTheEngine is the wave-1 acceptance test.
//
// Every class the registry advertises for these 25 roots, plus probes reaching each resolution
// branch, compared against the engine's own reading. The table was generated by pattern-matching
// `utilities.ts`, so this is the independent measurement: an extractor and the source are two claims,
// and spot-checking already found a defect in the extractor rather than in the source.
//
// Scored as a lattice rather than a rate. A case where both sides decline is an agreement about
// nothing and is counted separately from one where both produced the same reading, because folding
// silence into equality is how a table that stopped answering scores perfectly.
func TestFrameworkFunctionalUtilitiesMatchTheEngine(t *testing.T) {
	fixture := loadWave1Fixture(t, "wave1_fixtures.json")
	system := loadWave1DesignSystem(t)

	var agreed, bothDeclined, goSilent, engineSilent int
	var disagreements, silentNames []string

	for _, testCase := range fixture.Cases {
		utility, known := FrameworkFunctionalUtilities[testCase.Root]
		if !known {
			t.Fatalf("%s is in the fixture and not in the table; the fixture and the table disagree about which roots wave 1 covers", testCase.Root)
		}

		// A negative candidate parses to its own root: `-col-1` is root `-col`, not `col` negated,
		// because upstream registers the dashed name separately. The table is keyed on the
		// undashed root and carries SupportsNegative, so the lookup strips the dash and passes
		// negative through, which is what a real caller will do.
		candidates := ParseCandidate(testCase.ClassName, system)
		var reading Reading
		produced := false
		if len(candidates) > 0 {
			parsedRoot := candidates[0].Root
			negative := false
			if strings.HasPrefix(parsedRoot, "-") && utility.SupportsNegative {
				parsedRoot = parsedRoot[1:]
				negative = true
			}
			if parsedRoot == testCase.Root {
				reading, produced = utility.Reading(&candidates[0], system.Theme(), negative)
			}
		}

		switch {
		case testCase.Reading == nil && !produced:
			bothDeclined++
		case testCase.Reading == nil && produced:
			engineSilent++
			disagreements = append(disagreements, testCase.ClassName+": engine declined, table read "+formatReading(reading))
		case testCase.Reading != nil && !produced:
			goSilent++
			silentNames = append(silentNames, testCase.ClassName)
		default:
			expected := Reading{Order: testCase.Reading.Order, Count: testCase.Reading.Count}
			if readingsEqual(expected, reading) {
				agreed++
				continue
			}
			disagreements = append(disagreements, testCase.ClassName+": engine "+formatReading(expected)+", table "+formatReading(reading))
		}
	}

	sort.Strings(disagreements)
	sort.Strings(silentNames)

	// Every remaining silence must be a class the static table answers, and that is asserted rather
	// than noted. `cursor-auto` and `contain-none` are not entries in their root's `staticValues`
	// map; upstream registers them as separate `staticUtility` calls, so the functional path is
	// right to decline and M1's table is what answers them. A silence with no such explanation is a
	// gap in this table wearing the same shape.
	for _, className := range silentNames {
		if _, found := FrameworkStaticDeclarations[className]; !found {
			t.Errorf("%s: the engine reads it, this table declines, and no static registration covers it, so it is an unexplained gap", className)
		}
	}
	if len(silentNames) > 0 {
		t.Logf("table-silent classes, all covered by the static table: %v", silentNames)
	}
	t.Logf("wave 1: %d roots, %d cases, agreed %d, both-declined %d, table-silent %d, engine-silent %d, disagreed %d",
		fixture.RootCount, fixture.CaseCount, agreed, bothDeclined, goSilent, engineSilent, len(disagreements))

	// The population assertions, stated before the disagreements so a run that measured almost
	// nothing fails on the denominator rather than passing on the rate.
	if agreed < 150 {
		t.Errorf("only %d cases agreed of %d answered by the engine; a table that stopped answering scores perfectly on any comparison that counts only disagreements", agreed, fixture.Answered)
	}
	if bothDeclined < 50 {
		t.Errorf("only %d cases were declined by both sides; the rejection branches are under-exercised", bothDeclined)
	}

	for _, disagreement := range disagreements {
		t.Error(disagreement)
	}
}

// TestFrameworkFunctionalUtilitiesCoverTheUnprobableRoots is why this wave matters beyond its size.
//
// `gen_tailwind_collapse` reports eight roots it cannot reach with any probe value, so they are in
// KnownRoots and absent from every property table. Three of them are wave-1 roots and are answered
// here: `align`, `font-features` and `mask-radial-at`. Asserted by name, because the point is which
// roots stopped being unanswerable.
func TestFrameworkFunctionalUtilitiesCoverTheUnprobableRoots(t *testing.T) {
	for _, root := range []string{"align", "font-features", "mask-radial-at"} {
		utility, known := FrameworkFunctionalUtilities[root]
		if !known {
			t.Errorf("%s is one of the roots no probe value reaches and it is not in the table", root)
			continue
		}
		if utility.Property == "" {
			t.Errorf("%s is in the table with no property, so it answers nothing", root)
		}
	}
}

// TestFrameworkFunctionalUtilitiesShareOneBarePredicate pins the sharing the table exists to make visible.
//
// Twelve roots use the positive-integer handler. A closure per row would have made them twelve
// lookalike functions and a correction could reach eleven and miss the twelfth, which is the defect
// class this whole port keeps finding.
func TestFrameworkFunctionalUtilitiesShareOneBarePredicate(t *testing.T) {
	shared := 0
	for _, utility := range FrameworkFunctionalUtilities {
		if utility.BareValue == BareValuePositiveInteger {
			shared++
		}
	}
	if shared < 10 {
		t.Errorf("%d roots reference the shared positive-integer predicate; upstream has twelve in this wave, so the table may have inlined some", shared)
	}
}

func formatReading(reading Reading) string {
	raw, _ := json.Marshal(reading.Order)
	return string(raw) + "#" + itoa(reading.Count)
}

func loadWave1Fixture(t *testing.T, name string) wave1Fixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	var fixture wave1Fixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	if fixture.CaseCount == 0 || fixture.Answered == 0 {
		t.Fatalf("%s carries %d cases and %d answered; a comparison over it would pass by comparing nothing", name, fixture.CaseCount, fixture.Answered)
	}
	return fixture
}

func loadWave1DesignSystem(t *testing.T) *LoadedDesignSystem {
	t.Helper()
	system, err := LoadDesignSystem(LoadOptions{
		EntryPoint:          "/Users/kirkouimet/Projects/ahra/app/_theme/styles/theme.css",
		TailwindPackageRoot: "/Users/kirkouimet/Projects/ahra/node_modules/tailwindcss",
	})
	if err != nil {
		t.Skipf("the ahra design system is not available here: %v", err)
	}
	return system
}

// TestFrameworkStaticValuesDeclareTheirRootsProperty records why one branch cannot be mutation-tested.
//
// `Reading` looks a static value's property up rather than inheriting the root's, and mutating that
// lookup away does not fail the wave-1 suite. This is why: across all 16 wave-1 roots that declare
// staticValues, no entry names a different property. The branch is unreachable in this wave rather
// than untested, and the distinction is worth an assertion because the two look identical from a
// green run.
//
// If this test ever fails, a wave-1 root gained a diverging static value and the lookup it exercises
// is now load-bearing here. That is the moment to add the mutation, not to loosen this.
func TestFrameworkStaticValuesDeclareTheirRootsProperty(t *testing.T) {
	withStatics, diverging := 0, 0
	for root, utility := range FrameworkFunctionalUtilities {
		if len(utility.StaticValues) == 0 {
			continue
		}
		withStatics++
		for _, static := range utility.StaticValues {
			if static.Property != utility.Property {
				diverging++
				t.Logf("%s: static %q declares %q where the root declares %q", root, static.Name, static.Property, utility.Property)
			}
		}
	}

	if withStatics == 0 {
		t.Fatal("no wave-1 root declares staticValues, so this assertion measured nothing")
	}
	if diverging > 0 {
		t.Errorf("%d static values now declare a property their root does not; the property lookup in Reading is load-bearing in this wave and needs a mutation covering it", diverging)
	}
	t.Logf("%d roots declare staticValues, %d diverging properties", withStatics, diverging)
}
