package tailwind

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

type wave1Fixture struct {
	RootCount int `json:"rootCount"`
	CaseCount int `json:"caseCount"`
	Answered  int `json:"answered"`
	Rejected  int `json:"rejected"`
	Cases     []struct {
		Root       string  `json:"root"`
		ClassName  string  `json:"className"`
		ParsedRoot *string `json:"parsedRoot"`
		Kind       *string `json:"kind"`
		Reading    *struct {
			Order []int `json:"order"`
			Count int   `json:"count"`
		} `json:"reading"`
	} `json:"cases"`
}

// TestFrameworkFunctionalUtilitiesMatchTheEngine is the wave-1 acceptance test.
//
// Every class the registry advertises for these 25 roots, plus probes reaching each resolution
// branch, compared against the engine's own reading. The table was generated by pattern-matching
// `utilities.ts`, so this is the independent measurement: an extractor and the source are two claims,
// and spot-checking already found a defect in the extractor rather than in the source.
//
// Scored as a lattice rather than a rate. A case where both sides decline is an agreement about
// nothing and is counted separately from one where both produced the same reading, because folding
// silence into equality is how a table that stopped answering scores perfectly.
func TestFrameworkFunctionalUtilitiesMatchTheEngine(t *testing.T) {
	fixture := loadWave1Fixture(t, "wave1_fixtures.json")
	system := loadWave1DesignSystem(t)

	var agreed, bothDeclined, goSilent, engineSilent int
	var disagreements, silentNames []string

	for _, testCase := range fixture.Cases {
		utility, known := FrameworkFunctionalUtilities[testCase.Root]
		if !known {
			t.Fatalf("%s is in the fixture and not in the table; the fixture and the table disagree about which roots wave 1 covers", testCase.Root)
		}

		// A negative candidate parses to its own root: `-col-1` is root `-col`, not `col` negated,
		// because upstream registers the dashed name separately. The table is keyed on the
		// undashed root and carries SupportsNegative, so the lookup strips the dash and passes
		// negative through, which is what a real caller will do.
		candidates := ParseCandidate(testCase.ClassName, system)
		var reading Reading
		produced := false
		if len(candidates) > 0 {
			parsedRoot := candidates[0].Root
			negative := false
			if strings.HasPrefix(parsedRoot, "-") && utility.SupportsNegative {
				parsedRoot = parsedRoot[1:]
				negative = true
			}
			if parsedRoot == testCase.Root {
				reading, produced = utility.Reading(testCase.Root, &candidates[0], system.Theme(), negative)
			}
		}

		switch {
		case testCase.Reading == nil && !produced:
			bothDeclined++
		case testCase.Reading == nil && produced:
			engineSilent++
			disagreements = append(disagreements, testCase.ClassName+": engine declined, table read "+formatReading(reading))
		case testCase.Reading != nil && !produced:
			goSilent++
			silentNames = append(silentNames, testCase.ClassName)
		default:
			expected := Reading{Order: testCase.Reading.Order, Count: testCase.Reading.Count}
			if readingsEqual(expected, reading) {
				agreed++
				continue
			}
			disagreements = append(disagreements, testCase.ClassName+": engine "+formatReading(expected)+", table "+formatReading(reading))
		}
	}

	sort.Strings(disagreements)
	sort.Strings(silentNames)

	// Every remaining silence must be a class the static table answers, and that is asserted rather
	// than noted. `cursor-auto` and `contain-none` are not entries in their root's `staticValues`
	// map; upstream registers them as separate `staticUtility` calls, so the functional path is
	// right to decline and M1's table is what answers them. A silence with no such explanation is a
	// gap in this table wearing the same shape.
	for _, className := range silentNames {
		if _, found := FrameworkStaticDeclarations[className]; !found {
			t.Errorf("%s: the engine reads it, this table declines, and no static registration covers it, so it is an unexplained gap", className)
		}
	}
	if len(silentNames) > 0 {
		t.Logf("table-silent classes, all covered by the static table: %v", silentNames)
	}
	t.Logf("wave 1: %d roots, %d cases, agreed %d, both-declined %d, table-silent %d, engine-silent %d, disagreed %d",
		fixture.RootCount, fixture.CaseCount, agreed, bothDeclined, goSilent, engineSilent, len(disagreements))

	// The population assertions, stated before the disagreements so a run that measured almost
	// nothing fails on the denominator rather than passing on the rate.
	if agreed < 150 {
		t.Errorf("only %d cases agreed of %d answered by the engine; a table that stopped answering scores perfectly on any comparison that counts only disagreements", agreed, fixture.Answered)
	}
	if bothDeclined < 50 {
		t.Errorf("only %d cases were declined by both sides; the rejection branches are under-exercised", bothDeclined)
	}

	for _, disagreement := range disagreements {
		t.Error(disagreement)
	}
}

// TestFrameworkFunctionalUtilitiesCoverTheUnprobableRoots is why this wave matters beyond its size.
//
// `gen_tailwind_collapse` reports eight roots it cannot reach with any probe value, so they are in
// KnownRoots and absent from every property table. Seven of the eight are answered by this table.
// Asserted by name, because the point is which roots stopped being unanswerable rather than how many.
//
// The four this wave adds are the reason `RequiresValue` exists: `bg-size`, `bg-position`,
// `mask-size` and `mask-position` all spell their handler as `handle(value) { if (!value) return }`,
// which is why no probe value reached them and why they were invisible to a generator that only asks
// what a root reads.
func TestFrameworkFunctionalUtilitiesCoverTheUnprobableRoots(t *testing.T) {
	// Seven of the eight. `mask-radial` is the exception and stays uncovered: it emits four
	// declarations behind `--tw-*` custom properties, so it belongs to wave 2b rather than here, and
	// naming it in this list would claim coverage this table does not have.
	for _, root := range []string{
		"align", "font-features", "mask-radial-at",
		"bg-size", "bg-position", "mask-size", "mask-position",
	} {
		utility, known := FrameworkFunctionalUtilities[root]
		if !known {
			t.Errorf("%s is one of the roots no probe value reaches and it is not in the table", root)
			continue
		}
		if utility.Property == "" {
			t.Errorf("%s is in the table with no property, so it answers nothing", root)
		}
	}
}

// TestFrameworkFunctionalUtilitiesShareOneBarePredicate pins the sharing the table exists to make visible.
//
// Twelve roots use the positive-integer handler. A closure per row would have made them twelve
// lookalike functions and a correction could reach eleven and miss the twelfth, which is the defect
// class this whole port keeps finding.
func TestFrameworkFunctionalUtilitiesShareOneBarePredicate(t *testing.T) {
	shared := 0
	for _, utility := range FrameworkFunctionalUtilities {
		if utility.BareValue == BareValuePositiveInteger {
			shared++
		}
	}
	if shared < 10 {
		t.Errorf("%d roots reference the shared positive-integer predicate; upstream has twelve in this wave, so the table may have inlined some", shared)
	}
}

func formatReading(reading Reading) string {
	raw, _ := json.Marshal(reading.Order)
	return string(raw) + "#" + itoa(reading.Count)
}

func loadWave1Fixture(t *testing.T, name string) wave1Fixture {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	var fixture wave1Fixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	if fixture.CaseCount == 0 || fixture.Answered == 0 {
		t.Fatalf("%s carries %d cases and %d answered; a comparison over it would pass by comparing nothing", name, fixture.CaseCount, fixture.Answered)
	}
	return fixture
}

func loadWave1DesignSystem(t *testing.T) *LoadedDesignSystem {
	t.Helper()
	system, err := LoadDesignSystem(LoadOptions{
		EntryPoint:          "/Users/kirkouimet/Projects/ahra/app/_theme/styles/theme.css",
		TailwindPackageRoot: "/Users/kirkouimet/Projects/ahra/node_modules/tailwindcss",
	})
	if err != nil {
		t.Skipf("the ahra design system is not available here: %v", err)
	}
	return system
}

// TestFrameworkStaticValuesDeclareTheirRootsProperty records what the static lookup can and cannot show.
//
// The static emitter looks a static value's property up rather than inheriting the root's. That the
// lookup runs at all is now covered: removing it from `Emit` fails
// TestStaticValuesEmitTheirOwnProperty, because the ordinary handle body then answers `order-first`
// with the resolved value instead of the stored -9999. What no test in this wave can show is the
// lookup mattering, since across all 16 roots here that declare staticValues no entry names a
// property different from its root.
//
// So the divergence is what this test measures, and it measures it because unreachable and untested
// look identical from a green run.
//
// If this test ever fails, a root in this wave gained a diverging static value and the property half
// of the lookup became load-bearing here. That is the moment to add a mutation covering it, not to
// loosen this.
func TestFrameworkStaticValuesDeclareTheirRootsProperty(t *testing.T) {
	withStatics, diverging := 0, 0
	for root, utility := range FrameworkFunctionalUtilities {
		if len(utility.StaticValues) == 0 {
			continue
		}
		withStatics++
		for _, static := range utility.StaticValues {
			if static.Property != utility.Property {
				diverging++
				t.Logf("%s: static %q declares %q where the root declares %q", root, static.Name, static.Property, utility.Property)
			}
		}
	}

	if withStatics == 0 {
		t.Fatal("no wave-1 root declares staticValues, so this assertion measured nothing")
	}
	if diverging > 0 {
		t.Errorf("%d static values now declare a property their root does not; the property lookup in Reading is load-bearing in this wave and needs a mutation covering it", diverging)
	}
	t.Logf("%d roots declare staticValues, %d diverging properties", withStatics, diverging)
}

// TestFrameworkBareValueSuffixIsUnobservableInAReading records why a mutation of it survives.
//
// `delay-150` resolves to `150ms` and `delay-1` resolves to `1ms`, and both read `[352]#1`. The
// reading is a property position and a declaration count, and `getPropertySort` never reads a value,
// so removing the suffix entirely changes no reading anywhere and the wave-1 comparison passes.
//
// That makes the suffix real code with no coverage from the fixture, which is the shape that quietly
// rots. So it is asserted directly on the resolved value rather than through a reading, and the three
// suffixes upstream uses are named: `ms` for delay, `px` for outline-offset, `%` for zoom and opacity.
//
// The value matters even though the reading does not: it is what an arbitrary-value data-type
// inference would read downstream, and it is what the engine emits.
func TestFrameworkBareValueSuffixIsUnobservableInAReading(t *testing.T) {
	theme := NewTheme()
	cases := []struct {
		root     string
		bare     string
		expected string
	}{
		{"delay", "150", "150ms"},
		{"outline-offset", "2", "2px"},
		{"zoom", "50", "50%"},
		{"opacity", "25", "25%"},
	}

	for _, testCase := range cases {
		utility, known := FrameworkFunctionalUtilities[testCase.root]
		if !known {
			t.Errorf("%s is not in the table", testCase.root)
			continue
		}
		candidate := ParsedCandidate{
			Kind:  ParsedCandidateKindFunctional,
			Root:  testCase.root,
			Value: &ParsedValue{Kind: ParsedValueKindNamed, Value: testCase.bare},
		}
		resolved, produced := ResolveFunctionalUtilityValue(&candidate, utility.Description(), theme, false)
		if !produced {
			t.Errorf("%s-%s resolved to nothing", testCase.root, testCase.bare)
			continue
		}
		if resolved.Value != testCase.expected {
			t.Errorf("%s-%s resolved to %q, the engine resolves it to %q", testCase.root, testCase.bare, resolved.Value, testCase.expected)
		}
	}

	// The reading is deliberately shown to be blind to all of it, so the next reader does not add a
	// reading-based assertion here and believe it covers the suffix.
	utility := FrameworkFunctionalUtilities["delay"]
	long := ParsedCandidate{Kind: ParsedCandidateKindFunctional, Root: "delay", Value: &ParsedValue{Kind: ParsedValueKindNamed, Value: "150"}}
	short := ParsedCandidate{Kind: ParsedCandidateKindFunctional, Root: "delay", Value: &ParsedValue{Kind: ParsedValueKindNamed, Value: "1"}}
	longReading, _ := utility.Reading("delay", &long, theme, false)
	shortReading, _ := utility.Reading("delay", &short, theme, false)
	if !readingsEqual(longReading, shortReading) {
		t.Errorf("delay-150 and delay-1 read differently (%v#%d and %v#%d); if that is now true, a reading-based test can cover the suffix",
			longReading.Order, longReading.Count, shortReading.Order, shortReading.Count)
	}
}
