// Code generated by tools/gen_tailwind_framework_variants. DO NOT EDIT.
//
// Regenerate with:
//
//	go run ./tools/gen_tailwind_framework_variants -package-root <tailwindcss package>
//
// Source: Tailwind 4.3.3, read from the engine's own variant registry.
// 88 registrations over 82 distinct order numbers, 2 of which are shared by more than one root,
// and 4 of which carry a comparison function.
//
// Verified repository-invariant before being checked in, with the instrument CollapseFamilies was
// verified by: four independent generations — two installed tailwindcss packages, and each of the
// two corpus repositories' own theme.css loaded through its own install — produced identical names,
// orders and kinds. Zero difference. Both repositories declare `@custom-variant dark` and it does
// not appear as a difference, because Variants.set assigns kind onto an existing record and never
// touches order: redefining a framework variant changes the selector it emits without moving where
// it sorts. A repository's @custom-variant under a NEW name appends a position and stays
// live-loaded rather than being baked in here.
//
// Keyed on registration roots rather than on composed prefixes. The other variant table in this
// package, VariantOrder in property_order_table.go, is keyed on shapes like `group-hover:`, which
// have no registration of their own; the two sitting side by side is the difference being argued.

package tailwind

// FrameworkVariantRegistration is one variant the framework registers, with the order number the
// engine assigned it.
//
// Order is carried rather than re-derived, and that is the whole reason this type exists alongside
// FrameworkVariant. Replaying these through Register in sequence would give every root its own
// number, and the engine shares numbers: six roots hold one order in a default build. A shared
// order is where a comparison function gets to speak, and comparison is how the five breakpoints
// order by their resolved widths instead of alphabetically.
type FrameworkVariantRegistration struct {
	// Name is the registered root, as written before the colon: `hover`, `group`, `@max`.
	Name string
	// Order is the registration number Variants.set assigned. Shared across every root registered
	// inside one Variants.group.
	Order int
	// Kind is the registration kind, which decides which branch of Compare applies.
	Kind ParsedVariantKind
}

// FrameworkVariantComparisonGroup is one order number whose members are separated by a comparison
// function rather than by registration.
//
// The function itself cannot be generated: upstream's is a closure over the design system's theme,
// and reading a hardcoded breakpoint scale here would be the per-repository bug this port exists to
// remove. Measured on the engine, redefining `--breakpoint-sm` to `200rem` moves `sm` from dense
// index 0 to index 4. So what is generated is the order number and the direction, and
// LoadDesignSystem attaches CompareBreakpoints over the live theme.
//
// Ascending is probed against the engine rather than read from variants.ts, so a release that
// flipped one produces a diff here instead of silently reversing every class in the group.
type FrameworkVariantComparisonGroup struct {
	// Order is the shared registration number the comparison is keyed on.
	Order int
	// Ascending is the direction: the breakpoints and the container queries ascend, `max` and
	// `@max` descend.
	Ascending bool
	// Members are the roots holding this order, for diagnostics and for the test that asserts the
	// generated groups still match the generated registrations.
	Members []string
}

// FrameworkVariantRegistrations is every variant the installed Tailwind registers, in registration
// order.
//
// In order rather than sorted by name, so a reader sees the sequence the engine performed and an
// upgrade's diff shows where a new variant was inserted. Registrations() sorts by name when a
// caller needs that.
var FrameworkVariantRegistrations = []FrameworkVariantRegistration{
	{Name: "*", Order: 1, Kind: ParsedVariantKindStatic},
	{Name: "**", Order: 2, Kind: ParsedVariantKindStatic},
	{Name: "not", Order: 3, Kind: ParsedVariantKindCompound},
	{Name: "group", Order: 4, Kind: ParsedVariantKindCompound},
	{Name: "peer", Order: 5, Kind: ParsedVariantKindCompound},
	{Name: "first-letter", Order: 6, Kind: ParsedVariantKindStatic},
	{Name: "first-line", Order: 7, Kind: ParsedVariantKindStatic},
	{Name: "marker", Order: 8, Kind: ParsedVariantKindStatic},
	{Name: "selection", Order: 9, Kind: ParsedVariantKindStatic},
	{Name: "file", Order: 10, Kind: ParsedVariantKindStatic},
	{Name: "placeholder", Order: 11, Kind: ParsedVariantKindStatic},
	{Name: "backdrop", Order: 12, Kind: ParsedVariantKindStatic},
	{Name: "details-content", Order: 13, Kind: ParsedVariantKindStatic},
	{Name: "before", Order: 14, Kind: ParsedVariantKindStatic},
	{Name: "after", Order: 15, Kind: ParsedVariantKindStatic},
	{Name: "first", Order: 16, Kind: ParsedVariantKindStatic},
	{Name: "last", Order: 17, Kind: ParsedVariantKindStatic},
	{Name: "only", Order: 18, Kind: ParsedVariantKindStatic},
	{Name: "odd", Order: 19, Kind: ParsedVariantKindStatic},
	{Name: "even", Order: 20, Kind: ParsedVariantKindStatic},
	{Name: "first-of-type", Order: 21, Kind: ParsedVariantKindStatic},
	{Name: "last-of-type", Order: 22, Kind: ParsedVariantKindStatic},
	{Name: "only-of-type", Order: 23, Kind: ParsedVariantKindStatic},
	{Name: "visited", Order: 24, Kind: ParsedVariantKindStatic},
	{Name: "target", Order: 25, Kind: ParsedVariantKindStatic},
	{Name: "open", Order: 26, Kind: ParsedVariantKindStatic},
	{Name: "default", Order: 27, Kind: ParsedVariantKindStatic},
	{Name: "checked", Order: 28, Kind: ParsedVariantKindStatic},
	{Name: "indeterminate", Order: 29, Kind: ParsedVariantKindStatic},
	{Name: "placeholder-shown", Order: 30, Kind: ParsedVariantKindStatic},
	{Name: "autofill", Order: 31, Kind: ParsedVariantKindStatic},
	{Name: "optional", Order: 32, Kind: ParsedVariantKindStatic},
	{Name: "required", Order: 33, Kind: ParsedVariantKindStatic},
	{Name: "valid", Order: 34, Kind: ParsedVariantKindStatic},
	{Name: "invalid", Order: 35, Kind: ParsedVariantKindStatic},
	{Name: "user-valid", Order: 36, Kind: ParsedVariantKindStatic},
	{Name: "user-invalid", Order: 37, Kind: ParsedVariantKindStatic},
	{Name: "in-range", Order: 38, Kind: ParsedVariantKindStatic},
	{Name: "out-of-range", Order: 39, Kind: ParsedVariantKindStatic},
	{Name: "read-only", Order: 40, Kind: ParsedVariantKindStatic},
	{Name: "empty", Order: 41, Kind: ParsedVariantKindStatic},
	{Name: "focus-within", Order: 42, Kind: ParsedVariantKindStatic},
	{Name: "hover", Order: 43, Kind: ParsedVariantKindStatic},
	{Name: "focus", Order: 44, Kind: ParsedVariantKindStatic},
	{Name: "focus-visible", Order: 45, Kind: ParsedVariantKindStatic},
	{Name: "active", Order: 46, Kind: ParsedVariantKindStatic},
	{Name: "enabled", Order: 47, Kind: ParsedVariantKindStatic},
	{Name: "disabled", Order: 48, Kind: ParsedVariantKindStatic},
	{Name: "inert", Order: 49, Kind: ParsedVariantKindStatic},
	{Name: "in", Order: 50, Kind: ParsedVariantKindCompound},
	{Name: "has", Order: 51, Kind: ParsedVariantKindCompound},
	{Name: "aria", Order: 52, Kind: ParsedVariantKindFunctional},
	{Name: "data", Order: 53, Kind: ParsedVariantKindFunctional},
	{Name: "nth", Order: 54, Kind: ParsedVariantKindFunctional},
	{Name: "nth-last", Order: 55, Kind: ParsedVariantKindFunctional},
	{Name: "nth-of-type", Order: 56, Kind: ParsedVariantKindFunctional},
	{Name: "nth-last-of-type", Order: 57, Kind: ParsedVariantKindFunctional},
	{Name: "supports", Order: 58, Kind: ParsedVariantKindFunctional},
	{Name: "motion-safe", Order: 59, Kind: ParsedVariantKindStatic},
	{Name: "motion-reduce", Order: 60, Kind: ParsedVariantKindStatic},
	{Name: "contrast-more", Order: 61, Kind: ParsedVariantKindStatic},
	{Name: "contrast-less", Order: 62, Kind: ParsedVariantKindStatic},
	{Name: "max", Order: 63, Kind: ParsedVariantKindFunctional},
	{Name: "2xl", Order: 64, Kind: ParsedVariantKindStatic},
	{Name: "lg", Order: 64, Kind: ParsedVariantKindStatic},
	{Name: "md", Order: 64, Kind: ParsedVariantKindStatic},
	{Name: "min", Order: 64, Kind: ParsedVariantKindFunctional},
	{Name: "sm", Order: 64, Kind: ParsedVariantKindStatic},
	{Name: "xl", Order: 64, Kind: ParsedVariantKindStatic},
	{Name: "@max", Order: 65, Kind: ParsedVariantKindFunctional},
	{Name: "@", Order: 66, Kind: ParsedVariantKindFunctional},
	{Name: "@min", Order: 66, Kind: ParsedVariantKindFunctional},
	{Name: "portrait", Order: 67, Kind: ParsedVariantKindStatic},
	{Name: "landscape", Order: 68, Kind: ParsedVariantKindStatic},
	{Name: "ltr", Order: 69, Kind: ParsedVariantKindStatic},
	{Name: "rtl", Order: 70, Kind: ParsedVariantKindStatic},
	{Name: "dark", Order: 71, Kind: ParsedVariantKindStatic},
	{Name: "starting", Order: 72, Kind: ParsedVariantKindStatic},
	{Name: "print", Order: 73, Kind: ParsedVariantKindStatic},
	{Name: "forced-colors", Order: 74, Kind: ParsedVariantKindStatic},
	{Name: "inverted-colors", Order: 75, Kind: ParsedVariantKindStatic},
	{Name: "pointer-none", Order: 76, Kind: ParsedVariantKindStatic},
	{Name: "pointer-coarse", Order: 77, Kind: ParsedVariantKindStatic},
	{Name: "pointer-fine", Order: 78, Kind: ParsedVariantKindStatic},
	{Name: "any-pointer-none", Order: 79, Kind: ParsedVariantKindStatic},
	{Name: "any-pointer-coarse", Order: 80, Kind: ParsedVariantKindStatic},
	{Name: "any-pointer-fine", Order: 81, Kind: ParsedVariantKindStatic},
	{Name: "noscript", Order: 82, Kind: ParsedVariantKindStatic},
}

// FrameworkVariantComparisonGroups is every order number that carries a comparison function.
//
// All four are breakpoint comparisons in a default build. Without them the six roots sharing order
// 64 fall through to a root-name comparison, and `2xl` sorts before `sm` alphabetically, which
// reorders every responsive class in the tree.
var FrameworkVariantComparisonGroups = []FrameworkVariantComparisonGroup{
	{Order: 63, Ascending: false, Members: []string{"max"}},
	{Order: 64, Ascending: true, Members: []string{"sm", "md", "lg", "xl", "2xl", "min"}},
	{Order: 65, Ascending: false, Members: []string{"@max"}},
	{Order: 66, Ascending: true, Members: []string{"@", "@min"}},
}
