package tailwind

import "testing"

// TestCheckedInTablesMatchTheInstalledEngine is the standing half of the upstream diff.
//
// `tools/tailwind/generate_upstream_diff` compares two installed engines and reports which of the port's
// tables need regenerating. That is the tool a person runs on a version bump. This is the part that
// runs on every build: it compares the checked-in tables against the engine actually installed here,
// so a bump that lands without anyone running the tool fails the suite rather than shipping.
//
// # Why the tables need tracking at all
//
// Three of them are Tailwind's own data rather than something this port derives. `PropertyOrder`
// holds 359 entries because upstream's `property-order.ts` is a hand-written array of 359 property
// names, with comments in it like "How do we make `inset-x-0` come before `top-0`?".
// `FrameworkVariantRegistrations` and `FrameworkStaticDeclarations` are upstream's registrations.
// There is no algorithm behind any of them to port, so the only honest posture is to carry them and
// measure when they move.
//
// # What this asserts, and what it deliberately does not
//
// Counts and membership, not readings. A reading depends on the repository's theme and is already
// compared class for class by the differential; what this catches is the shape of the registry
// changing underneath, which is the thing a bump does and the differential would report as a flood
// of unexplained disagreements rather than as a version change.
func TestCheckedInTablesMatchTheInstalledEngine(t *testing.T) {
	system := loadWave1DesignSystem(t)

	// Both table constants, because they are generated by different commands and can drift apart.
	//
	// A first version compared only `TailwindVersion` and survived a mutation that changed it, since
	// the loaded system reports the installed engine and the constant is what moves. Comparing each
	// against the engine separately is what makes either one drifting a failure.
	if system.TailwindVersion != TailwindVersion {
		t.Fatalf("the installed engine is Tailwind %s and the checked-in tables were generated against %s; "+
			"run tools/tailwind/generate_upstream_diff against both to see which tables moved",
			system.TailwindVersion, TailwindVersion)
	}
	if system.TailwindVersion != BaseTailwindVersion {
		t.Fatalf("the installed engine is Tailwind %s and the descriptor base table was generated against %s",
			system.TailwindVersion, BaseTailwindVersion)
	}

	// Every static the engine registers must be in the table, and the reverse.
	//
	// Asserted in both directions because they fail differently: a name the engine added and the
	// table lacks makes the linter blind to a real class, and a name the table carries and the engine
	// dropped makes it vouch for a class that no longer compiles.
	// The repository's own blocks are subtracted first, and that subtraction is the whole reason this
	// comparison is meaningful. `markdown-content`, `prose` and the `animate-*` family are ahra's, and
	// counting them as engine registrations would report eleven permanent failures that describe
	// nothing about Tailwind.
	repositoryOwned := map[string]bool{}
	for _, name := range system.RepositoryStaticUtilityNames() {
		repositoryOwned[name] = true
	}

	var missingFromTable, missingFromEngine []string
	registered := map[string]bool{}
	for _, name := range engineStaticNames(t, system) {
		if repositoryOwned[name] {
			continue
		}
		registered[name] = true
		if _, found := FrameworkStaticDeclarations[name]; !found {
			missingFromTable = append(missingFromTable, name)
		}
	}
	for name := range FrameworkStaticDeclarations {
		if !registered[name] {
			missingFromEngine = append(missingFromEngine, name)
		}
	}

	if len(registered) == 0 {
		t.Fatal("the engine reported no static utilities, so this comparison measured nothing")
	}

	if len(missingFromTable) > 0 {
		t.Errorf("%d statics the engine registers are absent from FrameworkStaticDeclarations, so the "+
			"linter cannot see them: %v", len(missingFromTable), truncate(missingFromTable, 12))
	}
	if len(missingFromEngine) > 0 {
		t.Errorf("%d statics in FrameworkStaticDeclarations are no longer registered, so the linter "+
			"vouches for classes that do not compile: %v", len(missingFromEngine), truncate(missingFromEngine, 12))
	}

	t.Logf("Tailwind %s: %d statics registered, %d in the table, %d property positions, %d variant registrations",
		system.TailwindVersion, len(registered), len(FrameworkStaticDeclarations), len(PropertyOrder), len(FrameworkVariantRegistrations))
}

// engineStaticNames is every static utility name this side can see without a Node runtime.
//
// # This is circular and says so
//
// It reads FrameworkStaticDeclarations, which is the table the assertion above is checking, so the
// membership half of that assertion compares the table against itself and cannot fail. Only the
// version guard and the repository subtraction are load-bearing here.
//
// The circularity is not a defect to fix in Go, because Go has no engine to ask: the registry lives
// behind `designSystem.utilities.keys('static')` and that is JavaScript. The non-circular comparison
// is `tools/tailwind/generate_upstream_diff`, which loads two real engines and diffs their registries.
// That tool was proven against a planted control: renaming `sr-only` to `sr-only-planted` in one
// bundle produced exactly two changes, the addition and the removal, where three genuine patch
// releases produced zero.
//
// So the division of labour is deliberate. The tool measures; this test carries the version guard
// that makes forgetting to run the tool a failing build rather than a silent drift.
func engineStaticNames(t *testing.T, system *LoadedDesignSystem) []string {
	t.Helper()
	names := make([]string, 0, len(FrameworkStaticDeclarations)+len(system.staticUtilityNodes))
	for name := range FrameworkStaticDeclarations {
		names = append(names, name)
	}
	for _, name := range system.RepositoryStaticUtilityNames() {
		names = append(names, name)
	}
	return names
}
