package typescript

// noShadowFiresCases holds every invalid case in upstream corpus that carries no options key.
//
// Generated by walking the TypeScript AST of the two corpus files under
// tests/rules/no-shadow/ and taking each case code literal exactly as the parser read it, so
// no escape sequence was retyped on the way in. The names carry the upstream file and line.
var noShadowFiresCases = []struct {
	name     string
	source   string
	messages []string
}{
	{
		name:     "#1 no-shadow L9",
		source:   "\ntype T = 1;\n{\n  type T = 2;\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#2 no-shadow L31",
		source:   "\ntype T = 1;\nfunction foo<T>(arg: T) {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#3 no-shadow L51",
		source:   "\nfunction foo<T>() {\n  return function <T>() {};\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#4 no-shadow L72",
		source:   "\ntype T = string;\nfunction foo<T extends (arg: any) => void>(arg: T) {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#5 no-shadow L92",
		source:   "\nenum A {\n  A,\n  B,\n}\n      ",
		messages: []string{"noEnumShadow"},
	},
	{
		name:     "#6 no-shadow L114",
		source:   "\nenum A {\n  B = 2,\n}\n\nenum A {\n  A = 1,\n}\n      ",
		messages: []string{"noEnumShadow"},
	},
	{
		name:     "#7 no-shadow L491",
		source:   "\ninterface Foo {}\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#8 no-shadow L516",
		source:   "\nimport type { Foo } from 'bar';\n\ndeclare module 'baz' {\n  export interface Foo {\n    x: string;\n  }\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#9 no-shadow L541",
		source:   "\nimport { type Foo } from 'bar';\n\ndeclare module 'baz' {\n  export interface Foo {\n    x: string;\n  }\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#43 no-shadow-eslint L15",
		source:   "\nfunction a(x) {\n  var b = function c() {\n    var x = 'foo';\n  };\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#44 no-shadow-eslint L38",
		source:   "\nvar a = x => {\n  var b = () => {\n    var x = 'foo';\n  };\n};\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#45 no-shadow-eslint L62",
		source:   "\nfunction a(x) {\n  var b = function () {\n    var x = 'foo';\n  };\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#46 no-shadow-eslint L85",
		source:   "\nvar x = 1;\nfunction a(x) {\n  return ++x;\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#47 no-shadow-eslint L107",
		source:   "\nvar a = 3;\nfunction b() {\n  var a = 10;\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#48 no-shadow-eslint L129",
		source:   "\nvar a = 3;\nfunction b() {\n  var a = 10;\n}\nsetTimeout(function () {\n  b();\n}, 0);\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#49 no-shadow-eslint L154",
		source:   "\nvar a = 3;\nfunction b() {\n  var a = 10;\n  var b = 0;\n}\nsetTimeout(function () {\n  b();\n}, 0);\n      ",
		messages: []string{"noShadow", "noShadow"},
	},
	{
		name:     "#50 no-shadow-eslint L192",
		source:   "\nvar x = 1;\n{\n  let x = 2;\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#51 no-shadow-eslint L215",
		source:   "\nlet x = 1;\n{\n  const x = 2;\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#52 no-shadow-eslint L238",
		source:   "\n{\n  let a;\n}\nfunction a() {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#53 no-shadow-eslint L261",
		source:   "\n{\n  const a = 0;\n}\nfunction a() {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#54 no-shadow-eslint L284",
		source:   "\nfunction foo() {\n  let a;\n}\nfunction a() {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#55 no-shadow-eslint L307",
		source:   "\nfunction foo() {\n  var a;\n}\nfunction a() {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#56 no-shadow-eslint L330",
		source:   "\nfunction foo(a) {}\nfunction a() {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#57 no-shadow-eslint L705",
		source:   "\n(function a() {\n  function a() {}\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#58 no-shadow-eslint L726",
		source:   "\n(function a() {\n  class a {}\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#59 no-shadow-eslint L748",
		source:   "\n(function a() {\n  (function a() {});\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#60 no-shadow-eslint L769",
		source:   "\n(function a() {\n  (class a {});\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#61 no-shadow-eslint L791",
		source:   "\n(function () {\n  var a = function (a) {};\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#62 no-shadow-eslint L812",
		source:   "\n(function () {\n  var a = function () {\n    function a() {}\n  };\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#63 no-shadow-eslint L835",
		source:   "\n(function () {\n  var a = function () {\n    class a {}\n  };\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#64 no-shadow-eslint L859",
		source:   "\n(function () {\n  var a = function () {\n    (function a() {});\n  };\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#65 no-shadow-eslint L882",
		source:   "\n(function () {\n  var a = function () {\n    (class a {});\n  };\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#66 no-shadow-eslint L906",
		source:   "\n(function () {\n  var a = class {\n    constructor() {\n      class a {}\n    }\n  };\n})();\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#67 no-shadow-eslint L932",
		source:   "\nclass A {\n  constructor() {\n    var A;\n  }\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#68 no-shadow-eslint L956",
		source:   "\n(function a() {\n  function a() {\n    function a() {}\n  }\n})();\n      ",
		messages: []string{"noShadow", "noShadow"},
	},
	{
		name:     "#69 no-shadow-eslint L1107",
		source:   "\nfunction foo(cb) {\n  (function (cb) {\n    cb(42);\n  })(cb);\n}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#70 no-shadow-eslint L1130",
		source:   "\nconst FooBarComponent = memo(function FooBarComponent() {});\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#71 no-shadow-eslint L1149",
		source:   "\nconst FooBarComponent = memo(class FooBarComponent {});\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#72 no-shadow-eslint L1189",
		source:   "\nfunction foo(a = wrap(function a() {})) {}\n      ",
		messages: []string{"noShadow"},
	},
	{
		name:     "#73 no-shadow-eslint L1209",
		source:   "\nvar a = 1;\nvar b = function a() {};\n      ",
		messages: []string{"noShadow"},
	},
}

// noShadowSilentCases holds every valid case in the same corpus that carries no options key.
//
// These are the false positives upstream already thought about, and they are the half of the
// corpus that catches a port which reports too much.
var noShadowSilentCases = []struct {
	name   string
	source string
}{
	{
		name:   "#10 no-shadow L1097",
		source: "function foo<T = (arg: any) => any>(arg: T) {}",
	},
	{
		name:   "#11 no-shadow L1098",
		source: "function foo<T = ([arg]: [any]) => any>(arg: T) {}",
	},
	{
		name:   "#12 no-shadow L1099",
		source: "function foo<T = ({ args }: { args: any }) => any>(arg: T) {}",
	},
	{
		name:   "#13 no-shadow L1100",
		source: "function foo<T = (...args: any[]) => any>(fn: T, args: any[]) {}",
	},
	{
		name:   "#14 no-shadow L1101",
		source: "function foo<T extends (...args: any[]) => any>(fn: T, args: any[]) {}",
	},
	{
		name:   "#15 no-shadow L1102",
		source: "function foo<T extends (...args: any[]) => any>(fn: T, ...args: any[]) {}",
	},
	{
		name:   "#16 no-shadow L1103",
		source: "function foo<T extends ([args]: any[]) => any>(fn: T, args: any[]) {}",
	},
	{
		name:   "#17 no-shadow L1104",
		source: "function foo<T extends ([...args]: any[]) => any>(fn: T, args: any[]) {}",
	},
	{
		name:   "#18 no-shadow L1105",
		source: "function foo<T extends ({ args }: { args: any }) => any>(fn: T, args: any) {}",
	},
	{
		name:   "#19 no-shadow L1106",
		source: "\nfunction foo<T extends (id: string, ...args: any[]) => any>(\n  fn: T,\n  ...args: any[]\n) {}\n    ",
	},
	{
		name:   "#20 no-shadow L1112",
		source: "\ntype Args = 1;\nfunction foo<T extends (Args: any) => void>(arg: T) {}\n    ",
	},
	{
		name:   "#21 no-shadow L1117",
		source: "\nexport type ArrayInput<Func> = Func extends (arg0: Array<infer T>) => any\n  ? T[]\n  : Func extends (...args: infer T) => any\n    ? T\n    : never;\n    ",
	},
	{
		name:   "#22 no-shadow L1124",
		source: "\nfunction foo() {\n  var Object = 0;\n}\n    ",
	},
	{
		name:   "#23 no-shadow L1130",
		source: "\nfunction test(this: Foo) {\n  function test2(this: Bar) {}\n}\n    ",
	},
	{
		name:   "#24 no-shadow L1136",
		source: "\nclass Foo {\n  prop = 1;\n}\nnamespace Foo {\n  export const v = 2;\n}\n    ",
	},
	{
		name:   "#25 no-shadow L1144",
		source: "\nfunction Foo() {}\nnamespace Foo {\n  export const v = 2;\n}\n    ",
	},
	{
		name:   "#26 no-shadow L1150",
		source: "\nclass Foo {\n  prop = 1;\n}\ninterface Foo {\n  prop2: string;\n}\n    ",
	},
	{
		name:   "#27 no-shadow L1158",
		source: "\nimport type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n    ",
	},
	{
		name:   "#28 no-shadow L1168",
		source: "\nconst x = 1;\ntype x = string;\n    ",
	},
	{
		name:   "#29 no-shadow L1172",
		source: "\nconst x = 1;\n{\n  type x = string;\n}\n    ",
	},
	{
		name:   "#30 no-shadow L1206",
		source: "\nenum Direction {\n  left = 'left',\n  right = 'right',\n}\n    ",
	},
	{
		name:   "#31 no-shadow L1213",
		source: "\nenum A {\n  B,\n  C,\n}\n    ",
	},
	{
		name:   "#32 no-shadow L1219",
		source: "\nenum A {\n  B,\n  C = A.B,\n}\n    ",
	},
	{
		name:   "#33 no-shadow L1334",
		source: "\ndeclare global {\n  const a: string;\n\n  namespace Foo {\n    const a: number;\n  }\n}\nexport {};\n    ",
	},
	{
		name:   "#34 no-shadow L1367",
		source: "\nexport class Wrapper<Wrapped> {\n  private constructor(private readonly wrapped: Wrapped) {}\n\n  unwrap(): Wrapped {\n    return this.wrapped;\n  }\n\n  static create<Wrapped>(wrapped: Wrapped) {\n    return new Wrapper<Wrapped>(wrapped);\n  }\n}\n    ",
	},
	{
		name:   "#35 no-shadow L1380",
		source: "\nfunction makeA() {\n  return class A<T> {\n    constructor(public value: T) {}\n\n    static make<T>(value: T) {\n      return new A<T>(value);\n    }\n  };\n}\n    ",
	},
	{
		name:   "#36 no-shadow L1561",
		source: "const [x = y => y] = [].map(y => y);",
	},
	{
		name:   "#37 no-shadow L1656",
		source: "\nimport type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  export type Foo = string;\n}\n      ",
	},
	{
		name:   "#38 no-shadow L1665",
		source: "\nimport type { Foo } from 'bar';\n\ndeclare module 'bar' {\n  interface Foo {\n    x: string;\n  }\n}\n      ",
	},
	{
		name:   "#39 no-shadow L1676",
		source: "\nimport { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  export type Foo = string;\n}\n      ",
	},
	{
		name:   "#40 no-shadow L1685",
		source: "\nimport { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  export interface Foo {\n    x: string;\n  }\n}\n      ",
	},
	{
		name:   "#41 no-shadow L1696",
		source: "\nimport { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  type Foo = string;\n}\n      ",
	},
	{
		name:   "#42 no-shadow L1705",
		source: "\nimport { type Foo } from 'bar';\n\ndeclare module 'bar' {\n  interface Foo {\n    x: string;\n  }\n}\n      ",
	},
	{
		name:   "#74 no-shadow-eslint L1231",
		source: "\nvar a = 3;\nfunction b(x) {\n  a++;\n  return x + a;\n}\nsetTimeout(function () {\n  b(a);\n}, 0);\n    ",
	},
	{
		name:   "#75 no-shadow-eslint L1241",
		source: "\n(function () {\n  var doSomething = function doSomething() {};\n  doSomething();\n})();\n    ",
	},
	{
		name:   "#76 no-shadow-eslint L1247",
		source: "\nvar a = foo || function a() {};\n      ",
	},
	{
		name:   "#77 no-shadow-eslint L1253",
		source: "\nvar a = foo ? function a() {} : bar;\n      ",
	},
	{
		name:   "#78 no-shadow-eslint L1259",
		source: "\nfunction foo(a = function a() {}) {}\n      ",
	},
	{
		name:   "#79 no-shadow-eslint L1265",
		source: "\nvar arguments;\nfunction bar() {}\n    ",
	},
	{
		name:   "#80 no-shadow-eslint L1269",
		source: "\nvar a = 3;\nvar b = x => {\n  a++;\n  return x + a;\n};\nsetTimeout(() => {\n  b(a);\n}, 0);\n      ",
	},
	{
		name:   "#81 no-shadow-eslint L1282",
		source: "class A {}",
	},
	{
		name:   "#82 no-shadow-eslint L1286",
		source: "\nclass A {\n  constructor() {\n    var a;\n  }\n}\n      ",
	},
	{
		name:   "#83 no-shadow-eslint L1296",
		source: "\n(function () {\n  var A = class A {};\n})();\n      ",
	},
	{
		name:   "#84 no-shadow-eslint L1304",
		source: "\n{\n  var a;\n}\nvar a;\n      ",
	},
	{
		name:   "#85 no-shadow-eslint L1457",
		source: "\n{\n  let a;\n}\nlet a;\n      ",
	},
	{
		name:   "#86 no-shadow-eslint L1466",
		source: "\n{\n  let a;\n}\nvar a;\n      ",
	},
	{
		name:   "#87 no-shadow-eslint L1475",
		source: "\n{\n  const a = 0;\n}\nconst a = 1;\n      ",
	},
	{
		name:   "#88 no-shadow-eslint L1484",
		source: "\n{\n  const a = 0;\n}\nvar a;\n      ",
	},
	{
		name:   "#89 no-shadow-eslint L1493",
		source: "\nfunction foo() {\n  let a;\n}\nlet a;\n      ",
	},
	{
		name:   "#90 no-shadow-eslint L1502",
		source: "\nfunction foo() {\n  let a;\n}\nvar a;\n      ",
	},
	{
		name:   "#91 no-shadow-eslint L1511",
		source: "\nfunction foo() {\n  var a;\n}\nlet a;\n      ",
	},
	{
		name:   "#92 no-shadow-eslint L1520",
		source: "\nfunction foo() {\n  var a;\n}\nvar a;\n      ",
	},
	{
		name:   "#93 no-shadow-eslint L1529",
		source: "\nfunction foo(a) {}\nlet a;\n      ",
	},
	{
		name:   "#94 no-shadow-eslint L1536",
		source: "\nfunction foo(a) {}\nvar a;\n      ",
	},
	{
		name:   "#95 no-shadow-eslint L1543",
		source: "\nfunction foo() {\n  var Object = 0;\n}\n    ",
	},
	{
		name:   "#96 no-shadow-eslint L1548",
		source: "\nfunction foo() {\n  var top = 0;\n}\n      ",
	},
}
