package core

import (
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/system-inc/cohere/internal/lint/testing"
)

/*
 * ESLint 10.8.1's no-useless-backreference, run through the installed rule under @typescript-eslint/parser
 * over its whole test corpus and over the edges this port's own reading raised (#jjfa7qb), with every
 * finding's id, text and byte offset written here as ESLint answered.
 *
 * The corpus rows are the registry's corpus file, verbatim, less the rows ESLint runs under configured
 * globals. The edge rows were written for this port: a RegExp reached through an alias or globalThis,
 * a pattern and flags held in constant, written and destructured bindings, a template and a
 * concatenation, a literal handed to RegExp, a call across lines, and duplicate named groups.
 *
 * One edge is left out because the rule departs from ESLint there: `RegExp(String.raw`...`)`, whose
 * pattern ESLint evaluates by calling String.raw, and which reference.ConstantStringIn declines, as it
 * declines every built-in call. Its own test says what the rule does instead.
 */
func TestNoUselessBackreferenceAgreesWithESLint(t *testing.T) {
	t.Parallel()

	cases := []struct {
		origin string
		code   string
		want   []string
	}{
		{"corpus", "regExp('\\\\1(a)')", []string{}},
		{"corpus", "new Regexp('\\\\1(a)', 'u')", []string{}},
		{"corpus", "RegExp.foo('\\\\1(a)', 'u')", []string{}},
		{"corpus", "new foo.RegExp('\\\\1(a)')", []string{}},
		{"corpus", "RegExp(p)", []string{}},
		{"corpus", "new RegExp(p, 'u')", []string{}},
		{"corpus", "RegExp('\\\\1(a)' + suffix)", []string{}},
		{"corpus", "new RegExp(`${prefix}\\\\1(a)`)", []string{}},
		{"corpus", "let RegExp; new RegExp('\\\\1(a)');", []string{}},
		{"corpus", "function foo() { var RegExp; RegExp('\\\\1(a)', 'u'); }", []string{}},
		{"corpus", "function foo(RegExp) { new RegExp('\\\\1(a)'); }", []string{}},
		{"corpus", "if (foo) { const RegExp = bar; RegExp('\\\\1(a)'); }", []string{}},
		{"corpus", "/* globals RegExp:off */ new RegExp('\\\\1(a)');", []string{"forward new RegExp('\\\\1(a)')@25"}},
		{"corpus", "/(?:)/", []string{}},
		{"corpus", "/(?:a)/", []string{}},
		{"corpus", "new RegExp('')", []string{}},
		{"corpus", "RegExp('(?:a)|(?:b)*')", []string{}},
		{"corpus", "/^ab|[cd].\\n$/", []string{}},
		{"corpus", "/(a)/", []string{}},
		{"corpus", "RegExp('(a)|(b)')", []string{}},
		{"corpus", "new RegExp('\\\\n\\\\d(a)')", []string{}},
		{"corpus", "/\\0(a)/", []string{}},
		{"corpus", "/\\0(a)/u", []string{}},
		{"corpus", "/(?<=(a))(b)(?=(c))/", []string{}},
		{"corpus", "/(?<!(a))(b)(?!(c))/", []string{}},
		{"corpus", "/(?<foo>a)/", []string{}},
		{"corpus", "RegExp('\\\\\\\\1(a)')", []string{}},
		{"corpus", "/\\\\1(a)/", []string{}},
		{"corpus", "/\\1/", []string{}},
		{"corpus", "/^\\1$/", []string{}},
		{"corpus", "/\\2(a)/", []string{}},
		{"corpus", "/\\1(?:a)/", []string{}},
		{"corpus", "/\\1(?=a)/", []string{}},
		{"corpus", "/\\1(?!a)/", []string{}},
		{"corpus", "/^[\\1](a)$/", []string{}},
		{"corpus", "new RegExp('[\\\\1](a)')", []string{}},
		{"corpus", "/\\11(a)/", []string{}},
		{"corpus", "/\\k<foo>(a)/", []string{}},
		{"corpus", "/^(a)\\1\\2$/", []string{}},
		{"corpus", "/(a)\\1/", []string{}},
		{"corpus", "/(a).\\1/", []string{}},
		{"corpus", "RegExp('(a)\\\\1(b)')", []string{}},
		{"corpus", "/(a)(b)\\2(c)/", []string{}},
		{"corpus", "/(?<foo>a)\\k<foo>/", []string{}},
		{"corpus", "new RegExp('(.)\\\\1')", []string{}},
		{"corpus", "RegExp('(a)\\\\1(?:b)')", []string{}},
		{"corpus", "/(a)b\\1/", []string{}},
		{"corpus", "/((a)\\2)/", []string{}},
		{"corpus", "/((a)b\\2c)/", []string{}},
		{"corpus", "/^(?:(a)\\1)$/", []string{}},
		{"corpus", "/^((a)\\2)$/", []string{}},
		{"corpus", "/^(((a)\\3))|b$/", []string{}},
		{"corpus", "/a(?<foo>(.)b\\2)/", []string{}},
		{"corpus", "/(a)?(b)*(\\1)(c)/", []string{}},
		{"corpus", "/(a)?(b)*(\\2)(c)/", []string{}},
		{"corpus", "/(?<=(a))b\\1/", []string{}},
		{"corpus", "/(?<=(?=(a)\\1))b/", []string{}},
		{"corpus", "/(?<!\\1(a))b/", []string{}},
		{"corpus", "/(?<=\\1(a))b/", []string{}},
		{"corpus", "/(?<!\\1.(a))b/", []string{}},
		{"corpus", "/(?<=\\1.(a))b/", []string{}},
		{"corpus", "/(?<=(?:\\1.(a)))b/", []string{}},
		{"corpus", "/(?<!(?:\\1)((a)))b/", []string{}},
		{"corpus", "/(?<!(?:\\2)((a)))b/", []string{}},
		{"corpus", "/(?=(?<=\\1(a)))b/", []string{}},
		{"corpus", "/(?=(?<!\\1(a)))b/", []string{}},
		{"corpus", "/(.)(?<=\\2(a))b/", []string{}},
		{"corpus", "/^(a)\\1|b/", []string{}},
		{"corpus", "/^a|(b)\\1/", []string{}},
		{"corpus", "/^a|(b|c)\\1/", []string{}},
		{"corpus", "/^(a)|(b)\\2/", []string{}},
		{"corpus", "/^(?:(a)|(b)\\2)$/", []string{}},
		{"corpus", "/^a|(?:.|(b)\\1)/", []string{}},
		{"corpus", "/^a|(?:.|(b).(\\1))/", []string{}},
		{"corpus", "/^a|(?:.|(?:(b)).(\\1))/", []string{}},
		{"corpus", "/^a|(?:.|(?:(b)|c).(\\1))/", []string{}},
		{"corpus", "/^a|(?:.|(?:(b)).(\\1|c))/", []string{}},
		{"corpus", "/^a|(?:.|(?:(b)|c).(\\1|d))/", []string{}},
		{"corpus", "/.(?=(b))\\1/", []string{}},
		{"corpus", "/.(?<=(b))\\1/", []string{}},
		{"corpus", "/a(?!(b)\\1)./", []string{}},
		{"corpus", "/a(?<!\\1(b))./", []string{}},
		{"corpus", "/a(?!(b)(\\1))./", []string{}},
		{"corpus", "/a(?!(?:(b)\\1))./", []string{}},
		{"corpus", "/a(?!(?:(b))\\1)./", []string{}},
		{"corpus", "/a(?<!(?:\\1)(b))./", []string{}},
		{"corpus", "/a(?<!(?:(?:\\1)(b)))./", []string{}},
		{"corpus", "/(?<!(a))(b)(?!(c))\\2/", []string{}},
		{"corpus", "/a(?!(b|c)\\1)./", []string{}},
		{"corpus", "RegExp('\\\\1(a)[')", []string{}},
		{"corpus", "new RegExp('\\\\1(a){', 'u')", []string{}},
		{"corpus", "new RegExp('\\\\1(a)\\\\2', 'ug')", []string{}},
		{"corpus", "const flags = 'gus'; RegExp('\\\\1(a){', flags);", []string{}},
		{"corpus", "RegExp('\\\\1(a)\\\\k<foo>', 'u')", []string{}},
		{"corpus", "new RegExp('\\\\k<foo>(?<foo>a)\\\\k<bar>')", []string{}},
		{"corpus", "new RegExp('([[A--B]])\\\\1', 'v')", []string{}},
		{"corpus", "new RegExp('[[]\\\\1](a)', 'v')", []string{}},
		{"corpus", "/((?<foo>bar)\\k<foo>|(?<foo>baz))/", []string{}},
		{"corpus", "/(b)(\\2a)/", []string{"nested /(b)(\\2a)/@0"}},
		{"corpus", "/\\k<foo>(?<foo>bar)/", []string{"forward /\\k<foo>(?<foo>bar)/@0"}},
		{"corpus", "RegExp('(a|bc)|\\\\1')", []string{"disjunctive RegExp('(a|bc)|\\\\1')@0"}},
		{"corpus", "new RegExp('(?!(?<foo>\\\\n))\\\\1')", []string{"intoNegativeLookaround new RegExp('(?!(?<foo>\\\\n))\\\\1')@0"}},
		{"corpus", "/(?<!(a)\\1)b/", []string{"backward /(?<!(a)\\1)b/@0"}},
		{"corpus", "new RegExp('(\\\\1)')", []string{"nested new RegExp('(\\\\1)')@0"}},
		{"corpus", "/^(a\\1)$/", []string{"nested /^(a\\1)$/@0"}},
		{"corpus", "/^((a)\\1)$/", []string{"nested /^((a)\\1)$/@0"}},
		{"corpus", "new RegExp('^(a\\\\1b)$')", []string{"nested new RegExp('^(a\\\\1b)$')@0"}},
		{"corpus", "RegExp('^((\\\\1))$')", []string{"nested RegExp('^((\\\\1))$')@0"}},
		{"corpus", "/((\\2))/", []string{"nested /((\\2))/@0"}},
		{"corpus", "/a(?<foo>(.)b\\1)/", []string{"nested /a(?<foo>(.)b\\1)/@0"}},
		{"corpus", "/a(?<foo>\\k<foo>)b/", []string{"nested /a(?<foo>\\k<foo>)b/@0"}},
		{"corpus", "/^(\\1)*$/", []string{"nested /^(\\1)*$/@0"}},
		{"corpus", "/^(?:a)(?:((?:\\1)))*$/", []string{"nested /^(?:a)(?:((?:\\1)))*$/@0"}},
		{"corpus", "/(?!(\\1))/", []string{"nested /(?!(\\1))/@0"}},
		{"corpus", "/a|(b\\1c)/", []string{"nested /a|(b\\1c)/@0"}},
		{"corpus", "/(a|(\\1))/", []string{"nested /(a|(\\1))/@0"}},
		{"corpus", "/(a|(\\2))/", []string{"nested /(a|(\\2))/@0"}},
		{"corpus", "/(?:a|(\\1))/", []string{"nested /(?:a|(\\1))/@0"}},
		{"corpus", "/(a)?(b)*(\\3)/", []string{"nested /(a)?(b)*(\\3)/@0"}},
		{"corpus", "/(?<=(a\\1))b/", []string{"nested /(?<=(a\\1))b/@0"}},
		{"corpus", "/\\1(a)/", []string{"forward /\\1(a)/@0"}},
		{"corpus", "/\\1.(a)/", []string{"forward /\\1.(a)/@0"}},
		{"corpus", "/(?:\\1)(?:(a))/", []string{"forward /(?:\\1)(?:(a))/@0"}},
		{"corpus", "/(?:\\1)(?:((a)))/", []string{"forward /(?:\\1)(?:((a)))/@0"}},
		{"corpus", "/(?:\\2)(?:((a)))/", []string{"forward /(?:\\2)(?:((a)))/@0"}},
		{"corpus", "/(?:\\1)(?:((?:a)))/", []string{"forward /(?:\\1)(?:((?:a)))/@0"}},
		{"corpus", "/(\\2)(a)/", []string{"forward /(\\2)(a)/@0"}},
		{"corpus", "RegExp('(a)\\\\2(b)')", []string{"forward RegExp('(a)\\\\2(b)')@0"}},
		{"corpus", "/(?:a)(b)\\2(c)/", []string{"forward /(?:a)(b)\\2(c)/@0"}},
		{"corpus", "/\\k<foo>(?<foo>a)/", []string{"forward /\\k<foo>(?<foo>a)/@0"}},
		{"corpus", "/(?:a(b)\\2)(c)/", []string{"forward /(?:a(b)\\2)(c)/@0"}},
		{"corpus", "new RegExp('(a)(b)\\\\3(c)')", []string{"forward new RegExp('(a)(b)\\\\3(c)')@0"}},
		{"corpus", "/\\1(?<=(a))./", []string{"forward /\\1(?<=(a))./@0"}},
		{"corpus", "/\\1(?<!(a))./", []string{"forward /\\1(?<!(a))./@0"}},
		{"corpus", "/(?<=\\1)(?<=(a))/", []string{"forward /(?<=\\1)(?<=(a))/@0"}},
		{"corpus", "/(?<!\\1)(?<!(a))/", []string{"forward /(?<!\\1)(?<!(a))/@0"}},
		{"corpus", "/(?=\\1(a))./", []string{"forward /(?=\\1(a))./@0"}},
		{"corpus", "/(?!\\1(a))./", []string{"forward /(?!\\1(a))./@0"}},
		{"corpus", "/(?<=(a)\\1)b/", []string{"backward /(?<=(a)\\1)b/@0"}},
		{"corpus", "/(?<!.(a).\\1.)b/", []string{"backward /(?<!.(a).\\1.)b/@0"}},
		{"corpus", "/(.)(?<!(b|c)\\2)d/", []string{"backward /(.)(?<!(b|c)\\2)d/@0"}},
		{"corpus", "/(?<=(?:(a)\\1))b/", []string{"backward /(?<=(?:(a)\\1))b/@0"}},
		{"corpus", "/(?<=(?:(a))\\1)b/", []string{"backward /(?<=(?:(a))\\1)b/@0"}},
		{"corpus", "/(?<=(a)(?:\\1))b/", []string{"backward /(?<=(a)(?:\\1))b/@0"}},
		{"corpus", "/(?<!(?:(a))(?:\\1))b/", []string{"backward /(?<!(?:(a))(?:\\1))b/@0"}},
		{"corpus", "/(?<!(?:(a))(?:\\1)|.)b/", []string{"backward /(?<!(?:(a))(?:\\1)|.)b/@0"}},
		{"corpus", "/.(?!(?<!(a)\\1))./", []string{"backward /.(?!(?<!(a)\\1))./@0"}},
		{"corpus", "/.(?=(?<!(a)\\1))./", []string{"backward /.(?=(?<!(a)\\1))./@0"}},
		{"corpus", "/.(?!(?<=(a)\\1))./", []string{"backward /.(?!(?<=(a)\\1))./@0"}},
		{"corpus", "/.(?=(?<=(a)\\1))./", []string{"backward /.(?=(?<=(a)\\1))./@0"}},
		{"corpus", "/(a)|\\1b/", []string{"disjunctive /(a)|\\1b/@0"}},
		{"corpus", "/^(?:(a)|\\1b)$/", []string{"disjunctive /^(?:(a)|\\1b)$/@0"}},
		{"corpus", "/^(?:(a)|b(?:c|\\1))$/", []string{"disjunctive /^(?:(a)|b(?:c|\\1))$/@0"}},
		{"corpus", "/^(?:a|b(?:(c)|\\1))$/", []string{"disjunctive /^(?:a|b(?:(c)|\\1))$/@0"}},
		{"corpus", "/^(?:(a(?!b))|\\1b)+$/", []string{"disjunctive /^(?:(a(?!b))|\\1b)+$/@0"}},
		{"corpus", "/^(?:(?:(a)(?!b))|\\1b)+$/", []string{"disjunctive /^(?:(?:(a)(?!b))|\\1b)+$/@0"}},
		{"corpus", "/^(?:(a(?=a))|\\1b)+$/", []string{"disjunctive /^(?:(a(?=a))|\\1b)+$/@0"}},
		{"corpus", "/^(?:(a)(?=a)|\\1b)+$/", []string{"disjunctive /^(?:(a)(?=a)|\\1b)+$/@0"}},
		{"corpus", "/.(?:a|(b)).|(?:(\\1)|c)./", []string{"disjunctive /.(?:a|(b)).|(?:(\\1)|c)./@0"}},
		{"corpus", "/.(?!(a)|\\1)./", []string{"disjunctive /.(?!(a)|\\1)./@0"}},
		{"corpus", "/.(?<=\\1|(a))./", []string{"disjunctive /.(?<=\\1|(a))./@0"}},
		{"corpus", "/a(?!(b)).\\1/", []string{"intoNegativeLookaround /a(?!(b)).\\1/@0"}},
		{"corpus", "/(?<!(a))b\\1/", []string{"intoNegativeLookaround /(?<!(a))b\\1/@0"}},
		{"corpus", "/(?<!(a))(?:\\1)/", []string{"intoNegativeLookaround /(?<!(a))(?:\\1)/@0"}},
		{"corpus", "/.(?<!a|(b)).\\1/", []string{"intoNegativeLookaround /.(?<!a|(b)).\\1/@0"}},
		{"corpus", "/.(?!(a)).(?!\\1)./", []string{"intoNegativeLookaround /.(?!(a)).(?!\\1)./@0"}},
		{"corpus", "/.(?<!(a)).(?<!\\1)./", []string{"intoNegativeLookaround /.(?<!(a)).(?<!\\1)./@0"}},
		{"corpus", "/.(?=(?!(a))\\1)./", []string{"intoNegativeLookaround /.(?=(?!(a))\\1)./@0"}},
		{"corpus", "/.(?<!\\1(?!(a)))/", []string{"intoNegativeLookaround /.(?<!\\1(?!(a)))/@0"}},
		{"corpus", "/\\1(a)(b)\\2/", []string{"forward /\\1(a)(b)\\2/@0"}},
		{"corpus", "/\\1(a)\\1/", []string{"forward /\\1(a)\\1/@0"}},
		{"corpus", "/\\1(a)\\2(b)/", []string{"forward /\\1(a)\\2(b)/@0", "forward /\\1(a)\\2(b)/@0"}},
		{"corpus", "/\\1.(?<=(a)\\1)/", []string{"forward /\\1.(?<=(a)\\1)/@0", "backward /\\1.(?<=(a)\\1)/@0"}},
		{"corpus", "/(?!\\1(a)).\\1/", []string{"forward /(?!\\1(a)).\\1/@0", "intoNegativeLookaround /(?!\\1(a)).\\1/@0"}},
		{"corpus", "/(a)\\2(b)/; RegExp('(\\\\1)');", []string{"forward /(a)\\2(b)/@0", "nested RegExp('(\\\\1)')@12"}},
		{"corpus", "RegExp('\\\\1(a){', flags);", []string{"forward RegExp('\\\\1(a){', flags)@0"}},
		{"corpus", "const r = RegExp, p = '\\\\1', s = '(a)'; new r(p + s);", []string{"forward new r(p + s)@40"}},
		{"corpus", "new RegExp('\\\\1([[A--B]])', 'v')", []string{"forward new RegExp('\\\\1([[A--B]])', 'v')@0"}},
		{"corpus", "/\\k<foo>((?<foo>bar)|(?<foo>baz))/", []string{"forward /\\k<foo>((?<foo>bar)|(?<foo>baz))/@0"}},
		{"corpus", "/((?<foo>bar)|\\k<foo>(?<foo>baz))/", []string{"forward /((?<foo>bar)|\\k<foo>(?<foo>baz))/@0"}},
		{"corpus", "/\\k<foo>((?<foo>bar)|(?<foo>baz)|(?<foo>qux))/", []string{"forward /\\k<foo>((?<foo>bar)|(?<foo>baz)|(?<foo>qux))/@0"}},
		{"corpus", "/((?<foo>bar)|\\k<foo>(?<foo>baz)|(?<foo>qux))/", []string{"forward /((?<foo>bar)|\\k<foo>(?<foo>baz)|(?<foo>qux))/@0"}},
		{"corpus", "/((?<foo>bar)|\\k<foo>|(?<foo>baz))/", []string{"disjunctive /((?<foo>bar)|\\k<foo>|(?<foo>baz))/@0"}},
		{"corpus", "/((?<foo>bar)|\\k<foo>|(?<foo>baz)|(?<foo>qux))/", []string{"disjunctive /((?<foo>bar)|\\k<foo>|(?<foo>baz)|(?<foo>qux))/@0"}},
		{"corpus", "/((?<foo>bar)|(?<foo>baz\\k<foo>)|(?<foo>qux\\k<foo>))/", []string{"nested /((?<foo>bar)|(?<foo>baz\\k<foo>)|(?<foo>qux\\k<foo>))/@0", "nested /((?<foo>bar)|(?<foo>baz\\k<foo>)|(?<foo>qux\\k<foo>))/@0"}},
		{"corpus", "/(?<=((?<foo>bar)|(?<foo>baz))\\k<foo>)/", []string{"backward /(?<=((?<foo>bar)|(?<foo>baz))\\k<foo>)/@0"}},
		{"corpus", "/((?!(?<foo>bar))|(?!(?<foo>baz)))\\k<foo>/", []string{"intoNegativeLookaround /((?!(?<foo>bar))|(?!(?<foo>baz)))\\k<foo>/@0"}},
		{"edge", "const r = RegExp, p = '\\\\1', s = '(a)'; new r(p + s);", []string{"forward new r(p + s)@40"}},
		{"edge", "const flags = 'gus'; RegExp('\\\\1(a){', flags);", []string{}},
		{"edge", "let f = 'u'; f = ''; RegExp('\\\\1(a){', f);", []string{"forward RegExp('\\\\1(a){', f)@21"}},
		{"edge", "let p = '\\\\1(a)'; RegExp(p);", []string{"forward RegExp(p)@18"}},
		{"edge", "let p = '\\\\1(a)'; p = '(a)'; RegExp(p);", []string{}},
		{"edge", "const {p} = {p: '\\\\1(a)'}; RegExp(p);", []string{}},
		{"edge", "new RegExp(/\\1(a)/);", []string{"forward new RegExp(/\\1(a)/)@0", "forward /\\1(a)/@11"}},
		{"edge", "new RegExp(/\\1(a)/, 'u');", []string{"forward new RegExp(/\\1(a)/, 'u')@0", "forward /\\1(a)/@11"}},
		{"edge", "RegExp(`\\\\1(a)`);", []string{"forward RegExp(`\\\\1(a)`)@0"}},
		{"edge", "RegExp('\\\\1' + '(a)');", []string{"forward RegExp('\\\\1' + '(a)')@0"}},
		{"edge", "globalThis.RegExp('\\\\1(a)');", []string{"forward globalThis.RegExp('\\\\1(a)')@0"}},
		{"edge", "const R = globalThis.RegExp; new R('\\\\1(a)');", []string{"forward new R('\\\\1(a)')@29"}},
		{"edge", "RegExp(\n  '\\\\1(a)'\n);", []string{"forward RegExp(\n  '\\\\1(a)'\n)@0"}},
		{"edge", "function f(RegExp) { return /\\1(a)/; }", []string{"forward /\\1(a)/@28"}},
		{"edge", "const p = '(a)\\\\1'; const q = p + '\\\\2(b)'; RegExp(q);", []string{"forward RegExp(q)@44"}},
		{"edge", "RegExp(foo + '\\\\1(a)');", []string{}},
		{"edge", "RegExp('\\\\1(a)', flags);", []string{"forward RegExp('\\\\1(a)', flags)@0"}},
		{"edge", "/\\1(a)\\k<x>(?<x>b)/;", []string{"forward /\\1(a)\\k<x>(?<x>b)/@0", "forward /\\1(a)\\k<x>(?<x>b)/@0"}},
		{"edge", "/(?<a>x)|(?<a>y)\\k<a>/;", []string{}},
		{"edge", "RegExp(1);", []string{}},
	}

	for index, testCase := range cases {
		result := rule_testing.RunTypedVerbatimWithOptions(t, NoUselessBackreference, "input.ts", testCase.code, nil)
		source := result.SourceFile.Text()
		got := []string{}
		for _, diagnostic := range result.Diagnostics {
			got = append(got, fmt.Sprintf("%s %s@%d", diagnostic.Message.Id,
				source[diagnostic.Range.Pos():diagnostic.Range.End()], diagnostic.Range.Pos()))
		}
		want := append([]string{}, testCase.want...)
		sort.Strings(got)
		sort.Strings(want)
		if strings.Join(got, "\n") != strings.Join(want, "\n") {
			t.Errorf("case %d (%s): %q\n got: %q\nwant: %q", index, testCase.origin, testCase.code, got, want)
		}
	}
}
