package core

import (
	"fmt"
	"sort"
	"strings"
	"testing"

	"github.com/system-inc/cohere/internal/lint/rule"
	"github.com/system-inc/cohere/internal/lint/testing"
)

/*
 * ESLint 10.8.1's prefer-regex-literals, run through the installed rule under @typescript-eslint/parser
 * over its whole test corpus and over the edges the move onto the shelf's ReferenceTracker raised
 * (#jjfa7qb), with every finding's id, text and byte offset written here as ESLint answered.
 *
 * The corpus rows are the registry's corpus file, verbatim, less the rows ESLint runs under configured
 * globals. The edge rows were written for this port: RegExp reached through an alias, a parenthesized
 * callee, globalThis and a pattern destructured from it, a local RegExp and a parameter named RegExp.
 *
 * One edge is left out because the rule departs from ESLint there, as the tracker does for every rule
 * on it: `window.RegExp('a')`, which ESLint reports only under browser globals, and which the tracker
 * follows, since an undeclared `window` is the runtime's global object here. Its own test says so.
 */
func TestPreferRegexLiteralsAgreesWithESLint(t *testing.T) {
	t.Parallel()

	decode := rule.DecodeOptionsInto[PreferRegexLiteralsOptions]()
	cases := []struct {
		origin  string
		options string
		code    string
		want    []string
	}{
		{"corpus", "", "/abc/", []string{}},
		{"corpus", "", "/abc/g", []string{}},
		{"corpus", "", "new RegExp(pattern)", []string{}},
		{"corpus", "", "new RegExp('\\\\p{Emoji_Presentation}\\\\P{Script_Extensions=Latin}' + '', `ug`)", []string{}},
		{"corpus", "", "new RegExp('\\\\cA' + '')", []string{}},
		{"corpus", "", "RegExp(pattern, 'g')", []string{}},
		{"corpus", "", "new RegExp(f('a'))", []string{}},
		{"corpus", "", "RegExp(prefix + 'a')", []string{}},
		{"corpus", "", "new RegExp('a' + suffix)", []string{}},
		{"corpus", "", "RegExp(`a` + suffix);", []string{}},
		{"corpus", "", "new RegExp(String.raw`a` + suffix);", []string{}},
		{"corpus", "", "RegExp('a', flags)", []string{}},
		{"corpus", "", "const flags = 'gu';RegExp('a', flags)", []string{}},
		{"corpus", "", "RegExp('a', 'g' + flags)", []string{}},
		{"corpus", "", "new RegExp(String.raw`a`, flags);", []string{}},
		{"corpus", "", "RegExp(`${prefix}abc`)", []string{}},
		{"corpus", "", "new RegExp(`a${b}c`);", []string{}},
		{"corpus", "", "new RegExp(`a${''}c`);", []string{}},
		{"corpus", "", "new RegExp(String.raw`a${b}c`);", []string{}},
		{"corpus", "", "new RegExp(String.raw`a${''}c`);", []string{}},
		{"corpus", "", "new RegExp('a' + 'b')", []string{}},
		{"corpus", "", "RegExp(1)", []string{}},
		{"corpus", "", "new RegExp('(\\\\p{Emoji_Presentation})\\\\1' + '', `ug`)", []string{}},
		{"corpus", "", "RegExp(String.raw`\\78\\126` + '\\\\5934', '' + `g` + '')", []string{}},
		{"corpus", "", "func(new RegExp(String.raw`a${''}c\\d`, 'u'),new RegExp(String.raw`a${''}c\\d`, 'u'))", []string{}},
		{"corpus", "", "new RegExp('\\\\[' + \"b\\\\]\")", []string{}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, flags);", []string{}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, `u${flags}`);", []string{}},
		{"corpus", "{}", "new RegExp(/a/);", []string{}},
		{"corpus", "{\"disallowRedundantWrapping\":false}", "new RegExp(/a/);", []string{}},
		{"corpus", "", "new RegExp;", []string{}},
		{"corpus", "", "new RegExp();", []string{}},
		{"corpus", "", "RegExp();", []string{}},
		{"corpus", "", "new RegExp('a', 'g', 'b');", []string{}},
		{"corpus", "", "RegExp('a', 'g', 'b');", []string{}},
		{"corpus", "", "new RegExp(`a`, `g`, `b`);", []string{}},
		{"corpus", "", "RegExp(`a`, `g`, `b`);", []string{}},
		{"corpus", "", "new RegExp(String.raw`a`, String.raw`g`, String.raw`b`);", []string{}},
		{"corpus", "", "RegExp(String.raw`a`, String.raw`g`, String.raw`b`);", []string{}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, 'u', 'foo');", []string{}},
		{"corpus", "", "new RegExp(String`a`);", []string{}},
		{"corpus", "", "RegExp(raw`a`);", []string{}},
		{"corpus", "", "new RegExp(f(String.raw)`a`);", []string{}},
		{"corpus", "", "RegExp(string.raw`a`);", []string{}},
		{"corpus", "", "new RegExp(String.Raw`a`);", []string{}},
		{"corpus", "", "new RegExp(String[raw]`a`);", []string{}},
		{"corpus", "", "RegExp(String.raw.foo`a`);", []string{}},
		{"corpus", "", "new RegExp(String.foo.raw`a`);", []string{}},
		{"corpus", "", "RegExp(foo.String.raw`a`);", []string{}},
		{"corpus", "", "new RegExp(String.raw);", []string{}},
		{"corpus", "", "let String; new RegExp(String.raw`a`);", []string{}},
		{"corpus", "", "function foo() { var String; new RegExp(String.raw`a`); }", []string{}},
		{"corpus", "", "function foo(String) { RegExp(String.raw`a`); }", []string{}},
		{"corpus", "", "if (foo) { const String = bar; RegExp(String.raw`a`); }", []string{}},
		{"corpus", "", "/* globals String:off */ new RegExp(String.raw`a`);", []string{"unexpectedRegExp new RegExp(String.raw`a`)@25"}},
		{"corpus", "", "new Regexp('abc');", []string{}},
		{"corpus", "", "Regexp(`a`);", []string{}},
		{"corpus", "", "new Regexp(String.raw`a`);", []string{}},
		{"corpus", "", "let RegExp; new RegExp('a');", []string{}},
		{"corpus", "", "function foo() { var RegExp; RegExp('a', 'g'); }", []string{}},
		{"corpus", "", "function foo(RegExp) { new RegExp(String.raw`a`); }", []string{}},
		{"corpus", "", "if (foo) { const RegExp = bar; RegExp('a'); }", []string{}},
		{"corpus", "", "/* globals RegExp:off */ new RegExp('a');", []string{"unexpectedRegExp new RegExp('a')@25"}},
		{"corpus", "", "new globalThis.RegExp('a');", []string{"unexpectedRegExp new globalThis.RegExp('a')@0"}},
		{"corpus", "", "new globalThis.RegExp('a');", []string{"unexpectedRegExp new globalThis.RegExp('a')@0"}},
		{"corpus", "", "new globalThis.RegExp('a');", []string{"unexpectedRegExp new globalThis.RegExp('a')@0"}},
		{"corpus", "", "class C { #RegExp; foo() { globalThis.#RegExp('a'); } }", []string{}},
		{"corpus", "", "new RegExp('[[A--B]]' + a, 'v')", []string{}},
		{"corpus", "", "new RegExp('abc');", []string{"unexpectedRegExp new RegExp('abc')@0"}},
		{"corpus", "", "RegExp('abc');", []string{"unexpectedRegExp RegExp('abc')@0"}},
		{"corpus", "", "new RegExp('abc', 'g');", []string{"unexpectedRegExp new RegExp('abc', 'g')@0"}},
		{"corpus", "", "RegExp('abc', 'g');", []string{"unexpectedRegExp RegExp('abc', 'g')@0"}},
		{"corpus", "", "new RegExp(`abc`);", []string{"unexpectedRegExp new RegExp(`abc`)@0"}},
		{"corpus", "", "RegExp(`abc`);", []string{"unexpectedRegExp RegExp(`abc`)@0"}},
		{"corpus", "", "new RegExp(`abc`, `g`);", []string{"unexpectedRegExp new RegExp(`abc`, `g`)@0"}},
		{"corpus", "", "RegExp(`abc`, `g`);", []string{"unexpectedRegExp RegExp(`abc`, `g`)@0"}},
		{"corpus", "", "new RegExp(String.raw`abc`);", []string{"unexpectedRegExp new RegExp(String.raw`abc`)@0"}},
		{"corpus", "", "new RegExp(String.raw`abc\nabc`);", []string{"unexpectedRegExp new RegExp(String.raw`abc\nabc`)@0"}},
		{"corpus", "", "new RegExp(String.raw`\tabc\nabc`);", []string{"unexpectedRegExp new RegExp(String.raw`\tabc\nabc`)@0"}},
		{"corpus", "", "RegExp(String.raw`abc`);", []string{"unexpectedRegExp RegExp(String.raw`abc`)@0"}},
		{"corpus", "", "new RegExp(String.raw`abc`, String.raw`g`);", []string{"unexpectedRegExp new RegExp(String.raw`abc`, String.raw`g`)@0"}},
		{"corpus", "", "RegExp(String.raw`abc`, String.raw`g`);", []string{"unexpectedRegExp RegExp(String.raw`abc`, String.raw`g`)@0"}},
		{"corpus", "", "new RegExp(String['raw']`a`);", []string{"unexpectedRegExp new RegExp(String['raw']`a`)@0"}},
		{"corpus", "", "new RegExp('');", []string{"unexpectedRegExp new RegExp('')@0"}},
		{"corpus", "", "RegExp('', '');", []string{"unexpectedRegExp RegExp('', '')@0"}},
		{"corpus", "", "new RegExp(String.raw``);", []string{"unexpectedRegExp new RegExp(String.raw``)@0"}},
		{"corpus", "", "new RegExp('a', `g`);", []string{"unexpectedRegExp new RegExp('a', `g`)@0"}},
		{"corpus", "", "RegExp(`a`, 'g');", []string{"unexpectedRegExp RegExp(`a`, 'g')@0"}},
		{"corpus", "", "RegExp(String.raw`a`, 'g');", []string{"unexpectedRegExp RegExp(String.raw`a`, 'g')@0"}},
		{"corpus", "", "new RegExp(String.raw`\\d`, `g`);", []string{"unexpectedRegExp new RegExp(String.raw`\\d`, `g`)@0"}},
		{"corpus", "", "new RegExp(String.raw`\\\\d`, `g`);", []string{"unexpectedRegExp new RegExp(String.raw`\\\\d`, `g`)@0"}},
		{"corpus", "", "new RegExp(String['raw']`\\\\d`, `g`);", []string{"unexpectedRegExp new RegExp(String['raw']`\\\\d`, `g`)@0"}},
		{"corpus", "", "new RegExp(String[\"raw\"]`\\\\d`, `g`);", []string{"unexpectedRegExp new RegExp(String[\"raw\"]`\\\\d`, `g`)@0"}},
		{"corpus", "", "RegExp('a', String.raw`g`);", []string{"unexpectedRegExp RegExp('a', String.raw`g`)@0"}},
		{"corpus", "", "new globalThis.RegExp('a');", []string{"unexpectedRegExp new globalThis.RegExp('a')@0"}},
		{"corpus", "", "globalThis.RegExp('a');", []string{"unexpectedRegExp globalThis.RegExp('a')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/);", []string{"unexpectedRedundantRegExp new RegExp(/a/)@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, 'u');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, 'u')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/g, '');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/g, '')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/g, 'g');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/g, 'g')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/ig, 'g');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/ig, 'g')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/g, 'ig');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/g, 'ig')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/i, 'g');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/i, 'g')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/i, 'i');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/i, 'i')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, `u`);", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, `u`)@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, `gi`);", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, `gi`)@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp('a');", []string{"unexpectedRegExp new RegExp('a')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, String.raw`u`);", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, String.raw`u`)@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/ /* comment */);", []string{"unexpectedRedundantRegExp new RegExp(/a/ /* comment */)@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, 'd');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, 'd')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "(a)\nnew RegExp(/b/);", []string{"unexpectedRedundantRegExp new RegExp(/b/)@4"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "(a)\nnew RegExp(/b/, 'g');", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/b/, 'g')@4"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "a/RegExp(/foo/);", []string{"unexpectedRedundantRegExp RegExp(/foo/)@2"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "RegExp(/foo/)in a;", []string{"unexpectedRedundantRegExp RegExp(/foo/)@0"}},
		{"corpus", "", "new RegExp((String?.raw)`a`);", []string{"unexpectedRegExp new RegExp((String?.raw)`a`)@0"}},
		{"corpus", "", "new RegExp('+');", []string{"unexpectedRegExp new RegExp('+')@0"}},
		{"corpus", "", "new RegExp('*');", []string{"unexpectedRegExp new RegExp('*')@0"}},
		{"corpus", "", "RegExp('+');", []string{"unexpectedRegExp RegExp('+')@0"}},
		{"corpus", "", "RegExp('*');", []string{"unexpectedRegExp RegExp('*')@0"}},
		{"corpus", "", "new RegExp('+', 'g');", []string{"unexpectedRegExp new RegExp('+', 'g')@0"}},
		{"corpus", "", "new RegExp('*', 'g');", []string{"unexpectedRegExp new RegExp('*', 'g')@0"}},
		{"corpus", "", "RegExp('+', 'g');", []string{"unexpectedRegExp RegExp('+', 'g')@0"}},
		{"corpus", "", "RegExp('*', 'g');", []string{"unexpectedRegExp RegExp('*', 'g')@0"}},
		{"corpus", "", "RegExp('abc', 'u');", []string{"unexpectedRegExp RegExp('abc', 'u')@0"}},
		{"corpus", "", "new RegExp('abc', 'd');", []string{"unexpectedRegExp new RegExp('abc', 'd')@0"}},
		{"corpus", "", "RegExp('abc', 'd');", []string{"unexpectedRegExp RegExp('abc', 'd')@0"}},
		{"corpus", "", "RegExp('\\\\\\\\', '');", []string{"unexpectedRegExp RegExp('\\\\\\\\', '')@0"}},
		{"corpus", "", "RegExp('\\n', '');", []string{"unexpectedRegExp RegExp('\\n', '')@0"}},
		{"corpus", "", "RegExp('\\n\\n', '');", []string{"unexpectedRegExp RegExp('\\n\\n', '')@0"}},
		{"corpus", "", "RegExp('\\t', '');", []string{"unexpectedRegExp RegExp('\\t', '')@0"}},
		{"corpus", "", "RegExp('\\t\\t', '');", []string{"unexpectedRegExp RegExp('\\t\\t', '')@0"}},
		{"corpus", "", "RegExp('\\r\\n', '');", []string{"unexpectedRegExp RegExp('\\r\\n', '')@0"}},
		{"corpus", "", "RegExp('\\u1234', 'g')", []string{"unexpectedRegExp RegExp('\\u1234', 'g')@0"}},
		{"corpus", "", "RegExp('\\u{1234}', 'g')", []string{"unexpectedRegExp RegExp('\\u{1234}', 'g')@0"}},
		{"corpus", "", "RegExp('\\u{11111}', 'g')", []string{"unexpectedRegExp RegExp('\\u{11111}', 'g')@0"}},
		{"corpus", "", "RegExp('\\v', '');", []string{"unexpectedRegExp RegExp('\\v', '')@0"}},
		{"corpus", "", "RegExp('\\v\\v', '');", []string{"unexpectedRegExp RegExp('\\v\\v', '')@0"}},
		{"corpus", "", "RegExp('\\f', '');", []string{"unexpectedRegExp RegExp('\\f', '')@0"}},
		{"corpus", "", "RegExp('\\f\\f', '');", []string{"unexpectedRegExp RegExp('\\f\\f', '')@0"}},
		{"corpus", "", "RegExp('\\\\b', '');", []string{"unexpectedRegExp RegExp('\\\\b', '')@0"}},
		{"corpus", "", "RegExp('\\\\b\\\\b', '');", []string{"unexpectedRegExp RegExp('\\\\b\\\\b', '')@0"}},
		{"corpus", "", "new RegExp('\\\\B\\\\b', '');", []string{"unexpectedRegExp new RegExp('\\\\B\\\\b', '')@0"}},
		{"corpus", "", "RegExp('\\\\w', '');", []string{"unexpectedRegExp RegExp('\\\\w', '')@0"}},
		{"corpus", "", "RegExp('\\\\s', '');", []string{"unexpectedRegExp RegExp('\\\\s', '')@0"}},
		{"corpus", "", "new RegExp('\\\\S', '')", []string{"unexpectedRegExp new RegExp('\\\\S', '')@0"}},
		{"corpus", "", "new RegExp('\\\\D\\\\D', '')", []string{"unexpectedRegExp new RegExp('\\\\D\\\\D', '')@0"}},
		{"corpus", "", "new RegExp('\\\\0\\\\0', '');", []string{"unexpectedRegExp new RegExp('\\\\0\\\\0', '')@0"}},
		{"corpus", "", "new RegExp('\\0\\0', 'g');", []string{"unexpectedRegExp new RegExp('\\0\\0', 'g')@0"}},
		{"corpus", "", "RegExp('\\\\0\\\\0\\\\0', '')", []string{"unexpectedRegExp RegExp('\\\\0\\\\0\\\\0', '')@0"}},
		{"corpus", "", "RegExp('\\\\78\\\\126\\\\5934', '')", []string{"unexpectedRegExp RegExp('\\\\78\\\\126\\\\5934', '')@0"}},
		{"corpus", "", "a in(RegExp('abc'))", []string{"unexpectedRegExp RegExp('abc')@5"}},
		{"corpus", "", "x = y\n            RegExp(\"foo\").test(x) ? bar() : baz()", []string{"unexpectedRegExp RegExp(\"foo\")@18"}},
		{"corpus", "", "func(new RegExp(String.raw`\\w{1, 2`, 'u'),new RegExp(String.raw`\\w{1, 2`, 'u'))", []string{"unexpectedRegExp new RegExp(String.raw`\\w{1, 2`, 'u')@5", "unexpectedRegExp new RegExp(String.raw`\\w{1, 2`, 'u')@42"}},
		{"corpus", "", "x = y;\n            RegExp(\"foo\").test(x) ? bar() : baz()", []string{"unexpectedRegExp RegExp(\"foo\")@19"}},
		{"corpus", "", "typeof RegExp(\"foo\")", []string{"unexpectedRegExp RegExp(\"foo\")@7"}},
		{"corpus", "", "RegExp(\"foo\") instanceof RegExp(String.raw`blahblah`, 'g') ? typeof new RegExp('(\\\\p{Emoji_Presentation})\\\\1', `ug`) : false", []string{"unexpectedRegExp RegExp(\"foo\")@0", "unexpectedRegExp RegExp(String.raw`blahblah`, 'g')@25", "unexpectedRegExp new RegExp('(\\\\p{Emoji_Presentation})\\\\1', `ug`)@68"}},
		{"corpus", "", "[   new RegExp(`someregular`)]", []string{"unexpectedRegExp new RegExp(`someregular`)@4"}},
		{"corpus", "", "const totallyValidatesEmails = new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")\n            if (typeof totallyValidatesEmails === 'object') {\n                runSomethingThatExists(Regexp('stuff'))\n            }", []string{"unexpectedRegExp new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")@31"}},
		{"corpus", "", "!new RegExp('^Hey, ', 'u') && new RegExp('jk$') && ~new RegExp('^Sup, ') || new RegExp('hi') + new RegExp('person') === -new RegExp('hi again') ? 5 * new RegExp('abc') : 'notregbutstring'", []string{"unexpectedRegExp new RegExp('^Hey, ', 'u')@1", "unexpectedRegExp new RegExp('jk$')@30", "unexpectedRegExp new RegExp('^Sup, ')@52", "unexpectedRegExp new RegExp('hi')@76", "unexpectedRegExp new RegExp('person')@95", "unexpectedRegExp new RegExp('hi again')@121", "unexpectedRegExp new RegExp('abc')@150"}},
		{"corpus", "", "#!/usr/bin/sh\n            RegExp(\"foo\")", []string{"unexpectedRegExp RegExp(\"foo\")@26"}},
		{"corpus", "", "async function abc(){await new RegExp(\"foo\")}", []string{"unexpectedRegExp new RegExp(\"foo\")@27"}},
		{"corpus", "", "function* abc(){yield new RegExp(\"foo\")}", []string{"unexpectedRegExp new RegExp(\"foo\")@22"}},
		{"corpus", "", "function* abc(){yield* new RegExp(\"foo\")}", []string{"unexpectedRegExp new RegExp(\"foo\")@23"}},
		{"corpus", "", "console.log({ ...new RegExp('a') })", []string{"unexpectedRegExp new RegExp('a')@17"}},
		{"corpus", "", "delete RegExp('a');", []string{"unexpectedRegExp RegExp('a')@7"}},
		{"corpus", "", "void RegExp('a');", []string{"unexpectedRegExp RegExp('a')@5"}},
		{"corpus", "", "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")**RegExp('a')", []string{"unexpectedRegExp new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")@0", "unexpectedRegExp RegExp('a')@35"}},
		{"corpus", "", "new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")%RegExp('a')", []string{"unexpectedRegExp new RegExp(\"\\\\S+@(\\\\S+\\\\.)+\\\\S+\")@0", "unexpectedRegExp RegExp('a')@34"}},
		{"corpus", "", "a in RegExp('abc')", []string{"unexpectedRegExp RegExp('abc')@5"}},
		{"corpus", "", "\n            /abc/ == new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ === new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@23"}},
		{"corpus", "", "\n            /abc/ != new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ !== new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@23"}},
		{"corpus", "", "\n            /abc/ > new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            /abc/ < new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            /abc/ >= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ <= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ << new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ >> new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            /abc/ >>> new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@23"}},
		{"corpus", "", "\n            /abc/ ^ new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            /abc/ & new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            /abc/ | new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            null ?? new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@21"}},
		{"corpus", "", "\n            abc *= new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@20"}},
		{"corpus", "", "\n            console.log({a: new RegExp('sup')})\n            ", []string{"unexpectedRegExp new RegExp('sup')@29"}},
		{"corpus", "", "\n            console.log(() => {new RegExp('sup')})\n            ", []string{"unexpectedRegExp new RegExp('sup')@32"}},
		{"corpus", "", "\n            function abc() {new RegExp('sup')}\n            ", []string{"unexpectedRegExp new RegExp('sup')@29"}},
		{"corpus", "", "\n            function abc() {return new RegExp('sup')}\n            ", []string{"unexpectedRegExp new RegExp('sup')@36"}},
		{"corpus", "", "\n            abc <<= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            abc >>= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            abc >>>= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@22"}},
		{"corpus", "", "\n            abc ^= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@20"}},
		{"corpus", "", "\n            abc &= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@20"}},
		{"corpus", "", "\n            abc |= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@20"}},
		{"corpus", "", "\n            abc ??= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            abc &&= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            abc ||= new RegExp('cba');\n            ", []string{"unexpectedRegExp new RegExp('cba')@21"}},
		{"corpus", "", "\n            abc **= new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@21"}},
		{"corpus", "", "\n            abc /= new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@20"}},
		{"corpus", "", "\n            abc += new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@20"}},
		{"corpus", "", "\n            abc -= new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@20"}},
		{"corpus", "", "\n            abc %= new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@20"}},
		{"corpus", "", "\n            () => new RegExp('blah')\n            ", []string{"unexpectedRegExp new RegExp('blah')@19"}},
		{"corpus", "", "a/RegExp(\"foo\")in b", []string{"unexpectedRegExp RegExp(\"foo\")@2"}},
		{"corpus", "", "a/RegExp(\"foo\")instanceof b", []string{"unexpectedRegExp RegExp(\"foo\")@2"}},
		{"corpus", "", "do RegExp(\"foo\")\nwhile (true);", []string{"unexpectedRegExp RegExp(\"foo\")@3"}},
		{"corpus", "", "for(let i;i<5;i++) { break\nnew RegExp('search')}", []string{"unexpectedRegExp new RegExp('search')@27"}},
		{"corpus", "", "for(let i;i<5;i++) { continue\nnew RegExp('search')}", []string{"unexpectedRegExp new RegExp('search')@30"}},
		{"corpus", "", "\n            switch (value) {\n                case \"possibility\":\n                    console.log('possibility matched')\n                case RegExp('myReg').toString():\n                    console.log('matches a regexp\\' toString value')\n                    break;\n            }\n            ", []string{"unexpectedRegExp RegExp('myReg')@142"}},
		{"corpus", "", "throw new RegExp('abcdefg') // fail with a regular expression", []string{"unexpectedRegExp new RegExp('abcdefg')@6"}},
		{"corpus", "", "for (value of new RegExp('something being searched')) { console.log(value) }", []string{"unexpectedRegExp new RegExp('something being searched')@14"}},
		{"corpus", "", "(async function(){for await (value of new RegExp('something being searched')) { console.log(value) }})()", []string{"unexpectedRegExp new RegExp('something being searched')@38"}},
		{"corpus", "", "for (value in new RegExp('something being searched')) { console.log(value) }", []string{"unexpectedRegExp new RegExp('something being searched')@14"}},
		{"corpus", "", "if (condition1 && condition2) new RegExp('avalue').test(str);", []string{"unexpectedRegExp new RegExp('avalue')@30"}},
		{"corpus", "", "debugger\nnew RegExp('myReg')", []string{"unexpectedRegExp new RegExp('myReg')@9"}},
		{"corpus", "", "RegExp(\"\\\\\\n\")", []string{"unexpectedRegExp RegExp(\"\\\\\\n\")@0"}},
		{"corpus", "", "RegExp(\"\\\\\\t\")", []string{"unexpectedRegExp RegExp(\"\\\\\\t\")@0"}},
		{"corpus", "", "RegExp(\"\\\\\\f\")", []string{"unexpectedRegExp RegExp(\"\\\\\\f\")@0"}},
		{"corpus", "", "RegExp(\"\\\\\\v\")", []string{"unexpectedRegExp RegExp(\"\\\\\\v\")@0"}},
		{"corpus", "", "RegExp(\"\\\\\\r\")", []string{"unexpectedRegExp RegExp(\"\\\\\\r\")@0"}},
		{"corpus", "", "new RegExp(\"\t\")", []string{"unexpectedRegExp new RegExp(\"\t\")@0"}},
		{"corpus", "", "new RegExp(\"/\")", []string{"unexpectedRegExp new RegExp(\"/\")@0"}},
		{"corpus", "", "new RegExp(\"\\.\")", []string{"unexpectedRegExp new RegExp(\"\\.\")@0"}},
		{"corpus", "", "new RegExp(\"\\\\.\")", []string{"unexpectedRegExp new RegExp(\"\\\\.\")@0"}},
		{"corpus", "", "new RegExp(\"\\\\\\n\\\\\\n\")", []string{"unexpectedRegExp new RegExp(\"\\\\\\n\\\\\\n\")@0"}},
		{"corpus", "", "new RegExp(\"\\\\\\n\\\\\\f\\\\\\n\")", []string{"unexpectedRegExp new RegExp(\"\\\\\\n\\\\\\f\\\\\\n\")@0"}},
		{"corpus", "", "new RegExp(\"\\u000A\\u000A\");", []string{"unexpectedRegExp new RegExp(\"\\u000A\\u000A\")@0"}},
		{"corpus", "", "new RegExp('mysafereg' /* comment explaining its safety */)", []string{"unexpectedRegExp new RegExp('mysafereg' /* comment explaining its safety */)@0"}},
		{"corpus", "", "new RegExp('[[A--B]]', 'v')", []string{"unexpectedRegExp new RegExp('[[A--B]]', 'v')@0"}},
		{"corpus", "", "new RegExp('[[A--B]]', 'v')", []string{"unexpectedRegExp new RegExp('[[A--B]]', 'v')@0"}},
		{"corpus", "", "new RegExp('[[A&&&]]', 'v')", []string{"unexpectedRegExp new RegExp('[[A&&&]]', 'v')@0"}},
		{"corpus", "", "new RegExp('a', 'uv')", []string{"unexpectedRegExp new RegExp('a', 'uv')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, 'v')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, 'v')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/, 'v')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/, 'v')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/g, 'v')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/g, 'v')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/[[A--B]]/v, 'g')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/[[A--B]]/v, 'g')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/u, 'v')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/u, 'v')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/a/v, 'u')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/a/v, 'u')@0"}},
		{"corpus", "{\"disallowRedundantWrapping\":true}", "new RegExp(/[[A--B]]/v, 'u')", []string{"unexpectedRedundantRegExpWithFlags new RegExp(/[[A--B]]/v, 'u')@0"}},
		{"corpus", "", "new RegExp('(?i:foo)bar')", []string{"unexpectedRegExp new RegExp('(?i:foo)bar')@0"}},
		{"corpus", "", "new RegExp('(?i:foo)bar')", []string{"unexpectedRegExp new RegExp('(?i:foo)bar')@0"}},
		{"corpus", "", "var regex = new RegExp('foo', 'u');", []string{"unexpectedRegExp new RegExp('foo', 'u')@12"}},
		{"edge", "", "const R = RegExp; new R('a');", []string{"unexpectedRegExp new R('a')@18"}},
		{"edge", "", "(RegExp)('a');", []string{"unexpectedRegExp (RegExp)('a')@0"}},
		{"edge", "", "globalThis.RegExp('a');", []string{"unexpectedRegExp globalThis.RegExp('a')@0"}},
		{"edge", "", "let RegExp; new RegExp('a');", []string{}},
		{"edge", "", "const r = RegExp; r('a', 'g');", []string{"unexpectedRegExp r('a', 'g')@18"}},
		{"edge", "{\"disallowRedundantWrapping\":true}", "const R = RegExp; new R(/a/);", []string{"unexpectedRedundantRegExp new R(/a/)@18"}},
		{"edge", "", "const {RegExp: R} = globalThis; new R('a');", []string{"unexpectedRegExp new R('a')@32"}},
		{"edge", "", "const R = globalThis.RegExp; R(String.raw`\\d`);", []string{"unexpectedRegExp R(String.raw`\\d`)@29"}},
		{"edge", "", "function f(RegExp) { return RegExp('a'); }", []string{}},
		{"edge", "", "new RegExp(x);", []string{}},
	}

	for index, testCase := range cases {
		var options any
		if testCase.options != "" {
			decoded, err := decode([]byte(testCase.options))
			if err != nil {
				t.Fatalf("case %d (%s): ESLint accepts %s and the decoder refused it: %v", index, testCase.origin, testCase.options, err)
			}
			options = decoded
		}
		result := rule_testing.RunTypedVerbatimWithOptions(t, PreferRegexLiterals, "input.ts", testCase.code, options)
		source := result.SourceFile.Text()
		got := []string{}
		for _, diagnostic := range result.Diagnostics {
			got = append(got, fmt.Sprintf("%s %s@%d", diagnostic.Message.Id,
				source[diagnostic.Range.Pos():diagnostic.Range.End()], diagnostic.Range.Pos()))
		}
		want := append([]string{}, testCase.want...)
		sort.Strings(got)
		sort.Strings(want)
		if strings.Join(got, "\n") != strings.Join(want, "\n") {
			t.Errorf("case %d (%s, %s): %q\n got: %q\nwant: %q", index, testCase.origin, testCase.options, testCase.code, got, want)
		}
	}
}
