package settingsschema

import (
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/system-inc/cohere/internal/format/formatoptions"
	"github.com/system-inc/cohere/internal/lint/configuration"
)

// examples are a value for each top-level key, as a file would write it. The test decodes every one.
var examples = map[string]string{
	"$schema":        `"./schema/CohereSettings.schema.json"`,
	"extends":        `["cohere:typescript", "./NexusCohereSettings.json"]`,
	"rules":          `{ "no-debugger": "error", "eqeqeq": ["error", "always", { "null": "ignore" }] }`,
	"departures":     `{ "no-console": "This command-line tool writes to the console by design." }`,
	"overrides":      `[{ "files": ["**/*.test.ts"], "rules": { "no-console": "off" }, "reason": "Tests print their fixtures." }]`,
	"ignorePatterns": `["dist/**", "data/**", "modules/*/data/**"]`,
	"cohere":         `"^1.0.0"`,
	"plugins":        `["react"]`,
	"jsPlugins":      `["./code-quality/lint/rules/index.js"]`,
	"settings":       `{ "react": { "version": "19.0" } }`,
	FormatKey:        `{ "printWidth": 120, "tabWidth": 4, "singleQuote": true, "ignore": ["pnpm-lock.yaml", "*.sqlite"] }`,
}

// reference renders the reference document.
func reference(ruleNames []string) string {
	var document strings.Builder
	write := func(format string, arguments ...any) { fmt.Fprintf(&document, format, arguments...) }

	write("# CohereSettings.json\n\n")
	write("<!-- Generated by internal/settingsschema from the loader's own types; do not edit. Run\n")
	write("     `go run ./internal/settingsschema/tools/generate` from the module root after a change. -->\n\n")
	write("cohere reads `CohereSettings.json` at the project root. Its `extends` chain ends at the Nexus tier, the one\n")
	write("place the format block lives: either the rule set cohere carries, `%s`, or a `%s` of your own. With\n", formatoptions.NexusTierSetName, formatoptions.NexusTierFileName)
	write("the carried set, one file is the whole setup:\n\n")
	write("```json\n{\n    \"$schema\": %s,\n    \"extends\": \"%s\",\n    \"rules\": { \"no-debugger\": \"error\" },\n    \"ignorePatterns\": [\"dist/**\"]\n}\n```\n\n", examples["$schema"], formatoptions.NexusTierSetName)
	write("With a tier of your own, the project extends it, and it holds the format block:\n\n")
	write("```json\n{\n    \"$schema\": %s,\n    \"extends\": \"./%s\",\n    \"rules\": { \"no-debugger\": \"error\" }\n}\n```\n\n", examples["$schema"], formatoptions.NexusTierFileName)
	write("```json\n{\n    \"$schema\": \"./schema/NexusCohereSettings.schema.json\",\n    \"format\": %s\n}\n```\n\n", examples[FormatKey])
	write("Editors validate against [`CohereSettings.schema.json`](CohereSettings.schema.json) and\n")
	write("[`NexusCohereSettings.schema.json`](NexusCohereSettings.schema.json), from this directory of the cohere\n")
	write("repository; `$schema` names wherever you keep a copy. A key outside these lists is an error cohere names,\n")
	write("never something it silently ignores.\n\n")

	write("## Keys\n\n")
	write("| Key | Type | In |\n| --- | --- | --- |\n")
	for _, key := range configuration.TopLevelKeys() {
		where := "any settings file"
		switch key.Name {
		case FormatKey:
			where = "the Nexus tier only (" + formatoptions.NexusTierFileName + ")"
		case "settings":
			where = "the file cohere reads first"
		}
		write("| [`%s`](#%s) | %s | %s |\n", key.Name, anchor(key.Name), typeName(key), where)
	}
	write("\n")

	for _, key := range configuration.TopLevelKeys() {
		write("### `%s`\n\n%s\n\n", key.Name, topLevelDescriptions[key.Name])
		if key.Name == "extends" {
			write("The rule sets cohere carries: `%s`.\n\n", strings.Join(configuration.SetNames(), "`, `"))
		}
		if key.Name == "overrides" {
			write("Each block takes:\n\n")
			for _, field := range configuration.OverrideFields() {
				write("- `%s`: %s\n", field.Name, overrideDescriptions[field.Name])
			}
			write("\n")
		}
		if key.Name == FormatKey {
			write("| Option | Type | Values |\n| --- | --- | --- |\n")
			for _, option := range formatoptions.BlockKeys {
				values := ""
				if len(option.Enum) > 0 {
					values = "`" + strings.Join(option.Enum, "`, `") + "`"
				}
				kind := option.Type
				if kind == "array" {
					kind = "array of patterns"
				}
				write("| `%s` | %s | %s |\n", option.Name, kind, values)
			}
			write("\n")
			for _, option := range formatoptions.BlockKeys {
				write("- `%s`: %s\n", option.Name, formatDescriptions[option.Name])
			}
			write("\n")
		}
		write("```json\n{ \"%s\": %s }\n```\n\n", key.Name, examples[key.Name])
	}

	write("## Severities\n\n")
	write("A rule's value is a severity, or `[severity, ...options]` for a rule that takes options. The severities are\n")
	write("`off` (also `allow`), `warn` (also `warning`) and `error` (also `deny`), in any case.\n\n")

	write("## Rules\n\n")
	write("cohere implements %d rules. `cohere --rules` lists them for your project's language, and\n", len(ruleNames))
	write("`cohere --rules-enabled` lists the ones your settings turn on. A name cohere does not implement is accepted:\n")
	write("it records a decision about a rule, and is reported as unported rather than refused.\n\n")
	groups := map[string][]string{}
	for _, name := range ruleNames {
		namespace := "core"
		if before, _, namespaced := strings.Cut(name, "/"); namespaced {
			namespace = before
		}
		groups[namespace] = append(groups[namespace], name)
	}
	namespaces := make([]string, 0, len(groups))
	for namespace := range groups {
		namespaces = append(namespaces, namespace)
	}
	sort.Strings(namespaces)
	for _, namespace := range namespaces {
		write("<details><summary><code>%s</code>, %d rules</summary>\n\n", namespace, len(groups[namespace]))
		for _, name := range groups[namespace] {
			write("- `%s`\n", name)
		}
		write("\n</details>\n\n")
	}
	return strings.TrimRight(document.String(), "\n") + "\n"
}

// anchor is the heading anchor GitHub gives "### `name`".
func anchor(name string) string {
	return strings.ToLower(strings.TrimPrefix(name, "$"))
}

func typeName(key configuration.TopLevelKey) string {
	switch {
	case key.Name == FormatKey || key.Name == "settings":
		return "object"
	case key.Field == configuration.ExtendsListType:
		return "string or array of strings"
	case key.Field == nil:
		shape := ignoredKeyShapes[key.Name]()
		return fmt.Sprint(shape["type"])
	case key.Field.Kind() == reflect.String:
		return "string"
	case key.Field.Kind() == reflect.Slice && key.Field.Elem().Kind() == reflect.String:
		return "array of strings"
	case key.Field.Kind() == reflect.Slice:
		return "array of blocks"
	case key.Field.Kind() == reflect.Map && key.Field.Elem().Kind() == reflect.String:
		return "object of reasons"
	default:
		return "object of rule settings"
	}
}
