// Package settingsschema generates the JSON schemas for CohereSettings.json and NexusCohereSettings.json,
// and the reference document beside them, from the types that read those files.
//
// Nothing here lists a key by hand. The keys come from the lint loader (configuration.TopLevelKeys and
// OverrideFields, read off the structs it decodes into), the format block's from formatoptions.BlockKeys
// (the table its decoder runs on), and the rule names from the registry. What is written by hand is the
// prose a person reads about each key, and the test refuses a key with no prose as firmly as prose for
// a key that no longer exists. Run `go run ./internal/settingsschema/tools/generate` from the module
// root after a change; the test fails until the committed files match.
package settingsschema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/system-inc/cohere/internal/format/formatoptions"
	"github.com/system-inc/cohere/internal/lint/configuration"
)

// The files Build produces, relative to the module root.
const (
	ProjectSchemaPath = "schema/CohereSettings.schema.json"
	NexusSchemaPath   = "schema/NexusCohereSettings.schema.json"
	ReferencePath     = "schema/CohereSettings.md"
)

// FormatKey is the top-level key only the Nexus tier may carry.
const FormatKey = "format"

// Build renders every generated file, keyed by its path relative to the module root.
func Build(ruleNames []string) (map[string][]byte, error) {
	project, err := document(ruleNames, false)
	if err != nil {
		return nil, err
	}
	nexus, err := document(ruleNames, true)
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{}
	for path, schema := range map[string]map[string]any{ProjectSchemaPath: project, NexusSchemaPath: nexus} {
		encoded, err := encode(schema)
		if err != nil {
			return nil, err
		}
		files[path] = encoded
	}
	files[ReferencePath] = []byte(reference(ruleNames))
	return files, nil
}

// document is one schema: the project's, which has no `format`, or the Nexus tier's, which requires it.
func document(ruleNames []string, nexusTier bool) (map[string]any, error) {
	properties := map[string]any{}
	for _, key := range configuration.TopLevelKeys() {
		if key.Name == FormatKey && !nexusTier {
			continue
		}
		description, described := topLevelDescriptions[key.Name]
		if !described {
			return nil, fmt.Errorf("settingsschema: the loader accepts %q and nothing describes it; add it to topLevelDescriptions", key.Name)
		}
		shape, err := keyShape(key)
		if err != nil {
			return nil, err
		}
		shape["description"] = description
		properties[key.Name] = shape
	}

	defs, err := definitions(ruleNames)
	if err != nil {
		return nil, err
	}

	title := "CohereSettings.json"
	summary := "cohere's settings for one repository: what it checks, how strictly, and which paths it never touches. " +
		"The formatter's options live in the Nexus tier this file extends, never here."
	if nexusTier {
		title = "NexusCohereSettings.json"
		summary = "The Nexus tier every repository's settings extend. It is the one file that holds the format block, " +
			"so every project formats the same way."
	}
	schema := map[string]any{
		"$schema":              "https://json-schema.org/draft/2020-12/schema",
		"title":                title,
		"description":          summary + " Generated by internal/settingsschema; see " + ReferencePath + ".",
		"type":                 "object",
		"additionalProperties": false,
		"properties":           properties,
		"$defs":                defs,
	}
	if nexusTier {
		schema["required"] = []string{FormatKey}
	}
	return schema, nil
}

// keyShape is the schema for one top-level key's value, read off the Go type the loader decodes it into.
func keyShape(key configuration.TopLevelKey) (map[string]any, error) {
	if key.Field == nil {
		shape, known := ignoredKeyShapes[key.Name]
		if !known {
			return nil, fmt.Errorf("settingsschema: the loader accepts %q without decoding it, and ignoredKeyShapes does not say what it holds", key.Name)
		}
		return shape(), nil
	}
	return typeShape(key.Name, key.Field)
}

var stringSliceType = reflect.TypeOf([]string{})

// typeShape maps a decoded Go type to its schema. A type it does not know is an error, so a field whose
// type changes (extends becoming a list, say) fails the generator rather than publishing a stale shape.
func typeShape(name string, fieldType reflect.Type) (map[string]any, error) {
	switch {
	case fieldType == configuration.ExtendsListType:
		source := map[string]any{
			"type":      "string",
			"minLength": 1,
			"examples":  configuration.SetNames(),
		}
		return map[string]any{"oneOf": []any{
			source,
			map[string]any{"type": "array", "minItems": 1, "items": source},
		}}, nil
	case fieldType.Kind() == reflect.String:
		return map[string]any{"type": "string"}, nil
	case fieldType == stringSliceType:
		return map[string]any{"type": "array", "items": map[string]any{"type": "string"}}, nil
	case fieldType.Kind() == reflect.Map && fieldType.Key().Kind() == reflect.String && fieldType.Elem().Kind() == reflect.String:
		return map[string]any{"type": "object", "additionalProperties": map[string]any{"type": "string", "minLength": 1}}, nil
	case fieldType.Kind() == reflect.Map && fieldType.Key().Kind() == reflect.String && fieldType.Elem() == configuration.RuleValueType:
		return map[string]any{"$ref": "#/$defs/rules"}, nil
	case fieldType.Kind() == reflect.Slice && fieldType.Elem().Kind() == reflect.Struct:
		return map[string]any{"type": "array", "items": map[string]any{"$ref": "#/$defs/override"}}, nil
	}
	return nil, fmt.Errorf("settingsschema: %q decodes into %s, which the schema has no shape for; teach typeShape", name, fieldType)
}

// ignoredKeyShapes says what a key the loader accepts without decoding holds. The format block is built
// from formatoptions.BlockKeys.
var ignoredKeyShapes = map[string]func() map[string]any{
	"$schema": func() map[string]any { return map[string]any{"type": "string"} },
	"jsPlugins": func() map[string]any {
		return map[string]any{"type": "array", "items": map[string]any{"type": "string"}}
	},
	"settings": func() map[string]any { return map[string]any{"type": "object"} },
	FormatKey:  formatShape,
}

func formatShape() map[string]any {
	properties := map[string]any{}
	for _, key := range formatoptions.BlockKeys {
		shape := map[string]any{"description": formatDescriptions[key.Name]}
		switch key.Type {
		case "array":
			shape["type"] = "array"
			shape["items"] = map[string]any{"type": "string"}
		case "integer":
			shape["type"] = "integer"
			shape["minimum"] = 0
		default:
			shape["type"] = key.Type
		}
		if len(key.Enum) > 0 {
			shape["enum"] = key.Enum
		}
		properties[key.Name] = shape
	}
	return map[string]any{"type": "object", "additionalProperties": false, "properties": properties}
}

// definitions holds the shapes several keys share: a rule's setting, the rules object, and an override.
func definitions(ruleNames []string) (map[string]any, error) {
	severity := map[string]any{
		"type":        "string",
		"pattern":     severityPattern(),
		"description": "One of " + strings.Join(configuration.SeveritySpellings, ", ") + ", in any case.",
	}
	ruleProperties := map[string]any{}
	for _, name := range ruleNames {
		ruleProperties[name] = map[string]any{"$ref": "#/$defs/ruleSetting"}
	}
	overrideProperties := map[string]any{}
	for _, field := range configuration.OverrideFields() {
		shape, err := typeShape("overrides."+field.Name, field.Field)
		if err != nil {
			return nil, err
		}
		description, described := overrideDescriptions[field.Name]
		if !described {
			return nil, fmt.Errorf("settingsschema: an override accepts %q and nothing describes it; add it to overrideDescriptions", field.Name)
		}
		shape["description"] = description
		overrideProperties[field.Name] = shape
	}
	return map[string]any{
		"severity": severity,
		"ruleSetting": map[string]any{
			"description": "A severity, or [severity, ...options] for a rule that takes options.",
			"oneOf": []any{
				map[string]any{"$ref": "#/$defs/severity"},
				map[string]any{
					"type":        "array",
					"minItems":    1,
					"prefixItems": []any{map[string]any{"$ref": "#/$defs/severity"}},
				},
			},
		},
		"rules": map[string]any{
			"type": "object",
			"description": "Every rule cohere implements is listed for completion. A name it does not implement is accepted " +
				"and counted as a decision about that rule, so it is not an error here either.",
			"properties":           ruleProperties,
			"additionalProperties": map[string]any{"$ref": "#/$defs/ruleSetting"},
		},
		"override": map[string]any{
			"type":                 "object",
			"additionalProperties": false,
			"properties":           overrideProperties,
		},
	}, nil
}

// severityPattern matches every spelling parseSeverity accepts, in any case.
func severityPattern() string {
	var spellings []string
	for _, spelling := range configuration.SeveritySpellings {
		var pattern strings.Builder
		for _, character := range spelling {
			pattern.WriteString("[" + strings.ToLower(string(character)) + strings.ToUpper(string(character)) + "]")
		}
		spellings = append(spellings, pattern.String())
	}
	return "^(" + strings.Join(spellings, "|") + ")$"
}

// encode writes a schema with sorted keys and four-space indentation, so a regeneration diffs cleanly.
func encode(schema map[string]any) ([]byte, error) {
	var buffer bytes.Buffer
	encoder := json.NewEncoder(&buffer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "    ")
	if err := encoder.Encode(schema); err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

// SchemaKeys returns a generated schema's top-level property names, sorted, for the tests.
func SchemaKeys(encoded []byte) ([]string, error) {
	var schema struct {
		Properties map[string]json.RawMessage `json:"properties"`
	}
	if err := json.Unmarshal(encoded, &schema); err != nil {
		return nil, err
	}
	keys := make([]string, 0, len(schema.Properties))
	for key := range schema.Properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys, nil
}
