// Command generate produces cohere's ECMAScript Unicode property tables.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"slices"

	"github.com/system-inc/cohere/unicodeproperties/internal/ucd"
)

func main() {
	inventory := flag.Bool("inventory", false, "write inventory JSON to stdout")
	check := flag.Bool("check", false, "check generated tables for freshness")
	output := flag.String("output", "tables_generated.go", "output file")
	flag.Parse()
	t, err := ucd.Build()
	if err != nil {
		panic(err)
	}
	if *inventory {
		if err = json.NewEncoder(os.Stdout).Encode(t); err != nil {
			panic(err)
		}
		return
	}
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by go generate; DO NOT EDIT.\npackage unicodeproperties")
	fmt.Fprintf(&b, "const Version = %q\n", ucd.Version)
	keys := make([]string, 0, len(t.Properties))
	for k := range t.Properties {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	fmt.Fprintln(&b, "var properties = map[string]Property{")
	for _, k := range keys {
		p := t.Properties[k]
		fmt.Fprintf(&b, "%q: {Family:%q, Ranges: []Range{", k, p.Family)
		for _, r := range p.Ranges {
			fmt.Fprintf(&b, "{0x%x,0x%x},", r.Lo, r.Hi)
		}
		fmt.Fprintln(&b, "}},")
	}
	fmt.Fprintln(&b, "}")
	keys = keys[:0]
	for k := range t.Aliases {
		keys = append(keys, k)
	}
	slices.Sort(keys)
	fmt.Fprintln(&b, "var aliases = map[string]string{")
	for _, k := range keys {
		fmt.Fprintf(&b, "%q:%q,\n", k, t.Aliases[k])
	}
	fmt.Fprintln(&b, "}")
	data, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if *check {
		old, e := os.ReadFile(*output)
		if e != nil {
			panic(e)
		}
		if !bytes.Equal(old, data) {
			fmt.Fprintln(os.Stderr, "Unicode property tables are stale; run go generate ./unicodeproperties")
			os.Exit(1)
		}
		return
	}
	if err = os.WriteFile(*output, data, 0644); err != nil {
		panic(err)
	}
}
