package cst

import (
	"math/rand/v2"
	"strings"
)

// fixtures are compared token for token against upstream, whole and in chunks. They are grouped by the
// lexer state or parser method they mostly drive; most drive several.
var fixtures = []string{
	// stream: empty input, blank lines, comments, directives, byte order marks
	"",
	"\n",
	"\n\n",
	"  \n",
	" \t \n",
	"# c",
	"# c\n",
	"  # c\n# d\n",
	"%YAML 1.2\n---\n",
	"%YAML 1.2\n--- a",
	"%TAG ! tag:example.com,2000:\n--- !foo a",
	"%YAML 1.2 # comment\n---",
	"%YAML 1.2\t# comment\n---\n",
	"%FOO bar#baz\n---",
	"%FOO  \t \n---",
	"%",
	"%\n",
	"%YAML 1.2",
	"%YAML 1.2\r\n---\r\n",
	"\uFEFFa",
	"\uFEFF# c\n",
	"\uFEFF%YAML 1.2\n---",
	"\uFEFF\uFEFF",
	"\uFEFF",
	"\uFEFF\n",
	"a\n\uFEFF---\nb",
	"  %YAML 1.2",
	"a\n%YAML 1.2\n",

	// line-start: document markers
	"---",
	"---\n",
	"--- a",
	"---a",
	"--- # c\na",
	"...",
	"...\n",
	"... # c\n",
	"... a",
	"a\n...\nb",
	"a\n---\nb",
	"a\n...\n---\nb",
	"--",
	"----",
	"..",
	"....a",
	"-- a",
	"---\t a",
	"---\n---",
	"...\n...",
	"--- a\n--- b\n",
	"a\n...\n%YAML 1.2\n---\nb",
	"--- !t\na",
	"--- &x\na",
	"---\n# c\n",
	"# a\n---\n# b\n...\n# c",
	"a\n...\n# c\n",
	"...\r...",
	"---\r\na: b\r\n",
	"--- |\n a\n...",
	"--- >\n a\n--- b",
	"---\n...\n---\n...\n",
	"--- [a,\n---\n]",
	"... ...",
	"...\n# c\n...\n",
	"a\n... \nb",
	"a\n...\t\nb",

	// block-start: sequence, explicit key and value indicators at line start
	"-",
	"- ",
	"-a",
	"- a",
	"- - a",
	"- - - a",
	"-\ta",
	"-\n  a",
	"? a\n: b",
	"?",
	"? ",
	"?a",
	": a",
	":",
	"-\n",
	"? \n",
	": \n",
	"- ? a\n  : b",
	"? - a\n: - b",
	"- : a",
	"? : a",

	// doc: properties, flow starts, errors, aliases, quotes, block scalars, plain scalars
	"&a b",
	"&a\nb",
	"!t b",
	"!t\nb",
	"!<tag:x> b",
	"!<tag:x",
	"!<tag:x y",
	"!<> a",
	"!!str a",
	"!e%21 a",
	"!e%2 a",
	"!e%zz a",
	"!e! a",
	"! a",
	"!",
	"!!",
	"&",
	"&a",
	"&a &b c",
	"!a !b c",
	"&a !b c",
	"*",
	"*a",
	"*a b",
	"*a : b",
	"*a: b",
	"*a,b",
	"}",
	"]",
	"} a",
	"] : a",
	"'a'",
	"\"a\"",
	"'a' # c",
	"'a'b",
	"'a' b",
	"a #c",
	"a#b",
	"a: b",
	"a:b",
	"a :b",
	"a : b",
	"a b c",
	"@a",
	"`a",
	"a\u0000b",
	"\u0000",

	// flow
	"[a, b]",
	"{a: b, c: d}",
	"[a, [b, c], {d: e}]",
	"{a, b}",
	"[a: b]",
	"[a: b, c: d]",
	"[? a : b]",
	"[? a]",
	"{? a : b}",
	"{? a}",
	"{\"a\":b}",
	"{'a':b}",
	"[\"a\":b]",
	"[\"a\" :b]",
	"['a':b]",
	"[a,]",
	"[,]",
	"[,a]",
	"[a,,b]",
	"[a\n,b]",
	"[\n  a\n]",
	"{\n a: b\n}",
	"[a\n- b]",
	"a: [b\nc]",
	"a: [b\n c]",
	"[a # c\n, b]",
	"[a, # c\n b]",
	"[ # c\n]",
	"[*a, &b c, !t d]",
	"[&a, !t]",
	"[a, b] : c",
	"[a, b]: c",
	"{a: b}: c",
	"{a: b} : c",
	"- [a, b]\n- {c: d}",
	"[\n---\n]",
	"[a\n...\n]",
	"[a\n---\n]",
	"key: [\n  a\n]",
	"key: [\na\n]",
	"key: [\n  a\n  ]",
	"key: [\n  a\n]\nnext: b",
	"key:\n  [\n  a\n  ]",
	"key:\n  - [\n    a\n    ]",
	"- [\n  a\n  ]",
	"- [\na]",
	"[:a]",
	"[a:b]",
	"{:a}",
	"{a:}",
	"{a:,b}",
	"[a :b]",
	"[a]]",
	"[[a]",
	"[[a]]",
	"{[a]: b}",
	"{{a: b}: c}",
	"[- a]",
	"[a, -]",
	"[a, - b]",
	"[a\t, b]",
	"[\ta]",
	"[a\n\tb]",
	"[a, b\n",
	"[",
	"{",
	"[a",
	"{a: b",
	"[a\nb: c",
	"a: [b",
	"{a: b\nc: d",
	"[a,\n# c\nb]",
	"[a] # c",
	"[a] b",
	"[a] [b]",
	"[a]\n[b]",
	"{a: [b, {c: d}]}",
	"[a:\n b]",
	"{a\n: b}",
	"[\"a\"\n: b]",
	"[a, 'b'\n: c]",
	"{a: 1, b: 2}\n",
	"[{a: b}: c]",
	"[[a]: b]",
	"[a, ? b : c, d]",
	"{,}",
	"{a,}",
	"[a: b: c]",
	"[a: [b]: c]",
	"[: a]",
	"[:]",
	"{: }",
	"[a :\n b]",
	"[ a:b:c ]",
	"[ http://x.y ]",
	"[a,b]:c",
	"- [a]: b",
	"? [a]\n: b",
	"a:\n  [b]: c",
	"[a]: [b]: c",

	// quoted scalars
	"'a''b'",
	"''",
	"''''",
	"\"\"",
	"'a\n b'",
	"'a\nb'",
	"\"a\\\"b\"",
	"\"a\\\\\"",
	"\"a\\\\\\\"b\"",
	"\"a\\\\\\\\\" b",
	"\"a\n  b\"",
	"'unterminated",
	"\"unterminated",
	"\"unterminated\nnext",
	"'a\n\nb'",
	"key: 'a\nb'",
	"key: 'a\n b'",
	"key:\n  'a\n  b'",
	"key:\n  'a\n b'",
	"- \"a\n  b\"",
	"- \"a\nb\"",
	"  'a\n b'",
	"\"a\r\n b\"",
	"'a\r\nb'",
	"key: \"a\r\nb\"",
	"'a\n---\nb'",
	"'a\n--- b'",
	"\"a\n...\n\"",
	"'a\n----'",
	"\"a\\\nb\"",
	"'a' : b",
	"\"a\": b",
	"'a':b",
	"\"\\\"\"",
	"'a'\n'b'",
	"key: 'a'\n  'b'",

	// block scalars
	"|\n  a\n",
	">\n  a\n",
	"a: |\n  b\n  c\n",
	"a: >\n  b\n\n  c\n",
	"a: |\n  b\n\n\n",
	"a: |+\n  b\n\n\n",
	"a: |-\n  b\n",
	"a: |\n\n  b",
	"a: |\n  b\n c",
	"a: |2\n   b",
	"a: |2\n  b\n   c",
	"a: |1\n  b",
	"a: |9\n          b",
	"a: |0\n b",
	"a: |+2\n   b\n\n",
	"a: |2-\n   b\n",
	"a: >-2+ #c\n  b",
	"a: |++\n b",
	"a: |x\n",
	"| x\n a",
	"| # c\n a",
	"|  # c\n a",
	"|#c\n a",
	"|\n",
	"|",
	">",
	">\n",
	"|\n\n",
	"- |\n  a\n- b",
	"- >\n a\n b\n- c",
	"|\n  a\n\t\n",
	"|\n  a\n \t b\n",
	"|\n  a\n  \t\n",
	"|\n\ta",
	"|\n  a\n\t",
	"a: |\n  b\r\n  c\r\n",
	"a: |\r\n  b\r\n\r\n",
	"a: |\nb",
	"|\n  a\n   \n  b",
	"|\n a\n  \n",
	"|\n a\n  \n  ",
	"|\n a\n \n",
	"|+\n a\n  \n",
	"|-\n a\n  \n\n",
	"a: |\n  b\n# c\n",
	"a: |\n  b\n  # not a comment\nc: d",
	"a: |\n  b\n...\n",
	"a: |\n  b\n---\n",
	"a: |\n---",
	"key:\n  - |\n    a\n  - b",
	"a:\n  |\n  b",
	"- - |\n    a",
	"? |\n  a\n: >\n  b",
	"|\n   a\n  b",
	"|2\n   a\n  b",
	"[|\n a]",
	"a: !t |\n  b",
	"a: &x >\n  b",
	"|\r\n a\r\n",
	"|\r",
	"|\n\r",

	// plain scalars
	"a\n b",
	"a\n  b\n c",
	"a\nb",
	"a: b\n  c",
	"a: b\nc",
	"a:\n  b\n  c",
	"a:\n  b\n c",
	"a\r\nb",
	"a\r\n b",
	"a\rb",
	"a\r",
	"a\r\r",
	"a \r\n b",
	"a #b\n c",
	"a\n#c\nb",
	"a\n  # c\n  b",
	"a\n\n b",
	"a:b:c",
	"a: b: c",
	"a: b:c",
	"- a\n  b",
	"- a\n b",
	"a\n---\nb",
	"a\n--- b",
	"a\n...b",
	"a\n---b",
	"a  \n  b",
	"a\t\n\tb",
	"a:\tb",
	"a: \tb",
	"a:\t\tb\t",
	"a\t#c",
	"a \t#c",
	"http://example.com: b",
	"a,b",
	"a]b",
	"a{b}",
	"-a: b",
	"?a: b",
	":a: b",
	"a?: b",
	"a: -b",

	// block maps
	"a: b\nc: d",
	"a:\n  b: c\n  d: e\nf: g",
	"a:\n- b\n- c",
	"a:\n  - b\n  - c",
	"? a\n? b\n: c",
	"? a\n  b\n: c",
	"?\n: a",
	": a\n: b",
	"a: b\n  c: d",
	"a:\n\n\nb:",
	"a:\n  # c\n\nb:",
	"a: # c\n  b",
	"a: &x\n  b: c",
	"a: !t\n  b",
	"a: &x\nb: c",
	"&a a: b",
	"!t a: b\n!t c: d",
	"&a\na: b",
	"a: b # c\n# d\ne: f",
	"a:\n  b\n# c\n",
	"a: b\n  # indented\nc: d",
	"a: b\n    # deep\n  # less\nc: d",
	"a:\n  b: c\n  # comment\n",
	"a:\n  b: c\n# comment\n",
	"a:\n  b: c\n    # deeper\n",
	"a: - b",
	"a: b\n- c",
	"? a: b\n: c",
	"a: 'b'\n'c': d",
	"\"a\": b",
	"[a]: b\n{c: d}: e",
	"a:\n  ? b\n  : c",
	"? a\n: b\n? c\n: d",
	"- a: b\n  c: d\n- e: f",
	"a: b\n\n\n",
	"a:\n\n# c\n",
	"a:   \n  b",
	"a:\n  b:\n    c:\n      d: e\n  f: g\nh: i",
	"a:\n  b:\nc:",
	"a:\n\nb:\n\n",
	"a:\n  \n  \nb:",
	"a:\n  # c\n  # d\nb:",
	"a:\n# c\n\n# d\nb:",
	"a: b\n? c\n: d",
	"? a\n:\n? b",
	"? a\n? b",
	"?\n?\n:",
	"? a\n  : b",
	"? a\n:\n  b",
	"?\n  a\n:\n  b",
	"? a : b",
	"? a\n: b : c",
	"? a\n: : b",
	"a:\n  : b",
	"a: : b",
	"a:\n: b",
	": a\n: b\nc: d",
	"a: b\n: c",
	"? 'a'\n  : b",
	"? \"a\" : b\n: c",
	"? [a] : b\n: c",
	"? a\n: b\n  : c",
	"a: b\n c",
	"a: 'b'\n c",
	"a: [b]\n c",
	"a: [b]\nc: d",
	"a: {b: c}\n  d",
	"a:\n  [b]: c\n  [d]: e",
	"[a]:\n  b",
	"a: !t\n  - b",
	"a: &x\n  - b",
	"a:\n  &x b: c",
	"a:\n  !t\n  b: c",
	"a: b\n&x c: d",
	"a: b\n!t\nc: d",
	"a: b\n  &x\nc: d",
	"&x\n&y\na: b",
	"a: *x\nb: *y",
	"*x : *y",
	"a:\n  - b\nc: d",
	"a:\n- b\nc: d",
	"a:\n  - b\n  c: d",
	"- a\n- b: c\n  d: e",
	"a: b\nc:\n  d\ne: f",
	"a:\n  b\n  : c",
	"  a: b\n  c: d",
	"  a: b\nc: d",
	"a: b\n    c: d",
	"a:\n    b: c\n  d: e",
	"a: |\n  b\nc: >\n  d\n",
	"a: b # c\n  # d\ne: f",
	"a: [b] # c\n  # d\ne: f",
	"a: b\n  # c\n  # d\ne: f",
	"- a # c\n  # d\n- e",
	"- [a] # c\n  # d\n- e",
	"a:\n  b # c\n  # d\n",
	"a: 'b' # c\n  # d\n",

	// block sequences
	"- a\n- b",
	"- a\n  - b",
	"- - a\n  - b",
	"-\n  - a",
	"-\n- a",
	"- a\n- \n- c",
	"- &x a\n- *x",
	"- !t\n  a",
	"- &x\n  - a",
	"- !t\n- a",
	"-  # c\n  a",
	"- # c\n- a",
	"- a\n  # c\n- b",
	"- a\n# c\n- b",
	"- a\n    # deep\n- b",
	"  - a\n  - b\n- c",
	"- a\n -b",
	"- a\n  b: c",
	"- a\n - b",
	"- a\n   - b",
	"-\n -\n  - a",
	"- - - a\n    - b\n  - c\n- d",
	"- a: b\n- c",
	"- ? a\n  : b\n- c",
	"a:\n- b\n-\n- c",
	"- a\n\n\n- b",
	"- a\n\n# c\n\n- b",
	"- !t &a\n  b",
	"- a\n  !t b",
	"- a\n!t b",
	"- [a]\n  b",
	"- 'a'\n  b",
	"- 'a' # c\n- b",
	"- -",
	"- - ",
	"-\t-\ta",
	"- a\n\t- b",
	"- |\n a\n-",

	// errors and odd structure
	"- a\nb",
	"a\n  b: c",
	"a\nb: c",
	": : :",
	"- - - ",
	"? ? ?",
	"a: *",
	"\t- a",
	"\ta: b",
	"a:\n\t- b",
	"a: b\n\t# c",
	"a: b\n\tc: d",
	"\t",
	"\t\n",
	"\ta",
	"a:\n\tb",
	"? \ta",
	"a\r\n\tb",
	"- a\r- b",
	"\r",
	"\r\n",
	"\r\r\n",
	"a\r\rb",
	"[a\r]",
	"a: b\rc: d",
	"# c\rd",
	"a\n\r\n",
	"&a\r",
	"!t\r",
	"'a'\r",
	"[a]\r",
	"\u0085a",
	"\u2028a",
	"a\u2028b",

	// non-ASCII and astral characters
	"é: ü",
	"😀: 🎉",
	"- 😀\n- 日本",
	"a: \"😀\\u263a\"",
	"'😀'",
	"\"😀\n 😀\"",
	"[😀, 日本]",
	"{😀: 日本}",
	"\u00a0a",
	"a:\u00a0b",
	"😀\n😀",
	"\uFEFF😀",
	"# 😀\na",
	"a # 😀",
	"|\n 😀\n",
	"|\n  😀\n 😀",
	"&😀 a",
	"!😀 a",
	"*😀",
	"😀",
	"😀😀",
	"- 😀: 😀\n  😀: 😀",
	// A line that starts with an astral character, buffered whole with more to come: block-start
	// destructures peek(2) by code point, finds no second character, and waits, still at offset 0, so the
	// next parse call reports line start 0 a second time.
	"😀: a\nb",
	"😀 a\nb",
	"  😀\nb",
	"? 😀\n: 😀",
	"%😀\n---",
	"a\u3000b",
	"\u200ba: b",

	// CRLF throughout
	"a: b\r\nc: d\r\n",
	"- a\r\n- b\r\n",
	"a: |\r\n  b\r\n",
	"a: 'b\r\n  c'\r\n",
	"[a,\r\n b]\r\n",
	"# c\r\n",
	"a\r\n...\r\n",
	"a: >\r\n  b\r\n\r\n  c\r\n",
	"? a\r\n: b\r\n",
	"a:\r\n  - b\r\n  # c\r\n",
	"a: b # c\r\n# d\r\n",

	// larger documents
	"version: 2\nupdates:\n  - package-ecosystem: npm\n    directory: \"/\"\n    schedule:\n      interval: weekly\n    ignore:\n      - dependency-name: \"*\"\n        update-types: [\"version-update:semver-major\"]\n",
	"# Site settings\ntitle: My Blog\nemail: me@example.com\ndescription: >- # this means to ignore newlines\n  Write an awesome description for your new site here.\n  It will appear in your document head meta.\nbaseurl: \"\" # the subpath\nurl: \"\"\n\n# Build settings\nmarkdown: kramdown\nplugins:\n  - jekyll-feed\n",
	"anchors:\n  base: &base\n    name: base\n    value: 1\n  derived:\n    <<: *base\n    value: 2\nlist: [*base, {<<: *base}]\n",
	"%YAML 1.2\n%TAG !e! tag:example.com,2000:app/\n---\n!e!foo \"bar\"\n...\n---\n!!map {\n  ? !!str key\n  : !!seq [ !!str a, !!str b ],\n}\n...\n# trailing\n",
	"jobs:\n  build:\n    runs-on: ${{ matrix.os }}\n    steps:\n      - uses: actions/checkout@v4\n      - run: |\n          npm ci\n          npm test\n        env:\n          CI: true\n",
}

// generatedInputs draws inputs from an alphabet weighted toward the characters the lexer branches on,
// from a fixed seed so every run compares the same inputs.
func generatedInputs(count int) []string {
	random := rand.New(rand.NewPCG(1, 2))
	pieces := []string{
		" ", " ", " ", "  ", "\n", "\n", "\n", "\n  ", "\n    ", "\t", "\r\n", "\r",
		"-", "- ", "? ", ": ", ":", "?", "#", " #", "[", "]", "{", "}", ",", ", ",
		"'", "\"", "\\", "|", ">", "|-", ">+", "|2", "&a", "&", "!", "!t", "!!", "!<x>", "*a", "*",
		"%YAML 1.2", "%", "---", "...", "--- ", "... ",
		"a", "b", "ab", "x y", "1", "😀", "é", "\uFEFF",
	}
	inputs := make([]string, 0, count)
	for range count {
		length := 1 + random.IntN(24)
		var builder strings.Builder
		for range length {
			builder.WriteString(pieces[random.IntN(len(pieces))])
		}
		inputs = append(inputs, builder.String())
	}
	return inputs
}
