// Command generate_entities captures the HTML named character references micromark decodes, from the
// table the oracle's bundle carries, and writes them as Go.
//
// Usage:
//
//	go run ./internal/format/markdown/micromark/tools/generate_entities [-output <file.go>] [-check]
//
// decode-named-character-reference looks names up in character-entities, which the markdown bundle
// inlines as an object literal. The bundle also carries remark-parse 8's legacy table (with entries like
// `AEli`, no semicolon), which only MDX reaches, so the one wanted is the literal that opens with
// `{AElig:"\xC6",AMP:"&"`. It is cut out and evaluated by goja, so no table is restated by hand.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dop251/goja"
	"github.com/system-inc/cohere/internal/format/prettier"
)

const anchor = `{AElig:"\xC6",AMP:"&",`

func main() {
	output := flag.String("output", filepath.Join("internal", "format", "markdown", "micromark", "entities_generated.go"), "where to write the Go")
	check := flag.Bool("check", false, "regenerate and fail if the committed file disagrees")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *check {
		committed, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		if !bytes.Equal(committed, generated) {
			fmt.Fprintf(os.Stderr, "%s is stale: regenerate it\n", *output)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	bundles, err := prettier.Bundles()
	if err != nil {
		return nil, err
	}
	markdown := string(bundles.Files["plugins/markdown.js"])

	// Two copies are inlined: character-entities 1 as a CommonJS module (`exports={...}`), which
	// remark-parse 8's parse-entities uses, and character-entities 2 as an ES module binding
	// (`var x={...}`), which decode-named-character-reference uses. The second is micromark's.
	start := -1
	for offset := 0; ; {
		index := strings.Index(markdown[offset:], anchor)
		if index < 0 {
			break
		}
		index += offset
		if !strings.HasSuffix(markdown[:index], "exports=") {
			if start >= 0 {
				return nil, fmt.Errorf("found two ES module copies of the character-entities table, want exactly 1")
			}
			start = index
		}
		offset = index + len(anchor)
	}
	if start < 0 {
		return nil, fmt.Errorf("found no ES module copy of the character-entities table")
	}

	// The literal ends at the first `}` after which it evaluates. Values are strings that can hold a
	// brace (`lbrace`, `rbrace`), so the first `}` is not necessarily the end; evaluation decides.
	runtime := goja.New()
	var entities map[string]string
	for end := start + len(anchor); end < len(markdown); end++ {
		if markdown[end] != '}' {
			continue
		}
		value, err := runtime.RunString("JSON.stringify((" + markdown[start:end+1] + "))")
		if err != nil {
			continue
		}
		if err := json.Unmarshal([]byte(value.String()), &entities); err != nil {
			return nil, err
		}
		break
	}

	// Controls: the table is the full HTML set, and a few known answers.
	if len(entities) < 2000 {
		return nil, fmt.Errorf("decoded %d entities, want the full table of over 2000", len(entities))
	}
	for name, want := range map[string]string{"amp": "&", "copy": "©", "AElig": "Æ", "ngE": "≧̸"} {
		if entities[name] != want {
			return nil, fmt.Errorf("control failed: %s decoded to %q, want %q", name, entities[name], want)
		}
	}

	names := make([]string, 0, len(entities))
	for name := range entities {
		names = append(names, name)
	}
	sort.Strings(names)

	var source bytes.Buffer
	source.WriteString("// Code generated by generate_entities. DO NOT EDIT.\n//\n")
	source.WriteString("// The character-entities table, cut out of the embedded markdown bundle and evaluated by goja.\n")
	source.WriteString("// Regenerate with:\n//\n//\tgo run ./internal/format/markdown/micromark/tools/generate_entities\n\n")
	source.WriteString("package micromark\n\n")
	source.WriteString("// characterEntities maps a reference name, without `&` and `;`, to what it decodes to.\n")
	source.WriteString("var characterEntities = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&source, "\t%q: %q,\n", name, entities[name])
	}
	source.WriteString("}\n")

	return format.Source(source.Bytes())
}
